"use client";

import {useEffect,useMemo,useState} from "react";

type HealthCheck={ok:boolean;status?:number;latencyMs?:number;error?:string;critical?:boolean;optional?:boolean;enabled?:boolean;mode?:string;note?:string;provider?:string;skipped?:boolean};
type JobRun={id:string;jobName:string;status:string;startedAt:string;finishedAt?:string|null;processed:number;failed:number;error?:string|null};
type WebhookRow={provider:string;providerEventId:string;eventType:string;processedAt?:string|null;createdAt:string;attemptCount?:number;lastAttemptAt?:string|null;lastError?:string|null};
type UnmatchedEvent={providerEventId:string;eventType:string;providerObjectId?:string|null;accountId?:string|null;reason:string;createdAt:string};
type DrItem={ok:boolean;fresh:boolean;completedAt:string|null;ageMs:number|null;backup?:string;sizeBytes?:number;objects?:number;bytes?:number};
type Data={
 status:"operational"|"attention"|"degraded";
 timestamp:string;
 health:{criticalIssues:string[];warnings:string[];recentFailedNotifications:number;staleNotifications:number;recentFailedJobs:number};
 disasterRecovery:{ok:boolean;local:DrItem;offsite:DrItem;mediaInventory:DrItem;restoreDrill:DrItem};
 runtime:{color:string;web:HealthCheck;admin:HealthCheck;api:HealthCheck;node:string;uptimeSeconds:number;rssBytes:number;heapUsedBytes:number;appVersion:string;environment:string};
 services:Record<string,HealthCheck>;
 queues:{notifications:{status:string;channel:string;count:number}[];moderation:number;support:number};
 jobs:JobRun[];
 webhooks:{items:WebhookRow[];failed:number;pending:number};
 unmatchedProviderEvents:UnmatchedEvent[];
};

const bytes=(n:number)=>`${(n/1024/1024).toFixed(1)} Mo`;
const uptime=(n:number)=>n<3600?`${Math.floor(n/60)} min`:n<86400?`${(n/3600).toFixed(1)} h`:`${(n/86400).toFixed(1)} j`;
const parisDateTime=(v?:string|null)=>v?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"medium",timeZone:"Europe/Paris"}).format(new Date(v)):"—";
const serviceLabels:Record<string,string>={database:"Base de données",redis:"Redis",objectStorage:"Stockage média",notificationWorker:"Worker notifications",payment:"Paiement marketplace",stripeWebhook:"Webhook Stripe",sendcloud:"Sendcloud",hostingerMail:"E-mails transactionnels",smsVerification:"Vérification SMS",openai:"OpenAI",vehicleData:"Données véhicule"};
const warningLabels:Record<string,string>={"backup:media-inventory":"Inventaire média à actualiser","backup:restore-drill":"Test de restauration à renouveler","notifications:failed-24h":"Échecs de notifications durant les dernières 24 h","notifications:stale":"Notifications bloquées dans la file","jobs:failed-24h":"Job automatique en échec durant les dernières 24 h","webhooks:failed":"Webhook paiement en échec","finance:unmatched-events":"Événement financier à rapprocher"};
const criticalLabels:Record<string,string>={"runtime:web":"Site public inaccessible","runtime:admin":"Admin inaccessible","runtime:api":"API inaccessible","backup:local":"Sauvegarde locale trop ancienne","backup:offsite":"Sauvegarde hors site trop ancienne","service:database":"Base de données indisponible","service:redis":"Redis indisponible","service:objectStorage":"Stockage média indisponible","service:notificationWorker":"Worker notifications arrêté","service:hostingerMail":"Service e-mail transactionnel indisponible"};

function ServiceCard({name,value}:{name:string;value:HealthCheck}){
 const optional=Boolean(value.optional&&!value.ok);const tone=value.ok?"green":optional?"orange":"red";const label=value.ok?"OK":optional?"Optionnel":"À vérifier";
 return <article className="admin-card admin-integration admin-system-service-card"><div className="admin-integration-head"><div><h3>{serviceLabels[name]??name}</h3><p>{value.latencyMs!=null?`Latence ${value.latencyMs} ms`:value.mode?`Mode ${value.mode}`:value.provider?`Provider ${value.provider}`:value.enabled?"Activé":value.skipped?"Non requis":"Contrôle de configuration"}</p></div><span className={`admin-badge ${tone}`}>{label}</span></div>{value.critical&&<small className="admin-system-critical-label">Service critique</small>}{(value.error||value.note)&&<div className="admin-secret-note">{String(value.error??value.note)}</div>}</article>
}

function RuntimeCard({label,value}:{label:string;value:HealthCheck}){
 return <article className="admin-card admin-integration"><div className="admin-integration-head"><div><h3>{label}</h3><p>{value.status?`HTTP ${value.status}`:"Contrôle local"}{value.latencyMs!=null?` · ${value.latencyMs} ms`:""}</p></div><span className={`admin-badge ${value.ok?"green":"red"}`}>{value.ok?"En ligne":"Indisponible"}</span></div>{value.error&&<div className="admin-secret-note">{value.error}</div>}</article>
}

export default function SystemClient(){
 const[data,setData]=useState<Data|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 async function load(){setBusy(true);setError("");try{const r=await fetch("/api/admin/system/status",{credentials:"include",cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);setData(await r.json())}catch{setError("Impossible de vérifier l’état du système. Réessayez dans quelques secondes.")}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 const pending=useMemo(()=>data?.queues.notifications.filter(x=>x.status==="PENDING").reduce((a,x)=>a+x.count,0)??0,[data]);
 const failedQueue=useMemo(()=>data?.queues.notifications.filter(x=>x.status==="FAILED").reduce((a,x)=>a+x.count,0)??0,[data]);
 const flash=data?.status==="degraded"?{c:"err",t:"Un composant critique est indisponible. Une intervention est nécessaire."}:data?.status==="attention"?{c:"system-attention",t:"La plateforme fonctionne, mais certains éléments méritent une vérification."}:{c:"ok",t:"Les composants critiques répondent correctement."};
 return <div className="admin-system-page">
  <div className="admin-page-head"><div><p>Infrastructure</p><h1>État du système</h1><span className="subtitle">Disponibilité réelle des services, files, sauvegardes et intégrations. Les services optionnels n’abaissent plus l’état global.</span></div><button type="button" className="admin-btn primary" onClick={()=>void load()} disabled={busy}>{busy?"Vérification…":"Actualiser l’état"}</button></div>
  {error&&<div className="admin-flash err admin-system-load-error"><span>{error}</span><button className="admin-btn" onClick={()=>void load()}>Réessayer</button></div>}
  {!error&&<div className={`admin-flash ${flash.c}`}>{flash.t}</div>}

  <div className="admin-grid admin-kpis admin-system-kpis">
   <article className="admin-card admin-kpi"><small>Heure serveur</small><strong style={{fontSize:18}}>{data?parisDateTime(data.timestamp):"—"}</strong><p>Europe/Paris · heure française</p></article>
   <article className="admin-card admin-kpi"><small>Version active</small><strong style={{fontSize:20,textTransform:"uppercase"}}>{data?.runtime.color??"—"}</strong><p>{data?.runtime.environment??"—"} · Node {data?.runtime.node??"—"}</p></article>
   <article className="admin-card admin-kpi"><small>Uptime API</small><strong>{data?uptime(data.runtime.uptimeSeconds):"—"}</strong><p>processus actif</p></article>
   <article className="admin-card admin-kpi"><small>Mémoire RSS</small><strong>{data?bytes(data.runtime.rssBytes):"—"}</strong><p>heap {data?bytes(data.runtime.heapUsedBytes):"—"}</p></article>
   <article className="admin-card admin-kpi"><small>Notifications en attente</small><strong>{pending}</strong><p>{failedQueue} échec(s) historique(s)</p></article>
   <article className="admin-card admin-kpi"><small>Files métier</small><strong>{(data?.queues.moderation??0)+(data?.queues.support??0)}</strong><p>{data?.queues.moderation??0} modération · {data?.queues.support??0} support</p></article>
   <article className="admin-card admin-kpi"><small>Webhooks actifs en anomalie</small><strong>{data?.webhooks.failed??0}</strong><p>{data?.webhooks.pending??0} non traité(s)</p></article>
   <article className="admin-card admin-kpi"><small>Alertes récentes</small><strong>{(data?.health.warnings.length??0)+(data?.health.criticalIssues.length??0)}</strong><p>24 h + reprise après sinistre</p></article>
  </div>

  {(data?.health.criticalIssues.length||data?.health.warnings.length)?<section className="admin-card admin-section" style={{marginTop:18}}><div className="admin-section-head"><div><h2>Points à surveiller</h2><p>Les incidents critiques sont séparés des avertissements opérationnels.</p></div></div><div className="admin-system-alert-grid">{data.health.criticalIssues.map(x=><div className="admin-system-alert critical" key={x}><span>Critique</span><strong>{criticalLabels[x]??x}</strong></div>)}{data.health.warnings.map(x=><div className="admin-system-alert warning" key={x}><span>Attention</span><strong>{warningLabels[x]??x}</strong></div>)}</div></section>:null}

  <section className="admin-card admin-section" style={{marginTop:18}}><div className="admin-section-head"><div><h2>Runtime production</h2><p>Contrôle HTTP local de la couleur réellement servie avant nginx.</p></div><span className="admin-badge">{data?.runtime.color?String(data.runtime.color).toUpperCase():"—"}</span></div><div className="admin-integration-grid">{data&&<><RuntimeCard label="Site public" value={data.runtime.web}/><RuntimeCard label="Admin" value={data.runtime.admin}/><RuntimeCard label="API" value={data.runtime.api}/></>}</div></section>

  <section className="admin-card admin-section" style={{marginTop:18}}><div className="admin-section-head"><div><h2>Sauvegardes & reprise</h2><p>Les sauvegardes DB locale et hors site sont critiques. L’inventaire média et le test de restauration génèrent une alerte sans simuler une panne du site.</p></div><span className={`admin-badge ${data?.disasterRecovery?.local.fresh&&data?.disasterRecovery?.offsite.fresh?"green":"red"}`}>{data?.disasterRecovery?.local.fresh&&data?.disasterRecovery?.offsite.fresh?"Sauvegardé":"À vérifier"}</span></div><div className="admin-integration-grid">{data&&Object.entries({local:data.disasterRecovery.local,offsite:data.disasterRecovery.offsite,media:data.disasterRecovery.mediaInventory,restore:data.disasterRecovery.restoreDrill}).map(([key,val])=>{const labels:Record<string,string>={local:"Backup DB local",offsite:"Backup DB offsite",media:"Inventaire médias",restore:"Test de restauration"};return <article className="admin-card admin-integration" key={key}><div className="admin-integration-head"><div><h3>{labels[key]}</h3><p>{val.completedAt?parisDateTime(val.completedAt):"Aucune exécution confirmée"}</p></div><span className={`admin-badge ${val.fresh?"green":key==="local"||key==="offsite"?"red":"orange"}`}>{val.fresh?"À jour":"En retard"}</span></div>{val.backup&&<div className="admin-secret-note">{val.backup}</div>}{val.objects!=null&&<div className="admin-secret-note">{val.objects} média(s) inventorié(s)</div>}</article>})}</div></section>

  <section className="admin-card admin-section" style={{marginTop:18}}><div className="admin-section-head"><div><h2>Services & intégrations</h2><p>Les briques critiques et les fonctionnalités optionnelles sont distinguées explicitement.</p></div></div><div className="admin-integration-grid">{data&&Object.entries(data.services).map(([key,val])=><ServiceCard key={key} name={key} value={val}/>)}</div></section>

  <section className="admin-card admin-section" style={{marginTop:18}}><div className="admin-section-head"><div><h2>Jobs marketplace</h2><p>Dernières exécutions automatiques. Un échec récent apparaît aussi dans les alertes ci-dessus.</p></div><span className={`admin-badge ${(data?.health.recentFailedJobs??0)>0?"orange":"green"}`}>{data?.health.recentFailedJobs??0} échec(s) / 24 h</span></div><div className="admin-table-wrap"><table className="admin-table admin-mobile-cards"><thead><tr><th>Job</th><th>Statut</th><th>Démarré</th><th>Traités</th><th>Échecs</th><th>Erreur</th></tr></thead><tbody>{(data?.jobs??[]).map(j=><tr key={j.id}><td data-label="Job"><strong>{j.jobName}</strong></td><td data-label="Statut"><span className={`admin-badge ${j.status==="SUCCEEDED"?"green":j.status==="FAILED"?"red":"orange"}`}>{j.status}</span></td><td data-label="Démarré">{parisDateTime(j.startedAt)}</td><td data-label="Traités">{j.processed??0}</td><td data-label="Échecs">{j.failed??0}</td><td data-label="Erreur">{j.error??"—"}</td></tr>)}{!data?.jobs?.length&&<tr><td colSpan={6}><div className="admin-empty">Aucune exécution enregistrée.</div></td></tr>}</tbody></table></div></section>

  <section className="admin-card admin-section" style={{marginTop:18}}><div className="admin-section-head"><div><h2>Audit webhooks paiement</h2><p>Seuls les événements non traités avec erreur sont considérés comme incidents actifs.</p></div><span className={`admin-badge ${(data?.webhooks.failed??0)>0?"red":"green"}`}>{data?.webhooks.failed??0} échec(s)</span></div><div className="admin-table-wrap"><table className="admin-table admin-mobile-cards"><thead><tr><th>Événement</th><th>Type</th><th>État</th><th>Tentatives</th><th>Dernière erreur</th><th>Date</th></tr></thead><tbody>{(data?.webhooks.items??[]).map(w=><tr key={`${w.provider}-${w.providerEventId}`}><td data-label="Événement"><strong>{w.providerEventId.slice(0,22)}</strong><small style={{display:"block",marginTop:4}}>{w.provider}</small></td><td data-label="Type">{w.eventType}</td><td data-label="État"><span className={`admin-badge ${w.processedAt?"green":w.lastError?"red":"orange"}`}>{w.processedAt?"Traité":w.lastError?"Échec":"En attente"}</span></td><td data-label="Tentatives">{w.attemptCount??0}</td><td data-label="Erreur" title={w.lastError??undefined}>{w.lastError?String(w.lastError).slice(0,90):"—"}</td><td data-label="Date">{parisDateTime(w.createdAt)}</td></tr>)}{!data?.webhooks.items?.length&&<tr><td colSpan={6}><div className="admin-empty">Aucun webhook enregistré.</div></td></tr>}</tbody></table></div></section>

  <section className="admin-card admin-section" style={{marginTop:18}}><div className="admin-section-head"><div><h2>Événements financiers non appariés</h2><p>Ils sont signalés pour rapprochement, mais ne modifient jamais automatiquement une commande.</p></div><span className={`admin-badge ${(data?.unmatchedProviderEvents?.length??0)>0?"orange":"green"}`}>{data?.unmatchedProviderEvents?.length??0}</span></div><div className="admin-table-wrap"><table className="admin-table admin-mobile-cards"><thead><tr><th>Type</th><th>Objet provider</th><th>Compte</th><th>Motif</th><th>Date</th></tr></thead><tbody>{(data?.unmatchedProviderEvents??[]).map(e=><tr key={e.providerEventId}><td data-label="Type"><strong>{e.eventType}</strong></td><td data-label="Objet">{e.providerObjectId??"—"}</td><td data-label="Compte">{e.accountId??"—"}</td><td data-label="Motif">{e.reason}</td><td data-label="Date">{parisDateTime(e.createdAt)}</td></tr>)}{!data?.unmatchedProviderEvents?.length&&<tr><td colSpan={5}><div className="admin-empty">Aucun événement financier non apparié.</div></td></tr>}</tbody></table></div></section>

  <section className="admin-card admin-section" style={{marginTop:18}}><div className="admin-section-head"><div><h2>File notifications</h2><p>Les échecs récents et les éléments bloqués plus de 30 minutes sont surveillés séparément.</p></div><div className="admin-system-queue-badges"><span className={`admin-badge ${(data?.health.recentFailedNotifications??0)>0?"orange":"green"}`}>{data?.health.recentFailedNotifications??0} échec(s) / 24 h</span><span className={`admin-badge ${(data?.health.staleNotifications??0)>0?"red":"green"}`}>{data?.health.staleNotifications??0} bloquée(s)</span></div></div><div className="admin-table-wrap"><table className="admin-table admin-mobile-cards"><thead><tr><th>Statut</th><th>Canal</th><th>Nombre</th></tr></thead><tbody>{(data?.queues.notifications??[]).map((x,i)=><tr key={`${x.status}-${x.channel}-${i}`}><td data-label="Statut"><span className={`admin-badge ${x.status==="SENT"?"green":x.status==="FAILED"?"red":x.status==="PENDING"?"orange":""}`}>{x.status}</span></td><td data-label="Canal">{x.channel}</td><td data-label="Nombre"><strong>{x.count}</strong></td></tr>)}{!data?.queues.notifications.length&&<tr><td colSpan={3}><div className="admin-empty">File vide.</div></td></tr>}</tbody></table></div></section>
 </div>
}
