import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { AppIcon } from "../../../components/app-icon";
import { ReputationBadges } from "../../../components/reputation-badges";
import { MarketplaceListingCard } from "../../../components/marketplace-listing-card";
import { FollowButton } from "../../../components/follow-button";
import styles from "./page.module.css";

export const revalidate=60;

type ReputationBadge={code:string;label:string;shortLabel:string;description:string;icon:"shield"|"bolt"|"circle-check"|"truck"|"star"|"phone";priority:number};
type ReputationHistory={id:string;badgeCode:string;badge:ReputationBadge;eventType:"EARNED"|"LOST";createdAt:string;metadata:Record<string,unknown>|null};
type Reputation={badges:ReputationBadge[];cardBadges:ReputationBadge[];metrics:{reviewCount:number;reviewAverage:number|null;completedSales:number;cancellationRate:number;disputeRate:number;responseSamples:number;responseWithinTwoHoursRate:number;averageResponseMinutes:number|null;shipmentSamples:number;shipmentWithin48HoursRate:number};history:ReputationHistory[]};
type PublicProfile={profile:{id:string;kind:string;name:string;avatarUrl:string|null;memberSince:string;verified:boolean;siretVerified:boolean;emailVerified:boolean;phoneVerified:boolean;store:{name:string;slug:string|null}|null;activeListings:number;completedSales:number;trust:{score:number;reliableSeller:boolean;level:"NEW"|"ESTABLISHED"|"TRUSTED"};reputation?:Reputation|null};summary:{count:number;average:number|null;seller:{count:number;average:number|null};buyer:{count:number;average:number|null}};reviews:Array<{id:string;rating:number;comment:string|null;direction:string;createdAt:string;reviewerName:string}>;listings:Array<{id:string;title:string|null;slug:string|null;priceMinor:number|null;currency:string;city:string|null;categoryName:string;categoryDomain:string;transactionType:string|null;imageUrl:string|null;publishedAt:string|null}>};
const base=()=> (process.env.API_INTERNAL_URL??process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000").replace(/\/$/,"");
async function getProfile(id:string):Promise<PublicProfile|null>{const r=await fetch(`${base()}/public/users/${encodeURIComponent(id)}/reviews`,{next:{revalidate:60}});if(r.status===404)return null;if(!r.ok)throw new Error(`profile_api_${r.status}`);return r.json();}
function stars(rating:number){return `${"★".repeat(rating)}${"☆".repeat(5-rating)}`;}

export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;try{const data=await getProfile(id);if(!data)return{title:"Profil introuvable | Petit Annonces"};return{title:`${data.profile.name} | Petit Annonces`,description:`Consultez le profil, les évaluations et la réputation de ${data.profile.name} sur Petit Annonces.`};}catch{return{title:"Profil | Petit Annonces"};}}

export default async function PublicProfilePage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;let data:PublicProfile|null=null;try{data=await getProfile(id);}catch{data=null;}if(!data)notFound();
 const sellerReviews=data.reviews.filter(r=>r.direction==="BUYER_TO_SELLER");const buyerReviews=data.reviews.filter(r=>r.direction==="SELLER_TO_BUYER");
 const joined=new Intl.DateTimeFormat("fr-FR",{year:"numeric",month:"long"}).format(new Date(data.profile.memberSince));const isPro=data.profile.kind==="PROFESSIONNEL";const baseReputationBadges=data.profile.reputation?.badges??[];const phoneBadge:ReputationBadge={code:"PHONE_VERIFIE",label:"Téléphone vérifié",shortLabel:"Téléphone",description:"Numéro de téléphone confirmé par code SMS.",icon:"phone",priority:89};const profileBadgeIndex=baseReputationBadges.findIndex(b=>b.code==="PROFILE_VERIFIE");const reputationBadges=data.profile.phoneVerified?[...baseReputationBadges.slice(0,profileBadgeIndex>=0?profileBadgeIndex+1:baseReputationBadges.length),phoneBadge,...baseReputationBadges.slice(profileBadgeIndex>=0?profileBadgeIndex+1:baseReputationBadges.length)]:baseReputationBadges;
 return <div className={styles.page}><main className={styles.shell}><a href="/" className={styles.back}>← Retour aux annonces</a>
  <section className={styles.hero}><div className={styles.heroGlow}/><div className={styles.avatarWrap}><div className={styles.avatar}>{data.profile.avatarUrl?<img src={data.profile.avatarUrl} alt=""/>:data.profile.name.slice(0,2).toUpperCase()}</div>{(data.profile.phoneVerified||data.profile.verified||data.profile.siretVerified)&&<span className={styles.avatarStatus}><AppIcon name="check"/></span>}</div><div className={styles.heroContent}><div className={styles.titleRow}><div><h1>{data.profile.name}</h1><p>{isPro?"Professionnel":"Particulier"} · Membre depuis {joined}</p>{isPro&&<div className={styles.proIdentityLine}><span><AppIcon name="briefcase"/>Compte professionnel</span>{data.profile.store?.slug&&<a href={`/boutique/${data.profile.store.slug}`}><AppIcon name="store"/>Voir la boutique</a>}</div>}</div><div className={styles.badges}>{data.profile.emailVerified&&<span className={styles.verified}><AppIcon name="check"/>E-mail vérifié</span>}{data.profile.siretVerified&&<span className={styles.verified}><AppIcon name="shield"/>SIRET vérifié</span>}{!data.profile.siretVerified&&data.profile.verified&&<span className={styles.verified}><AppIcon name="shield"/>Profil vérifié</span>}{data.profile.trust.reliableSeller&&<span className={styles.reliable}><AppIcon name="star"/>Vendeur fiable</span>}</div></div><div className={styles.followActions}><FollowButton targetType="USER" targetId={data.profile.id} label="Suivre le vendeur" followingLabel="Vendeur suivi"/></div><div className={styles.stats}><div><span className={styles.statIcon}><AppIcon name="shield"/></span><strong>{data.profile.trust.score}/100</strong><span>Indice de confiance</span></div><div><span className={styles.statIcon}><AppIcon name="star"/></span><strong>{data.summary.average!=null?data.summary.average.toFixed(1):"—"}</strong><span>Note moyenne</span></div><div><span className={styles.statIcon}><AppIcon name="comments"/></span><strong>{data.summary.count}</strong><span>Avis vérifiés</span></div><div><span className={styles.statIcon}><AppIcon name="check"/></span><strong>{data.profile.completedSales}</strong><span>Ventes finalisées</span></div><div><span className={styles.statIcon}><AppIcon name="list"/></span><strong>{data.profile.activeListings}</strong><span>Annonces actives</span></div></div></div></section>
  {data.profile.reputation&&<section className={`${styles.card} ${styles.reputationCard}`}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Réputation</p><h2>Badges gagnés automatiquement</h2></div><span className={styles.reputationCount}>{reputationBadges.length} badge{reputationBadges.length>1?"s":""}</span></div>{reputationBadges.length?<ReputationBadges badges={reputationBadges} metrics={data.profile.reputation.metrics} variant="profile"/>:<div className={styles.reputationEmpty}><AppIcon name="shield"/><div><strong>Les badges se gagnent avec l’activité</strong><span>Ils apparaissent automatiquement lorsque les critères de réponse, de vente, d’évaluation, d’expédition ou de vérification sont atteints.</span></div></div>}<div className={styles.reputationHistory}><div className={styles.reputationHistoryHead}><strong>Historique des badges</strong><span>Suivi actif à partir du 9 septembre 2026</span></div>{data.profile.reputation.history?.length?<div className={styles.reputationHistoryList}>{data.profile.reputation.history.map(event=><div key={event.id} className={styles.reputationHistoryItem} data-event={event.eventType}><span><AppIcon name={event.eventType==="EARNED"?"circle-check":"info"}/></span><div><strong>{event.eventType==="EARNED"?"Badge obtenu":"Badge retiré"} · {event.badge.label}</strong><small>{new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(event.createdAt))}</small></div></div>)}</div>:<p className={styles.reputationHistoryEmpty}>Aucun changement de badge enregistré depuis l’activation du suivi.</p>}</div><p className={styles.reputationNote}>Touchez un badge pour voir ses critères. Les badges ne peuvent pas être choisis par le membre : ils sont recalculés automatiquement et peuvent disparaître si les critères ne sont plus remplis.</p></section>}
  <section className={styles.card}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Confiance</p><h2>Indice de confiance Petit Annonces</h2></div><div className={styles.score}>{data.profile.trust.score}/100</div></div><div className={styles.trustMeter}><div className={styles.trustMeterTop}><span>Niveau de confiance</span><strong>{data.profile.trust.level==="TRUSTED"?"Très bon":data.profile.trust.level==="ESTABLISHED"?"Établi":"Nouveau"}</strong></div><div className={styles.trustBar}><i style={{width:`${data.profile.trust.score}%`}}/></div></div><div className={styles.trustExplain}><div><span className={styles.trustIcon}><AppIcon name="check"/></span><b>Transactions finalisées</b><span>{data.profile.completedSales} vente{data.profile.completedSales>1?"s":""} finalisée{data.profile.completedSales>1?"s":""}</span></div><div><span className={styles.trustIcon}><AppIcon name="star"/></span><b>Avis après transaction</b><span>{data.summary.count?`${data.summary.count} avis · ${data.summary.average?.toFixed(1)}/5`:"Pas encore d’avis"}</span></div><div><span className={styles.trustIcon}><AppIcon name="shield"/></span><b>Compte</b><span>{data.profile.siretVerified?"SIRET vérifié auprès du registre public":data.profile.verified?"Profil professionnel ou boutique vérifiée":data.profile.emailVerified&&data.profile.phoneVerified?"E-mail et téléphone vérifiés":data.profile.phoneVerified?"Téléphone vérifié":data.profile.emailVerified?"E-mail vérifié":"Compte non vérifié"}</span></div></div><p className={styles.explainNote}>L’indice combine l’ancienneté du compte, les transactions finalisées, les évaluations reçues et la vérification du compte. Le badge « Vendeur fiable » est attribué uniquement lorsque plusieurs critères minimums sont atteints.</p></section>

  {data.listings.length>0&&<section className={styles.card}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Annonces</p><h2>Annonces actives de {data.profile.name}</h2></div><span className={styles.listingCount}>{data.profile.activeListings} active{data.profile.activeListings>1?"s":""}</span></div><div className={styles.listingGrid}>{data.listings.map(item=><MarketplaceListingCard key={item.id} item={{id:item.id,slug:item.slug,title:item.title,priceMinor:item.priceMinor,currency:item.currency,city:item.city,imageUrl:item.imageUrl,category:{name:item.categoryName,slug:"",domain:item.categoryDomain},property:item.transactionType?{transactionType:item.transactionType}:null,sellerReputation:{verified:data.profile.verified||data.profile.siretVerified,kind:data.profile.kind,hasStore:Boolean(data.profile.store),avatarUrl:data.profile.avatarUrl,sellerName:data.profile.name,reviewCount:data.summary.seller.count,reviewAverage:data.summary.seller.average,trust:{reliableSeller:data.profile.trust.reliableSeller},cardBadges:data.profile.reputation?.cardBadges}}}/>)}</div></section>}
  <section className={styles.card}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Réputation</p><h2>Avis après transaction</h2></div>{data.summary.average!=null&&<div className={styles.score}>{data.summary.average.toFixed(1)} ★</div>}</div>
  <div className={styles.reviewSummary}><div><span>Comme vendeur</span><strong>{data.summary.seller.average!=null?`${data.summary.seller.average.toFixed(1)} ★`:"—"}</strong><small>{data.summary.seller.count} avis</small></div><div><span>Comme acheteur</span><strong>{data.summary.buyer.average!=null?`${data.summary.buyer.average.toFixed(1)} ★`:"—"}</strong><small>{data.summary.buyer.count} avis</small></div></div>
  {!data.reviews.length?<div className={styles.empty}>Aucun avis pour le moment.</div>:<><h3 className={styles.reviewGroupTitle}>Avis en tant que vendeur</h3>{sellerReviews.length?<div className={styles.reviews}>{sellerReviews.map(review=><article key={review.id} className={styles.review}><div className={styles.reviewTop}><strong>{stars(review.rating)}</strong><span>{new Intl.DateTimeFormat("fr-FR").format(new Date(review.createdAt))}</span></div>{review.comment&&<p>{review.comment}</p>}<small>Par {review.reviewerName} · Transaction vérifiée</small></article>)}</div>:<div className={styles.emptyMini}>Aucun avis vendeur.</div>}<h3 className={styles.reviewGroupTitle}>Avis en tant qu’acheteur</h3>{buyerReviews.length?<div className={styles.reviews}>{buyerReviews.map(review=><article key={review.id} className={styles.review}><div className={styles.reviewTop}><strong>{stars(review.rating)}</strong><span>{new Intl.DateTimeFormat("fr-FR").format(new Date(review.createdAt))}</span></div>{review.comment&&<p>{review.comment}</p>}<small>Par {review.reviewerName} · Transaction vérifiée</small></article>)}</div>:<div className={styles.emptyMini}>Aucun avis acheteur.</div>}</>}</section>
 </main></div>;
}
