import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SiteHeader } from "../../../components/site-header";
import styles from "./page.module.css";

type PublicProfile={profile:{id:string;kind:string;name:string;avatarUrl:string|null;memberSince:string;verified:boolean;store:{name:string;slug:string|null}|null;activeListings:number};summary:{count:number;average:number|null};reviews:Array<{id:string;rating:number;comment:string|null;direction:string;createdAt:string;reviewerName:string}>};
const base=()=> (process.env.API_INTERNAL_URL??process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000").replace(/\/$/,"");
async function getProfile(id:string):Promise<PublicProfile|null>{const r=await fetch(`${base()}/public/users/${encodeURIComponent(id)}/reviews`,{next:{revalidate:60}});if(r.status===404)return null;if(!r.ok)throw new Error(`profile_api_${r.status}`);return r.json();}
function stars(rating:number){return `${"★".repeat(rating)}${"☆".repeat(5-rating)}`;}

export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;try{const data=await getProfile(id);if(!data)return{title:"Profil introuvable | Petit Annonces"};return{title:`${data.profile.name} | Petit Annonces`,description:`Consultez le profil, les évaluations et la réputation de ${data.profile.name} sur Petit Annonces.`};}catch{return{title:"Profil | Petit Annonces"};}}

export default async function PublicProfilePage({params}:{params:Promise<{id:string}>}){const {id}=await params;let data:PublicProfile|null=null;try{data=await getProfile(id);}catch{data=null;}if(!data)notFound();const joined=new Intl.DateTimeFormat("fr-FR",{year:"numeric",month:"long"}).format(new Date(data.profile.memberSince));return <div className={styles.page}><SiteHeader/><main className={styles.shell}><a href="/" className={styles.back}>← Retour aux annonces</a><section className={styles.hero}><div className={styles.avatar}>{data.profile.avatarUrl?<img src={data.profile.avatarUrl} alt=""/>:data.profile.name.slice(0,2).toUpperCase()}</div><div><div className={styles.titleRow}><h1>{data.profile.name}</h1>{data.profile.verified&&<span className={styles.verified}>✓ Vérifié</span>}</div><p>{data.profile.kind==="PROFESSIONNEL"?"Professionnel":"Particulier"} · Membre depuis {joined}</p><div className={styles.stats}><div><strong>{data.summary.average!=null?data.summary.average.toFixed(1):"—"}</strong><span>Note moyenne</span></div><div><strong>{data.summary.count}</strong><span>Avis</span></div><div><strong>{data.profile.activeListings}</strong><span>Annonces actives</span></div></div></div></section><section className={styles.card}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Réputation</p><h2>Avis après transaction</h2></div>{data.summary.average!=null&&<div className={styles.score}>{data.summary.average.toFixed(1)} ★</div>}</div>{!data.reviews.length?<div className={styles.empty}>Aucun avis pour le moment.</div>:<div className={styles.reviews}>{data.reviews.map(review=><article key={review.id} className={styles.review}><div className={styles.reviewTop}><strong>{stars(review.rating)}</strong><span>{new Intl.DateTimeFormat("fr-FR").format(new Date(review.createdAt))}</span></div>{review.comment&&<p>{review.comment}</p>}<small>Par {review.reviewerName} · Transaction vérifiée</small></article>)}</div>}</section></main></div>}
