"use client";
import {useEffect,useMemo,useState} from "react";
import {ProfessionalWorkspace} from "../../components/professional-workspace";
import {AppIcon} from "../../components/app-icon";
import {formatListingPrice} from "../../lib/listing-price";
import {fetchWithRetry} from "../../lib/fetch-resilient";
import styles from "./page.module.css";

type Data={user:{name:string;email:string;avatarUrl:string|null};business:any;subscription:any;stats:{activeListings:number;totalListings:number;draftListings:number;pendingListings:number;soldListings:number;unreadConversations:number;pendingOffers:number;stores:number;maxStores:number;orders:number;completedOrders:number;sellerRevenueMinor:number;reviewCount:number;reviewAverage:number|null;trustScore:number;trustLevel:string;verified:boolean};stores:Array<{id:string;name:string;slug:string;status:string;isVerified:boolean;logoUrl:string|null;city:string|null;_count:{listings:number}}>;recentListings:Array<{id:string;title:string|null;slug:string|null;status:string;priceMinor:number|null;currency:string;city:string|null;imageUrl:string|null;store:{name:string}|null;category:{name:string;domain:string};property?:{transactionType?:string|null}|null}>;recentOrders:Array<{id:string;orderNumber:string;status:string;sellerNetMinor:number;currency:string;createdAt:string;listingTitle:string|null}>};
type AnalyticsMini={engagement:{favorites:number;conversations:number;pendingOffers:number};sales:{orders:number;completed:number;revenueMinor:number};topListings:Array<{id:string;title:string|null;slug:string|null;status:string;favorites:number;conversations:number;orders:number;revenueMinor:number}>};
type SuiteOverview={sector:"IMMOBILIER"|"AUTOMOBILE"|"COMMERCE"|"VACANCES"|"SERVICES"|"GENERAL";features:{crm:boolean;appointments:boolean;team:boolean;reservations:boolean;feed:boolean;sales:boolean};leads:Record<string,number>;appointments:{upcoming:number;today:number};team:{active:number;pending:number};feed:{items:number;lastSeenAt:string|null};access:{role:string;isOwner:boolean;permissions:string[]}};
function api(){return (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"")}
function money(n:number,c="EUR"){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:c,maximumFractionDigits:0}).format((n||0)/100)}
const statusLabel:Record<string,string>={DRAFT:"Brouillon",PENDING:"En validation",PUBLISHED:"En ligne",SUSPENDED:"Suspendue",SOLD:"Vendue",EXPIRED:"Expirée"};
const orderStatusLabel:Record<string,string>={PENDING:"En attente",PAID:"Payée",PROCESSING:"En préparation",SHIPPED:"Expédiée",DELIVERED:"Livrée",COMPLETED:"Terminée",CANCELED:"Annulée",REFUNDED:"Remboursée",DISPUTED:"Litige"};
export default function ProDashboard(){
 const[data,setData]=useState<Data|null>(null),[analytics,setAnalytics]=useState<AnalyticsMini|null>(null),[suite,setSuite]=useState<SuiteOverview|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([fetchWithRetry(`${api()}/pro/dashboard`,{credentials:"include",cache:"no-store"},{timeoutMs:7000,retries:1}),fetchWithRetry(`${api()}/pro/analytics?days=30`,{credentials:"include",cache:"no-store"},{timeoutMs:7000,retries:1}),fetchWithRetry(`${api()}/pro/suite/overview`,{credentials:"include",cache:"no-store"},{timeoutMs:7000,retries:1})]).then(async([r,a,s])=>{if(r.status===401){location.href="/connexion?next=%2Fespace-pro";return null}if(r.status===403){location.href="/professionnels";return null}if(!r.ok)throw new Error();return{dashboard:await r.json() as Data,analytics:a.ok?await a.json() as AnalyticsMini:null,suite:s.ok?await s.json() as SuiteOverview:null}}).then(p=>{if(p){setData(p.dashboard);setAnalytics(p.analytics);setSuite(p.suite)}}).catch(()=>setError("Impossible de charger votre espace professionnel.")).finally(()=>setLoading(false))},[]);
 const priorities=useMemo(()=>{if(!data)return[] as Array<{title:string;text:string;href:string;icon:"user-shield"|"store"|"plus"|"comments"|"handshake"}>;const p:Array<{title:string;text:string;href:string;icon:"user-shield"|"store"|"plus"|"comments"|"handshake"}>=[];if(data.business?.verificationStatus!=="VERIFIED")p.push({title:"Vérifier mon entreprise",text:"Complétez votre SIRET pour renforcer la confiance.",href:"/espace-pro/entreprise",icon:"user-shield"});if(!data.stores.length)p.push({title:"Créer ma boutique",text:"Ajoutez une vitrine professionnelle à vos annonces.",href:"/espace-pro/boutiques",icon:"store"});if(data.stats.activeListings===0)p.push({title:"Publier une annonce",text:"Votre catalogue n’a aucune annonce active.",href:"/deposer-une-annonce",icon:"plus"});if(data.stats.unreadConversations>0)p.push({title:"Répondre aux messages",text:`${data.stats.unreadConversations} conversation(s) attendent une réponse.`,href:"/espace-pro/messages",icon:"comments"});if(data.stats.pendingOffers>0)p.push({title:"Traiter les offres",text:`${data.stats.pendingOffers} offre(s) sont en attente.`,href:"/espace-pro/messages",icon:"handshake"});return p.slice(0,4)},[data]);
 return <ProfessionalWorkspace summary={data}><div className={styles.shell}>
  {error?<div className={styles.error}>{error}</div>:loading?<div className={styles.loading}><i/><i/><i/><i/><i/></div>:data&&<>
   <header className={styles.hero}><div><span className={styles.kicker}>Petit Annonces Business</span><h1>Bonjour {data.user.name?.split(" ")[0]||"Pro"}</h1><p>Voici l’essentiel de votre activité, sans les informations secondaires.</p><div className={styles.heroMeta}><span>{data.business?.verificationStatus==="VERIFIED"?"✓ Entreprise vérifiée":"Vérification à compléter"}</span><span>{data.subscription?.plan?.name??"Compte Pro"}</span></div></div><div className={styles.heroActions}><a className={styles.secondary} href="/espace-pro/compte"><AppIcon name="user"/> Mon compte Pro</a><a className={styles.primary} href="/deposer-une-annonce"><AppIcon name="plus"/> Nouvelle annonce</a></div></header>

   <section className={styles.kpis}>
    <a href="/espace-pro/annonces"><i><AppIcon name="list"/></i><div><small>Annonces actives</small><strong>{data.stats.activeListings}</strong><span>{data.stats.pendingListings} en validation · {data.stats.draftListings} brouillon(s)</span></div></a>
    <a href="/espace-pro/messages"><i><AppIcon name="comments"/></i><div><small>Messages non lus</small><strong>{data.stats.unreadConversations}</strong><span>{data.stats.pendingOffers} offre(s) à traiter</span></div></a>
    <a href="/espace-pro/ventes"><i><AppIcon name="credit-card"/></i><div><small>Ventes terminées</small><strong>{data.stats.completedOrders}</strong><span>{data.stats.orders} commande(s) au total</span></div></a>
    <a href="/espace-pro/analytics"><i><AppIcon name="wallet"/></i><div><small>Chiffre vendeur</small><strong>{money(data.stats.sellerRevenueMinor)}</strong><span>Performance globale du compte</span></div></a>
   </section>

   <section className={styles.quick}><a href="/espace-pro/messages"><AppIcon name="comments"/><span>Messages</span></a><a href="/espace-pro/annonces"><AppIcon name="list"/><span>Annonces</span></a><a href="/espace-pro/boutiques"><AppIcon name="store"/><span>Boutique</span></a><a href="/espace-pro/analytics"><AppIcon name="gauge"/><span>Statistiques</span></a>{suite?.features.crm&&<a href="/espace-pro/crm"><AppIcon name="handshake"/><span>CRM</span></a>}{suite?.features.appointments&&<a href="/espace-pro/rendez-vous"><AppIcon name="calendar"/><span>Rendez-vous</span></a>}<a href="/espace-pro/visibilite"><AppIcon name="sparkles"/><span>Visibilité</span></a></section>

   <div className={styles.mainGrid}><div className={styles.mainCol}>
    <section className={styles.panel}><div className={styles.panelHead}><div><span>À faire maintenant</span><h2>Priorités</h2></div>{priorities.length===0&&<b className={styles.ok}><AppIcon name="circle-check"/> Tout est à jour</b>}</div>{priorities.length?<div className={styles.priorityList}>{priorities.map(x=><a key={x.href+x.title} href={x.href}><i><AppIcon name={x.icon}/></i><div><strong>{x.title}</strong><span>{x.text}</span></div><b>›</b></a>)}</div>:<div className={styles.goodState}><AppIcon name="circle-check"/><div><strong>Aucune action urgente</strong><span>Votre compte professionnel est correctement configuré.</span></div></div>}</section>

    <section className={styles.panel}><div className={styles.panelHead}><div><span>Catalogue</span><h2>Annonces récentes</h2></div><a href="/espace-pro/annonces">Voir toutes →</a></div><div className={styles.listings}>{data.recentListings.slice(0,5).map(l=><a key={l.id} href={l.slug?`/annonce/${l.slug}`:`/deposer-une-annonce?listingId=${encodeURIComponent(l.id)}`}><div className={styles.thumb}>{l.imageUrl?<img src={l.imageUrl} alt=""/>:<AppIcon name="image"/>}</div><div><strong>{l.title??"Annonce sans titre"}</strong><span>{l.category.name}{l.city?` · ${l.city}`:""}</span><b>{formatListingPrice(l.priceMinor,l.currency,{domain:l.category.domain,transactionType:l.property?.transactionType??null},"Prix non défini")}</b></div><em className={`${styles.status} ${styles[`s${l.status}`]??""}`}>{statusLabel[l.status]??l.status}</em></a>)}{!data.recentListings.length&&<div className={styles.empty}><AppIcon name="list"/><strong>Aucune annonce</strong><span>Publiez votre première annonce professionnelle.</span><a href="/deposer-une-annonce">Créer une annonce</a></div>}</div></section>
   </div>

   <aside className={styles.sideCol}>
    <section className={styles.panel}><div className={styles.panelHead}><div><span>30 derniers jours</span><h2>Performance</h2></div><a href="/espace-pro/analytics">Détails →</a></div><div className={styles.performance}><div><small>Favoris</small><strong>{analytics?.engagement.favorites??0}</strong></div><div><small>Conversations</small><strong>{analytics?.engagement.conversations??0}</strong></div><div><small>Commandes</small><strong>{analytics?.sales.orders??0}</strong></div><div><small>CA période</small><strong>{money(analytics?.sales.revenueMinor??0)}</strong></div></div></section>

    <section className={styles.panel}><div className={styles.panelHead}><div><span>Compte</span><h2>Profil professionnel</h2></div><strong className={styles.score}>{data.stats.trustScore}/100</strong></div><div className={styles.progress}><i style={{width:`${Math.max(0,Math.min(100,data.stats.trustScore))}%`}}/></div><div className={styles.profileRows}><span><small>Entreprise</small><b>{data.business?.verificationStatus==="VERIFIED"?"Vérifiée":"À compléter"}</b></span><span><small>Réputation</small><b>{data.stats.reviewCount} avis</b></span><span><small>Boutiques</small><b>{data.stats.stores}</b></span></div><a className={styles.accountLink} href="/espace-pro/compte">Gérer mon compte Pro →</a></section>

    <section className={styles.panel}><div className={styles.panelHead}><div><span>Vitrines</span><h2>Mes boutiques</h2></div><a href="/espace-pro/boutiques">Gérer →</a></div><div className={styles.stores}>{data.stores.slice(0,3).map(s=><a key={s.id} href={s.status==="ACTIVE"?`/boutique/${s.slug}`:"/espace-pro/boutiques"}><i>{s.logoUrl?<img src={s.logoUrl} alt=""/>:<AppIcon name="store"/>}</i><div><strong>{s.name}</strong><span>{s._count.listings} annonce(s){s.city?` · ${s.city}`:""}</span></div><b>›</b></a>)}{!data.stores.length&&<div className={styles.miniEmpty}>Aucune boutique configurée.</div>}</div></section>
   </aside></div>

   <section className={styles.panel}><div className={styles.panelHead}><div><span>Transactions</span><h2>Dernières ventes</h2></div><a href="/espace-pro/ventes">Voir toutes →</a></div><div className={styles.orders}>{data.recentOrders.slice(0,4).map(o=><a href={`/commandes/${o.id}`} key={o.id}><span>{o.orderNumber}</span><strong>{o.listingTitle??"Commande"}</strong><small>{new Date(o.createdAt).toLocaleDateString("fr-FR",{timeZone:"Europe/Paris"})} · {orderStatusLabel[o.status]??o.status}</small><b>{money(o.sellerNetMinor,o.currency)}</b></a>)}{!data.recentOrders.length&&<div className={styles.miniEmpty}>Aucune vente enregistrée pour le moment.</div>}</div></section>
  </>}
 </div></ProfessionalWorkspace>
}
