import {LegalPage} from "../../components/legal-page";
export const metadata={title:"Politique de confidentialité | Petit Annonces",alternates:{canonical:"/confidentialite"}};
export default function Page(){const sections=[
{id:"donnees",title:"Données que nous traitons",body:"Petit Annonces traite les données nécessaires au fonctionnement du compte et de la marketplace : informations de compte et de profil, annonces, favoris, recherches, messages, commandes, support, sécurité, modération et informations professionnelles lorsque cela est nécessaire.",bullets:["Données d'identification et de contact fournies par l'utilisateur.","Contenu des annonces, photos, catégories et localisation renseignée.","Historique des commandes, statuts de livraison et références de paiement.","Données de sécurité telles que sessions, événements de connexion et signaux anti-fraude.","Données techniques nécessaires au service et à sa sécurité, pouvant inclure adresse IP, user-agent, identifiants de session, token de notification push, plateforme et libellé de l’appareil."]},
{id:"finalites",title:"Pourquoi ces données sont utilisées",body:"Les traitements sont réalisés pour fournir le service, sécuriser les comptes, permettre les échanges et transactions, répondre au support, prévenir la fraude, assurer la modération et respecter les obligations légales applicables.",bullets:["Exécution du service demandé par l'utilisateur.","Respect d'obligations légales ou réglementaires.","Intérêt légitime lié à la sécurité, la prévention de la fraude et l'amélioration du service, lorsque ce fondement est approprié.","Consentement lorsque celui-ci est requis, notamment pour certains traceurs non essentiels."]},
{id:"paiement",title:"Paiements et données bancaires",body:"Les paiements par carte sont traités par un prestataire spécialisé. Petit Annonces ne doit pas stocker les données complètes de carte lorsque le prestataire de paiement les traite directement. Les informations nécessaires au suivi d'une transaction, d'un remboursement ou d'un versement peuvent être conservées.",note:"Les coordonnées de versement vendeur sont protégées et ne doivent pas être exposées en clair dans l'interface ou les journaux techniques."},
{id:"partage",title:"Destinataires et sous-traitants",body:"Les données ne sont partagées qu'avec les personnes ou prestataires qui en ont besoin pour exécuter leur mission : hébergement, stockage de médias, paiement, livraison, e-mail, sécurité, support ou obligations réglementaires.",bullets:["Chaque prestataire ne reçoit que les données nécessaires à sa mission.","Pour préparer une livraison, le prestataire de transport peut recevoir les informations nécessaires de l’expéditeur et du destinataire : nom, adresse, code postal, ville, pays et, lorsque nécessaire, téléphone et e-mail.","Pour délivrer des notifications, les services push peuvent recevoir un token technique, la plateforme et des informations limitées sur l’appareil nécessaires à l’acheminement.","Les accès internes sont limités selon les rôles et besoins opérationnels.","Les transferts internationaux, lorsqu’ils existent, doivent être encadrés par un mécanisme juridique approprié." ]},
{id:"conservation",title:"Durées de conservation",body:"Les durées varient selon la nature des données. Les informations actives sont conservées pendant la relation avec l'utilisateur, puis certaines données peuvent être archivées pendant la durée nécessaire à la preuve, à la sécurité, à la comptabilité, au traitement des litiges ou aux obligations légales.",bullets:["Les données inutiles ne doivent pas être conservées indéfiniment.","Des délais spécifiques peuvent s'appliquer aux factures, transactions, signalements ou obligations fiscales.","Les données de sécurité peuvent être conservées pendant une durée proportionnée au risque.","Les journaux d’accès HTTP du serveur sont actuellement configurés avec une rotation quotidienne et jusqu’à 14 rotations ; certains contrôles anti-abus conservent plutôt une empreinte cryptographique de l’adresse IP que l’adresse en clair." ]},
{id:"droits",title:"Vos droits RGPD",body:"Selon votre situation et le fondement du traitement, vous pouvez demander l'accès, la rectification, l'effacement, la limitation, l'opposition ou la portabilité de certaines données.",bullets:["Une vérification d'identité peut être demandée avant de traiter une demande sensible.","Certaines données ne peuvent pas être supprimées immédiatement lorsqu'une obligation légale de conservation s'applique.","Vous pouvez contacter le service client pour exercer vos droits et, si nécessaire, saisir l'autorité de contrôle compétente." ]},
{id:"securite",title:"Sécurité et confidentialité",body:"Petit Annonces applique des mesures techniques et organisationnelles visant à limiter les accès non autorisés, détecter les comportements suspects et réduire l'exposition des données personnelles.",bullets:["Sessions sécurisées et révocables.","Journalisation des actions administratives sensibles.","Protection des secrets et données de paiement.","Procédures de réponse aux incidents lorsque nécessaire." ]},
{id:"mineurs",title:"Utilisateurs mineurs et données sensibles",body:"Le service ne doit pas encourager la collecte de données sensibles ou inutiles. Les utilisateurs ne doivent pas publier dans une annonce des documents d'identité, mots de passe, codes de sécurité, coordonnées bancaires complètes ou informations privées sans nécessité légitime."}
];return <LegalPage eyebrow="Vie privée" title="Politique de confidentialité" intro="Comment Petit Annonces collecte, utilise, protège et conserve les données nécessaires au fonctionnement de la plateforme et à la sécurité de ses utilisateurs." updated="11 septembre 2026" sections={sections}/>;}
