"use client";
import {useEffect,useState} from "react";
type Row={id:string;providerReference:string|null;clientReference:string;hotelCode:number;hotelName:string|null;city:string|null;imageUrl:string|null;checkIn:string;checkOut:string;guests:number;status:string;environment:string;currency:string|null;total:number|null;createdAt:string;updatedAt:string;email:string;userName:string|null};
type Payload={items:Row[];page:number;limit:number;total:number;stats:{total:number;confirmed:number;pending:number;attention:number;volume:number}};
function date(v:string){return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v.length===10?v+"T12:00:00":v))}
function money(v:number,c="EUR"){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:c}).format(v)}
function badge(status:string){const s=status.toUpperCase();return s==="CONFIRMED"||s==="OK"?"green":s==="FAILED"||s==="UNKNOWN"?"red":s==="PENDING"?"orange":""}
export default function HbxBookingsClient(){
 const[data,setData]=useState<Payload>({items:[],page:1,limit:30,total:0,stats:{total:0,confirmed:0,pending:0,attention:0,volume:0}}),[busy,setBusy]=useState(true),[status,setStatus]=useState("ALL"),[query,setQuery]=useState(""),[page,setPage]=useState(1),[message,setMessage]=useState("");
 async function load(targetPage=page){setBusy(true);setMessage("");try{const q=new URLSearchParams({status,query,page:String(targetPage),limit:"30"});const r=await fetch("/api/admin/hbx/bookings?"+q.toString(),{credentials:"include",cache:"no-store"});const p=await r.json().catch(()=>null) as Payload|null;if(!r.ok||!p){setMessage(r.status===403?"Vous n’avez pas accès aux réservations HBX.":"Impossible de charger les réservations HBX.");return}setData(p);setPage(p.page)}catch{setMessage("Connexion interrompue pendant le chargement.")}finally{setBusy(false)}}
 useEffect(()=>{void load(1)},[]);
 function submit(e:React.FormEvent){e.preventDefault();void load(1)}
 const pages=Math.max(1,Math.ceil(data.total/Math.max(1,data.limit)));
 return <><div className="admin-page-head"><div><p>Vacances · Hotelbeds</p><h1>Réservations HBX</h1><span className="subtitle">Suivez les réservations hôtels partenaires, leurs références fournisseur et les opérations TEST/LIVE.</span></div><button type="button" className="admin-btn" onClick={()=>void load()}>{busy?"Actualisation…":"Actualiser"}</button></div>
 <div className="admin-grid admin-kpis"><article className="admin-card admin-kpi"><small>Total réservations</small><strong>{data.stats.total}</strong><p>Tous environnements</p></article><article className="admin-card admin-kpi"><small>Confirmées</small><strong>{data.stats.confirmed}</strong><p>Références HBX reçues</p></article><article className="admin-card admin-kpi"><small>À surveiller</small><strong>{data.stats.pending+data.stats.attention}</strong><p>{data.stats.attention} erreur(s) / statut inconnu</p></article><article className="admin-card admin-kpi"><small>Volume confirmé</small><strong>{money(Number(data.stats.volume||0))}</strong><p>Valeur fournisseur enregistrée</p></article></div>
 <section className="admin-card admin-section" style={{marginTop:16}}><form className="admin-toolbar" onSubmit={submit}><input className="admin-input admin-search" placeholder="Référence HBX, PA, hôtel ou e-mail…" value={query} onChange={e=>setQuery(e.target.value)}/><select className="admin-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Tous les statuts</option><option value="CONFIRMED">Confirmées</option><option value="PENDING">En attente</option><option value="UNKNOWN">À vérifier</option><option value="FAILED">Échecs</option><option value="CANCELLED">Annulées</option></select><button className="admin-btn primary" type="submit">Filtrer</button></form>
 {message&&<div className="admin-flash err">{message}</div>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Hôtel</th><th>Voyageur</th><th>Séjour</th><th>Références</th><th>Statut</th><th>Total</th><th>Env.</th><th></th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td><div style={{display:"flex",alignItems:"center",gap:10}}>{item.imageUrl?<img className="thumb" src={item.imageUrl} alt=""/>:<span className="thumb" style={{display:"grid",placeItems:"center"}}>🏨</span>}<div><strong>{item.hotelName??("Hôtel #"+item.hotelCode)}</strong><small style={{display:"block",color:"#858494"}}>{item.city??"France"}</small></div></div></td><td><strong>{item.userName??"Membre"}</strong><small style={{display:"block",color:"#858494"}}>{item.email}</small></td><td>{date(item.checkIn)} → {date(item.checkOut)}<small style={{display:"block",color:"#858494"}}>{item.guests} voyageur(s)</small></td><td><strong>{item.providerReference??"—"}</strong><small style={{display:"block",color:"#858494"}}>{item.clientReference}</small></td><td><span className={"admin-badge "+badge(item.status)}>{item.status}</span></td><td>{item.total!=null?money(Number(item.total),item.currency??"EUR"):"—"}</td><td><span className="admin-badge">{item.environment.toUpperCase()}</span></td><td><a className="admin-btn" href={"/hbx-bookings/"+encodeURIComponent(item.providerReference??item.clientReference)}>Ouvrir</a></td></tr>)}{!busy&&!data.items.length&&<tr><td colSpan={8}><div className="admin-empty">Aucune réservation HBX pour ces critères.</div></td></tr>}</tbody></table></div>
 <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,marginTop:14}}><button className="admin-btn" disabled={page<=1||busy} onClick={()=>void load(page-1)}>← Précédent</button><span style={{fontSize:12,color:"#777"}}>Page {page} / {pages} · {data.total} résultat(s)</span><button className="admin-btn" disabled={page>=pages||busy} onClick={()=>void load(page+1)}>Suivant →</button></div></section></>
}
