"use client";
import {useEffect,useMemo,useState} from "react";

type Data={days:number;summary:{total:number;loggedTotal:number;removedListings:number;leboncoin:number;uniqueUsers:number;published:number;completeLocation:number;goodDescription:number;goodTitle:number;withPrice:number;withPhotos:number;goodPhotos:number;avgPhotos:number;lowQualityRecent:number};sources:Array<{source:string;label:string;total:number;published:number;avgPhotos:number}>;statuses:Array<{status:string;count:number}>;categories:Array<{name:string;slug:string;count:number;published:number}>;daily:Array<{day:string;imports:number;leboncoin:number;published:number}>;recent:Array<{id:string;listingId:string;source:string;sourceLabel:string;sourceUrl:string|null;createdAt:string;title:string|null;city:string|null;postalCode:string|null;status:string;slug:string|null;publishedAt:string|null;category:{name:string;slug:string};seller:{name:string;email:string};mediaCount:number;qualityScore:number;qualityIssues:string[]}>};
const n=(v:number)=>Number(v||0).toLocaleString("fr-FR");
const pct=(a:number,b:number)=>b>0?`${Math.round(a/b*100)}%`:"0%";
function statusLabel(value:string){return ({DRAFT:"Brouillon",PENDING_REVIEW:"En modération",PUBLISHED:"Publié",REJECTED:"Refusé",EXPIRED:"Expiré",DELETED:"Supprimé"} as Record<string,string>)[value]??value}

export default function ImportsClient(){
 const[days,setDays]=useState(30),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");const[reload,setReload]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError("");fetch(`/api/admin/import-health?days=${days}`,{credentials:"include",cache:"no-store"}).then(async r=>{const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.message??p.error??"import_health_unavailable");if(active)setData(p)}).catch(e=>{if(active){setData(null);setError(e instanceof Error?e.message:"import_health_unavailable")}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[days,reload]);
 const max=useMemo(()=>Math.max(1,...(data?.daily??[]).map(r=>Math.max(r.imports,r.published))),[data]);
 const s=data?.summary;
 return <div className="admin-import-health-page">
  <div className="admin-page-head"><div><p>Qualité & acquisition</p><h1>Santé des imports</h1><span className="subtitle">Suivez les imports d’annonces, avec un focus Leboncoin : volume, qualité des données, photos, publication et anomalies à corriger.</span></div><div className="admin-import-health-actions"><select className="admin-select" value={days} onChange={e=>setDays(Number(e.target.value))}><option value="7">7 jours</option><option value="30">30 jours</option><option value="90">90 jours</option></select><button type="button" className="admin-btn" onClick={()=>setReload(v=>v+1)} disabled={loading}>{loading?"Chargement…":"Actualiser"}</button></div></div>
  {error&&<div className="admin-flash err">Impossible de charger les imports : {error}</div>}
  <div className="admin-grid admin-kpis admin-import-health-kpis">
   <article className="admin-card admin-kpi"><small>Imports enregistrés</small><strong>{loading?"…":n(s?.loggedTotal??0)}</strong><p>{n(s?.total??0)} annonce(s) encore présente(s) · {n(s?.removedListings??0)} supprimée(s)</p></article>
   <article className="admin-card admin-kpi"><small>Leboncoin</small><strong>{loading?"…":n(s?.leboncoin??0)}</strong><p>{pct(s?.leboncoin??0,s?.total??0)} du volume importé</p></article>
   <article className="admin-card admin-kpi"><small>Imports publiés</small><strong>{loading?"…":n(s?.published??0)}</strong><p>{pct(s?.published??0,s?.total??0)} import → publication</p></article>
   <article className="admin-card admin-kpi"><small>Photos moyennes</small><strong>{loading?"…":(s?.avgPhotos??0).toLocaleString("fr-FR",{maximumFractionDigits:1})}</strong><p>{pct(s?.goodPhotos??0,s?.total??0)} avec au moins 3 photos</p></article>
  </div>
  <p className="admin-import-health-note">Les ratios de qualité, Leboncoin et publication utilisent les imports dont l’annonce existe encore. Les imports supprimés restent comptés dans « Imports enregistrés » pour conserver l’historique.</p>

  <section className="admin-card admin-section" style={{marginTop:16}}><div className="admin-section-head"><div><h2>Qualité des imports</h2><p>Mesure directement les champs du brouillon créé, sans estimation externe.</p></div><span className={`admin-badge ${(s?.lowQualityRecent??0)>0?"orange":"green"}`}>{s?.lowQualityRecent??0} alerte(s) récente(s)</span></div><div className="admin-grid admin-import-quality-grid">
   {[['Localisation complète',s?.completeLocation??0],['Avec photo',s?.withPhotos??0],['3 photos ou plus',s?.goodPhotos??0],['Description ≥ 80 caractères',s?.goodDescription??0],['Titre exploitable',s?.goodTitle??0],['Prix renseigné',s?.withPrice??0]].map(([label,value])=><div className="admin-import-quality" key={String(label)}><div><strong>{label}</strong><span>{pct(Number(value),s?.total??0)}</span></div><div className="admin-import-progress"><i style={{width:pct(Number(value),s?.total??0)}}/></div><small>{n(Number(value))} / {n(s?.total??0)}</small></div>)}
  </div></section>

  <div className="admin-grid admin-two-col" style={{marginTop:16}}>
   <section className="admin-card admin-section"><div className="admin-section-head"><div><h2>Volume quotidien</h2><p>Imports créés et annonces importées ensuite publiées.</p></div></div><div className="admin-mini-chart admin-import-chart">{(data?.daily??[]).map(r=><div className="admin-chart-day" key={r.day} title={`${r.day} · ${r.imports} imports · ${r.published} publiés`}><div className="admin-chart-bars"><i style={{height:`${Math.max(2,r.imports/max*100)}%`}}/><i style={{height:`${Math.max(2,r.published/max*100)}%`}}/></div><small>{new Date(`${r.day}T00:00:00`).toLocaleDateString("fr-FR",{day:"2-digit",month:"2-digit"})}</small></div>)}</div><div className="admin-chart-legend"><span><i/> Imports</span><span><i/> Publiés</span></div></section>
   <aside className="admin-card admin-section"><div className="admin-section-head"><div><h2>Sources</h2><p>Origine des annonces importées.</p></div></div><div className="admin-stack-list">{(data?.sources??[]).map(r=><div className="admin-order-row admin-import-source-row" key={r.source}><div><strong>{r.label}</strong><small>{r.avgPhotos.toLocaleString("fr-FR",{maximumFractionDigits:1})} photo(s) en moyenne</small></div><b>{n(r.total)} · {pct(r.published,r.total)} publiés</b></div>)}</div></aside>
  </div>

  <div className="admin-grid admin-two-col" style={{marginTop:16}}>
   <section className="admin-card admin-section"><div className="admin-section-head"><div><h2>Catégories importées</h2><p>Les catégories qui reçoivent le plus d’annonces importées.</p></div></div><div className="admin-stack-list">{(data?.categories??[]).map(r=><div className="admin-order-row admin-import-source-row" key={r.slug}><div><strong>{r.name}</strong><small>{r.slug}</small></div><b>{n(r.count)} · {pct(r.published,r.count)} publiés</b></div>)}</div></section>
   <section className="admin-card admin-section"><div className="admin-section-head"><div><h2>Statut des annonces importées</h2><p>Situation actuelle des annonces créées depuis un import.</p></div></div><div className="admin-stack-list">{(data?.statuses??[]).map(r=><div className="admin-order-row admin-import-source-row" key={r.status}><div><strong>{statusLabel(r.status)}</strong><small>{r.status}</small></div><b>{n(r.count)}</b></div>)}</div></section>
  </div>

  <section className="admin-card admin-section" style={{marginTop:16}}><div className="admin-section-head"><div><h2>Derniers imports</h2><p>Les imports incomplets apparaissent immédiatement grâce au score qualité.</p></div></div><div className="admin-table-wrap"><table className="admin-table admin-mobile-cards admin-import-table"><thead><tr><th>Annonce</th><th>Source</th><th>Utilisateur</th><th>Catégorie</th><th>Localisation</th><th>Photos</th><th>Qualité</th><th>Statut</th><th>Importé le</th></tr></thead><tbody>{(data?.recent??[]).map(r=><tr key={r.id}><td data-label="Annonce"><a href={`/listings/${r.listingId}`} className="admin-import-listing-link"><strong>{r.title??"Annonce sans titre"}</strong><small>{r.listingId}</small></a></td><td data-label="Source"><span className={`admin-badge ${r.source==="LEBONCOIN"?"green":""}`}>{r.sourceLabel}</span></td><td data-label="Utilisateur"><strong>{r.seller.name}</strong><small>{r.seller.email}</small></td><td data-label="Catégorie">{r.category.name}</td><td data-label="Localisation">{[r.postalCode,r.city].filter(Boolean).join(" ")||"—"}</td><td data-label="Photos">{r.mediaCount}</td><td data-label="Qualité"><span className={`admin-badge ${r.qualityScore>=85?"green":r.qualityScore>=70?"":"orange"}`}>{r.qualityScore}/100</span>{r.qualityIssues.length>0&&<small className="admin-import-issues">{r.qualityIssues.join(" · ")}</small>}</td><td data-label="Statut"><span className={`admin-badge ${r.publishedAt?"green":"orange"}`}>{statusLabel(r.status)}</span></td><td data-label="Importé le">{new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Paris"}).format(new Date(r.createdAt))}</td></tr>)}{!loading&&!(data?.recent?.length)&&<tr><td colSpan={9}><div className="admin-empty">Aucun import sur cette période.</div></td></tr>}</tbody></table></div></section>
 </div>
}
