import {LegalPage} from "../../components/legal-page";
export const metadata={title:"Classement, référencement et mises en avant | Petit Annonces",alternates:{canonical:"/classement-referencement"}};
export default function Page(){const sections=[
{id:"referencement",title:"Conditions de référencement",body:"Une annonce peut être référencée dans Petit Annonces lorsqu’elle est publiée, rattachée à une catégorie active et respecte les règles de contenu, de sécurité, de conformité et de modération applicables.",bullets:["Les annonces en brouillon, en attente de correction, suspendues, expirées, vendues ou supprimées ne sont pas présentées comme des annonces actives dans la recherche publique.","La plateforme peut refuser ou retirer un contenu illicite, trompeur, dangereux, contrefait, interdit, dupliqué de manière abusive ou contraire aux Conditions générales.","Les annonces professionnelles doivent respecter les obligations d’identification et d’information qui leur sont applicables."]},
{id:"classement",title:"Classement par défaut",body:"Le tri par défaut « Plus récentes » privilégie principalement la date de publication ou de remise en avant, sous réserve des filtres choisis par l’utilisateur et des emplacements de mise en avant décrits ci-dessous.",bullets:["Lorsqu’une recherche textuelle utilise un moteur de pertinence, la correspondance avec les mots recherchés peut être prise en compte avant la récence.","Les filtres de catégorie, ville, prix, distance et caractéristiques réduisent d’abord l’ensemble des annonces éligibles.","L’utilisateur peut choisir un tri par prix croissant ou décroissant ; dans ce cas, le prix devient le critère principal et la récence départage certains résultats."]},
{id:"payant",title:"Mises en avant payantes",body:"Petit Annonces commercialise des options de visibilité. Une rémunération peut donc influencer la place de certaines annonces dans les résultats lorsque le vendeur active une option de mise en avant.",bullets:["Les promotions de type remontée, sponsorisée ou à la une peuvent occuper des emplacements dédiés dans le flux des résultats récents.","Le type de promotion, sa priorité et sa date d’activation déterminent l’ordre entre annonces promues éligibles.","Une annonce bénéficiant d’une promotion affiche un badge de visibilité afin que l’utilisateur puisse identifier cette influence commerciale.","Le paiement d’une promotion ne permet pas de contourner les règles de modération, de conformité ou d’éligibilité."]},
{id:"liens",title:"Relations contractuelles et capitalistiques",body:"Petit Annonces peut avoir une relation contractuelle avec un vendeur professionnel ou percevoir une rémunération pour un abonnement ou une option de visibilité. Cette relation n’accorde pas un droit général à un meilleur classement en dehors des mécanismes de visibilité explicitement prévus. Petit Annonces n’indique pas détenir de participation capitalistique dans les vendeurs référencés."},
{id:"dereferencement",title:"Déréférencement et restrictions",body:"Une annonce peut être déréférencée ou perdre de la visibilité lorsqu’elle expire, est vendue, retirée par son auteur, fait l’objet d’une mesure de modération, présente un risque de fraude ou de sécurité, ne respecte plus les règles de la catégorie ou doit être retirée en application d’une obligation légale.",bullets:["Lorsque la loi ou les règles applicables l’exigent, la décision peut être motivée et une voie de contestation peut être proposée.","Les produits dangereux peuvent être retirés ou faire l’objet d’un avertissement conformément aux règles de sécurité produit.","Les comptes présentant des violations répétées peuvent faire l’objet de restrictions proportionnées."]},
{id:"actualisation",title:"Actualisation des résultats",body:"Les résultats évoluent à mesure que des annonces sont publiées, modifiées, expirent, sont vendues, modérées ou promues. Les pages publiques peuvent utiliser un cache technique de courte durée pour améliorer les performances ; elles sont ensuite rafraîchies automatiquement."}
];return <LegalPage eyebrow="Transparence marketplace" title="Classement & référencement" intro="Comment les annonces sont référencées, classées, mises en avant et éventuellement déréférencées sur Petit Annonces." updated="26 septembre 2026" sections={sections}/>;}