"use client";

import { FormEvent, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { SiteHeader } from "../../components/site-header";
import styles from "../auth.module.css";

function apiBase(){return (process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000").replace(/\/$/,"")}

export default function ResetPasswordPage(){
  const search=useSearchParams();const token=useMemo(()=>search.get("token")??"",[search]);const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setError("");if(!token){setError("Lien de réinitialisation invalide.");return}if(password!==confirm){setError("Les mots de passe ne correspondent pas.");return}setBusy(true);try{const r=await fetch(`${apiBase()}/auth/reset-password`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,password})});if(!r.ok){const p=await r.json().catch(()=>({}));throw new Error(p.error??"reset_failed")}setDone(true)}catch(err){const code=err instanceof Error?err.message:"reset_failed";setError(code==="invalid_or_expired_token"?"Ce lien a expiré ou a déjà été utilisé.":"Impossible de modifier le mot de passe.")}finally{setBusy(false)}}
  return <div className={styles.page}><SiteHeader/><main className={styles.main}><div className={styles.authGrid}><section className={styles.formCard}><span className={styles.eyebrow}>Nouveau mot de passe</span><h1 className={styles.title}>Sécurisez de nouveau votre compte</h1><p className={styles.lead}>Choisissez un mot de passe d’au moins 10 caractères et différent de vos anciens mots de passe.</p>{error&&<div className={styles.error}>{error}</div>}{done?<div className={styles.success}><strong>Mot de passe modifié.</strong><br/>Vous pouvez maintenant vous reconnecter avec votre nouveau mot de passe.<br/><a className={styles.inlineLink} href="/connexion">Se connecter</a></div>:<form className={styles.form} onSubmit={submit}><label className={styles.field}>Nouveau mot de passe<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={10} required/></label><label className={styles.field}>Confirmer le mot de passe<input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={10} required/></label><button className={styles.primary} disabled={busy}>{busy?"Mise à jour…":"Modifier mon mot de passe"}</button></form>}<p className={styles.footText}><a href="/mot-de-passe-oublie">Demander un nouveau lien</a></p></section><aside className={styles.benefitCard}><span className={styles.eyebrow}>Bonnes pratiques</span><h2 className={styles.title}>Un compte mieux protégé en quelques secondes.</h2><p className={styles.lead}>Après la réinitialisation, toutes les anciennes sessions sont automatiquement déconnectées.</p><div className={styles.benefits}><div className={styles.benefit}><div className={styles.benefitIcon}>A1</div><div><strong>10 caractères minimum</strong><p>Une phrase de passe longue est plus facile à retenir et plus robuste.</p></div></div><div className={styles.benefit}><div className={styles.benefitIcon}>∞</div><div><strong>Mot de passe unique</strong><p>Évitez de réutiliser celui de votre e-mail ou d’un autre service.</p></div></div><div className={styles.benefit}><div className={styles.benefitIcon}>✓</div><div><strong>Sessions révoquées</strong><p>Les anciens appareils devront se reconnecter avec le nouveau mot de passe.</p></div></div></div></aside></div></main></div>
}
