"use client";

import { useEffect, useState } from "react";
import { SiteHeader } from "../../../components/site-header";
import styles from "./page.module.css";

type WalletPayload={wallet:{id:string;balance:number};transactions:Array<{id:string;type:string;amount:number;referenceType:string|null;referenceId:string|null;createdAt:string}>};
function apiBase(){return (process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000").replace(/\/$/,"")}
function label(type:string|null){if(type==="WELCOME_BONUS")return "Bonus de bienvenue";if(type==="LISTING_PROMOTION")return "Mise en avant d’annonce";if(type==="COUPON")return "Crédits coupon";if(type==="ADMIN")return "Ajustement Petit Annonces";return "Mouvement de crédits"}

export default function WalletPage(){
  const [data,setData]=useState<WalletPayload|null>(null);const [error,setError]=useState("");
  useEffect(()=>{fetch(`${apiBase()}/promotions/wallet`,{credentials:"include"}).then(async r=>{if(!r.ok)throw new Error("wallet_unavailable");return r.json() as Promise<WalletPayload>}).then(setData).catch(()=>setError("Connectez-vous pour consulter votre portefeuille PA."))},[]);
  return <div className={styles.page}><SiteHeader/><main className={styles.shell}><aside className={styles.side}><a href="/mon-compte">Vue d’ensemble</a><a href="/mon-compte/annonces">Mes annonces</a><a className={styles.active} href="/mon-compte/portefeuille">Portefeuille PA</a><a href="/mon-compte/parametres">Paramètres</a></aside><section className={styles.content}><div className={styles.heading}><span>Mes crédits</span><h1>Portefeuille PA</h1><p>Consultez vos crédits Petit Annonces et l’historique de leurs utilisations.</p></div>{error&&<div className={styles.error}>{error}</div>}<section className={styles.balance}><div><small>Solde disponible</small><strong>{data?.wallet.balance??0} PA</strong><p>Les crédits PA servent uniquement aux fonctionnalités éligibles de Petit Annonces, par exemple certaines options de mise en avant. Ils ne représentent pas de l’argent réel.</p></div><div className={styles.badge}>Usage plateforme uniquement</div></section><div className={styles.grid}><section className={styles.card}><h2>Historique des crédits</h2>{!data?<div className={styles.empty}>Chargement du portefeuille…</div>:data.transactions.length===0?<div className={styles.empty}>Aucun mouvement pour le moment.</div>:data.transactions.map(tx=><div className={styles.tx} key={tx.id}><div><strong>{label(tx.referenceType)}</strong><span>{new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(tx.createdAt))}</span></div><div className={`${styles.amount} ${tx.amount<0?styles.negative:""}`}>{tx.amount>0?"+":""}{tx.amount} PA</div></div>)}</section><aside className={`${styles.card} ${styles.info}`}><h2>Comment ça marche ?</h2><div><strong>20 PA offerts</strong><p>Chaque nouveau membre reçoit automatiquement 20 PA après la vérification de son adresse e-mail.</p></div><div><strong>Utilisation interne</strong><p>Les crédits sont utilisables uniquement dans Petit Annonces pour les services éligibles.</p></div><div><strong>Pas de retrait</strong><p>Les PA ne sont ni convertibles en euros, ni transférables vers un compte bancaire.</p></div><a className={styles.link} href="/deposer-une-annonce">Déposer une annonce →</a></aside></div></section></main></div>
}
