"use client";
import {useEffect,useMemo,useState} from "react";
import {AccountSidebar} from "../../../components/account-sidebar";
import {AppIcon} from "../../../components/app-icon";
import {fetchWithRetry} from "../../../lib/fetch-resilient";
import styles from "./page.module.css";

type CreditPackage={id:string;name:string;description:string|null;badge:string|null;creditMinor:number;priceMinor:number;currency:string;sortOrder:number;isActive:boolean};
type Data={wallet:{balanceMinor:number;currency:string};transactions:Array<{id:string;type:string;amountMinor:number;referenceType:string;referenceId:string|null;createdAt:string}>;packages:CreditPackage[]};
const API=process.env.NEXT_PUBLIC_API_URL??"/api";
const money=(minor:number,currency="EUR")=>new Intl.NumberFormat("fr-FR",{style:"currency",currency,minimumFractionDigits:2}).format(minor/100);
const labels:Record<string,string>={WELCOME:"Crédit de bienvenue",LISTING_PROMOTION:"Mise en avant d’annonce",LISTING_RENEWAL:"Prolongation d’annonce",ADMIN_ADJUSTMENT:"Ajustement Petit Annonces",CREDIT_PURCHASE:"Rechargement de crédit"};

export function WalletClient(){
 const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[checkoutId,setCheckoutId]=useState<string|null>(null),[notice,setNotice]=useState<{kind:"ok"|"info";text:string}|null>(null);
 async function load(){setError("");let r:Response;try{r=await fetchWithRetry(`${API}/promotions/wallet`,{credentials:"include",cache:"no-store"},{timeoutMs:7000,retries:1})}catch{setError("Impossible de charger votre crédit Petit Annonces.");return}if(r.status===401){location.href="/connexion?next=%2Fmon-compte%2Fportefeuille";return}if(!r.ok){setError("Impossible de charger votre crédit Petit Annonces.");return}setData(await r.json())}
 useEffect(()=>{const q=new URLSearchParams(window.location.search).get("credit");if(q==="success")setNotice({kind:"ok",text:"Paiement reçu. Votre crédit est ajouté automatiquement après confirmation Stripe."});else if(q==="cancelled")setNotice({kind:"info",text:"Rechargement annulé. Aucun montant n’a été ajouté à votre crédit."});void load()},[]);
 const totalAdded=useMemo(()=>data?.transactions.filter(t=>t.amountMinor>0).reduce((n,t)=>n+t.amountMinor,0)??0,[data]);
 async function buy(pack:CreditPackage){setCheckoutId(pack.id);setError("");try{const r=await fetch(`${API}/billing/stripe/credits/checkout`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({packageId:pack.id})});const p=await r.json().catch(()=>({})) as {url?:string;error?:string};if(r.status===401){location.href="/connexion?next=%2Fmon-compte%2Fportefeuille";return}if(!r.ok||!p.url)throw new Error(p.error??"checkout_failed");location.href=p.url}catch{setError("Le rechargement est momentanément indisponible. Réessayez plus tard.");setCheckoutId(null)}}
 return <main className={styles.accountShell}><AccountSidebar/><section className={styles.main}>
   <header className={styles.hero}><div className={styles.heroCopy}><span className={styles.eyebrow}><AppIcon name="wallet"/> Crédit Petit Annonces</span><h1>Votre crédit, simplement.</h1><p>Rechargez quand vous le souhaitez et utilisez votre solde pour les services disponibles sur Petit Annonces.</p><div className={styles.heroTrust}><span><AppIcon name="shield"/> Paiement Stripe sécurisé</span><span><AppIcon name="circle-check"/> Crédit non expirant</span><span><AppIcon name="lock"/> Utilisable uniquement sur Petit Annonces</span></div></div><div className={styles.balanceCard}><small>Solde disponible</small><strong>{data?money(data.wallet.balanceMinor,data.wallet.currency):"—"}</strong><span>{data?.wallet.balanceMinor?"Prêt à être utilisé":"Rechargez votre compte quand vous en avez besoin"}</span></div></header>
   {notice&&<div className={`${styles.notice} ${notice.kind==="ok"?styles.noticeOk:""}`}><AppIcon name={notice.kind==="ok"?"circle-check":"info"}/><span>{notice.text}</span></div>}{error&&<div className={styles.error}><AppIcon name="info"/><span>{error}</span></div>}
   <section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.kicker}>RECHARGER</span><h2>Choisissez votre pack</h2><p>Le montant acheté est ajouté à votre solde après confirmation du paiement.</p></div></div><div className={styles.packGrid}>{(data?.packages??[]).map((pack,index)=><article className={`${styles.pack} ${pack.badge||index===1?styles.packFeatured:""}`} key={pack.id}>{(pack.badge||index===1)&&<span className={styles.packBadge}>{pack.badge||"Le plus choisi"}</span>}<div className={styles.packIcon}><AppIcon name="wallet"/></div><h3>{pack.name}</h3><strong>{money(pack.creditMinor,pack.currency)}</strong><small>de crédit Petit Annonces</small><p>{pack.description||"Crédit utilisable pour les services proposés sur la plateforme."}</p>{pack.priceMinor!==pack.creditMinor&&<div className={styles.packValue}>Valeur crédit {money(pack.creditMinor,pack.currency)}</div>}<button type="button" onClick={()=>void buy(pack)} disabled={checkoutId!==null}>{checkoutId===pack.id?"Ouverture du paiement…":`Recharger pour ${money(pack.priceMinor,pack.currency)}`}</button></article>)}{data&&data.packages.length===0&&<div className={styles.emptyPacks}>Aucun pack de rechargement n’est disponible pour le moment.</div>}</div><p className={styles.creditRule}>Le crédit Petit Annonces n’est ni transférable ni retirable en espèces. Il sert uniquement au paiement des services éligibles de la plateforme.</p></section>
   <div className={styles.twoCol}><section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.kicker}>HISTORIQUE</span><h2>Derniers mouvements</h2></div><span className={styles.totalAdded}>+ {money(totalAdded,data?.wallet.currency??"EUR")} crédités</span></div><div className={styles.history}>{(data?.transactions??[]).map(t=><article key={t.id}><span className={`${styles.txIcon} ${t.amountMinor>=0?styles.txPositive:styles.txNegative}`}><AppIcon name={t.amountMinor>=0?"plus":"arrow-right"}/></span><div><strong>{labels[t.referenceType]??"Mouvement de crédit"}</strong><small>{new Date(t.createdAt).toLocaleString("fr-FR",{dateStyle:"medium",timeStyle:"short"})}</small></div><b className={t.amountMinor>=0?styles.positive:styles.negative}>{t.amountMinor>=0?"+":""}{money(t.amountMinor,data?.wallet.currency??"EUR")}</b></article>)}{data&&!data.transactions.length&&<div className={styles.empty}>Aucun mouvement pour le moment.</div>}</div></section>
   <aside className={styles.helpCard}><span className={styles.kicker}>COMMENT ÇA MARCHE ?</span><h2>Un solde dédié à vos services</h2><div><span><AppIcon name="sparkles"/></span><p><strong>Boostez vos annonces</strong><small>Utilisez votre crédit sur les options de visibilité compatibles.</small></p></div><div><span><AppIcon name="calendar"/></span><p><strong>Prolongez vos annonces</strong><small>Les prolongations payantes peuvent être réglées avec votre solde.</small></p></div><div><span><AppIcon name="shield"/></span><p><strong>Solde séparé de vos ventes</strong><small>Le crédit Petit Annonces n’est pas un portefeuille bancaire et ne remplace pas vos versements vendeur.</small></p></div></aside></div>
 </section></main>
}
