import type {Metadata} from "next";
import {AppIcon} from "../../components/app-icon";
import {CampaignLink} from "../../components/campaign-link";
import styles from "../campaign-landing.module.css";

export const metadata:Metadata={title:{absolute:"Petite annonce gratuite : publier en France | PetitAnnonces.fr"},description:"Déposez et publiez gratuitement une petite annonce en France. Ajoutez vos photos, votre prix et votre ville en quelques étapes simples sur PetitAnnonces.fr.",alternates:{canonical:"https://petitannonces.fr/deposer-annonce-gratuite"},openGraph:{title:"Petite annonce gratuite : publier en France | PetitAnnonces.fr",description:"Publiez gratuitement votre petite annonce partout en France avec un parcours simple et guidé.",url:"https://petitannonces.fr/deposer-annonce-gratuite",type:"website"}};
type Params=Record<string,string|string[]|undefined>;type Props={searchParams:Promise<Params>};
const TRACKING_KEYS=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","fbclid","gclid","gbraid","wbraid","msclkid"] as const;
function first(value:string|string[]|undefined){return Array.isArray(value)?value[0]:value}
const FAQ=[
 {q:"Comment déposer une petite annonce gratuite ?",a:"Créez votre compte, choisissez la catégorie, ajoutez un titre, des photos, un prix et votre ville, puis envoyez l’annonce pour contrôle avant publication."},
 {q:"Combien coûte la publication d’une annonce ?",a:"Le dépôt d’une annonce par un particulier est gratuit sur Petit Annonces, sous réserve des règles de publication et de modération de la plateforme."},
 {q:"Puis-je publier une annonce partout en France ?",a:"Oui. Vous pouvez renseigner votre ville et votre code postal afin que les acheteurs trouvent plus facilement votre annonce dans leur zone."},
];

export default async function FreeListingLanding({searchParams}:Props){
 const params=await searchParams;const next=new URLSearchParams({mode:"manual"});for(const key of TRACKING_KEYS){const value=first(params[key]);if(value)next.set(key,value)}const cta=`/deposer-une-annonce?${next.toString()}`;
 return <div className={styles.page}><main>
  <section className={styles.hero}><div className={styles.heroInner}>
   <div className={styles.copy}><span className={styles.kicker}><AppIcon name="plus"/> Petite annonce gratuite</span><h1>Déposez une petite annonce gratuite. <em>Publiez partout en France.</em></h1><p>Publiez gratuitement une petite annonce en quelques minutes : choisissez la bonne catégorie, ajoutez vos photos, votre prix et votre ville, puis envoyez-la au contrôle avant publication.</p><div className={styles.points}><span><AppIcon name="circle-check"/> Publication gratuite</span><span><AppIcon name="camera"/> Photos simples à ajouter</span><span><AppIcon name="location"/> Annonce partout en France</span><span><AppIcon name="wallet"/> 5 € de crédit de bienvenue</span></div><div className={styles.ctaRow}><CampaignLink className={styles.primary} href={cta} cta="hero_primary" landing="/deposer-annonce-gratuite" campaign="listing_general">Déposer une annonce <AppIcon name="arrow-right"/></CampaignLink><small>Compte gratuit · 5 € de crédit Petit Annonces après vérification de l’e-mail.</small></div></div>
   <div className={styles.visual} aria-label="Création guidée d’une annonce"><div className={styles.mockHeader}><b>Votre annonce</b><span><AppIcon name="shield"/> Parcours guidé</span></div><div className={styles.mockMain}><div className={styles.mockCard}><span><AppIcon name="list"/></span><div><strong>Choisissez la catégorie</strong><small>Véhicules, immobilier, maison, mode, services et plus encore.</small></div></div><div className={styles.mockCard}><span><AppIcon name="camera"/></span><div><strong>Ajoutez vos photos</strong><small>Choisissez la meilleure photo comme couverture.</small></div></div><div className={styles.mockCard}><span><AppIcon name="location"/></span><div><strong>Prix & localisation</strong><small>Indiquez votre prix et votre ville.</small></div></div><div className={`${styles.mockCard} ${styles.mockCardAccent}`}><span><AppIcon name="circle-check"/></span><div><strong>Envoyez pour publication</strong><small>Votre annonce passe par les contrôles Petit Annonces.</small></div></div></div></div>
  </div></section>
  <section className={styles.steps}><div className={styles.shell}><div className={styles.sectionHead}><span>Quelques minutes suffisent</span><h2>Comment publier une petite annonce gratuitement ?</h2><p>Le formulaire s’adapte à la catégorie choisie pour ne demander que les informations utiles, de la création jusqu’à la publication.</p></div><div className={styles.stepGrid}><article><i>1</i><span><AppIcon name="list"/></span><h3>Présentez votre objet</h3><p>Choisissez la bonne catégorie et ajoutez un titre facile à comprendre.</p></article><article><i>2</i><span><AppIcon name="camera"/></span><h3>Montrez ce que vous vendez</h3><p>Ajoutez vos photos, les caractéristiques utiles et une description claire.</p></article><article><i>3</i><span><AppIcon name="circle-check"/></span><h3>Fixez votre prix et publiez</h3><p>Vérifiez l’annonce, choisissez votre prix puis envoyez-la en modération.</p></article></div></div></section>
  <section className={styles.trust}><div className={styles.shell}><div className={styles.trustCopy}><span>Vendre sur Petit Annonces</span><h2>Tout ce qu’il faut pour vendre sans compliquer le parcours.</h2><p>Votre espace regroupe brouillons, annonces, favoris, messages et notifications afin que vous puissiez suivre les contacts depuis le web ou la PWA.</p><p>Vous publiez pour une entreprise, un commerce ou un magasin ? <a href="/professionnels">Découvrez comment déposer des annonces professionnelles et ouvrir une boutique Pro</a>.</p><CampaignLink className={styles.secondary} href={cta} cta="trust_secondary" landing="/deposer-annonce-gratuite" campaign="listing_general">Créer mon annonce <AppIcon name="arrow-right"/></CampaignLink></div><div className={styles.trustCards}><article><AppIcon name="shield"/><div><strong>Contrôles de sécurité</strong><small>Les annonces restent soumises aux règles de contenu et à la modération avant publication.</small></div></article><article><AppIcon name="comments"/><div><strong>Messagerie intégrée</strong><small>Échangez avec les acheteurs depuis Petit Annonces.</small></div></article><article><AppIcon name="location"/><div><strong>Près de chez vous</strong><small>La ville et le code postal permettent aux acheteurs de trouver les annonces locales.</small></div></article><article><AppIcon name="credit-card"/><div><strong>Paiement sécurisé</strong><small>Sur les annonces éligibles, acheteurs et vendeurs peuvent utiliser le parcours de paiement sécurisé Petit Annonces.</small></div></article></div></div></section>
  <section className={styles.steps} aria-labelledby="faq-annonce-gratuite"><div className={styles.shell}><div className={styles.sectionHead}><span>Questions fréquentes</span><h2 id="faq-annonce-gratuite">Publier une annonce gratuite sur Petit Annonces</h2><p>Les réponses essentielles avant de mettre votre annonce en ligne.</p></div><div className={styles.stepGrid}>{FAQ.map((item,index)=><article key={item.q}><i>{index+1}</i><span><AppIcon name="circle-check"/></span><h3>{item.q}</h3><p>{item.a}</p></article>)}</div></div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"FAQPage",mainEntity:FAQ.map(item=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))})}}/>
  <CampaignLink className={styles.mobileCta} href={cta} cta="mobile_sticky" landing="/deposer-annonce-gratuite" campaign="listing_general">Déposer une annonce <AppIcon name="arrow-right"/></CampaignLink>
 </main></div>;
}
