import type {Metadata} from "next";
import {AppIcon} from "../../components/app-icon";
import {CampaignLink} from "../../components/campaign-link";
import styles from "../campaign-landing.module.css";

export const metadata:Metadata={title:"90 jours Pro offerts | Ouvrir une boutique Petit Annonces",description:"Créez votre compte professionnel et profitez de 90 jours de la formule Professionnel offerts, avec boutique publique et import CSV jusqu’à 200 annonces par lot.",alternates:{canonical:"https://petitannonces.fr/ouvrir-boutique-pro"},openGraph:{title:"90 jours Pro offerts | Petit Annonces",description:"SIRET vérifié, boutique publique et import CSV : démarrez 90 jours gratuitement, sans carte bancaire ni prélèvement automatique.",url:"https://petitannonces.fr/ouvrir-boutique-pro",type:"website"}};
type Params=Record<string,string|string[]|undefined>;type Props={searchParams:Promise<Params>};
const TRACKING_KEYS=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","fbclid","gclid","gbraid","wbraid","msclkid"] as const;
function first(value:string|string[]|undefined){return Array.isArray(value)?value[0]:value}

export default async function ProLanding({searchParams}:Props){
 const params=await searchParams;const next=new URLSearchParams({type:"pro"});for(const key of TRACKING_KEYS){const value=first(params[key]);if(value)next.set(key,value)}const cta=`/inscription?${next.toString()}`;
 return <div className={styles.page}><main>
  <section className={styles.hero}><div className={styles.heroInner}>
   <div className={styles.copy}><span className={styles.kicker}><AppIcon name="sparkles"/> Offre de lancement · 90 jours Pro offerts</span><h1>Professionnel ? <em>Importez votre catalogue.</em></h1><p>Créez votre boutique avec votre SIRET et profitez de 90 jours de la formule Professionnel offerts pour publier plus vite et importer jusqu’à 200 annonces CSV par lot.</p><div className={styles.points}><span><AppIcon name="user-shield"/> SIRET vérifié</span><span><AppIcon name="store"/> Boutique publique</span><span><AppIcon name="list"/> Import CSV · 200 annonces</span></div><div className={styles.ctaRow}><CampaignLink className={styles.primary} href={cta} cta="hero_primary" landing="/ouvrir-boutique-pro" campaign="pro_general">Démarrer mes 90 jours offerts <AppIcon name="arrow-right"/></CampaignLink><small>Sans carte bancaire. Aucun prélèvement automatique à la fin des 90 jours.</small></div></div>
   <div className={`${styles.visual} ${styles.proVisual}`} aria-label="Aperçu d’un espace professionnel Petit Annonces"><div className={styles.mockHeader}><b>Espace Pro</b><span><AppIcon name="shield"/> Entreprise vérifiée</span></div><div className={styles.mockMain}><div className={`${styles.mockCard} ${styles.mockCardAccent}`}><span><AppIcon name="store"/></span><div><strong>Votre boutique publique</strong><small>Nom commercial, ville, identité et annonces réunis.</small></div></div><div className={styles.mockCard}><span><AppIcon name="list"/></span><div><strong>Gérez vos annonces</strong><small>Publiez, suivez et organisez votre catalogue depuis un seul espace.</small></div></div><div className={styles.mockCard}><span><AppIcon name="comments"/></span><div><strong>Messages & contacts</strong><small>Centralisez les échanges avec les acheteurs.</small></div></div><div className={styles.mockCard}><span><AppIcon name="gauge"/></span><div><strong>Visibilité & statistiques</strong><small>Accédez aux outils activés pour votre formule professionnelle.</small></div></div></div></div>
  </div></section>
  <section className={styles.steps}><div className={styles.shell}><div className={styles.sectionHead}><span>Inscription professionnelle</span><h2>Votre entreprise prête en quelques étapes</h2><p>Le parcours récupère les informations légales disponibles afin d’éviter les saisies inutiles.</p></div><div className={styles.stepGrid}><article><i>1</i><span><AppIcon name="user-shield"/></span><h3>Vérifiez votre SIRET</h3><p>Saisissez les 14 chiffres et confirmez les informations officielles de votre entreprise.</p></article><article><i>2</i><span><AppIcon name="briefcase"/></span><h3>Créez vos identifiants</h3><p>Ajoutez le responsable du compte et l’adresse e-mail professionnelle.</p></article><article><i>3</i><span><AppIcon name="store"/></span><h3>Ouvrez votre boutique</h3><p>Choisissez le nom de votre vitrine puis personnalisez logo, couverture et annonces depuis l’Espace Pro.</p></article></div></div></section>
  <section className={styles.trust}><div className={styles.shell}><div className={styles.trustCopy}><span>Une présence professionnelle</span><h2>Donnez à vos annonces une identité plus claire.</h2><p>Votre boutique permet de regrouper votre activité et vos annonces autour d’une identité professionnelle vérifiée. Les offres et options payantes restent séparées de la création initiale du compte.</p><CampaignLink className={styles.secondary} href={cta} cta="trust_secondary" landing="/ouvrir-boutique-pro" campaign="pro_general">Commencer l’inscription Pro <AppIcon name="arrow-right"/></CampaignLink></div><div className={styles.trustCards}><article><AppIcon name="store"/><div><strong>Vitrine dédiée</strong><small>Votre boutique réunit votre identité professionnelle et vos annonces publiées.</small></div></article><article><AppIcon name="gauge"/><div><strong>Outils professionnels</strong><small>Gérez annonces, visibilité, ventes et statistiques depuis l’Espace Pro.</small></div></article><article><AppIcon name="shield"/><div><strong>Crédibilité renforcée</strong><small>La vérification SIRET distingue clairement le compte professionnel.</small></div></article></div></div></section>
  <CampaignLink className={styles.mobileCta} href={cta} cta="mobile_sticky" landing="/ouvrir-boutique-pro" campaign="pro_general">90 jours Pro offerts <AppIcon name="arrow-right"/></CampaignLink>
 </main></div>;
}
