import {LegalPage} from "../../components/legal-page";
export const metadata={title:"Conditions générales | Petit Annonces",alternates:{canonical:"/conditions-generales"}};
export default function Page(){const sections=[
{id:"objet",title:"Objet et rôle de Petit Annonces",body:"Petit Annonces met à disposition une plateforme permettant aux particuliers et aux professionnels de publier des annonces, d'échanger via la messagerie, de faire des offres et, lorsque la fonctionnalité est proposée, d'utiliser un parcours de transaction, livraison et protection intégré.",bullets:["Petit Annonces n'est pas le propriétaire des biens publiés par les utilisateurs.","Chaque vendeur reste responsable de la description, de la disponibilité et de la conformité de son annonce.","Certaines fonctionnalités peuvent dépendre de prestataires de paiement, livraison ou vérification."]},
{id:"compte",title:"Création et sécurité du compte",body:"L'utilisateur doit fournir des informations exactes et maintenir ses coordonnées à jour. L'accès au compte est personnel et les identifiants ne doivent pas être partagés.",bullets:["Un seul compte doit être utilisé conformément au parcours prévu par la plateforme.","Les vérifications e-mail, téléphone ou identité peuvent être demandées selon le niveau de risque ou la fonctionnalité utilisée.","Toute activité suspecte peut entraîner une mesure de protection temporaire du compte."],note:"Petit Annonces ne demande jamais un mot de passe, un code OTP ou un code de secours dans un ticket de support."},
{id:"annonces",title:"Publication, contenu et modération",body:"Les annonces doivent décrire de manière loyale le bien ou le service proposé. Les contenus trompeurs, illicites, dangereux, contrefaits ou interdits par la réglementation ou les règles de la plateforme sont prohibés.",bullets:["Les photos doivent correspondre au produit ou bien proposé.","Le prix, l'état, les caractéristiques essentielles et les éventuels défauts doivent être indiqués de manière compréhensible.","Des contrôles automatisés et humains peuvent retarder la publication ou conduire à une demande de correction.","Une annonce vendue, expirée, suspendue ou supprimée peut être rendue non indexable ou retirée de la recherche publique."]},
{id:"transactions",title:"Paiement, commande et protection",body:"Lorsqu'un paiement protégé est disponible, il est traité par un prestataire de paiement spécialisé. Petit Annonces organise le parcours de commande, le suivi et les règles de protection affichées dans l'interface.",bullets:["L'acheteur doit vérifier le récapitulatif avant paiement.","Le vendeur doit respecter les informations d'expédition et de suivi associées à la commande.","Un litige, retour ou remboursement en cours peut suspendre le versement vendeur.","Le montant net vendeur devient éligible au versement selon le calendrier affiché dans IBAN & versements, notamment au 21e jour après livraison lorsque les conditions sont réunies."]},
{id:"livraison",title:"Livraison et preuve d'expédition",body:"Lorsque l'expédition intégrée est disponible, le vendeur utilise le bouton « Préparer mon envoi » et suit les instructions de la commande. Les informations de suivi servent à sécuriser la transaction et à déterminer les étapes de livraison.",bullets:["L'emballage doit être adapté au produit.","Le vendeur doit remettre le colis au transporteur dans le délai annoncé.","Les informations de suivi ne doivent pas être falsifiées."]},
{id:"professionnels",title:"Utilisateurs professionnels",body:"Un vendeur professionnel doit s'inscrire avec son statut professionnel, fournir un SIRET valide et maintenir ses informations d'entreprise à jour. Les informations officielles disponibles peuvent être récupérées à partir de sources publiques afin de simplifier la vérification.",bullets:["Les professionnels doivent respecter leurs obligations d'information précontractuelle et de droit de la consommation.","La boutique professionnelle ne doit pas induire l'utilisateur en erreur sur l'identité de l'entreprise.","Les obligations de facturation, garanties légales et droit de rétractation s'appliquent lorsqu'elles sont prévues par la loi."]},
{id:"moderation",title:"Modération, signalement et recours",body:"Les utilisateurs peuvent signaler un contenu, un comportement ou une annonce. Les signalements potentiellement illicites peuvent utiliser le formulaire DSA dédié afin de recevoir une référence distincte et un suivi adapté.",bullets:["Une mesure de modération importante peut être accompagnée d'une motivation.","Les décisions éligibles peuvent être contestées via le mécanisme prévu par la plateforme.","Les abus répétés du système de signalement peuvent faire l'objet de mesures de protection."],note:"Les décisions concernant un litige, la conformité ou la sécurité peuvent nécessiter une revue humaine même lorsqu'un assistant automatisé fournit une première orientation."},
{id:"responsabilite",title:"Responsabilité et disponibilité",body:"Petit Annonces met en œuvre des moyens raisonnables pour maintenir la disponibilité et la sécurité du service. Des opérations de maintenance, incidents techniques ou interventions de prestataires peuvent toutefois interrompre temporairement certaines fonctionnalités.",bullets:["L'utilisateur est responsable de ses contenus et de ses échanges avec les autres membres.","La plateforme peut limiter une fonctionnalité afin de prévenir une fraude ou protéger les utilisateurs.","Aucune disponibilité continue sans interruption ne peut être garantie." ]},
{id:"evolution",title:"Évolution des conditions",body:"Les présentes conditions peuvent évoluer pour tenir compte des changements du service, de la réglementation ou des mesures de sécurité. Lorsqu'une modification substantielle l'exige, les utilisateurs sont informés par un moyen approprié avant son entrée en vigueur."}
];return <LegalPage eyebrow="Règles de la plateforme" title="Conditions générales" intro="Les règles essentielles pour utiliser Petit Annonces, publier, acheter, vendre, expédier et utiliser les services professionnels en toute confiance." updated="7 septembre 2026" sections={sections}/>;}