"use client";

import {FormEvent,useEffect,useState} from "react";
import {useParams} from "next/navigation";
import styles from "./support-ticket.module.css";

type Ticket={id:string;reference:string;category:string;subject:string;status:string;priority:string;createdAt:string;lastMessageAt:string;email?:string|null;displayName?:string|null;firstName?:string|null;lastName?:string|null;phone?:string|null;userKind?:string|null};
type Msg={id:string;authorType:string;body:string;internalNote:boolean;createdAt:string};
type Evidence={id:string;fileName:string;mimeType:string;sizeBytes:number;downloadUrl:string;createdAt:string};
type Payout={status:string;amountMinor:number;currency:string;failureReason:string|null;eligibleAt:string|null;paidAt:string|null};
type VacationIncident={id:string;reservationId:string;type:string;summary:string;status:string;resolution:string|null;claimStatus:"NONE"|"REQUESTED"|"UNDER_REVIEW"|"APPROVED"|"REJECTED";claimedAmountMinor:number|null;approvedAmountMinor:number|null;currency:string;claimDecisionNote:string|null;createdAt:string;resolvedAt:string|null;checkIn:string;checkOut:string;listingTitle:string|null;city:string|null;evidence:Evidence[];payout:Payout|null};
const statusLabel:Record<string,string>={OPEN:"Ouvert",PENDING_CUSTOMER:"En attente du client",PENDING_INTERNAL:"Traitement interne",RESOLVED:"Résolu",CLOSED:"Fermé"};
const categoryLabel:Record<string,string>={ACCOUNT:"Compte",LISTING:"Annonce",PAYMENT:"Paiement",ORDER:"Commande",SHIPPING:"Livraison",DISPUTE:"Litige",PROFESSIONAL:"Professionnel",COMPLIANCE:"Conformité",SAFETY:"Sécurité",OTHER:"Autre"};
const incidentLabel:Record<string,string>={DAMAGE:"Dommage",ACCESS:"Accès / clés",CLEANLINESS:"Propreté",SAFETY:"Sécurité",BEHAVIOR:"Comportement",NO_SHOW:"No-show",OTHER:"Autre"};
const claimLabel:Record<string,string>={NONE:"Aucune demande",REQUESTED:"À examiner",UNDER_REVIEW:"Informations complémentaires",APPROVED:"Montant retenu",REJECTED:"Rejetée"};
function money(minor:number|null){return minor==null?"—":new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(minor/100)}
function fileSize(bytes:number){return bytes>=1024*1024?`${(bytes/(1024*1024)).toFixed(1)} Mo`:`${Math.max(1,Math.round(bytes/1024))} Ko`}

export default function SupportTicketClient(){
 const{id}=useParams<{id:string}>();
 const[ticket,setTicket]=useState<Ticket|null>(null),[messages,setMessages]=useState<Msg[]>([]),[incident,setIncident]=useState<VacationIncident|null>(null),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[notice,setNotice]=useState(""),[internal,setInternal]=useState(false),[status,setStatus]=useState("PENDING_CUSTOMER"),[approvedDraft,setApprovedDraft]=useState(""),[assessmentNote,setAssessmentNote]=useState("");
 async function load(){setLoading(true);const r=await fetch(`/api/admin/support/tickets/${encodeURIComponent(id)}`,{credentials:"include",cache:"no-store"});const p=await r.json().catch(()=>({}));if(r.ok){setTicket(p.ticket);setMessages(p.messages??[]);setIncident(p.vacationIncident??null);const vi=p.vacationIncident as VacationIncident|null;if(vi?.approvedAmountMinor!=null)setApprovedDraft((vi.approvedAmountMinor/100).toFixed(2));else if(vi?.claimedAmountMinor!=null)setApprovedDraft((vi.claimedAmountMinor/100).toFixed(2));setAssessmentNote(vi?.claimDecisionNote??"");setStatus(p.ticket?.status==="CLOSED"?"CLOSED":"PENDING_CUSTOMER")}else setNotice("Impossible de charger ce ticket.");setLoading(false)}
 useEffect(()=>{void load()},[id]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body=String(f.get("body")??"").trim();if(body.length<2)return;setSending(true);setNotice("");try{const r=await fetch(`/api/admin/support/tickets/${encodeURIComponent(id)}/reply`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({body,internalNote:internal,status:internal?undefined:status}),signal:AbortSignal.timeout(15000)});const p=await r.json().catch(()=>({}));if(r.ok){e.currentTarget.reset();setNotice(internal?"Note interne ajoutée.":"Réponse envoyée au client.");await load()}else if(p?.error==="vacation_incident_resolution_required")setNotice("Ce ticket Vacances doit être clôturé avec une décision depuis le bloc Incident Vacances.");else setNotice("Impossible d’enregistrer la réponse.")}catch{setNotice("La réponse n’a pas pu être confirmée.")}finally{setSending(false)}}
 async function closeTicket(){if(!ticket||ticket.status==="CLOSED"||sending)return;if(!window.confirm("Fermer ce ticket sans ajouter de motif ? Le client pourra ouvrir une nouvelle demande si nécessaire."))return;setSending(true);setNotice("");try{const r=await fetch(`/api/admin/support/tickets/${encodeURIComponent(id)}/close`,{method:"POST",credentials:"include"});const p=await r.json().catch(()=>({}));if(r.ok){setNotice("Ticket fermé.");await load()}else if(p?.error==="vacation_incident_resolution_required")setNotice("Ce ticket est lié à un incident Vacances actif. Résolvez d’abord l’incident.");else setNotice("Impossible de fermer ce ticket.")}catch{setNotice("La fermeture du ticket n’a pas pu être confirmée.")}finally{setSending(false)}}
 async function assess(decision:"APPROVED"|"REJECTED"|"NEEDS_MORE_INFO"){if(!incident)return;let approvedAmountMinor:number|undefined;if(decision==="APPROVED"){const amount=Number(approvedDraft.replace(",","."));if(!Number.isFinite(amount)||amount<1){setNotice("Indiquez le montant retenu avant de valider.");return}approvedAmountMinor=Math.round(amount*100);if(incident.claimedAmountMinor&&approvedAmountMinor>incident.claimedAmountMinor){setNotice("Le montant retenu ne peut pas dépasser le montant déclaré par l’hôte.");return}}setSending(true);setNotice("");try{const r=await fetch(`/api/admin/vacation-incidents/${encodeURIComponent(incident.id)}/assessment`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({decision,approvedAmountMinor,note:assessmentNote.trim()||undefined})});const p=await r.json().catch(()=>({}));if(!r.ok){setNotice(p?.error==="no_compensation_claim"?"Aucune demande d’indemnisation n’a été déposée.":p?.error==="invalid_approved_amount"?"Le montant retenu est invalide.":"L’évaluation n’a pas pu être enregistrée.");return}setNotice(decision==="APPROVED"?"Montant retenu enregistré. Aucun débit supplémentaire n’a été effectué.":decision==="REJECTED"?"Demande d’indemnisation rejetée.":"Le dossier reste en attente d’éléments complémentaires.");await load()}finally{setSending(false)}}
 async function resolveIncident(decision:"RELEASE_HOST"|"KEEP_HOLD"|"REFUND_REVIEW"){if(!incident)return;const label=decision==="RELEASE_HOST"?"autoriser le versement de l’acompte à l’hôte":decision==="REFUND_REVIEW"?"maintenir l’acompte bloqué pour une revue de remboursement":"maintenir l’acompte bloqué";if(!window.confirm(`Confirmer : ${label} ?`))return;setSending(true);setNotice("");try{const r=await fetch(`/api/admin/vacation-incidents/${encodeURIComponent(incident.id)}/resolve`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({decision,note:assessmentNote.trim()||undefined})});const p=await r.json().catch(()=>({}));if(!r.ok){setNotice(p?.error==="incident_already_resolved"?"Ce dossier a déjà été résolu.":p?.error==="claim_assessment_required"?"Évaluez d’abord la demande d’indemnisation avant de clôturer l’incident.":"Impossible de clôturer le dossier Vacances.");return}setNotice(decision==="RELEASE_HOST"?"Incident résolu. Le versement de l’acompte peut reprendre si aucun autre blocage n’existe.":decision==="REFUND_REVIEW"?"Incident résolu côté support. L’acompte reste bloqué pour revue de remboursement.":"Incident résolu. L’acompte reste bloqué manuellement.");await load()}finally{setSending(false)}}
 if(loading)return <div className="admin-card admin-section">Chargement du ticket…</div>;
 if(!ticket)return <div className="admin-card admin-section">Ticket introuvable.</div>;
 const name=ticket.displayName||[ticket.firstName,ticket.lastName].filter(Boolean).join(" ")||"Utilisateur";
 return <>
  <div className="admin-page-head"><div><p>Service client · {ticket.reference}</p><h1>{ticket.subject}</h1><span className="subtitle">Conversation complète et réponse au client.</span></div><div className={styles.pageActions}>{ticket.status!=="CLOSED"&&<button type="button" className="admin-btn" disabled={sending} onClick={()=>void closeTicket()}>Fermer sans motif</button>}<a className="admin-btn" href="/support">← Retour aux tickets</a></div></div>
  {notice&&<div className="admin-flash ok">{notice}</div>}
  <div className={styles.layout}>
   <main className={styles.main}>
    {incident&&<section className="admin-card admin-section" style={{borderColor:["OPEN","UNDER_REVIEW"].includes(incident.status)?"#e9c46a":undefined}}>
     <div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start",flexWrap:"wrap"}}><div><p style={{margin:"0 0 4px",fontSize:12,fontWeight:800,letterSpacing:1,color:"#8b6b2d"}}>INCIDENT VACANCES</p><h2 style={{margin:"0 0 6px"}}>{incidentLabel[incident.type]??incident.type}</h2><p style={{margin:0,color:"#677085"}}>{incident.listingTitle??"Hébergement Vacances"}{incident.city?` · ${incident.city}`:""} · {String(incident.checkIn).slice(0,10)} → {String(incident.checkOut).slice(0,10)}</p></div><span className={`admin-badge ${incident.status==="OPEN"?"orange":""}`}>{incident.status}</span></div>
     <p style={{whiteSpace:"pre-wrap",lineHeight:1.55}}>{incident.summary}</p>
     <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,margin:"12px 0"}}><div className="admin-card" style={{padding:12}}><small>Acompte</small><strong style={{display:"block",fontSize:18,marginTop:4}}>{incident.payout?money(incident.payout.amountMinor):"—"}</strong><span style={{fontSize:12,color:"#687086"}}>{incident.payout?.status??"Aucun versement"}{incident.payout?.failureReason?` · ${incident.payout.failureReason}`:""}</span></div><div className="admin-card" style={{padding:12}}><small>Indemnisation</small><strong style={{display:"block",fontSize:18,marginTop:4}}>{incident.claimedAmountMinor?money(incident.claimedAmountMinor):"—"}</strong><span style={{fontSize:12,color:"#687086"}}>{claimLabel[incident.claimStatus]??incident.claimStatus}{incident.approvedAmountMinor!=null?` · retenu ${money(incident.approvedAmountMinor)}`:""}</span></div><div className="admin-card" style={{padding:12}}><small>Justificatifs</small><strong style={{display:"block",fontSize:18,marginTop:4}}>{incident.evidence?.length??0}</strong><span style={{fontSize:12,color:"#687086"}}>Stockage privé</span></div></div>
     {incident.evidence?.length>0&&<div style={{borderTop:"1px solid #eceff3",paddingTop:12}}><strong>Justificatifs privés</strong><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:8,marginTop:8}}>{incident.evidence.map(e=><a className="admin-btn" style={{justifyContent:"flex-start",overflow:"hidden"}} key={e.id} href={e.downloadUrl} target="_blank" rel="noreferrer"><span style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{e.fileName}</span><small style={{marginLeft:"auto"}}>{fileSize(e.sizeBytes)}</small></a>)}</div></div>}
     {incident.claimedAmountMinor&&["OPEN","UNDER_REVIEW"].includes(incident.status)&&<div style={{display:"grid",gap:9,borderTop:"1px solid #eceff3",paddingTop:12,marginTop:12}}><div><strong>Évaluation de l’indemnisation</strong><p style={{margin:"4px 0 0",fontSize:12,color:"#687086"}}>L’hôte réclame {money(incident.claimedAmountMinor)}. Valider un montant ne débite pas automatiquement le voyageur.</p></div><div style={{display:"grid",gridTemplateColumns:"minmax(150px,220px) 1fr",gap:8}}><label style={{display:"grid",gap:4,fontSize:12,fontWeight:700}}>Montant retenu (€)<input style={{height:40,border:"1px solid #dfe4ec",borderRadius:9,padding:"0 10px"}} type="number" min="1" step="0.01" max={(incident.claimedAmountMinor/100).toFixed(2)} value={approvedDraft} onChange={e=>setApprovedDraft(e.target.value)}/></label><label style={{display:"grid",gap:4,fontSize:12,fontWeight:700}}>Note d’évaluation<input style={{height:40,border:"1px solid #dfe4ec",borderRadius:9,padding:"0 10px"}} maxLength={2000} value={assessmentNote} onChange={e=>setAssessmentNote(e.target.value)} placeholder="Éléments retenus, facture, photo, explication…"/></label></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" className="admin-btn primary" disabled={sending} onClick={()=>void assess("APPROVED")}>Valider le montant</button><button type="button" className="admin-btn" disabled={sending} onClick={()=>void assess("NEEDS_MORE_INFO")}>Demander des éléments</button><button type="button" className="admin-btn" disabled={sending} onClick={()=>void assess("REJECTED")}>Rejeter la demande</button></div></div>}
     {["OPEN","UNDER_REVIEW"].includes(incident.status)&&<div style={{display:"grid",gap:8,paddingTop:12,marginTop:12,borderTop:"1px solid #eceff3"}}><div><strong>Décision sur l’acompte</strong><p style={{margin:"4px 0 0",fontSize:12,color:"#687086"}}>Cette décision concerne l’acompte de réservation déjà encaissé, pas un nouveau prélèvement pour dommage.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" className="admin-btn primary" disabled={sending} onClick={()=>void resolveIncident("RELEASE_HOST")}>Résoudre · verser l’acompte à l’hôte</button><button type="button" className="admin-btn" disabled={sending} onClick={()=>void resolveIncident("REFUND_REVIEW")}>Revue remboursement</button><button type="button" className="admin-btn" disabled={sending} onClick={()=>void resolveIncident("KEEP_HOLD")}>Résoudre · garder bloqué</button></div></div>}
     {incident.resolution&&<p style={{marginBottom:0,fontWeight:700}}>Décision finale : {incident.resolution}</p>}
    </section>}
    <section className="admin-card admin-section"><div className={styles.thread}>{messages.map(m=><article key={m.id} className={`${styles.message} ${m.authorType==="CUSTOMER"?styles.customer:m.internalNote?styles.note:styles.agent}`}><div><strong>{m.internalNote?"Note interne":m.authorType==="CUSTOMER"?name:m.authorType==="SYSTEM"?"Assistant Petit Annonces":"Service client"}</strong><small>{new Date(m.createdAt).toLocaleString("fr-FR")}</small></div><p>{m.body}</p></article>)}{!messages.length&&<div className="admin-empty">Aucun message.</div>}</div></section>
    {ticket.status==="CLOSED"?<section className="admin-card admin-section"><div className={styles.closedNotice}><strong>Ticket fermé</strong><p>Ce dossier est clôturé. Le client peut ouvrir une nouvelle demande s’il a encore besoin d’aide.</p></div></section>:<section className="admin-card admin-section"><div className={styles.composeHead}><div><h2>Répondre</h2><p>La réponse publique sera visible par l’utilisateur dans son espace assistance.</p></div><label><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/> Note interne</label></div><form className={styles.form} onSubmit={submit}><textarea name="body" required minLength={2} maxLength={5000} rows={8} placeholder={internal?"Ajouter une note visible uniquement par l’équipe…":"Écrire une réponse claire au client…"}/>{!internal&&<div className={styles.sendRow}><select value={status} onChange={e=>setStatus(e.target.value)}><option value="PENDING_CUSTOMER">En attente du client</option><option value="PENDING_INTERNAL">Traitement interne</option><option value="RESOLVED">Résolu</option><option value="CLOSED">Fermé</option></select><button className="admin-btn primary" disabled={sending}>{sending?"Envoi…":"Envoyer la réponse"}</button></div>}{internal&&<div className={styles.sendRow}><span/><button className="admin-btn" disabled={sending}>{sending?"Enregistrement…":"Ajouter la note"}</button></div>}</form></section>}
   </main>
   <aside className={styles.side}><section className="admin-card admin-section"><h3>Dossier</h3><dl><div><dt>Statut</dt><dd>{statusLabel[ticket.status]??ticket.status}</dd></div><div><dt>Catégorie</dt><dd>{categoryLabel[ticket.category]??ticket.category}</dd></div><div><dt>Priorité</dt><dd>{ticket.priority}</dd></div><div><dt>Créé le</dt><dd>{new Date(ticket.createdAt).toLocaleString("fr-FR")}</dd></div></dl></section><section className="admin-card admin-section"><h3>Client</h3><dl><div><dt>Nom</dt><dd>{name}</dd></div><div><dt>Type</dt><dd>{ticket.userKind??"—"}</dd></div><div><dt>E-mail</dt><dd>{ticket.email??"—"}</dd></div><div><dt>Téléphone</dt><dd>{ticket.phone??"—"}</dd></div></dl></section></aside>
  </div>
 </>
}