"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {AccountSidebar} from "../../components/account-sidebar";
import {AppIcon} from "../../components/app-icon";
import styles from "./page.module.css";

type Ticket={id:string;reference:string;category:string;subject:string;status:string;priority:string;lastMessageAt:string;createdAt:string};
type TicketMessage={id:string;authorType:string;body:string;createdAt:string};
type Faq={id:string;slug:string;category:string;question:string;answer:string};
const api=()=> (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"");
const statusLabel:Record<string,string>={OPEN:"Ouvert",PENDING_CUSTOMER:"Votre réponse est attendue",PENDING_INTERNAL:"En cours de traitement",RESOLVED:"Résolu",CLOSED:"Fermé"};
const categoryLabel:Record<string,string>={ACCOUNT:"Mon compte",LISTING:"Une annonce",PAYMENT:"Paiement",ORDER:"Commande",SHIPPING:"Livraison",DISPUTE:"Litige",PROFESSIONAL:"Compte professionnel",COMPLIANCE:"Conformité",SAFETY:"Sécurité",OTHER:"Autre"};
const helpCards=[
 {icon:"list" as const,title:"Annonces",text:"Publication, modification, modération ou visibilité d’une annonce.",category:"LISTING"},
 {icon:"credit-card" as const,title:"Paiement & commande",text:"Achat, vente, remboursement, protection acheteur ou versement vendeur.",category:"PAYMENT"},
 {icon:"store" as const,title:"Compte professionnel",text:"SIRET, vérification, abonnement, boutique et outils Pro.",category:"PROFESSIONAL"},
 {icon:"shield" as const,title:"Sécurité",text:"Signalement, compte compromis ou comportement suspect.",category:"SAFETY"},
];
export default function Page(){
 const[tickets,setTickets]=useState<Ticket[]>([]),[selected,setSelected]=useState<string|null>(null),[messages,setMessages]=useState<TicketMessage[]>([]),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[replying,setReplying]=useState(false),[closing,setClosing]=useState(false),[notice,setNotice]=useState(""),[authenticated,setAuthenticated]=useState<boolean|null>(null),[preset,setPreset]=useState("ACCOUNT"),[faqs,setFaqs]=useState<Faq[]>([]),[faqCategory,setFaqCategory]=useState("ALL"),[faqQuery,setFaqQuery]=useState("");
 async function load(){const r=await fetch(`${api()}/support/tickets`,{credentials:"include",cache:"no-store"});if(r.status===401){setAuthenticated(false);setLoading(false);return}setAuthenticated(true);if(r.ok){const p=await r.json();setTickets(p.tickets??[])}setLoading(false)}
 useEffect(()=>{const q=new URLSearchParams(location.search);const id=q.get("ticket");const category=q.get("category");if(category&&categoryLabel[category])setPreset(category);void load().then(()=>{if(id)void openTicket(id)});fetch(`${api()}/support/faqs`,{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(p=>setFaqs(p.faqs??[])).catch(()=>setFaqs([]))},[]);
 async function openTicket(id:string){setSelected(id);const r=await fetch(`${api()}/support/tickets/${encodeURIComponent(id)}`,{credentials:"include",cache:"no-store"});if(r.ok){const p=await r.json();setMessages(p.messages??[])}else{setSelected(null);setMessages([]);if(r.status===401)setAuthenticated(false);else setNotice("Cette demande d’assistance est introuvable ou n’est plus accessible.")}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(authenticated===false){location.href="/connexion?next=%2Fassistance";return}setSending(true);setNotice("");const f=new FormData(e.currentTarget);const payload={category:String(f.get("category")),subject:String(f.get("subject")),body:String(f.get("body"))};try{const r=await fetch(`${api()}/support/tickets`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)});const p=await r.json().catch(()=>({}));if(r.status===401){location.href="/connexion?next=%2Fassistance";return}if(r.ok){setNotice(`Votre demande ${p.ticket.reference} a bien été envoyée.`);e.currentTarget.reset();await load();await openTicket(p.ticket.id)}else setNotice("Impossible d’envoyer la demande. Vérifiez les champs puis réessayez.")}catch{setNotice("Le service client met trop de temps à répondre. Votre demande n’a pas été confirmée ; réessayez dans un instant.")}finally{setSending(false)}}
 async function replyTicket(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setReplying(true);setNotice("");const form=e.currentTarget;const f=new FormData(form);const body=String(f.get("reply")??"").trim();if(!body){setReplying(false);return}const optimisticId=`local-${Date.now()}`;setMessages(current=>[...current,{id:optimisticId,authorType:"CUSTOMER",body,createdAt:new Date().toISOString()}]);form.reset();try{const r=await fetch(`${api()}/support/tickets/${encodeURIComponent(selected)}/reply`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({body}),signal:AbortSignal.timeout(15000)});if(r.ok){const p=await r.json().catch(()=>({}));if(p.message?.id)setMessages(current=>current.map(m=>m.id===optimisticId?p.message:m));setNotice("Votre message a été envoyé. L’assistant Petit Annonces analyse votre demande.");await load();setTimeout(()=>{void openTicket(selected)},700);setTimeout(()=>{void openTicket(selected)},2200)}else{setMessages(current=>current.filter(m=>m.id!==optimisticId));const p=await r.json().catch(()=>({}));setNotice(p.error==="ticket_closed"?"Cette demande est fermée. Créez une nouvelle demande si nécessaire.":"Votre réponse n’a pas pu être envoyée.")}}catch{setMessages(current=>current.filter(m=>m.id!==optimisticId));setNotice("La réponse n’a pas pu être confirmée. Réessayez dans un instant.")}finally{setReplying(false)}}
 async function closeTicket(){if(!selected||closing)return;if(!window.confirm("Clôturer cette demande d’assistance ? Vous pourrez ouvrir une nouvelle demande si nécessaire."))return;setClosing(true);setNotice("");try{const r=await fetch(`${api()}/support/tickets/${encodeURIComponent(selected)}/close`,{method:"POST",credentials:"include"});const p=await r.json().catch(()=>({}));if(r.ok){setNotice("Votre demande a été clôturée.");await load();await openTicket(selected)}else if(p.error==="vacation_incident_resolution_required")setNotice("Cette demande est liée à un dossier Vacances encore actif et ne peut pas être clôturée ici.");else setNotice("Impossible de clôturer cette demande pour le moment.")}catch{setNotice("La clôture n’a pas pu être confirmée. Réessayez dans un instant.")}finally{setClosing(false)}}
 const openCount=useMemo(()=>tickets.filter(t=>!["RESOLVED","CLOSED"].includes(t.status)).length,[tickets]);const selectedTicket=tickets.find(t=>t.id===selected)??null;const visibleFaqs=useMemo(()=>{const q=faqQuery.trim().toLocaleLowerCase("fr-FR");return faqs.filter(f=>(faqCategory==="ALL"||f.category===faqCategory)&&(!q||`${f.question} ${f.answer}`.toLocaleLowerCase("fr-FR").includes(q)))},[faqs,faqCategory,faqQuery]);
 return <div className={styles.page}><main className={styles.accountShell}>{authenticated!==false&&<AccountSidebar/>}<section className={styles.content}>
  <header className={styles.hero}><div><span className={styles.eyebrow}>Centre d’aide Petit Annonces</span><h1>Comment pouvons-nous vous aider ?</h1><p>Consultez les réponses fréquentes ou contactez notre assistant. Les dossiers sensibles restent vérifiés par notre équipe.</p></div><div className={styles.heroBadge}><AppIcon name="comments"/><span><b>Assistant + équipe</b><small>Réponse rapide et suivi humain</small></span></div></header>
  {notice&&<div className={styles.notice}>{notice}</div>}
  {authenticated===false&&<section className={styles.loginCard}><div><AppIcon name="user-shield"/></div><h2>Connectez-vous pour contacter le support</h2><p>Votre compte permet de suivre toutes vos demandes et les réponses du service client au même endroit.</p><a href="/connexion?next=%2Fassistance">Se connecter</a></section>}
  <section className={styles.topicSection}><div className={styles.topicHead}><span>Choisir un sujet</span><h2>Allez directement à l’essentiel</h2><p>Sélectionnez le thème qui correspond à votre demande.</p></div><div className={styles.helpGrid}>{helpCards.map(c=><button key={c.title} type="button" onClick={()=>{setPreset(c.category);document.getElementById("support-form")?.scrollIntoView({behavior:"smooth"})}}><span><AppIcon name={c.icon}/></span><div><strong>{c.title}</strong><p>{c.text}</p></div><i>›</i></button>)}</div></section>
  <section id="faq" className={styles.faqSection}><div className={styles.faqHead}><div><span>Questions fréquentes</span><h2>Trouvez une réponse immédiatement</h2><p>Les solutions issues des demandes résolues sont anonymisées, classées et ajoutées automatiquement ici.</p></div><b>{faqs.length} réponse{faqs.length>1?"s":""}</b></div><div className={styles.faqTools}><div className={styles.faqSearch}><AppIcon name="search"/><input value={faqQuery} onChange={e=>setFaqQuery(e.target.value)} placeholder="Rechercher dans l’aide…"/></div><div className={styles.faqCategories}><button className={faqCategory==="ALL"?styles.faqActive:""} onClick={()=>setFaqCategory("ALL")}>Toutes</button>{Object.entries(categoryLabel).map(([v,l])=><button key={v} className={faqCategory===v?styles.faqActive:""} onClick={()=>setFaqCategory(v)}>{l}</button>)}</div></div><div className={styles.faqList}>{visibleFaqs.slice(0,10).map(f=><details key={f.id}><summary><span>{categoryLabel[f.category]??f.category}</span><strong>{f.question}</strong><i>+</i></summary><p>{f.answer}</p></details>)}{!visibleFaqs.length&&<div className={styles.faqEmpty}>Aucune réponse ne correspond encore à cette recherche. Vous pouvez ouvrir une demande ci-dessous.</div>}</div></section>
  {authenticated!==false&&<div className={styles.workspace}>
   <section id="support-form" className={styles.card}><div className={styles.cardHead}><div><span>Nouvelle demande</span><h2>Contacter le service client</h2><p>Plus votre demande est précise, plus notre équipe peut vous répondre efficacement.</p></div><AppIcon name="comments"/></div><form className={styles.form} onSubmit={submit}><label>Catégorie<select name="category" value={preset} onChange={e=>setPreset(e.target.value)}>{Object.entries(categoryLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Sujet<input name="subject" required minLength={4} maxLength={180} placeholder="Ex. Je n’arrive pas à publier mon annonce"/></label><label>Votre message<textarea name="body" required minLength={10} maxLength={5000} rows={7} placeholder="Expliquez le problème, ce que vous avez déjà essayé et ajoutez le numéro d’annonce ou de commande si vous l’avez."/></label><button disabled={sending}>{sending?"Envoi en cours…":"Envoyer ma demande"}</button></form></section>
   <section className={styles.card}><div className={styles.cardHead}><div><span>Suivi</span><h2>Mes demandes</h2><p>{loading?"Chargement…":`${openCount} demande${openCount>1?"s":""} en cours`}</p></div><b className={styles.ticketCount}>{tickets.length}</b></div><div className={styles.ticketList}>{tickets.map(t=><button key={t.id} className={selected===t.id?styles.ticketActive:""} onClick={()=>void openTicket(t.id)}><div><strong>{t.subject}</strong><small>{t.reference} · {categoryLabel[t.category]??t.category}</small></div><span>{statusLabel[t.status]??t.status}</span></button>)}{!loading&&!tickets.length&&<div className={styles.empty}>Vous n’avez encore aucune demande. Notre équipe est accessible depuis le formulaire ci-contre.</div>}</div></section>
  </div>}
  {selected&&selectedTicket&&<section className={styles.threadCard}><div className={styles.threadHead}><div><span>{selectedTicket.reference}</span><h2>{selectedTicket.subject}</h2><p>{statusLabel[selectedTicket.status]??selectedTicket.status}</p></div><div className={styles.threadActions}>{selectedTicket.status!=="CLOSED"&&<button type="button" className={styles.closeTicketButton} disabled={closing} onClick={()=>void closeTicket()}>{closing?"Clôture…":"Clôturer la demande"}</button>}<button type="button" onClick={()=>{setSelected(null);setMessages([])}}>Masquer</button></div></div><div className={styles.thread}>{messages.map(m=><article key={m.id} className={m.authorType==="CUSTOMER"?styles.customer:styles.agent}><div><strong>{m.authorType==="CUSTOMER"?"Vous":m.authorType==="SYSTEM"?"Assistant Petit Annonces":"Service client Petit Annonces"}</strong><small>{new Date(m.createdAt).toLocaleString("fr-FR")}</small></div><p>{m.body}</p></article>)}</div>{selectedTicket.status!=="CLOSED"&&<form className={styles.replyForm} onSubmit={replyTicket}><textarea name="reply" minLength={2} maxLength={5000} required rows={4} placeholder="Répondre au service client…"/><button disabled={replying}>{replying?"Envoi…":"Envoyer ma réponse"}</button></form>}</section>}
  <section className={styles.safety}><AppIcon name="shield"/><div><strong>Besoin de signaler un contenu potentiellement illicite ?</strong><p>Le formulaire DSA dédié fournit une référence de suivi juridique distincte d’une demande de support classique.</p></div><a href="/signaler-contenu-illicite">Accéder au signalement</a></section>
 </section></main></div>;
}