"use client";
import {useEffect,useMemo,useState} from "react";

type Mail={id:string;from:string;to:string;replyTo:string;messageId:string|null;subject:string;date:string|null;preview:string;body:string;read:boolean};
export default function InboxPage(){
 const[messages,setMessages]=useState<Mail[]>([]),[selected,setSelected]=useState<Mail|null>(null),[address,setAddress]=useState("info@petitannonces.fr"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[replying,setReplying]=useState(false),[replyBody,setReplyBody]=useState(""),[sending,setSending]=useState(false),[deleting,setDeleting]=useState(false),[sentMsg,setSentMsg]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/admin/inbox",{credentials:"include",cache:"no-store"});const p=await r.json().catch(()=>({messages:[]}));if(!r.ok){setError("Impossible de charger la boîte de réception.");return}const nextMessages:Mail[]=p.messages??[];setMessages(nextMessages);setAddress(p.address??address);setSelected(prev=>prev?(nextMessages.find(x=>x.id===prev.id)??nextMessages[0]??null):(nextMessages[0]??null))}catch{setError("Connexion impossible avec la boîte de réception.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const unread=useMemo(()=>messages.filter(x=>!x.read).length,[messages]);
 async function open(m:Mail){setSelected({...m,read:true});setReplying(false);setReplyBody("");setSentMsg("");if(!m.read){setMessages(v=>v.map(x=>x.id===m.id?{...x,read:true}:x));await fetch(`/api/admin/inbox/${m.id}/read`,{method:"POST",credentials:"include"}).catch(()=>undefined)}}
 async function removeSelected(){if(!selected||deleting)return;if(!window.confirm(`Supprimer définitivement « ${selected.subject} » de la boîte de réception ?`))return;setDeleting(true);setError("");setSentMsg("");try{const r=await fetch(`/api/admin/inbox/${selected.id}`,{method:"DELETE",credentials:"include"});if(!r.ok){setError("Impossible de supprimer cet e-mail.");return}const remaining=messages.filter(x=>x.id!==selected.id);setMessages(remaining);setSelected(remaining[0]??null);setReplying(false);setReplyBody("");setSentMsg("E-mail supprimé de la boîte de réception.")}catch{setError("Connexion interrompue pendant la suppression.")}finally{setDeleting(false)}}
 async function sendReply(){if(!selected||!replyBody.trim())return;setSending(true);setError("");setSentMsg("");try{const r=await fetch(`/api/admin/inbox/${selected.id}/reply`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({body:replyBody})});const p=await r.json().catch(()=>({}));if(!r.ok){setError(p.error==="invalid_recipient"?"Adresse de réponse invalide.":"Envoi impossible. Vérifiez le serveur e-mail.");return}setSentMsg(`Réponse envoyée à ${p.to??selected.replyTo}.`);setReplyBody("");setReplying(false)}catch{setError("Connexion interrompue pendant l’envoi.")}finally{setSending(false)}}
 return <>
  <div className="admin-page-head admin-inbox-head"><div><p>Messagerie professionnelle</p><h1>Boîte de réception</h1><span className="subtitle">{address} · messages reçus directement sur le domaine petitannonces.fr</span></div><div className="admin-inbox-head-actions">{unread>0&&<span className="admin-badge orange">{unread} non lu(s)</span>}<button type="button" className="admin-btn" onClick={()=>void load()} disabled={loading}>{loading?"Actualisation…":"Actualiser"}</button></div></div>
  {error&&<div className="admin-flash err">{error}</div>}{sentMsg&&<div className="admin-flash ok">{sentMsg}</div>}
  <div className="admin-grid admin-inbox-grid">
   <section className="admin-card admin-section admin-inbox-list-card"><div className="admin-inbox-list-head"><strong>Messages</strong><p>{messages.length} message(s)</p></div><div className="admin-inbox-list">{messages.map(m=><button type="button" key={m.id} onClick={()=>void open(m)} className={`admin-inbox-item ${selected?.id===m.id?"active":""}`}><div><strong className={m.read?"":"unread"}>{m.from}</strong>{!m.read&&<span className="admin-badge orange">Nouveau</span>}</div><b className={m.read?"":"unread"}>{m.subject}</b><p>{m.preview}</p><small>{m.date?new Date(m.date).toLocaleString("fr-FR"):"Date inconnue"}</small></button>)}{!messages.length&&!loading&&<div className="admin-empty">Aucun e-mail reçu pour le moment.</div>}</div></section>
   <section className="admin-card admin-section admin-inbox-reader">{selected?<><div className="admin-section-head admin-inbox-message-head"><div><h2>{selected.subject}</h2><p><strong>De :</strong> {selected.from}</p><p><strong>Répondre à :</strong> {selected.replyTo||"—"}</p><p><strong>À :</strong> {selected.to}</p><p>{selected.date?new Date(selected.date).toLocaleString("fr-FR"):""}</p></div><div className="admin-inbox-message-actions"><button type="button" className="admin-btn primary" disabled={!selected.replyTo} onClick={()=>{setReplying(v=>!v);setSentMsg("")}}>{replying?"Fermer la réponse":"Répondre"}</button><button type="button" className="admin-btn danger" disabled={deleting} onClick={()=>void removeSelected()}>{deleting?"Suppression…":"Supprimer"}</button></div></div><div className="admin-inbox-body">{selected.body}</div>{replying&&<div className="admin-inbox-reply"><div className="admin-section-head"><div><h3>Répondre</h3><p>Depuis <strong>{address}</strong> vers <strong>{selected.replyTo}</strong></p></div></div><textarea className="admin-input" rows={10} value={replyBody} onChange={e=>setReplyBody(e.target.value)} placeholder="Rédigez votre réponse…"/><div className="admin-inbox-reply-actions"><button type="button" className="admin-btn" onClick={()=>{setReplying(false);setReplyBody("")}}>Annuler</button><button type="button" className="admin-btn primary" disabled={sending||!replyBody.trim()} onClick={()=>void sendReply()}>{sending?"Envoi…":"Envoyer la réponse"}</button></div></div>}</>:<div className="admin-empty">Sélectionnez un message pour l’afficher.</div>}</section>
  </div>
 </>}