import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { LongtailListingPage, moneyRange, seoApi, type LongtailData } from "../../../../lib/seo-longtail";

export const revalidate=120;
type Props={params:Promise<{make:string;model:string}>};type Meta={make:string;model:string;total:number;minPrice:number|null;maxPrice:number|null};
async function meta(make:string,model:string):Promise<Meta|null>{const r=await fetch(`${seoApi()}/seo/vehicle/${encodeURIComponent(make)}/${encodeURIComponent(model)}`,{next:{revalidate:300}});if(!r.ok)return null;return r.json()}
async function data(m:Meta):Promise<LongtailData>{const q=new URLSearchParams({category:"vehicules",make:m.make,model:m.model,limit:"24",sort:"recent"});const r=await fetch(`${seoApi()}/search?${q}`,{next:{revalidate:120}});return r.ok?r.json():{total:0,items:[]}}
export async function generateMetadata({params}:Props):Promise<Metadata>{const{make,model}=await params;const m=await meta(make,model);if(!m)return{title:"Véhicule d’occasion | Petit Annonces",robots:{index:false,follow:true}};const title=`${m.make} ${m.model} d’occasion : petites annonces | Petit Annonces`;const description=`${m.total} annonce${m.total>1?"s":""} ${m.make} ${m.model} d’occasion disponible${m.total>1?"s":""} en France${moneyRange(m.minPrice,m.maxPrice)?`. Prix observés : ${moneyRange(m.minPrice,m.maxPrice)}`:""}.`;return{title:{absolute:title},description,alternates:{canonical:`/vehicules/${make}/${model}`},robots:{index:m.total>=3,follow:true},openGraph:{type:"website",url:`/vehicules/${make}/${model}`,title,description}}}
export default async function Page({params}:Props){const{make,model}=await params;const m=await meta(make,model);if(!m)notFound();const d=await data(m);return <LongtailListingPage eyebrow="Modèle d’occasion" title={`${m.make} ${m.model} d’occasion : petites annonces`} description={`Retrouvez les ${m.make} ${m.model} actuellement proposées par les vendeurs Petit Annonces. ${m.total} annonce${m.total>1?"s":""}${moneyRange(m.minPrice,m.maxPrice)?`, avec une fourchette de prix de ${moneyRange(m.minPrice,m.maxPrice)}`:""}.`} data={d} backHref={`/vehicules/${make}`} backLabel={m.make} canonicalPath={`/vehicules/${make}/${model}`}/>}
