"use client";
import {useEffect,useMemo,useState} from "react";
type Referral={id:string;status:string;createdAt:string;qualifiedAt:string|null;rewardedAt:string|null;displayName:string;maskedEmail:string;emailVerifiedAt:string|null;rewardMinor:number};
type Payload={referralCode:{code:string;rewardCredits:number};referrals:Referral[];rewardsEnabled:boolean;rewardRule?:string;stats?:{total:number;verified:number;rewarded:number;pending:number;awaitingFirstListing?:number;earnedMinor:number;currency:string}};
function euro(minor:number){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format((Number(minor)||0)/100)}
function api(){return(process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"")}
function status(v:string){return ({PENDING:"En attente de vérification",QUALIFIED:"E-mail vérifié · 1re annonce à faire valider",REWARDED:"5 € gagnés",CANCELED:"Annulée"} as Record<string,string>)[v]??v}
export default function ReferralClient(){
 const[data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[copied,setCopied]=useState(false);
 useEffect(()=>{fetch(`${api()}/referrals/me`,{credentials:"include",cache:"no-store"}).then(async r=>{if(r.status===401){location.href="/connexion?next=%2Fparrainage";return null}if(!r.ok)throw new Error();return r.json()}).then(p=>p&&setData(p)).catch(()=>setError("Impossible de charger votre code de parrainage pour le moment."))},[]);
 const link=useMemo(()=>data?`https://petitannonces.fr/inscription?ref=${encodeURIComponent(data.referralCode.code)}&utm_source=referral&utm_medium=share&utm_campaign=parrainage_5eur`:"",[data]);
 async function copy(){if(!link)return;try{await navigator.clipboard.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setError("Copie impossible sur cet appareil.")}}
 async function share(){if(!link)return;if(navigator.share){try{await navigator.share({title:"Petit Annonces · Parrainage 5 €",text:"Je vous invite sur Petit Annonces. Inscrivez-vous avec mon lien, vérifiez votre e-mail puis publiez une première annonce. Dès qu’elle est approuvée, je gagne 5 € de crédit Petit Annonces et vous profitez de votre crédit de bienvenue.",url:link});return}catch{}}await copy()}
 return <div style={{minHeight:"100vh",background:"#fafafe"}}><main className="shell" style={{paddingBlock:48,maxWidth:980}}>
  <p style={{color:"#5b4cf0",fontWeight:900,textTransform:"uppercase",fontSize:12}}>Parrainage</p><h1 style={{marginTop:8,fontSize:"clamp(32px,5vw,48px)"}}>Parrainez un membre, gagnez 5 €.</h1><p style={{marginTop:12,color:"#6c6c7d",lineHeight:1.7,maxWidth:760}}>Partagez votre lien personnel. Dès que votre proche crée son compte, <strong>vérifie son adresse e-mail puis publie une première annonce qui est approuvée</strong>, <strong>5,00 €</strong> de crédit Petit Annonces sont ajoutés à votre portefeuille. Votre invité conserve également son crédit de bienvenue prévu à l’inscription.</p>{data?.stats&&<div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:18}}><span style={{padding:"9px 12px",borderRadius:12,background:"#ecfbf1",color:"#178447",fontWeight:850}}>Gains : {euro(data.stats.earnedMinor)}</span><span style={{padding:"9px 12px",borderRadius:12,background:"#f3f1ff",color:"#5b4cf0",fontWeight:850}}>{data.stats.awaitingFirstListing??0} en attente de 1re annonce</span><span style={{padding:"9px 12px",borderRadius:12,background:"#fff8e8",color:"#8b6d1f",fontWeight:850}}>{data.stats.pending} e-mail(s) à vérifier</span></div>}
  {error&&<div style={{marginTop:20,padding:14,borderRadius:14,background:"#fff0f0",color:"#a52a2a"}}>{error}</div>}
  <section style={{marginTop:28,border:"1px solid #e7e7ee",borderRadius:22,padding:"clamp(18px,4vw,28px)",background:"white"}}><small style={{fontWeight:800,color:"#747487"}}>Votre code personnel</small><div style={{display:"flex",gap:12,alignItems:"center",flexWrap:"wrap",marginTop:8}}><strong style={{fontSize:28,letterSpacing:1}}>{data?.referralCode.code??"Chargement…"}</strong>{data&&<span style={{padding:"5px 9px",borderRadius:999,background:"#ecfbf1",color:"#178447",fontSize:12,fontWeight:850}}>5 € après 1re annonce approuvée</span>}{data&&<button type="button" onClick={()=>void copy()} style={{border:0,borderRadius:12,padding:"11px 15px",fontWeight:850,cursor:"pointer"}}>{copied?"Copié ✓":"Copier le lien"}</button>}{data&&<button type="button" onClick={()=>void share()} style={{border:0,borderRadius:12,padding:"11px 15px",fontWeight:850,cursor:"pointer"}}>Partager</button>}</div>{link&&<p style={{marginTop:12,overflowWrap:"anywhere",color:"#5b4cf0",fontSize:14}}>{link}</p>}</section>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:16,marginTop:22}}>{[["1","Partagez votre lien","Le code de parrainage est ajouté automatiquement au lien d’inscription."],["2","Votre proche crée son compte","L’invitation est rattachée automatiquement à son nouveau compte Petit Annonces."],["3","Première annonce approuvée = 5 €","Après vérification de son e-mail, votre proche publie une première annonce. Dès qu’elle est approuvée, 5 € de crédit sont ajoutés à votre portefeuille."]].map(([n,title,text])=><article key={n} style={{border:"1px solid #e7e7ee",borderRadius:20,padding:20,background:"white"}}><strong style={{color:"#5b4cf0"}}>{n}</strong><h2 style={{fontSize:18,marginTop:8}}>{title}</h2><p style={{color:"#6c6c7d",lineHeight:1.55}}>{text}</p></article>)}</div>
  <section style={{marginTop:24,border:"1px solid #e7e7ee",borderRadius:22,padding:"clamp(18px,4vw,28px)",background:"white"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"end",flexWrap:"wrap"}}><div><small style={{fontWeight:800,color:"#747487"}}>Suivi</small><h2 style={{marginTop:4}}>Mes membres parrainés</h2></div><div style={{textAlign:"right"}}><strong style={{display:"block",fontSize:28}}>{data?.referrals.length??0}</strong>{data?.stats&&<small style={{color:"#178447",fontWeight:850}}>Gagné : {euro(data.stats.earnedMinor)}</small>}</div></div>{data?.referrals.length?<div style={{marginTop:16,display:"grid",gap:10}}>{data.referrals.map(r=><div key={r.id} style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:14,alignItems:"center",padding:"14px 0",borderTop:"1px solid #eeeef4"}}><div style={{minWidth:0}}><strong style={{display:"block",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{r.displayName||"Membre invité"}</strong><small style={{display:"block",marginTop:4,color:"#777789"}}>{r.maskedEmail} · inscrit le {new Date(r.createdAt).toLocaleDateString("fr-FR")}</small><span style={{display:"inline-block",marginTop:6,fontSize:12,fontWeight:850,color:r.status==="REWARDED"?"#178447":r.status==="CANCELED"?"#a52a2a":"#5b4cf0"}}>{status(r.status)}</span></div><div style={{textAlign:"right"}}><strong style={{fontSize:17,color:r.rewardMinor>0?"#178447":"#777789"}}>{r.rewardMinor>0?`+${euro(r.rewardMinor)}`:"—"}</strong>{r.rewardedAt&&<small style={{display:"block",marginTop:4,color:"#90909e"}}>{new Date(r.rewardedAt).toLocaleDateString("fr-FR")}</small>}</div></div>)}</div>:data?<p style={{marginTop:16,color:"#777789"}}>Aucun membre parrainé pour le moment. Partagez votre lien pour commencer.</p>:null}</section><p style={{marginTop:16,color:"#8b8b99",fontSize:12,lineHeight:1.6}}>Le crédit de parrainage n’est pas retirable en espèces. Il est utilisable pour les services Petit Annonces éligibles. Les auto-parrainages et comptes frauduleux ne sont pas éligibles.</p>
 </main></div>
}