"use client";

import { FormEvent, useState } from "react";
import { SiteHeader } from "../../components/site-header";
import styles from "../auth.module.css";

function apiBase(){return (process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000").replace(/\/$/,"")}

export default function ForgotPasswordPage(){
  const [email,setEmail]=useState("");const [busy,setBusy]=useState(false);const [sent,setSent]=useState(false);const [devToken,setDevToken]=useState("");const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch(`${apiBase()}/auth/forgot-password`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});if(!r.ok)throw new Error("request_failed");const p=await r.json();setDevToken(p.devResetToken??"");setSent(true)}catch{setError("Impossible d’envoyer la demande pour le moment.")}finally{setBusy(false)}}
  return <div className={styles.page}><SiteHeader/><main className={styles.main}><div className={styles.authGrid}><section className={styles.formCard}><span className={styles.eyebrow}>Sécurité du compte</span><h1 className={styles.title}>Mot de passe oublié ?</h1><p className={styles.lead}>Indiquez votre adresse e-mail. Si un compte existe, vous recevrez un lien sécurisé pour choisir un nouveau mot de passe.</p>{error&&<div className={styles.error}>{error}</div>}{sent?<div className={styles.success}><strong>Demande enregistrée.</strong><br/>Consultez votre boîte e-mail et suivez le lien de réinitialisation.{devToken&&<><br/><a className={styles.inlineLink} href={`/reinitialiser-mot-de-passe?token=${devToken}`}>Lien de développement</a></>}</div>:<form className={styles.form} onSubmit={submit}><label className={styles.field}>Adresse e-mail<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="vous@exemple.fr" required/></label><button className={styles.primary} disabled={busy}>{busy?"Envoi…":"Recevoir le lien"}</button></form>}<p className={styles.footText}><a href="/connexion">← Retour à la connexion</a></p></section><aside className={styles.benefitCard}><span className={styles.eyebrow}>Protection</span><h2 className={styles.title}>Votre sécurité reste prioritaire.</h2><p className={styles.lead}>Le lien de réinitialisation est temporaire et ne peut être utilisé qu’une seule fois.</p><div className={styles.benefits}><div className={styles.benefit}><div className={styles.benefitIcon}>⏱</div><div><strong>Lien temporaire</strong><p>Le jeton expire automatiquement après 30 minutes.</p></div></div><div className={styles.benefit}><div className={styles.benefitIcon}>✓</div><div><strong>Usage unique</strong><p>Après changement du mot de passe, le lien devient inutilisable.</p></div></div><div className={styles.benefit}><div className={styles.benefitIcon}>⌁</div><div><strong>Sessions protégées</strong><p>Les autres sessions actives sont révoquées après la réinitialisation.</p></div></div></div></aside></div></main></div>
}
