import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PA } from '../../constants/theme';
import { ApiError, apiRequest } from '../../lib/api';
import { useAuth } from '../../lib/auth';
import { money } from '../../lib/format';
import { AppIcon } from '../../components/app-icon';

type ListingPayload={listing:{id:string;title:string|null;priceMinor:number|null;currency:string;commerce?:{acceptsOffers:boolean}}};
type ConversationPayload={conversation:{id:string}};

export default function OfferScreen(){
 const p=useLocalSearchParams<{listingId:string;conversationId?:string;parentOfferId?:string;amountMinor?:string}>();
 const {token,user,loading:authLoading}=useAuth();
 const [listing,setListing]=useState<ListingPayload['listing']|null>(null);
 const [amount,setAmount]=useState('');
 const [loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!token||!p.listingId){setLoading(false);return}apiRequest<ListingPayload>(`/public/listings/${encodeURIComponent(String(p.listingId))}`).then(x=>{setListing(x.listing);if(p.amountMinor)setAmount((Number(p.amountMinor)/100).toFixed(2).replace('.',','));else if(x.listing.priceMinor)setAmount((x.listing.priceMinor/100*0.9).toFixed(2).replace('.',','))}).catch(()=>setError('Annonce indisponible.')).finally(()=>setLoading(false))},[token,p.listingId,p.amountMinor]);
 const parsed=useMemo(()=>Number(amount.replace(',','.')),[amount]);
 async function submit(){if(!token||!user||!p.listingId||!Number.isFinite(parsed)||parsed<1||sending)return;setSending(true);setError('');try{let conversationId=p.conversationId?String(p.conversationId):'';if(!conversationId){const c=await apiRequest<ConversationPayload>('/conversations',{method:'POST',token,body:{listingId:String(p.listingId)}});conversationId=c.conversation.id}await apiRequest(`/conversations/${encodeURIComponent(conversationId)}/offers`,{method:'POST',token,body:{amount:parsed,parentOfferId:p.parentOfferId?String(p.parentOfferId):undefined}});router.replace(`/messages/${conversationId}` as never)}catch(e){const code=e instanceof ApiError?e.code:'';setError(code==='offers_disabled'?'Le vendeur n’accepte pas les offres.':code==='offer_rate_limited'?'Vous avez envoyé trop d’offres. Réessayez dans une minute.':code==='offers_temporarily_restricted'?'Les offres sont temporairement limitées sur votre compte.':code==='offer_cannot_be_countered'?'Cette offre ne peut plus recevoir de contre-offre.':'Impossible d’envoyer cette offre.')}finally{setSending(false)}}
 if(authLoading||loading)return <SafeAreaView style={s.center}><ActivityIndicator color={PA.primary}/></SafeAreaView>;
 if(!user||!token)return <SafeAreaView style={s.center}><Text style={s.title}>Faire une offre</Text><Text style={s.muted}>Connectez-vous pour proposer un prix.</Text><Pressable style={s.primary} onPress={()=>router.replace('/auth/login')}><Text style={s.primaryText}>Se connecter</Text></Pressable></SafeAreaView>;
 return <SafeAreaView style={s.safe} edges={['top','bottom']}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={{flexGrow:1}} keyboardShouldPersistTaps="handled" keyboardDismissMode="interactive" automaticallyAdjustKeyboardInsets><View style={s.header}><Pressable accessibilityRole="button" accessibilityLabel="Retour" style={s.back} onPress={()=>router.back()}><AppIcon name="chevron-left" size={15} color={PA.ink}/></Pressable><View><Text style={s.eyebrow}>{p.parentOfferId?'CONTRE-OFFRE':'NÉGOCIATION'}</Text><Text style={s.title}>Faire une offre</Text></View></View><View style={s.card}><Text style={s.listing}>{listing?.title||'Annonce Petit Annonces'}</Text><Text style={s.ask}>Prix affiché : {money(listing?.priceMinor??0,listing?.currency??'EUR')}</Text><Text style={s.label}>Votre prix proposé</Text><View style={s.amountRow}><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" style={s.input} placeholder="0,00" placeholderTextColor="#9a9aa5"/><Text style={s.euro}>€</Text></View><Text style={s.note}>L’offre reste valable 48 heures. Le paiement n’est effectué que si l’offre est acceptée puis payée via Petit Annonces.</Text>{error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={sending||!Number.isFinite(parsed)||parsed<1} onPress={()=>void submit()} style={[s.primary,(sending||!Number.isFinite(parsed)||parsed<1)&&s.disabled]}><Text style={s.primaryText}>{sending?'Envoi…':p.parentOfferId?'Envoyer la contre-offre':'Envoyer mon offre'}</Text></Pressable></View></ScrollView></KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:PA.bg},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12,padding:24,backgroundColor:PA.bg},header:{flexDirection:'row',alignItems:'center',gap:12,padding:16},back:{width:40,height:40,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center'},backText:{fontSize:29,lineHeight:30,color:PA.ink},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.1,color:PA.primary},title:{fontSize:24,fontWeight:'900',color:PA.ink},muted:{fontSize:12,color:PA.muted,textAlign:'center'},card:{margin:16,marginTop:4,padding:18,borderRadius:22,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line},listing:{fontSize:16,fontWeight:'900',color:PA.ink},ask:{fontSize:12,color:PA.muted,marginTop:5},label:{fontSize:11,fontWeight:'900',color:PA.ink,marginTop:22,marginBottom:8},amountRow:{flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:PA.line,borderRadius:16,paddingHorizontal:14},input:{flex:1,height:58,fontSize:24,fontWeight:'900',color:PA.ink},euro:{fontSize:22,fontWeight:'900',color:PA.ink},note:{fontSize:10.5,lineHeight:16,color:PA.muted,marginTop:12},primary:{height:50,borderRadius:14,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center',marginTop:18},primaryText:{fontSize:12,fontWeight:'900',color:'#fff'},disabled:{opacity:.45},error:{marginTop:12,padding:10,borderRadius:10,backgroundColor:'#fff0f0',color:PA.danger,fontSize:11}})
