import type { Metadata } from "next";
import { CatalogFilterPanel } from "../../components/catalog-filter-panel";
import { AppIcon } from "../../components/app-icon";
import { MarketplaceListingCard } from "../../components/marketplace-listing-card";
import { SearchPageAutoForm } from "../../components/auto-search-forms";
import { SearchResultsMap } from "../../components/search-results-map";
import { SearchViewControls } from "../../components/search-view-controls";
import { arrangePromotedFlow, type ListingPromotion } from "../../lib/listing-promotions";
import styles from "./page.module.css";

type SearchParams=Promise<Record<string,string|string[]|undefined>>;
type SearchItem={id:string;slug:string|null;title:string|null;priceMinor:number|null;currency:string;city:string|null;latitude:number|null;longitude:number|null;distanceKm?:number;publishedAt:string|null;createdAt:string;category:{name:string;slug:string;domain:string};vehicle?:{modelYear?:number|null;mileageKm?:number|null;fuel?:string|null}|null;property?:{surfaceM2?:number|null;rooms?:number|null;transactionType?:string|null}|null;imageUrl:string|null;promotions?:ListingPromotion[];commerce?:{securePaymentEnabled?:boolean;shippingEnabled?:boolean};sellerReputation:{verified:boolean;kind?:string;hasStore?:boolean;paymentReady?:boolean;avatarUrl?:string|null;sellerName?:string|null;reviewCount:number;reviewAverage:number|null;completedSales:number;trust:{score:number;reliableSeller:boolean;level:"NEW"|"ESTABLISHED"|"TRUSTED"}}};
type SearchPayload={total:number;items:SearchItem[]};
type CategoryNode={id:string;name:string;slug:string;domain:string;children?:CategoryNode[]};
type FilterCategoryNode={name:string;slug:string;children?:FilterCategoryNode[]};
type FilterOption={value:string;label:string;count?:number};
type FilterAttribute={key:string;label:string;type:"TEXT"|"NUMBER"|"SELECT"|"MULTISELECT"|"BOOLEAN"|"DATE";unit:string|null;options:FilterOption[];min?:number;max?:number;dependsOn?:string};
type FilterPayload={attributes?:FilterAttribute[];priceRange?:{min:number|null;max:number|null;count:number}};
type HeaderBrand={siteName:string;tagline:string;logoUrl:string|null;mobileLogoUrl:string|null;accentColor:string;navigationCategorySlugs?:string[]};
const FALLBACK_BRAND:HeaderBrand={siteName:"Petit Annonces",tagline:"",logoUrl:null,mobileLogoUrl:null,accentColor:"#5b4cf0"};
const base=()=> (process.env.API_INTERNAL_URL??process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000").replace(/\/$/,"");
const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]:v;
const attrPairs=(params:Record<string,string|string[]|undefined>)=>Object.entries(params).filter(([key,value])=>key.startsWith("attr_")&&Boolean(one(value))).map(([key,value])=>[key,one(value)!] as const);

export const metadata:Metadata={title:"Recherche d’annonces",description:"Recherchez des annonces partout en France sur Petit Annonces.",alternates:{canonical:"/recherche"},robots:{index:false,follow:true}};

function initialAttributeState(params:Record<string,string|string[]|undefined>){const values:Record<string,string>={};const ranges:Record<string,{min:string;max:string}>={};for(const [rawKey,value] of attrPairs(params)){const match=rawKey.match(/^attr_(.+?)(?:_(min|max))?$/);if(!match)continue;const key=match[1]??"";const side=match[2];if(!key)continue;if(side){ranges[key]={...(ranges[key]??{min:"",max:""}),[side]:value}}else values[key]=value}return{values,ranges}}
function slimFilterTree(nodes:CategoryNode[]):FilterCategoryNode[]{return nodes.map(node=>({name:node.name,slug:node.slug,...((node.children?.length??0)>0?{children:slimFilterTree(node.children??[])}:{})}))}
async function search(params:Record<string,string|string[]|undefined>):Promise<SearchPayload>{const qs=new URLSearchParams();const view=one(params.view)==="map"?"map":"list";for(const key of ["q","category","city","minPrice","maxPrice","radiusKm","near","north","south","east","west","page","sort"]){const value=one(params[key]);if(value)qs.set(key,value);}for(const [key,value] of attrPairs(params))qs.set(key,value);if(view==="map")qs.set("map","1");qs.set("limit",view==="map"?"50":"25");const r=await fetch(`${base()}/search?${qs.toString()}`,{next:{revalidate:10}});if(!r.ok)return{total:0,items:[]};return r.json();}
async function pageData(category:string,brand:string){const safe=(promise:Promise<Response>)=>promise.catch(()=>null);const [brandRes,categoryRes,filterRes]=await Promise.all([safe(fetch(`${base()}/public/site-config`,{next:{revalidate:300}})),safe(fetch(`${base()}/categories/tree`,{next:{revalidate:300}})),category?safe(fetch(`${base()}/categories/${encodeURIComponent(category)}/filter-attributes${brand?`?brand=${encodeURIComponent(brand)}`:""}`,{next:{revalidate:30}})):Promise.resolve(null)]);let site=FALLBACK_BRAND,rawCategories:CategoryNode[]=[],filters:FilterPayload={attributes:[],priceRange:{min:null,max:null,count:0}};if(brandRes?.ok){const payload=await brandRes.json() as {site?:Partial<HeaderBrand>};site={...FALLBACK_BRAND,...(payload.site??{})}}if(categoryRes?.ok){const payload=await categoryRes.json() as {categories?:CategoryNode[]};rawCategories=payload.categories??[]}if(filterRes?.ok){filters=await filterRes.json() as FilterPayload}const headerCategories=rawCategories.map(({id,name,slug,domain})=>({id,name,slug,domain}));const filterCategories=slimFilterTree(rawCategories);return{site,headerCategories,filterCategories,filters}}


export default async function SearchPage({searchParams}:{searchParams:SearchParams}) {
  const params=await searchParams;const category=one(params.category)??"";const initialAttrs=initialAttributeState(params);const [data,support]=await Promise.all([search(params),pageData(category,initialAttrs.values.brand??"")]);const q=one(params.q)??"";const city=one(params.city)??"";const minPrice=one(params.minPrice)??"";const maxPrice=one(params.maxPrice)??"";const radiusKm=one(params.radiusKm)??"";const near=one(params.near)??"";const sort=one(params.sort)??"recent";const view=one(params.view)==="map"?"map":"list";const embed=one(params.embed)==="1";const pageSize=view==="map"?50:25;const page=Math.max(1,Number(one(params.page)??"1")||1);const totalPages=Math.max(1,Math.ceil(data.total/pageSize));const start=data.total?(page-1)*pageSize+1:0;const end=Math.min(page*pageSize,data.total);const flow=sort==="recent"?arrangePromotedFlow(data.items):data.items.map(item=>({item,spotlight:null}));const north=Number(one(params.north)),south=Number(one(params.south)),east=Number(one(params.east)),west=Number(one(params.west));const mapBounds=[north,south,east,west].every(Number.isFinite)&&south<north&&west<east?{north,south,east,west}:null;
  const dynamicFilters=attrPairs(params).map(([key,value])=>{const raw=key.slice(5);const side=raw.endsWith("_min")?" min.":raw.endsWith("_max")?" max.":"";const baseKey=raw.replace(/_(min|max)$/,"" );const label=baseKey.replace(/([A-Z])/g," $1").replace(/[-_]/g," ").trim();return{key,label:`${label}${side} : ${value}`}});
  const activeFilters=[q&&{key:"q",label:`Recherche : ${q}`},category&&{key:"category",label:`Catégorie : ${category}`},near&&{key:"near",label:`Autour de moi${city?` · ${city}`:""}`},!near&&city&&{key:"city",label:`Lieu : ${city}`},minPrice&&{key:"minPrice",label:`Prix min. : ${minPrice} €`},maxPrice&&{key:"maxPrice",label:`Prix max. : ${maxPrice} €`},radiusKm&&{key:"radiusKm",label:`Rayon : ${radiusKm} km`},mapBounds&&{key:"__map",label:"Zone de la carte"},...dynamicFilters].filter(Boolean) as Array<{key:string;label:string}>;
  function hrefForPage(target:number){const next=new URLSearchParams();for(const k of ["q","category","city","minPrice","maxPrice","radiusKm","near","sort","view","north","south","east","west"]){const v=one(params[k]);if(v)next.set(k,v)}for(const [key,value] of attrPairs(params))next.set(key,value);if(target>1)next.set("page",String(target));return `/recherche${next.toString()?`?${next.toString()}`:""}`;}
  function removeHref(key:string){const next=new URLSearchParams();for(const k of ["q","category","city","minPrice","maxPrice","radiusKm","near","sort","view","north","south","east","west"]){const v=one(params[k]);if(!v)continue;if(key==="__map"&&["north","south","east","west"].includes(k))continue;if(k!==key)next.set(k,v)}for(const [attrKey,value] of attrPairs(params))if(attrKey!==key)next.set(attrKey,value);return `/recherche${next.toString()?`?${next.toString()}`:""}`;}
  const pagination=Array.from({length:totalPages},(_,i)=>i+1).filter(n=>n===1||n===totalPages||Math.abs(n-page)<=2);
  if(embed&&view==="map")return <main style={{height:"100vh",overflow:"hidden",background:"#eef1f5"}}><SearchResultsMap items={data.items} total={data.total} initialBounds={mapBounds} embedded/></main>;
  return <div className={styles.page}><main className={styles.shell}>
    <header className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}>Explorer Petit Annonces</p><h1>Trouvez exactement ce que vous cherchez.</h1><p>Recherchez parmi les annonces disponibles partout en France.</p></div><SearchPageAutoForm initialQuery={q} initialCity={city} className={styles.searchbar} fieldClassName={styles.searchField}/></header>
    <div className={styles.layout}><CatalogFilterPanel key={`${category}|${city}|${minPrice}|${maxPrice}|${radiusKm}|${near}|${sort}|${view}|${attrPairs(params).map(([key,value])=>`${key}=${value}`).join("&")}`} category={category} city={city} minPrice={minPrice} maxPrice={maxPrice} q={q} sort={sort} radiusKm={radiusKm} near={near} view={view} initialCategoryTree={support.filterCategories} initialAttributes={(support.filters.attributes??[]).filter(attribute=>attribute.key&&attribute.label).slice(0,18)} initialPriceRange={support.filters.priceRange??{min:null,max:null,count:0}} initialAttributeValues={initialAttrs.values} initialAttributeRanges={initialAttrs.ranges}/><section className={styles.results}><div className={styles.toolbar}><div className={styles.resultCount}><span>Résultats</span><b>{data.total?(view==="map"?`${data.total.toLocaleString("fr-FR")} annonce${data.total>1?"s":""} sur la carte`:`${start}–${end} sur ${data.total.toLocaleString("fr-FR")}`):"Aucune annonce"}</b></div><form method="get" action="/recherche" className={styles.sortForm}>{["q","category","city","minPrice","maxPrice","radiusKm","near","view","north","south","east","west"].map(k=>{const v=one(params[k]);return v?<input key={k} type="hidden" name={k} value={v}/>:null})}{attrPairs(params).map(([key,value])=><input key={key} type="hidden" name={key} value={value}/>)}<label>Trier par <select name="sort" defaultValue={sort}><option value="recent">Plus récentes</option><option value="price_asc">Prix croissant</option><option value="price_desc">Prix décroissant</option></select></label><button type="submit">Appliquer</button></form></div>{activeFilters.length>0&&<div className={styles.activeFilters}>{activeFilters.map(f=><a key={f.key} href={removeHref(f.key)}>{f.label}<span>×</span></a>)}<a className={styles.clearAll} href="/recherche">Tout effacer</a></div>}
      <SearchViewControls view={view}/>
      {view==="list"&&<div className={styles.suggestions}><span>Repères</span><span className={styles.legendBadge}><AppIcon name="star"/> Avis après transaction</span><span className={styles.legendReliable}><AppIcon name="circle-check"/> Vendeur fiable</span></div>}
      {!data.items.length?<div className={styles.empty}><span className={styles.emptyIcon}><AppIcon name="search"/></span><strong>Aucune annonce ne correspond à votre recherche.</strong><span>Essayez d’élargir la zone, de retirer un filtre de prix ou de choisir une catégorie plus générale.</span><div><a href="/recherche">Réinitialiser les filtres</a><a href="/">Voir les dernières annonces</a></div></div>:view==="map"?<SearchResultsMap items={data.items} total={data.total} initialBounds={mapBounds}/>:<div className={styles.grid}>{flow.map(({item},index)=><MarketplaceListingCard key={item.id} item={item} imagePriority={index<4}/>)}</div>}
      {view==="list"&&data.total>pageSize&&<nav className={styles.pagination} aria-label="Pagination des résultats"><a className={page<=1?styles.disabled:""} aria-disabled={page<=1} href={hrefForPage(Math.max(1,page-1))}>← Précédent</a><div>{pagination.map((n,index)=>{const prev=pagination[index-1];return <span key={n}>{prev&&n-prev>1&&<i>…</i>}<a className={n===page?styles.activePage:""} aria-current={n===page?"page":undefined} href={hrefForPage(n)}>{n}</a></span>})}</div><a className={page>=totalPages?styles.disabled:""} aria-disabled={page>=totalPages} href={hrefForPage(Math.min(totalPages,page+1))}>Suivant →</a></nav>}
    </section></div>
  </main></div>;
}
