import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { apiRequest } from '../../lib/api';
import { PA } from '../../constants/theme';
import { ListingCard } from '../../components/listing-card';
import type { Listing } from '../../types/api';
import { AppIcon } from '../../components/app-icon';

type Review={id:string;rating:number;comment?:string|null;createdAt:string;reviewerName:string};
type ApiListing={id:string;title:string|null;slug:string|null;priceMinor:number|null;currency:string;city:string|null;categoryName:string;categoryDomain:string;imageUrl?:string|null;publishedAt?:string|null};
type Profile={id:string;kind:string;name:string;avatarUrl?:string|null;memberSince:string;verified:boolean;siretVerified?:boolean;emailVerified?:boolean;store?:{name:string;slug:string}|null;activeListings:number;completedSales:number;trust?:{score?:number;reliableSeller?:boolean;level?:string};reputation?:any};
type Payload={profile:Profile;summary:{count:number;average:number|null;seller?:{count:number;average:number|null};buyer?:{count:number;average:number|null}};reviews:Review[];listings:ApiListing[]};

function mapListing(x:ApiListing):Listing{return{id:x.id,slug:x.slug,title:x.title,priceMinor:x.priceMinor,currency:x.currency,city:x.city,publishedAt:x.publishedAt??null,imageUrl:x.imageUrl??null,category:{name:x.categoryName,slug:'',domain:x.categoryDomain}}}
function stars(v:number){return '★'.repeat(Math.max(1,Math.min(5,Math.round(v))))+'☆'.repeat(Math.max(0,5-Math.round(v)))}

export default function SellerProfileScreen(){
 const{id}=useLocalSearchParams<{id:string}>();const[data,setData]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState('');
 const load=useCallback(async(soft=false)=>{if(!id)return;if(soft)setRefreshing(true);else setLoading(true);setError('');try{setData(await apiRequest<Payload>(`/public/users/${encodeURIComponent(String(id))}/reviews`))}catch{setError('Ce profil vendeur est indisponible.')}finally{setLoading(false);setRefreshing(false)}},[id]);useEffect(()=>{void load()},[load]);
 const listings=useMemo(()=>data?.listings?.map(mapListing)??[],[data]);
 if(loading)return <SafeAreaView style={s.center}><ActivityIndicator color={PA.primary}/></SafeAreaView>;
 if(error||!data)return <SafeAreaView style={s.center}><Text style={s.error}>{error||'Profil indisponible'}</Text><Pressable onPress={()=>router.back()}><Text style={s.link}>Retour</Text></Pressable></SafeAreaView>;
 const p=data.profile;const trustScore=Math.max(0,Math.min(100,Number(p.trust?.score??0)));const badges=Array.isArray(p.reputation?.badges)?p.reputation.badges:[];
 return <SafeAreaView style={s.safe} edges={['top']}><FlatList data={listings} numColumns={2} keyExtractor={x=>x.id} columnWrapperStyle={s.row} contentContainerStyle={s.list} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={PA.primary}/>} ListHeaderComponent={<View><View style={s.top}><Pressable accessibilityRole="button" accessibilityLabel="Retour" style={s.back} onPress={()=>router.back()}><AppIcon name="chevron-left" size={15} color={PA.ink}/></Pressable><Text style={s.topTitle}>Profil vendeur</Text><View style={{width:40}}/></View><View style={s.hero}><View style={s.avatar}>{p.avatarUrl?<Image source={{uri:p.avatarUrl}} style={s.avatarImg} contentFit="cover"/>:<Text style={s.avatarText}>{p.name.slice(0,1).toUpperCase()}</Text>}</View><Text style={s.name}>{p.name}{p.verified?' ✓':''}</Text><Text style={s.kind}>{p.kind==='PROFESSIONNEL'?'Professionnel':'Particulier'} · membre depuis {new Date(p.memberSince).getFullYear()}</Text><View style={s.stats}><View style={s.stat}><Text style={s.statValue}>{trustScore}</Text><Text style={s.statLabel}>Score confiance</Text></View><View style={s.stat}><Text style={s.statValue}>{p.completedSales}</Text><Text style={s.statLabel}>Ventes</Text></View><View style={s.stat}><Text style={s.statValue}>{data.summary.average!=null?data.summary.average.toFixed(1):'—'}</Text><Text style={s.statLabel}>{data.summary.count} avis</Text></View></View>{p.trust?.reliableSeller?<View style={s.reliable}><Text style={s.reliableText}>✓ Vendeur fiable</Text></View>:null}{badges.length?<View style={s.badges}>{badges.slice(0,5).map((b:any,i:number)=><View key={String(b?.code??i)} style={s.badge}><Text style={s.badgeText}>{String(b?.label??b?.name??b?.code??'Badge')}</Text></View>)}</View>:null}{p.store?.slug?<Pressable style={s.storeButton} onPress={()=>router.push(`/store/${p.store!.slug}` as never)}><Text style={s.storeButtonText}>Voir la boutique · {p.store.name}</Text></Pressable>:null}</View><View style={s.section}><View style={s.sectionHead}><Text style={s.sectionTitle}>Avis récents</Text><Text style={s.sectionMeta}>{data.summary.count} au total</Text></View>{data.reviews.length?data.reviews.slice(0,5).map(r=><View key={r.id} style={s.review}><View style={s.reviewTop}><Text style={s.reviewer}>{r.reviewerName}</Text><Text style={s.stars}>{stars(r.rating)}</Text></View>{r.comment?<Text style={s.reviewText}>{r.comment}</Text>:null}<Text style={s.reviewDate}>{new Date(r.createdAt).toLocaleDateString('fr-FR',{dateStyle:'medium'})}</Text></View>):<Text style={s.empty}>Aucun avis pour le moment.</Text>}</View><View style={s.sectionHeadListings}><Text style={s.sectionTitle}>Annonces du vendeur</Text><Text style={s.sectionMeta}>{p.activeListings} active{p.activeListings>1?'s':''}</Text></View></View>} renderItem={({item})=><ListingCard listing={item}/>} ListEmptyComponent={<View style={s.emptyBox}><Text style={s.empty}>Aucune annonce active actuellement.</Text></View>} /></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:PA.bg},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10,backgroundColor:PA.bg,padding:24},error:{fontSize:14,color:PA.ink,textAlign:'center'},link:{fontWeight:'900',color:PA.primary},top:{height:54,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:40,height:40,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center'},backText:{fontSize:29,lineHeight:30,color:PA.ink},topTitle:{fontSize:13,fontWeight:'900',color:PA.ink},list:{paddingHorizontal:14,paddingBottom:36},row:{justifyContent:'space-between'},hero:{alignItems:'center',padding:20,borderRadius:22,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line},avatar:{width:82,height:82,borderRadius:24,overflow:'hidden',backgroundColor:'#efedff',alignItems:'center',justifyContent:'center'},avatarImg:{width:'100%',height:'100%'},avatarText:{fontSize:30,fontWeight:'900',color:PA.primary},name:{fontSize:22,fontWeight:'900',color:PA.ink,marginTop:11},kind:{fontSize:11,color:PA.muted,marginTop:4},stats:{width:'100%',flexDirection:'row',gap:8,marginTop:18},stat:{flex:1,padding:11,borderRadius:14,backgroundColor:'#f7f7fa',alignItems:'center'},statValue:{fontSize:18,fontWeight:'900',color:PA.ink},statLabel:{fontSize:8.5,color:PA.muted,textAlign:'center',marginTop:2},reliable:{marginTop:12,paddingHorizontal:12,paddingVertical:7,borderRadius:999,backgroundColor:'#eaf9f2'},reliableText:{fontSize:10,fontWeight:'900',color:PA.success},badges:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:6,marginTop:10},badge:{paddingHorizontal:9,paddingVertical:5,borderRadius:999,backgroundColor:'#efedff'},badgeText:{fontSize:8.5,fontWeight:'800',color:PA.primary},storeButton:{width:'100%',minHeight:45,borderRadius:13,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center',marginTop:14,paddingHorizontal:12},storeButtonText:{fontSize:11,fontWeight:'900',color:'#fff'},section:{marginTop:14,padding:15,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:4},sectionHeadListings:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:20,marginBottom:10},sectionTitle:{fontSize:16,fontWeight:'900',color:PA.ink},sectionMeta:{fontSize:9.5,fontWeight:'800',color:PA.muted},review:{paddingVertical:11,borderTopWidth:1,borderTopColor:'#f0f0f4'},reviewTop:{flexDirection:'row',justifyContent:'space-between',gap:8},reviewer:{fontSize:11,fontWeight:'900',color:PA.ink},stars:{fontSize:10,color:'#f59e0b'},reviewText:{fontSize:11,lineHeight:16,color:PA.muted,marginTop:4},reviewDate:{fontSize:8.5,color:'#aaaab4',marginTop:5},empty:{fontSize:11,color:PA.muted,textAlign:'center'},emptyBox:{padding:25}})