"use client";
import {useEffect,useState} from "react";
import {ProfessionalWorkspace} from "../../../components/professional-workspace";
import {formatListingPrice} from "../../../lib/listing-price";
import {fetchWithRetry} from "../../../lib/fetch-resilient";
import styles from "../pro-tools.module.css";

type Status="DRAFT"|"PENDING"|"PUBLISHED"|"SUSPENDED"|"SOLD"|"EXPIRED";
type L={id:string;title:string|null;slug:string|null;status:Status;priceMinor:number|null;currency:string;city:string|null;updatedAt:string;imageUrl?:string|null;quality?:{score:number;level:"EXCELLENT"|"BON"|"A_AMELIORER";photoCount:number;issues:Array<{code:string;label:string;step:number}>};category:{name:string;domain:string};property?:{transactionType?:string|null}|null;store?:{id:string;name:string}|null;moderation?:{decisionAction:string|null;statement:string|null}|null;lifecycle?:{expiresAt:string;freeRenewalAvailable:boolean;renewalCostMinor:number;renewalCurrency:string}|null;promotions?:Array<{id:string;name:string;endsAt:string|null;startsAt:string|null}>};
const labels:Record<Status|"ALL",string>={ALL:"Toutes",DRAFT:"Brouillons",PENDING:"En modération",PUBLISHED:"Actives",SUSPENDED:"En pause",SOLD:"Vendues",EXPIRED:"Expirées"};
function api(){return(process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"")}
export default function ProListings(){
 const[list,setList]=useState<L[]>([]),[stores,setStores]=useState<Array<{id:string;name:string;status:string}>>([]),[q,setQ]=useState(""),[status,setStatus]=useState<Status|"ALL">("ALL"),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true),[counts,setCounts]=useState<Record<string,number>>({ALL:0,DRAFT:0,PENDING:0,PUBLISHED:0,SUSPENDED:0,SOLD:0,EXPIRED:0}),[selected,setSelected]=useState<string[]>([]),[bulkAction,setBulkAction]=useState("PAUSE"),[bulkPrice,setBulkPrice]=useState("");
 async function load(){setLoading(true);const sp=new URLSearchParams();if(status!=="ALL")sp.set("status",status);if(q.trim())sp.set("q",q.trim());let r:Response;try{r=await fetchWithRetry(`${api()}/account/listings?${sp}`,{credentials:"include",cache:"no-store"},{timeoutMs:7000,retries:1})}catch{setMsg("Impossible de charger les annonces.");setLoading(false);return}if(r.status===401){location.href="/connexion?next=%2Fespace-pro%2Fannonces";return}if(!r.ok){setMsg("Impossible de charger les annonces.");setLoading(false);return}const p=await r.json();setList(p.listings??[]);setCounts(p.counts??{});setLoading(false)}
 useEffect(()=>{void load()},[status]);
 useEffect(()=>{fetchWithRetry(`${api()}/pro/me`,{credentials:"include",cache:"no-store"},{timeoutMs:6500,retries:1}).then(r=>r.ok?r.json():null).then(p=>setStores((p?.professional?.stores??[]).map((x:any)=>({id:x.id,name:x.name,status:x.status})))).catch(()=>{})},[]);
 async function assign(x:L,id:string){let r;if(!id&&x.store?.id)r=await fetch(`${api()}/pro/stores/${x.store.id}/listings/${x.id}`,{method:"DELETE",credentials:"include"});else if(id)r=await fetch(`${api()}/pro/stores/${id}/listings/${x.id}`,{method:"POST",credentials:"include"});else return;if(!r.ok){setMsg("Impossible de modifier la boutique.");return}await load()}
 async function changeStatus(id:string,next:Status){setMsg("");const r=await fetch(`${api()}/account/listings/${encodeURIComponent(id)}/status`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({status:next})});if(!r.ok){setMsg("Cette action n’est pas disponible pour cette annonce.");return}await load()}
 async function deleteListing(item:L){const label=item.title?.trim()||"cette annonce";if(!window.confirm(`Supprimer définitivement « ${label} » ? Cette action est irréversible.`))return;setMsg("");const r=await fetch(`${api()}/account/listings/${encodeURIComponent(item.id)}`,{method:"DELETE",credentials:"include"});const p=await r.json().catch(()=>({})) as {error?:string;message?:string};if(!r.ok){setMsg(p.error==="listing_has_orders"?"Cette annonce est liée à une commande et doit être conservée dans l’historique de la transaction.":p.message||"Impossible de supprimer cette annonce pour le moment.");return}await load();setMsg("Annonce supprimée définitivement.")}
 async function renewListing(item:L){const free=item.lifecycle?.freeRenewalAvailable!==false;if(free){if(!window.confirm("Prolonger gratuitement cette annonce de 30 jours ?"))return;const r=await fetch(`${api()}/account/listings/${encodeURIComponent(item.id)}/renew`,{method:"POST",credentials:"include"});if(!r.ok){setMsg("Impossible de prolonger cette annonce.");return}setMsg("Annonce prolongée gratuitement de 30 jours.");await load();return}if(!window.confirm("Prolonger cette annonce de 30 jours pour 0,99 € ?"))return;const r=await fetch(`${api()}/billing/stripe/listing-renewal/checkout`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({listingId:item.id})});const p=await r.json().catch(()=>({}));if(!r.ok||!p.url){setMsg("Impossible d’ouvrir le paiement sécurisé.");return}window.location.href=p.url}
 async function runBulk(){if(!selected.length)return;const body:any={listingIds:selected,action:bulkAction};if(bulkAction==="SET_PRICE"){const n=Number(bulkPrice.replace(",","."));if(!Number.isFinite(n)||n<0){setMsg("Indiquez un prix valide.");return}body.priceMinor=Math.round(n*100)}if(!window.confirm(`Appliquer cette action à ${selected.length} annonce(s) ?`))return;const r=await fetch(`${api()}/pro/listings/bulk`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const p=await r.json().catch(()=>({}));if(!r.ok){setMsg(p.error==="invalid_bulk_transition"?"Certaines annonces sélectionnées ne sont pas dans un statut compatible.":"Action groupée impossible.");return}setMsg(`${p.count??selected.length} annonce(s) mise(s) à jour.`);setSelected([]);await load()}
 return <ProfessionalWorkspace><main className={styles.shell}>
  <header className={styles.hero}><div><span className={styles.kicker}>Catalogue professionnel</span><h1>Mes annonces</h1><p>Gérez vos annonces, vos boutiques et leur visibilité depuis un catalogue unique.</p></div><div className={styles.actions}><a className={`${styles.button} ${styles.secondary}`} href="/espace-pro/imports">Importer</a><a className={styles.button} href="/deposer-une-annonce">Nouvelle annonce</a></div></header>
  {msg&&<div className={styles.notice}>{msg}</div>}
  <section className={styles.bulkBar}><label className={styles.bulkSelectAll}><input type="checkbox" checked={list.length>0&&selected.length===list.length} onChange={e=>setSelected(e.target.checked?list.map(x=>x.id):[])}/> Tout sélectionner</label><span className={styles.bulkCount}>{selected.length} sélectionnée(s)</span><select className={styles.bulkControl} value={bulkAction} onChange={e=>setBulkAction(e.target.value)}><option value="PAUSE">Mettre en pause</option><option value="RESUME">Republier</option><option value="SOLD">Marquer vendues</option><option value="SET_PRICE">Modifier le prix</option><option value="EXTEND_30">Prolonger +30 jours</option></select>{bulkAction==="SET_PRICE"&&<input className={styles.bulkPrice} value={bulkPrice} onChange={e=>setBulkPrice(e.target.value)} inputMode="decimal" placeholder="Prix en €"/>}<button type="button" className={styles.button} disabled={!selected.length} onClick={()=>void runBulk()}>Appliquer</button></section>
  <section className={styles.catalogToolbar}><div className={styles.catalogTabs}>{(Object.keys(labels) as Array<Status|"ALL">).map(s=><button type="button" key={s} className={status===s?styles.catalogTabActive:""} onClick={()=>setStatus(s)}>{labels[s]}<span>{counts[s]??0}</span></button>)}</div><form className={styles.catalogSearch} onSubmit={e=>{e.preventDefault();void load()}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher une annonce"/><button>Rechercher</button></form></section>
  {loading?<div className={styles.catalogSkeleton}>{[0,1,2].map(i=><div key={i}/>)}</div>:!list.length?<section className={styles.catalogEmpty}><strong>Aucune annonce dans cette section.</strong><p>Changez de filtre ou créez une nouvelle annonce.</p><a className={styles.button} href="/deposer-une-annonce">Créer une annonce</a></section>:<section className={styles.proListingGrid}>{list.map(x=><article className={styles.proListingCard} key={x.id}>
   <label className={styles.proSelectRow}><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(prev=>e.target.checked?[...prev,x.id]:prev.filter(id=>id!==x.id))}/> Sélectionner</label><div className={styles.proListingMedia}>{x.imageUrl?<img src={x.imageUrl} alt={x.title??"Annonce"}/>:<span>{x.category.name.slice(0,1).toUpperCase()}</span>}</div>
   <div className={styles.proListingBody}><div className={styles.proListingTop}><div><small>{x.category.name}</small><h2>{x.title??"Annonce sans titre"}</h2></div><span className={`${styles.proListingBadge} ${styles[`proStatus${x.status}`]??""}`}>{labels[x.status]}</span></div><strong className={styles.proListingPrice}>{formatListingPrice(x.priceMinor,x.currency,{domain:x.category.domain,transactionType:x.property?.transactionType??null},"Prix non défini")}</strong><div className={styles.proListingMeta}><span>{x.city??"France"}</span><span>Mis à jour le {new Date(x.updatedAt).toLocaleDateString("fr-FR")}</span>{x.lifecycle?.expiresAt&&x.status==="PUBLISHED"&&<span>Expire le {new Date(x.lifecycle.expiresAt).toLocaleDateString("fr-FR")}</span>}</div>
   {x.quality&&<div className={styles.proQuality}><div className={styles.proQualityHead}><span>Qualité de l’annonce</span><strong>{x.quality.score}/100</strong></div><div className={styles.proQualityTrack}><i style={{width:`${x.quality.score}%`}}/></div><div className={styles.proQualityFoot}><span>{x.quality.score>=85?"Excellente":x.quality.score>=65?"Bonne":"À améliorer"} · {x.quality.photoCount} photo{x.quality.photoCount>1?"s":""}</span>{x.quality.issues[0]?<a href={`/deposer-une-annonce?listingId=${encodeURIComponent(x.id)}&resumeStep=${x.quality.issues[0].step}&mode=edit`}>{x.quality.issues[0].label} →</a>:<b>Annonce complète ✓</b>}</div></div>}
   {x.promotions?.length?<div className={styles.proPromotionRow}>{x.promotions.map(p=><span key={p.id}>{p.name}</span>)}</div>:null}
   {x.status==="PENDING"&&<div className={styles.proListingInfo}>Vérification en cours par la modération.</div>}
   {x.status==="SUSPENDED"&&x.moderation?.statement&&<div className={`${styles.proListingInfo} ${styles.proListingWarn}`}>{x.moderation.statement}</div>}
   {stores.length>0&&<label className={styles.proStoreSelect}>Boutique<select value={x.store?.id??""} onChange={e=>void assign(x,e.target.value)}><option value="">Hors boutique</option>{stores.map(s=><option key={s.id} value={s.id} disabled={s.status==="SUSPENDED"}>{s.name}{s.status==="SUSPENDED"?" · suspendue":""}</option>)}</select></label>}
   </div>
   <div className={styles.proListingActions}>{x.status==="PUBLISHED"&&x.slug?<a className={styles.proActionPrimary} href={`/annonce/${x.slug}`}>Voir l’annonce</a>:x.status==="DRAFT"?<a className={styles.proActionPrimary} href={`/deposer-une-annonce?listingId=${x.id}`}>Continuer</a>:x.status==="EXPIRED"?<button type="button" className={styles.proActionPrimary} onClick={()=>void renewListing(x)}>{x.lifecycle?.freeRenewalAvailable!==false?"Prolonger +30 j":"Prolonger · 0,99 €"}</button>:x.status==="SUSPENDED"?<button type="button" className={styles.proActionPrimary} onClick={()=>void changeStatus(x.id,"PENDING")}>Republier</button>:null}<details className={styles.proMore}><summary>Plus</summary><div>{["PUBLISHED","SUSPENDED","EXPIRED"].includes(x.status)&&<a href={`/deposer-une-annonce?listingId=${x.id}&resumeStep=0&mode=edit`}>Modifier</a>}{x.status==="PUBLISHED"&&<a href={`/espace-pro/visibilite?listingId=${x.id}`}>Booster</a>}{x.status==="PUBLISHED"&&<button type="button" onClick={()=>void changeStatus(x.id,"SUSPENDED")}>Mettre en pause</button>}{x.status==="PUBLISHED"&&<button type="button" onClick={()=>void changeStatus(x.id,"SOLD")}>Marquer comme vendue</button>}<button type="button" className={styles.proActionDanger} onClick={()=>void deleteListing(x)}>Supprimer définitivement</button></div></details></div>
  </article>)}</section>}
 </main></ProfessionalWorkspace>}
