import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {AppIcon} from "../../../components/app-icon";
import {VacationMap} from "../../../components/vacation-map";
import styles from "../page.module.css";

type Meta={city:string;slug:string;total:number;indexable:boolean;minPrice:number|null;maxPrice:number|null;updatedAt:string;types:Array<{slug:string;name:string;count:number}>};
type VacationMeta={capacity?:number;bedrooms?:number;minimumNights?:number;amenities?:string[];petsAllowed?:boolean};
type Item={id:string;slug:string|null;title:string|null;priceMinor:number|null;currency:string;city:string|null;postalCode:string|null;imageUrl:string|null;latitude:number|null;longitude:number|null;category:{name:string;slug:string};sellerReputation?:{verified?:boolean};vacation?:VacationMeta;estimatedStayMinor?:number|null};
type Payload={page:number;limit:number;total:number;nights:number|null;items:Item[]};
type HbxHotel={code:number;name:string;destinationCode:string;destinationName:string|null;city:string|null;countryCode:string|null;categoryCode:string|null;categoryName:string|null;stars:number|null;address:string|null;postalCode:string|null;description:string|null;imageUrl:string|null;latitude:number|null;longitude:number|null;liveRate?:{displayRate:number;netRate:number;sellingRate:number|null;maxRate:number|null;currency:string;priceSource:"sellingRate"|"net";hotelMandatory:boolean|null;roomName:string|null;boardName:string|null;rateClass:string|null;rateType:string|null;requiresCheckRate:boolean;paymentType:string|null;selectionToken:string|null;cancellationFrom:string|null;cancellationAmount:number|null}};
type HbxPayload={provider:string;environment:string;destination:{code:string;name:string;countryCode:string}|null;total:number;items:HbxHotel[];availability:{ready:boolean;reason:string;detail?:string}};
type SP={type?:string;checkIn?:string;checkOut?:string;guests?:string;amenity?:string;pets?:string;minPrice?:string;maxPrice?:string;sort?:string;page?:string;view?:string;north?:string;south?:string;east?:string;west?:string};
const api=()=> (process.env.API_INTERNAL_URL??process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000").replace(/\/$/,"");
const amenityLabel:Record<string,string>={wifi:"Wi-Fi",parking:"Parking",pool:"Piscine","air-conditioning":"Climatisation",kitchen:"Cuisine",washer:"Lave-linge","terrace-balcony":"Terrasse / balcon","sea-view":"Vue mer",spa:"Spa / jacuzzi",breakfast:"Petit-déjeuner"};
function hbxHotelHref(hotel:HbxHotel,city:string,p:SP){const q=new URLSearchParams({city});if(p.checkIn)q.set("checkIn",p.checkIn);if(p.checkOut)q.set("checkOut",p.checkOut);q.set("guests",String(Math.max(1,Number(p.guests)||1)));if(hotel.liveRate?.selectionToken)q.set("offer",hotel.liveRate.selectionToken);return `/vacances/hotel/${hotel.code}?${q.toString()}`}

function money(v:number,c="EUR"){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:c,maximumFractionDigits:v%100===0?0:2}).format(v/100)}
function qstring(city:string,p:SP,page?:number){const q=new URLSearchParams({city});for(const[k,v]of Object.entries(p))if(v&&k!=="page")q.set(k,v);if(page&&page>1)q.set("page",String(page));return q.toString()}
function pageQuery(p:SP,page:number){const q=new URLSearchParams();for(const[k,v]of Object.entries(p))if(v&&k!=="page")q.set(k,v);if(page>1)q.set("page",String(page));return q.toString()}
function viewHref(slug:string,p:SP,mode:"list"|"map"){const q=new URLSearchParams();for(const[key,value]of Object.entries(p))if(value&&key!=="page"&&key!=="view")q.set(key,value);if(mode==="map")q.set("view","map");const s=q.toString();return `/vacances/${slug}${s?`?${s}`:""}`}
function mapBounds(p:SP){const north=Number(p.north),south=Number(p.south),east=Number(p.east),west=Number(p.west);return [north,south,east,west].every(Number.isFinite)&&south<north&&west<east?{north,south,east,west}:null}
async function getMeta(slug:string){try{const r=await fetch(`${api()}/seo/vacation/${encodeURIComponent(slug)}`,{next:{revalidate:300}});if(!r.ok)return null;return r.json() as Promise<Meta>}catch{return null}}
async function search(city:string,p:SP){try{const qs=new URLSearchParams(qstring(city,p));if(p.view==="map")qs.set("limit","48");const r=await fetch(`${api()}/vacances/search?${qs.toString()}`,{cache:"no-store"});if(!r.ok)return{page:1,limit:p.view==="map"?48:24,total:0,nights:null,items:[]} as Payload;return r.json() as Promise<Payload>}catch{return{page:1,limit:p.view==="map"?48:24,total:0,nights:null,items:[]} as Payload}}
async function hbxSearch(city:string,p:SP):Promise<HbxPayload|null>{try{const q=new URLSearchParams({city,limit:"12",guests:String(Math.max(1,Number(p.guests)||1))});const validDates=Boolean(p.checkIn&&p.checkOut&&p.checkOut>p.checkIn);if(validDates){q.set("checkIn",p.checkIn!);q.set("checkOut",p.checkOut!)}const r=await fetch(`${api()}/vacances/hbx/search?${q.toString()}`,{cache:"no-store"});if(r.status===429)return{provider:"HBX",environment:"test",destination:null,total:0,items:[],availability:{ready:false,reason:"hbx_quota_exceeded"}};if(!r.ok)return null;return r.json() as Promise<HbxPayload>}catch{return null}}
function cityFromSlug(slug:string){return slug.split("-").filter(Boolean).map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(" ")}

export async function generateMetadata({params}:{params:Promise<{city:string}>}):Promise<Metadata>{const {city:slug}=await params;const meta=await getMeta(slug);if(!meta)return{title:"Destination Vacances introuvable | Petit Annonces",robots:{index:false,follow:false}};const price=meta.minPrice!=null?` dès ${money(meta.minPrice)}/nuit`:"";return{title:`Location de vacances à ${meta.city} | Petit Annonces Vacances`,description:`Trouvez hôtels, appartements, maisons, villas, gîtes et campings à ${meta.city}${price}. Vérifiez les disponibilités selon vos dates sur Petit Annonces Vacances.`,alternates:{canonical:`/vacances/${meta.slug}`},robots:{index:meta.indexable,follow:true},openGraph:{title:`Vacances à ${meta.city} | Petit Annonces`,description:`${meta.total} hébergement${meta.total>1?"s":""} de vacances actuellement proposé${meta.total>1?"s":""} à ${meta.city}.`,url:`https://petitannonces.fr/vacances/${meta.slug}`,type:"website"}}}

export default async function VacationCityPage({params,searchParams}:{params:Promise<{city:string}>;searchParams:Promise<SP>}){
 const [{city:slug},sp]=await Promise.all([params,searchParams]);const nativeMeta=await getMeta(slug);const requestedCity=nativeMeta?.city??cityFromSlug(slug);const hbxData=await hbxSearch(requestedCity,sp);const meta:Meta=nativeMeta??(hbxData?.destination?{city:hbxData.destination.name,slug,total:0,indexable:false,minPrice:null,maxPrice:null,updatedAt:new Date().toISOString(),types:[]}:null as any);if(!meta)notFound();const data=await search(meta.city,sp);const guests=Math.max(1,Number(sp.guests)||1),dateError=Boolean(sp.checkIn&&sp.checkOut&&sp.checkOut<=sp.checkIn),datesReady=Boolean(sp.checkIn&&sp.checkOut&&!dateError),page=Math.max(1,data.page||1),pages=Math.max(1,Math.ceil(data.total/Math.max(1,data.limit||24)));
 const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Petit Annonces",item:"https://petitannonces.fr/"},{"@type":"ListItem",position:2,name:"Vacances",item:"https://petitannonces.fr/vacances"},{"@type":"ListItem",position:3,name:meta.city,item:`https://petitannonces.fr/vacances/${meta.slug}`}]};
 return <div className={styles.page}><main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb).replace(/</g,"\\u003c")}}/>
  <section className={styles.hero}><div className={styles.heroInner}><div className={styles.brandLine}><span><AppIcon name="calendar"/></span><div><small>PETIT ANNONCES</small><strong>Vacances</strong></div></div><div className={styles.heroCopy}><span>Destination · {meta.city}</span><h1>Location de vacances à {meta.city}</h1><p>{meta.total} hébergement{meta.total>1?"s":""} actuellement disponible{meta.total>1?"s":""}. Comparez les tarifs par nuit et vérifiez vos dates avant d’envoyer votre demande de réservation.</p></div><form className={styles.searchBox} action={`/vacances/${meta.slug}`}><label className={styles.destination}><span>Destination</span><div><AppIcon name="location"/><input value={meta.city} readOnly/></div></label><label><span>Arrivée</span><input name="checkIn" type="date" defaultValue={sp.checkIn??""}/></label><label><span>Départ</span><input name="checkOut" type="date" defaultValue={sp.checkOut??""}/></label><label><span>Voyageurs</span><select name="guests" defaultValue={String(guests)}>{Array.from({length:12},(_,i)=>i+1).map(n=><option key={n} value={n}>{n} voyageur{n>1?"s":""}</option>)}</select></label>{sp.type&&<input type="hidden" name="type" value={sp.type}/>}<button><AppIcon name="search"/>Vérifier les disponibilités</button></form><div className={styles.heroTrust}><span><AppIcon name="location"/>{meta.city}</span>{meta.minPrice!=null&&<span><AppIcon name="calendar"/>À partir de {money(meta.minPrice)} / nuit</span>}<span><AppIcon name="shield"/>Annonces modérées</span></div></div></section>{dateError&&<section className={styles.shell}><div className={styles.hbxNotice}><AppIcon name="calendar"/><div><strong>Dates de séjour incorrectes</strong><span>La date de départ doit être postérieure à la date d’arrivée. Modifiez vos dates puis relancez la recherche.</span></div></div></section>}
  <section className={styles.shell}><div className={styles.typeHead}><div><span>Hébergements à {meta.city}</span><h2>Choisissez votre type de séjour</h2></div><a href="/vacances">Changer de destination</a></div><div className={styles.types}>{meta.types.map(t=><a key={t.slug} className={sp.type===t.slug?styles.typeActive:""} href={`/vacances/${meta.slug}?type=${encodeURIComponent(t.slug)}`}><i>☀️</i><strong>{t.name}</strong><span>{t.count} annonce{t.count>1?"s":""} →</span></a>)}</div>
  {hbxData?.availability.reason==="hbx_quota_exceeded"&&<section className={styles.hbxSection}><div className={styles.hbxNotice}><AppIcon name="info"/><div><strong>Disponibilités hôtels temporairement indisponibles</strong><span>Réessayez un peu plus tard pour vérifier les tarifs et disponibilités HBX pour cette destination.</span></div></div></section>}
  {hbxData?.items.length?<section className={styles.hbxSection}><div className={styles.hbxHead}><div><span>Hôtels partenaires · HBX</span><h2>Hôtels à {hbxData.destination?.name??meta.city}</h2><p>{datesReady&&hbxData.availability.ready?"Disponibilités et tarifs vérifiés pour votre séjour.":"Sélection d’hôtels partenaires. Ajoutez vos dates pour vérifier les disponibilités en temps réel."}</p></div><b>Environnement {hbxData.environment.toUpperCase()}</b></div><div className={styles.hbxGrid}>{hbxData.items.map(hotel=><article className={styles.hbxCard} key={hotel.code}><div className={styles.hbxPhoto}>{hotel.imageUrl?<img src={hotel.imageUrl} alt={hotel.name} loading="lazy"/>:<span>🏨</span>}<em>HBX</em></div><div className={styles.hbxBody}><div className={styles.hbxMeta}><span>{hotel.categoryName??"Hôtel"}</span>{hotel.stars&&<b>{"★".repeat(hotel.stars)}</b>}</div><h3>{hotel.name}</h3><p><AppIcon name="location"/>{hotel.city??hbxData.destination?.name}{hotel.postalCode?` · ${hotel.postalCode}`:""}</p>{hotel.description&&<small>{hotel.description}</small>}<div className={styles.hbxFoot}><span><AppIcon name="shield"/>Partenaire hôtelier</span>{hotel.liveRate?<><strong>{new Intl.NumberFormat("fr-FR",{style:"currency",currency:hotel.liveRate.currency}).format(hotel.liveRate.displayRate)} · séjour</strong><small>{hotel.liveRate.priceSource==="net"?"Tarif fournisseur TEST":"Tarif public HBX"}{hotel.liveRate.requiresCheckRate?" · vérification requise":""}</small>{hotel.liveRate.boardName&&<small>{hotel.liveRate.boardName}{hotel.liveRate.roomName?` · ${hotel.liveRate.roomName}`:""}</small>}</>:<strong>{datesReady?"Indisponible pour ces dates":"Ajoutez vos dates"}</strong>}</div><a className={styles.hbxDetailLink} href={hbxHotelHref(hotel,hbxData.destination?.name??meta.city,sp)}>Voir l’hôtel <AppIcon name="arrow-right"/></a></div></article>)}</div><div className={styles.hbxNotice}><AppIcon name="shield"/><div><strong>{hbxData.availability.ready?"Disponibilités HBX en temps réel":"Catalogue HBX connecté"}</strong><span>{hbxData.availability.ready?"Les hôtels ci-dessus sont disponibles pour les dates et voyageurs sélectionnés.":"Choisissez une arrivée, un départ et le nombre de voyageurs pour lancer le contrôle de disponibilité."}</span></div></div></section>:null}

  <div className={styles.contentGrid}><aside className={styles.filters}><form action={`/vacances/${meta.slug}`}><input type="hidden" name="checkIn" value={sp.checkIn??""}/><input type="hidden" name="checkOut" value={sp.checkOut??""}/><input type="hidden" name="guests" value={String(guests)}/>{sp.view==="map"&&<input type="hidden" name="view" value="map"/>}<div className={styles.filterHead}><div><b>Filtres</b><span>Affinez votre séjour à {meta.city}</span></div><a href={`/vacances/${meta.slug}`}>Réinitialiser</a></div><label><span>Type d’hébergement</span><select name="type" defaultValue={sp.type??""}><option value="">Tous</option>{meta.types.map(t=><option value={t.slug} key={t.slug}>{t.name}</option>)}</select></label><div className={styles.priceGrid}><label><span>Prix min. / nuit</span><input type="number" min="0" name="minPrice" defaultValue={sp.minPrice??""} placeholder="0 €"/></label><label><span>Prix max. / nuit</span><input type="number" min="0" name="maxPrice" defaultValue={sp.maxPrice??""} placeholder="Max"/></label></div><label><span>Équipement</span><select name="amenity" defaultValue={sp.amenity??""}><option value="">Tous les équipements</option>{Object.entries(amenityLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><span>Animaux</span><select name="pets" defaultValue={sp.pets??""}><option value="">Indifférent</option><option value="true">Animaux acceptés</option><option value="false">Sans animaux</option></select></label><label><span>Trier par</span><select name="sort" defaultValue={sp.sort??"recent"}><option value="recent">Plus récents</option><option value="price_asc">Prix croissant</option><option value="price_desc">Prix décroissant</option></select></label><button>Afficher les résultats</button></form></aside>
  <section className={styles.results}><div className={styles.resultsHead}><div><span>PETIT ANNONCES VACANCES</span><h2>Séjours à {meta.city}</h2><p>{data.total} hébergement{data.total>1?"s":""}{datesReady&&data.nights?` · ${data.nights} nuit${data.nights>1?"s":""}`:""}</p></div>{datesReady?<b className={styles.availablePill}><AppIcon name="circle-check"/>Disponibles pour vos dates</b>:<b className={styles.datePill}><AppIcon name="calendar"/>Ajoutez vos dates</b>}</div>
  <nav className={styles.viewSwitch} aria-label="Affichage des résultats"><a className={sp.view==="map"?"":styles.viewActive} href={viewHref(meta.slug,sp,"list")}><AppIcon name="list"/>Liste</a><a className={sp.view==="map"?styles.viewActive:""} href={viewHref(meta.slug,sp,"map")}><AppIcon name="location"/>Carte</a></nav>
  {!data.items.length?<div className={styles.empty}><span>☀️</span><h3>Aucun hébergement pour ces critères</h3><p>Essayez d’autres dates, retirez un filtre ou consultez toutes les offres Vacances.</p><a href={`/vacances/${meta.slug}`}>Voir toutes les offres à {meta.city}</a></div>:sp.view==="map"?<VacationMap items={data.items} total={data.total} initialBounds={mapBounds(sp)}/>:<div className={styles.cards}>{data.items.map(item=><article className={styles.card} key={item.id}><a className={styles.photo} href={item.slug?`/annonce/${item.slug}`:`/vacances/${meta.slug}`}>{item.imageUrl?<img src={item.imageUrl} alt={item.title??`${item.category.name} à ${meta.city}`}/>:<span>☀️</span>}{datesReady&&<b><AppIcon name="circle-check"/>Disponible</b>}</a><div className={styles.cardBody}><div className={styles.cardMeta}><span>{item.category.name}</span>{item.sellerReputation?.verified&&<em>✓ Vérifié</em>}</div><a href={item.slug?`/annonce/${item.slug}`:`/vacances/${meta.slug}`}><h3>{item.title??`Hébergement de vacances à ${meta.city}`}</h3></a><p><AppIcon name="location"/>{item.city??meta.city}</p><div className={styles.facts}>{item.vacation?.capacity&&<span>👤 {item.vacation.capacity} voyageur{Number(item.vacation.capacity)>1?"s":""}</span>}{item.vacation?.bedrooms&&<span>🛏️ {item.vacation.bedrooms} chambre{Number(item.vacation.bedrooms)>1?"s":""}</span>}{item.vacation?.minimumNights&&<span>🌙 min. {item.vacation.minimumNights} nuit{Number(item.vacation.minimumNights)>1?"s":""}</span>}</div><div className={styles.cardFoot}><div>{item.priceMinor!=null?<><strong>{money(item.priceMinor,item.currency)}</strong><span>/ nuit</span>{datesReady&&item.estimatedStayMinor!=null&&<small>{data.nights} nuit{data.nights!==1?"s":""} · {money(item.estimatedStayMinor,item.currency)} estimés</small>}</>:<strong>Prix sur demande</strong>}</div><a href={item.slug?`/annonce/${item.slug}`:`/vacances/${meta.slug}`}>Voir →</a></div></div></article>)}</div>}
  {sp.view!=="map"&&pages>1&&<nav className={styles.pagination}>{page>1?<a href={`/vacances/${meta.slug}?${pageQuery(sp,page-1)}`}>← Précédent</a>:<span/>}<b>Page {page} / {pages}</b>{page<pages?<a href={`/vacances/${meta.slug}?${pageQuery(sp,page+1)}`}>Suivant →</a>:<span/>}</nav>}
  </section></div>
  <section className={styles.hostCta}><div><span>Vous louez à {meta.city} ?</span><h2>Publiez votre hébergement sur Petit Annonces Vacances</h2><p>Ajoutez votre tarif par nuit, vos équipements, vos disponibilités et vos conditions de réservation.</p></div><a href="/deposer-une-annonce"><AppIcon name="plus"/>Déposer une annonce Vacances</a></section>
  <section className={styles.info}><div><AppIcon name="calendar"/><h3>Disponibilités à jour</h3><p>Les hôtes peuvent fermer leur calendrier et les réservations acceptées bloquent automatiquement les dates.</p></div><div><AppIcon name="credit-card"/><h3>Acompte protégé</h3><p>Lorsqu’un acompte est demandé, son montant et la politique d’annulation sont affichés avant la réservation.</p></div><div><AppIcon name="shield"/><h3>Réservez avec vigilance</h3><p>Utilisez la messagerie Petit Annonces et vérifiez les conditions du séjour avant tout engagement.</p></div></section>
  </section></main></div>
}
