import {LegalPage} from "../../components/legal-page";
export const metadata={title:"Mentions légales | Petit Annonces",alternates:{canonical:"/mentions-legales"}};
export default function Page(){const sections=[
{id:"service",title:"Édition du service",body:"Petit Annonces est une plateforme de petites annonces destinée au marché français. L'identité juridique complète de l'exploitant, son adresse, ses coordonnées de contact et, lorsque cela s'applique, ses informations d'immatriculation doivent correspondre aux informations administratives configurées par l'exploitant du service.",note:"Aucune information juridique d'entreprise non vérifiée n'est affichée automatiquement sur cette page."},
{id:"hebergement",title:"Hébergement et infrastructure",body:"Le service repose sur une infrastructure d'hébergement et de stockage configurée pour Petit Annonces. Les informations précises de l'hébergeur légalement requises doivent être maintenues à jour par l'exploitant lorsque l'infrastructure ou le fournisseur change."},
{id:"contact",title:"Contact et service client",body:"Pour toute question concernant le fonctionnement du site, un compte, une annonce, une commande ou l'exercice d'un droit, utilisez le Centre d'aide Petit Annonces. Les demandes sont associées à une référence afin d'en assurer le suivi.",bullets:["Support général : Centre d'aide.","Signalement d'un contenu potentiellement illicite : formulaire DSA dédié.","Demandes relatives aux données personnelles : via le service client avec la catégorie appropriée." ]},
{id:"propriete",title:"Propriété intellectuelle",body:"La marque, les éléments graphiques, textes, interfaces, bases de données, logiciels et contenus éditoriaux propres à Petit Annonces sont protégés par les droits applicables. Les utilisateurs conservent les droits qu'ils détiennent sur leurs contenus, tout en accordant les autorisations nécessaires à leur affichage et au fonctionnement du service."},
{id:"responsabilite",title:"Responsabilité éditoriale et contenus utilisateurs",body:"Les annonces, messages et contenus publiés par les utilisateurs restent sous leur responsabilité. Petit Annonces met en place des outils de modération, signalement et retrait afin de traiter les contenus qui enfreignent les règles ou la réglementation applicable."},
{id:"liens",title:"Liens et services externes",body:"Certaines fonctionnalités peuvent rediriger vers un prestataire ou intégrer un service tiers, notamment pour le paiement, la livraison ou une vérification. Les conditions et politiques propres à ces services peuvent alors s'appliquer en complément de celles de Petit Annonces."},
{id:"droit",title:"Droit applicable et documents contractuels",body:"Les relations avec Petit Annonces sont encadrées par les documents publiés sur le site, notamment les Conditions générales, la Politique de confidentialité, la Politique de cookies et les règles de conformité. Les règles impératives applicables au consommateur demeurent réservées."}
];return <LegalPage eyebrow="Informations légales" title="Mentions légales" intro="Les informations relatives à l'édition du service, aux responsabilités, aux droits sur les contenus et aux moyens de contacter Petit Annonces." updated="7 septembre 2026" sections={sections}/>;}