import {LegalPage} from "../../components/legal-page";
export const metadata={title:"Mentions légales | Petit Annonces",alternates:{canonical:"/mentions-legales"}};
export default function Page(){const sections=[
{id:"editeur",title:"Éditeur du service",body:"Le site et l'application PetitAnnonces.fr sont édités par Hakan ERSOY, entrepreneur individuel (Hakan ERSOY EI), 16 rue de la Libération, 42150 La Ricamarie, France.",bullets:["SIREN : 813 061 256.","SIRET : 813 061 256 00042.","TVA intracommunautaire : FR52 813 061 256.","Téléphone : +33 7 66 17 75 75.","E-mail de l’éditeur : info@getsy.fr.","Support Petit Annonces : info@petitannonces.fr."]},
{id:"publication",title:"Direction de la publication",body:"Directeur de la publication : Hakan ERSOY, en qualité d’entrepreneur individuel exploitant Petit Annonces."},
{id:"hebergement",title:"Hébergement",body:"Le service principal PetitAnnonces.fr est hébergé sur une infrastructure IKOULA en France.",bullets:["IKOULA Net, SAS au capital de 181 260 €.","SIREN : 417 680 618 — RCS Paris.","Siège : 2 Cité Paradis, 75010 Paris, France.","Téléphone : +33 1 84 01 02 50.","Les médias et sauvegardes peuvent utiliser des services techniques distincts décrits dans la politique de confidentialité lorsque cela est nécessaire au fonctionnement du service."]},
{id:"contact",title:"Contact",body:"Pour une question sur un compte, une annonce, une commande ou l’exercice d’un droit, utilisez le Centre d’aide ou écrivez au support. Les contenus potentiellement illicites disposent d’un formulaire DSA séparé.",bullets:["Centre d’aide : /assistance.","Contenu potentiellement illicite : /signaler-contenu-illicite.","Données personnelles : info@getsy.fr.","Sécurité produit : Centre d’aide, catégorie sécurité/conformité."]},
{id:"propriete",title:"Propriété intellectuelle",body:"La marque, les interfaces, logiciels, bases de données, textes et éléments graphiques propres à Petit Annonces sont protégés par les droits applicables. Les utilisateurs restent responsables des droits attachés aux contenus qu’ils publient et accordent à Petit Annonces les autorisations strictement nécessaires à leur hébergement, affichage, adaptation technique et diffusion dans le cadre du service."},
{id:"intermediation",title:"Rôle de la plateforme",body:"Petit Annonces fournit un service d’intermédiation et n’est pas propriétaire des biens ou services publiés par les utilisateurs. Le statut particulier ou professionnel du vendeur est affiché lorsque cette information est disponible. Les règles de classement, de référencement et de mise en avant payante sont décrites dans la rubrique Transparence du classement."},
{id:"droit",title:"Droit applicable",body:"Le service est soumis au droit français et aux règlements européens directement applicables. Les dispositions impératives protectrices des consommateurs demeurent applicables indépendamment des présentes mentions."}
];return <LegalPage eyebrow="Informations légales" title="Mentions légales" intro="Identité de l’éditeur, hébergeur, contacts et responsabilités applicables à PetitAnnonces.fr." updated="26 septembre 2026" sections={sections}/>;}