"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { AdminIcon } from "../../../components/admin-icon";
import styles from "./content-policy-panel.module.css";

type Signal={code:string;field:string;term?:string};
type Hold={id:string;userId:string;status:"PENDING"|"REJECTED";reasonCode?:string;signals:Signal[];attemptTitle:string|null;attemptDescription:string|null;attemptCount:number;email:string;userName:string;createdAt:string;updatedAt:string;reviewNote?:string|null};
type Term={id:string;term:string;enabled:boolean;createdAt:string;updatedAt:string};
type Reply={terms:Term[];holds:Hold[];summary:{activeTerms:number;pending:number;blocked:number}};

const signalLabel=(s:Signal)=>s.code==="CONTACT_PHONE"?"Téléphone détecté":s.code==="CONTACT_EMAIL"?"E-mail détecté":s.code==="MANUAL_BLOCK"?"Blocage manuel":s.term?`Terme interdit : ${s.term}`:"Terme interdit";
const dateTime=(value:string)=>new Intl.DateTimeFormat("fr-FR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));

export function ContentPolicyPanel(){
 const[data,setData]=useState<Reply>({terms:[],holds:[],summary:{activeTerms:0,pending:0,blocked:0}});
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[notice,setNotice]=useState(""),[newTerm,setNewTerm]=useState("");
 const[manualEmail,setManualEmail]=useState(""),[manualIp,setManualIp]=useState(""),[manualNote,setManualNote]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/moderation/content-policy",{credentials:"include",cache:"no-store"});if(!r.ok)throw 0;setData(await r.json() as Reply)}catch{setNotice("Impossible de charger les règles anti-spam.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const enabledTerms=useMemo(()=>data.terms.filter(t=>t.enabled),[data.terms]);
 async function addTerm(e:FormEvent){e.preventDefault();const term=newTerm.trim();if(term.length<3)return;setBusy("add");setNotice("");try{const r=await fetch("/api/admin/moderation/content-policy/terms",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({term})});if(r.status===409){setNotice("Ce terme existe déjà dans le filtre.");return}if(!r.ok)throw 0;setNewTerm("");setNotice("Terme ajouté au filtre.");await load()}catch{setNotice("Le terme n’a pas pu être ajouté.")}finally{setBusy("")}}
 async function toggleTerm(term:Term){setBusy(`term:${term.id}`);try{const r=await fetch(`/api/admin/moderation/content-policy/terms/${encodeURIComponent(term.id)}`,{method:"PATCH",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({enabled:!term.enabled})});if(!r.ok)throw 0;await load()}catch{setNotice("La règle n’a pas pu être modifiée.")}finally{setBusy("")}}
 async function removeTerm(term:Term){setBusy(`term:${term.id}`);try{const r=await fetch(`/api/admin/moderation/content-policy/terms/${encodeURIComponent(term.id)}`,{method:"DELETE",credentials:"include"});if(!r.ok)throw 0;await load()}catch{setNotice("Le terme n’a pas pu être supprimé.")}finally{setBusy("")}}
 async function manualBlock(e:FormEvent){e.preventDefault();const email=manualEmail.trim(),note=manualNote.trim(),ip=manualIp.trim();if(!email||note.length<3)return;setBusy("manual");setNotice("");try{const r=await fetch("/api/admin/moderation/content-policy/holds/manual",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({email,ip,note})});const p=await r.json().catch(()=>({})) as {error?:string};if(!r.ok){const labels:Record<string,string>={user_not_found:"Aucun utilisateur ne correspond à cette adresse e-mail.",invalid_ip:"L’adresse IP saisie n’est pas valide.",protected_staff_account:"Un compte administrateur ou modérateur ne peut pas être bloqué depuis cet écran.",invalid_request:"Vérifiez l’e-mail, l’IP et le motif."};setNotice(labels[p.error??""]??"Le blocage manuel n’a pas pu être créé.");return}setManualEmail("");setManualIp("");setManualNote("");setNotice(ip?"Compte et adresse IP placés sous blocage manuel.":"Compte placé sous blocage manuel.");await load()}catch{setNotice("Connexion interrompue pendant le blocage manuel.")}finally{setBusy("")}}
 async function decide(hold:Hold,action:"APPROVE"|"KEEP_BLOCKED"){setBusy(`hold:${hold.id}`);setNotice("");const note=action==="APPROVE"?"Compte vérifié manuellement ; restriction anti-spam levée.":"Blocage confirmé par la modération ; restriction de sécurité maintenue.";try{const r=await fetch(`/api/admin/moderation/content-policy/holds/${encodeURIComponent(hold.id)}/decision`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({action,note})});if(!r.ok)throw 0;setNotice(action==="APPROVE"?"Restriction levée manuellement.":"Blocage confirmé et maintenu.");await load()}catch{setNotice("La décision n’a pas pu être enregistrée.")}finally{setBusy("")}}
 return <section className={styles.panel}>
  <div className={styles.head}><div><span>Filtre automatique</span><h2>Anti-spam & blocages</h2><p>Bloquez automatiquement les contenus interdits ou placez manuellement un compte sous contrôle de la modération.</p></div><div className={styles.kpis}><b>{data.summary.pending}<small>à vérifier</small></b><b>{data.summary.activeTerms}<small>termes actifs</small></b></div></div>
  {notice&&<div className={styles.notice}>{notice}<button type="button" onClick={()=>setNotice("")}>×</button></div>}
  <form className={styles.manualForm} onSubmit={manualBlock}>
   <div><strong>Bloquer un utilisateur manuellement</strong><small>L’e-mail est obligatoire. L’IP est facultative ; si elle est fournie, elle sera hachée et bloquée avec le compte.</small></div>
   <label><span>E-mail utilisateur</span><input type="email" value={manualEmail} onChange={e=>setManualEmail(e.target.value)} placeholder="utilisateur@exemple.fr" required/></label>
   <label><span>Adresse IP (facultatif)</span><input value={manualIp} onChange={e=>setManualIp(e.target.value)} placeholder="Ex. 203.0.113.10" inputMode="text"/></label>
   <label className={styles.manualReason}><span>Motif *</span><textarea value={manualNote} onChange={e=>setManualNote(e.target.value)} rows={2} maxLength={1000} placeholder="Motif du blocage pour le dossier de modération" required/></label>
   <button disabled={busy==="manual"||!manualEmail.trim()||manualNote.trim().length<3}><AdminIcon name="shield"/>{busy==="manual"?"Blocage…":"Bloquer le compte"}</button>
  </form>
  <div className={styles.grid}>
   <article className={styles.card}><div className={styles.cardHead}><div><AdminIcon name="warning"/><div><h3>Comptes bloqués</h3><p>Le compte reste bloqué jusqu’à une décision manuelle.</p></div></div><span>{data.holds.length}</span></div>{loading?<p className={styles.empty}>Chargement…</p>:data.holds.length===0?<p className={styles.empty}>Aucun blocage à examiner.</p>:<div className={styles.holdList}>{data.holds.map(hold=><div className={styles.hold} key={hold.id}><div className={styles.holdTop}><div><strong>{hold.userName||hold.email}</strong><small>{hold.email} · {dateTime(hold.updatedAt)} · {hold.attemptCount} occurrence{hold.attemptCount>1?"s":""}</small></div><em className={hold.status==="REJECTED"?styles.rejected:styles.pending}>{hold.status==="REJECTED"?"Blocage maintenu":"À vérifier"}</em></div><h4>{hold.reasonCode==="MANUAL_MODERATION_BLOCK"?"Blocage manuel":hold.attemptTitle||"Signal anti-spam"}</h4>{hold.attemptDescription&&<p>{hold.attemptDescription.slice(0,320)}{hold.attemptDescription.length>320?"…":""}</p>}<div className={styles.signals}>{(hold.signals??[]).map((signal,index)=><span key={`${signal.code}-${index}`}>{signalLabel(signal)}{signal.field!=="account"?` · ${signal.field==="title"?"titre":signal.field==="description"?"description":"titre + description"}`:""}</span>)}</div><div className={styles.holdActions}><button type="button" className={styles.keep} disabled={Boolean(busy)} onClick={()=>void decide(hold,"KEEP_BLOCKED")}><AdminIcon name="shield"/>Maintenir le blocage</button><button type="button" className={styles.approve} disabled={Boolean(busy)} onClick={()=>void decide(hold,"APPROVE")}><AdminIcon name="check"/>Approuver & débloquer</button></div></div>)}</div>}</article>
   <article className={styles.card}><div className={styles.cardHead}><div><AdminIcon name="content"/><div><h3>Termes interdits</h3><p>Le filtre ignore accents, casse et ponctuation.</p></div></div><span>{enabledTerms.length}</span></div><form className={styles.addForm} onSubmit={addTerm}><input value={newTerm} onChange={e=>setNewTerm(e.target.value)} maxLength={120} placeholder="Ex. retour affectif"/><button disabled={busy==="add"||newTerm.trim().length<3}><AdminIcon name="plus"/>Ajouter</button></form><div className={styles.termList}>{data.terms.map(term=><div key={term.id} className={!term.enabled?styles.termDisabled:""}><span>{term.term}</span><div><button type="button" disabled={Boolean(busy)} onClick={()=>void toggleTerm(term)}>{term.enabled?"Désactiver":"Activer"}</button><button type="button" className={styles.delete} disabled={Boolean(busy)} onClick={()=>void removeTerm(term)}>Supprimer</button></div></div>)}</div></article>
  </div>
 </section>
}
