"use client";

import { FormEvent, useState } from "react";
import { SiteHeader } from "../../components/site-header";
import styles from "../auth.module.css";

function apiBase(){return (process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000").replace(/\/$/,"")}

const benefits=[
  ["▣","Gérez vos annonces","Modifiez, mettez en pause, republiez ou marquez vos articles comme vendus."],
  ["✉","Centralisez vos échanges","Retrouvez vos messages, vos offres et vos conversations en un seul endroit."],
  ["↔","Suivez vos achats et ventes","Gardez un œil sur vos commandes, paiements, livraisons et litiges."],
  ["✓","Profitez d’un espace plus sûr","Historique, profil et outils de confiance vous accompagnent à chaque transaction."],
];

export default function LoginPage(){
  const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [remember,setRemember]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch(`${apiBase()}/auth/login`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({email,password,remember})});if(!r.ok){const p=await r.json().catch(()=>({}));throw new Error(p.error??"login_failed")}window.location.href="/mon-compte"}catch(err){const code=err instanceof Error?err.message:"login_failed";setError(code==="invalid_credentials"?"E-mail ou mot de passe incorrect.":code==="email_verification_required"?"Veuillez d’abord vérifier votre adresse e-mail.":"Connexion impossible. Réessayez dans quelques instants.")}finally{setBusy(false)}}
  return <div className={styles.page}><SiteHeader/><main className={styles.main}><div className={styles.authGrid}><section className={styles.formCard}><span className={styles.eyebrow}>Bienvenue</span><h1 className={styles.title}>Connectez-vous à Petit Annonces</h1><p className={styles.lead}>Retrouvez vos annonces, vos messages, vos achats et vos ventes dans un espace personnel simple et sécurisé.</p><div className={styles.switcher}><a className={styles.active} href="/connexion">Connexion</a><a href="/inscription">Créer un compte</a></div>{error&&<div className={styles.error}>{error}</div>}<form className={styles.form} onSubmit={submit}><label className={styles.field}>Adresse e-mail<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="vous@exemple.fr" required/></label><label className={styles.field}>Mot de passe<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Votre mot de passe" required/></label><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",flexWrap:"wrap"}}><label className={styles.check}><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span>Rester connecté</span></label><a className={styles.inlineLink} href="/mot-de-passe-oublie">Mot de passe oublié ?</a></div><button className={styles.primary} disabled={busy}>{busy?"Connexion…":"Se connecter"}</button></form><div className={styles.divider}>ou</div><p className={styles.footText}>Pas encore de compte ? <a href="/inscription">Inscrivez-vous gratuitement</a></p><p className={styles.footText}>Vous êtes professionnel ? <a href="/inscription/pro">Ouvrir un compte Pro</a></p></section><aside className={styles.benefitCard}><span className={styles.eyebrow}>Votre espace personnel</span><h2 className={styles.title}>Tout ce qui compte, au même endroit.</h2><p className={styles.lead}>Connectez-vous pour gagner du temps, répondre plus vite et garder une vue claire sur toute votre activité.</p><div className={styles.benefits}>{benefits.map(([icon,title,text])=><div className={styles.benefit} key={title}><div className={styles.benefitIcon}>{icon}</div><div><strong>{title}</strong><p>{text}</p></div></div>)}</div><div className={styles.trustRow}><div><b>Paiement protégé</b><span>Transactions sécurisées</span></div><div><b>Messagerie intégrée</b><span>Échanges centralisés</span></div><div><b>Support & modération</b><span>Plus de sérénité</span></div></div></aside></div></main></div>
}
