import { Image } from 'expo-image';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { PA } from '../constants/theme';
import { money } from '../lib/format';
import type { Listing, ListingPromotion } from '../types/api';
import { AppIcon } from './app-icon';

function relativeTime(value:string|null){if(!value)return'';const t=new Date(value).getTime();if(!Number.isFinite(t))return'';const sec=Math.max(0,Math.floor((Date.now()-t)/1000));if(sec<60)return'à l’instant';const min=Math.floor(sec/60);if(min<60)return`il y a ${min} min`;const h=Math.floor(min/60);if(h<24)return`il y a ${h} h`;const d=Math.floor(h/24);if(d<7)return`il y a ${d} j`;return new Date(value).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit'})}
function promotionLabel(type:string){if(type==='URGENT')return'Urgent';if(type==='FEATURED')return'À la une';if(type==='BUMP')return'Remontée';if(type==='SPONSORED')return'Sponsorisé';if(type==='GALLERY')return'Galerie';return'Boosté'}
function promotionColor(type:string){if(type==='URGENT')return'#e53e3e';if(type==='FEATURED')return'#5b4cf0';if(type==='BUMP')return'#2563eb';if(type==='SPONSORED')return'#181827';if(type==='GALLERY')return'#7c3aed';return PA.primary}
function mainPromo(promotions?:ListingPromotion[]){return promotions?.find(p=>p.type==='FEATURED')??promotions?.find(p=>p.type==='SPONSORED')??promotions?.find(p=>p.type==='BUMP')??promotions?.find(p=>p.type==='GALLERY')??null}

export function ListingCard({ listing }: { listing: Listing }) {
  const router=useRouter();const href=listing.slug?`/annonce/${listing.slug}`:null;const isPro=listing.sellerReputation?.kind==='PROFESSIONNEL'||listing.sellerReputation?.hasStore===true;const urgent=listing.promotions?.some(p=>p.type==='URGENT')===true;const promo=mainPromo(listing.promotions);const shipping=listing.commerce?.shippingEnabled===true;const secure=listing.commerce?.securePaymentEnabled===true;
  return <Pressable disabled={!href} onPress={()=>href&&router.push(href as never)} style={({pressed})=>[s.card,pressed&&s.pressed]}>
    <View style={s.photoWrap}>{listing.imageUrl?<Image source={{uri:listing.imageUrl}} style={s.photo} contentFit="contain" transition={100}/>:<View style={s.empty}><AppIcon name="image" size={25} color="#a6a1bb"/></View>}<View style={s.favorite}><AppIcon name="heart" size={14} color="#625b72"/></View>{(promo||urgent||isPro)?<View style={s.badges}>{promo?<View style={[s.promoBadge,{backgroundColor:promotionColor(promo.type)}]}><Text style={s.promoText}>{promotionLabel(promo.type)}</Text></View>:null}{urgent?<View style={[s.iconBadge,s.urgentBadge]}><AppIcon name="bolt" size={9} color="#fff"/></View>:null}{isPro?<View style={[s.iconBadge,s.proBadge]}><AppIcon name="store" size={9} color="#fff"/></View>:null}</View>:null}{(shipping||secure)?<View style={s.serviceBadges}>{shipping?<View style={s.serviceBadge}><AppIcon name="truck" size={9} color="#285a9f"/></View>:null}{secure?<View style={s.serviceBadge}><AppIcon name="shield-halved" size={9} color="#087a55"/></View>:null}</View>:null}</View>
    <View style={s.body}><Text style={s.title} numberOfLines={2}>{listing.title||listing.category.name}</Text><Text style={s.price} numberOfLines={1}>{money(listing.priceMinor,listing.currency)}</Text><View style={s.meta}><Text style={s.city} numberOfLines={1}>{listing.city||'France'}</Text><Text style={s.time} numberOfLines={1}>{relativeTime(listing.publishedAt)}</Text></View></View>
  </Pressable>
}

const s=StyleSheet.create({card:{width:'48.6%',minWidth:0,borderWidth:1,borderColor:'#e9e8ef',borderRadius:14,backgroundColor:'#fff',overflow:'hidden',marginBottom:11,shadowColor:'#231f47',shadowOpacity:.035,shadowRadius:6,shadowOffset:{width:0,height:3}},pressed:{opacity:.87},photoWrap:{height:136,margin:4,marginBottom:0,borderRadius:11,backgroundColor:'#f3f3f6',overflow:'hidden',alignItems:'center',justifyContent:'center'},photo:{width:'100%',height:'100%',backgroundColor:'#f3f3f6'},empty:{width:'100%',height:'100%',alignItems:'center',justifyContent:'center',backgroundColor:'#f3f3f6'},favorite:{position:'absolute',right:6,top:6,width:29,height:29,borderRadius:15,borderWidth:1,borderColor:'rgba(224,222,232,.9)',backgroundColor:'rgba(255,255,255,.94)',alignItems:'center',justifyContent:'center',shadowColor:'#1f1c41',shadowOpacity:.08,shadowRadius:5,shadowOffset:{width:0,height:3}},badges:{position:'absolute',left:6,top:6,maxWidth:'72%',flexDirection:'row',alignItems:'center',gap:4},promoBadge:{minHeight:22,borderRadius:7,paddingHorizontal:7,alignItems:'center',justifyContent:'center'},promoText:{fontSize:8.5,fontWeight:'900',color:'#fff'},iconBadge:{width:22,height:22,borderRadius:11,alignItems:'center',justifyContent:'center'},urgentBadge:{backgroundColor:'#e53e3e'},proBadge:{backgroundColor:PA.primary},serviceBadges:{position:'absolute',right:6,bottom:6,flexDirection:'row',gap:4},serviceBadge:{width:24,height:24,borderRadius:8,backgroundColor:'rgba(255,255,255,.95)',borderWidth:1,borderColor:'rgba(220,219,230,.95)',alignItems:'center',justifyContent:'center'},body:{paddingHorizontal:9,paddingTop:9,paddingBottom:11},title:{height:36,fontSize:13,lineHeight:18,fontWeight:'900',color:'#252334',marginBottom:6},price:{fontSize:16,lineHeight:19,fontWeight:'900',color:'#181727'},meta:{marginTop:7,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:7},city:{flex:1,fontSize:10.5,fontWeight:'600',color:'#6e6b78'},time:{maxWidth:'42%',fontSize:9.5,color:'#8f8c98'}});
