"use client";
import { useEffect, useMemo, useState } from "react";

type Platform="ANDROID"|"IOS"|"PWA";
type BlockId="search"|"categories"|"latest"|"map"|"discover"|"pro_banner"|"more"|"vacation";
type Audience="ALL"|"GUEST"|"AUTH"|"PRO";
type Block={id:BlockId;enabled:boolean;order:number;title:string;subtitle:string;itemLimit:number;variant:"DEFAULT"|"COMPACT"|"WIDE";audience:Audience};
type NavItem={id:"home"|"search"|"sell"|"messages"|"account";label:string;enabled:boolean;order:number};
type PlatformConfig={header:{enabled:boolean;showLogo:boolean;showPostButton:boolean;showNotifications:boolean;showAccount:boolean};blocks:Block[];bottomNav:{enabled:boolean;items:NavItem[]};theme:{primary:string;background:string;cardRadius:number;density:"COMPACT"|"COMFORTABLE"};abTest:{enabled:boolean;percentB:number;variantBOrder:BlockId[]}};
type Config={schemaVersion:1;platforms:Record<Platform,PlatformConfig>};
type History={revision:number;publishedAt:string;actorUserId:string|null;note:string|null};
type Payload={draft:Config;published:Config;effective:Config;history:History[];scheduled:{publishAt:string;scheduledAt:string;note:string|null}|null};

const blockNames:Record<BlockId,string>={search:"Recherche",categories:"Catégories",latest:"Dernières annonces",map:"Carte de France",discover:"À découvrir",pro_banner:"Bannière Pro",more:"Plus d’annonces",vacation:"Vacances"};
const platformNames:Record<Platform,string>={ANDROID:"Android",IOS:"iOS",PWA:"PWA"};
const navNames:Record<NavItem["id"],string>={home:"Accueil",search:"Recherche",sell:"Déposer",messages:"Messages",account:"Compte"};

export default function MobileUiClient(){
 const[data,setData]=useState<Payload|null>(null);const[draft,setDraft]=useState<Config|null>(null);const[platform,setPlatform]=useState<Platform>("ANDROID");const[busy,setBusy]=useState("");const[msg,setMsg]=useState<{ok:boolean;text:string}|null>(null);const[drag,setDrag]=useState<BlockId|null>(null);const[navDrag,setNavDrag]=useState<NavItem["id"]|null>(null);const[scheduleAt,setScheduleAt]=useState("");const[note,setNote]=useState("");
 async function load(){const r=await fetch("/api/admin/mobile-ui",{credentials:"include",cache:"no-store"});if(!r.ok)return;const p=await r.json() as Payload;setData(p);setDraft(p.draft)}
 useEffect(()=>{void load()},[]);
 const pc=draft?.platforms[platform];
 const blocks=useMemo(()=>[...(pc?.blocks??[])].sort((a,b)=>a.order-b.order),[pc]);
 const nav=useMemo(()=>[...(pc?.bottomNav.items??[])].sort((a,b)=>a.order-b.order),[pc]);
 function setPlatformConfig(updater:(value:PlatformConfig)=>PlatformConfig){setDraft(prev=>prev?{...prev,platforms:{...prev.platforms,[platform]:updater(prev.platforms[platform])}}:prev)}
 function patchBlock(id:BlockId,patch:Partial<Block>){setPlatformConfig(p=>({...p,blocks:p.blocks.map(b=>b.id===id?{...b,...patch}:b)}))}
 function reorderBlock(from:BlockId,to:BlockId){if(from===to)return;setPlatformConfig(p=>{const arr=[...p.blocks].sort((a,b)=>a.order-b.order);const fi=arr.findIndex(x=>x.id===from),ti=arr.findIndex(x=>x.id===to);if(fi<0||ti<0)return p;const[m]=arr.splice(fi,1);if(!m)return p;arr.splice(ti,0,m);return{...p,blocks:arr.map((b,i)=>({...b,order:(i+1)*10}))}})}
 function patchNav(id:NavItem["id"],patch:Partial<NavItem>){setPlatformConfig(p=>({...p,bottomNav:{...p.bottomNav,items:p.bottomNav.items.map(n=>n.id===id?{...n,...patch}:n)}}))}
 function reorderNav(from:NavItem["id"],to:NavItem["id"]){if(from===to)return;setPlatformConfig(p=>{const arr=[...p.bottomNav.items].sort((a,b)=>a.order-b.order);const fi=arr.findIndex(x=>x.id===from),ti=arr.findIndex(x=>x.id===to);if(fi<0||ti<0)return p;const[m]=arr.splice(fi,1);if(!m)return p;arr.splice(ti,0,m);return{...p,bottomNav:{...p.bottomNav,items:arr.map((n,i)=>({...n,order:(i+1)*10}))}}})}
 async function save(){if(!draft)return;setBusy("save");setMsg(null);const r=await fetch("/api/admin/mobile-ui/draft",{method:"PUT",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});setBusy("");if(r.ok){setMsg({ok:true,text:"Brouillon enregistré."});await load()}else setMsg({ok:false,text:"Impossible d’enregistrer le brouillon."})}
 async function publish(){if(!draft)return;setBusy("publish");setMsg(null);let r=await fetch("/api/admin/mobile-ui/draft",{method:"PUT",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});if(r.ok)r=await fetch("/api/admin/mobile-ui/publish",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({note})});setBusy("");if(r.ok){setMsg({ok:true,text:"Nouvelle interface publiée."});setNote("");await load()}else setMsg({ok:false,text:"Publierma başarısız."})}
 async function schedule(){if(!draft||!scheduleAt)return;setBusy("schedule");let r=await fetch("/api/admin/mobile-ui/draft",{method:"PUT",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});if(r.ok)r=await fetch("/api/admin/mobile-ui/schedule",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({publishAt:new Date(scheduleAt).toISOString(),note})});setBusy("");if(r.ok){setMsg({ok:true,text:"Publication planifiée."});await load()}else setMsg({ok:false,text:"Impossible de planifier la publication."})}
 async function cancelSchedule(){const r=await fetch("/api/admin/mobile-ui/schedule",{method:"DELETE",credentials:"include"});if(r.ok){setMsg({ok:true,text:"Publication planifiée annulée."});await load()}}
 async function rollback(revision:number){if(!confirm(`v${revision}  : restaurer cette version ?`))return;setBusy("rollback");const r=await fetch(`/api/admin/mobile-ui/rollback/${revision}`,{method:"POST",credentials:"include"});setBusy("");if(r.ok){setMsg({ok:true,text:`v${revision}  restaurée et republiée comme nouvelle version.`});await load()}else setMsg({ok:false,text:"Restauration impossible."})}
 if(!draft||!pc)return <div className="admin-card admin-section">Chargement…</div>;
 return <>
  <div className="admin-page-head"><div><p>Server-driven UI</p><h1>Mobil uygulama · Arayüz yönetimi</h1><span className="subtitle">Blokları, header’ı, alt menüyü ve görünümü mağaza güncellemesi olmadan yönetin.</span></div><div className="mobile-ui-actions"><button type="button" className="admin-btn" disabled={!!busy} onClick={()=>void save()}>Enregistrer le brouillon</button><button type="button" className="admin-btn primary" disabled={!!busy} onClick={()=>void publish()}>Publier</button></div></div>
  {msg&&<div className={`admin-flash ${msg.ok?"ok":"err"}`}>{msg.text}</div>}
  <div className="mobile-ui-platforms">{(["ANDROID","IOS","PWA"] as Platform[]).map(p=><button type="button" className={platform===p?"active":""} key={p} onClick={()=>setPlatform(p)}>{platformNames[p]}</button>)}</div>
  <div className="mobile-ui-workspace">
   <div className="mobile-ui-editor">
    <section className="admin-card admin-section"><div className="admin-section-head"><div><h2>Blocs de la page d’accueil</h2><p>Glissez-déposez pour réordonner. Chaque bloc possède ses propres réglages.</p></div><span className="admin-badge green">Contrôle en direct</span></div>
     <div className="mobile-ui-block-list">{blocks.map(b=><div key={b.id} draggable onDragStart={()=>setDrag(b.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag)reorderBlock(drag,b.id);setDrag(null)}} className={`mobile-ui-block ${b.enabled?"":"disabled"}`}>
      <div className="mobile-ui-drag">⋮⋮</div><div className="mobile-ui-block-main"><div className="mobile-ui-block-title"><strong>{blockNames[b.id]}</strong><label><input type="checkbox" checked={b.enabled} onChange={e=>patchBlock(b.id,{enabled:e.target.checked})}/> Afficher</label></div>
      <div className="mobile-ui-fields"><label>Titre<input value={b.title} onChange={e=>patchBlock(b.id,{title:e.target.value})}/></label><label>Sous-titre<input value={b.subtitle} onChange={e=>patchBlock(b.id,{subtitle:e.target.value})}/></label><label>Nombre d’éléments<input type="number" min={1} max={24} value={b.itemLimit} onChange={e=>patchBlock(b.id,{itemLimit:Number(e.target.value)||1})}/></label><label>Affichage<select value={b.variant} onChange={e=>patchBlock(b.id,{variant:e.target.value as Block["variant"]})}><option value="DEFAULT">Standard</option><option value="COMPACT">Compact</option><option value="WIDE">Large</option></select></label><label>Audience<select value={b.audience} onChange={e=>patchBlock(b.id,{audience:e.target.value as Audience})}><option value="ALL">Tous</option><option value="GUEST">Visiteurs</option><option value="AUTH">Membres</option><option value="PRO">Professionnels</option></select></label></div></div>
     </div>)}</div>
    </section>
    <section className="admin-card admin-section"><div className="admin-section-head"><div><h2>Header</h2><p>Gérez les éléments de l’en-tête de l’application.</p></div></div><div className="mobile-ui-toggle-grid">{([['enabled','Header'],['showLogo','Logo'],['showPostButton','Déposer'],['showNotifications','Bildirim'],['showAccount','Profil']] as const).map(([k,label])=><label key={k}><input type="checkbox" checked={pc.header[k]} onChange={e=>setPlatformConfig(p=>({...p,header:{...p.header,[k]:e.target.checked}}))}/><span>{label}</span></label>)}</div></section>
    <section className="admin-card admin-section"><div className="admin-section-head"><div><h2>Navigation basse</h2><p>Glissez les onglets, masquez-les ou modifiez leurs libellés.</p></div><label className="mobile-ui-switch"><input type="checkbox" checked={pc.bottomNav.enabled} onChange={e=>setPlatformConfig(p=>({...p,bottomNav:{...p.bottomNav,enabled:e.target.checked}}))}/> Navigation active</label></div><div className="mobile-ui-nav-list">{nav.map(n=><div draggable key={n.id} onDragStart={()=>setNavDrag(n.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(navDrag)reorderNav(navDrag,n.id);setNavDrag(null)}}><span>⋮⋮</span><strong>{navNames[n.id]}</strong><input value={n.label} onChange={e=>patchNav(n.id,{label:e.target.value})}/><label><input type="checkbox" checked={n.enabled} onChange={e=>patchNav(n.id,{enabled:e.target.checked})}/> Afficher</label></div>)}</div></section>
    <section className="admin-card admin-section"><div className="admin-section-head"><div><h2>Thème et densité</h2><p>Couleur principale, arrondis des cartes et densité du contenu.</p></div></div><div className="mobile-ui-theme"><label>Couleur principale<input type="color" value={pc.theme.primary} onChange={e=>setPlatformConfig(p=>({...p,theme:{...p.theme,primary:e.target.value}}))}/><code>{pc.theme.primary}</code></label><label>Arrière-plan<input type="color" value={pc.theme.background} onChange={e=>setPlatformConfig(p=>({...p,theme:{...p.theme,background:e.target.value}}))}/><code>{pc.theme.background}</code></label><label>Rayon des cartes<input type="range" min={8} max={32} value={pc.theme.cardRadius} onChange={e=>setPlatformConfig(p=>({...p,theme:{...p.theme,cardRadius:Number(e.target.value)}}))}/><strong>{pc.theme.cardRadius}px</strong></label><label>Densité<select value={pc.theme.density} onChange={e=>setPlatformConfig(p=>({...p,theme:{...p.theme,density:e.target.value as PlatformConfig['theme']['density']}}))}><option value="COMFORTABLE">Confortable</option><option value="COMPACT">Compact</option></select></label></div></section>
    <section className="admin-card admin-section"><div className="admin-section-head"><div><h2>Test A/B de mise en page</h2><p>Affichez un second ordre de blocs à une part du trafic.</p></div><label className="mobile-ui-switch"><input type="checkbox" checked={pc.abTest.enabled} onChange={e=>setPlatformConfig(p=>({...p,abTest:{...p.abTest,enabled:e.target.checked}}))}/> Actif</label></div><div className="mobile-ui-ab"><label>Trafic variante B<input type="range" min={1} max={99} value={pc.abTest.percentB} onChange={e=>setPlatformConfig(p=>({...p,abTest:{...p.abTest,percentB:Number(e.target.value)}}))}/><strong>%{pc.abTest.percentB}</strong></label><button type="button" className="admin-btn" onClick={()=>setPlatformConfig(p=>({...p,abTest:{...p.abTest,variantBOrder:[...p.blocks].sort((a,b)=>b.order-a.order).map(b=>b.id)}}))}>Créer B en ordre inversé</button><button type="button" className="admin-btn" onClick={()=>setPlatformConfig(p=>({...p,abTest:{...p.abTest,variantBOrder:[]}}))}>Effacer l’ordre B</button></div>{pc.abTest.variantBOrder.length>0&&<div className="mobile-ui-b-order">{pc.abTest.variantBOrder.map((id,i)=><span key={id}>{i+1}. {blockNames[id]}</span>)}</div>}</section>
    <section className="admin-card admin-section"><div className="admin-section-head"><div><h2>Publierma</h2><p>Publiez immédiatement ou planifiez une date de mise en ligne.</p></div></div><div className="mobile-ui-publish"><label>Note de version<input value={note} maxLength={240} onChange={e=>setNote(e.target.value)} placeholder="Ex. ordre de la carte mis à jour"/></label><label>Date de publication<input type="datetime-local" value={scheduleAt} onChange={e=>setScheduleAt(e.target.value)}/></label><button type="button" className="admin-btn" disabled={!scheduleAt||!!busy} onClick={()=>void schedule()}>Planifier</button>{data?.scheduled&&<div className="mobile-ui-scheduled"><strong>Planifierndı:</strong> {new Date(data.scheduled.publishAt).toLocaleString('fr-FR')} <button type="button" onClick={()=>void cancelSchedule()}>Annuler</button></div>}</div></section>
    <section className="admin-card admin-section"><div className="admin-section-head"><div><h2>Historique des versions</h2><p>Restaurez une publication précédente en un clic.</p></div></div><div className="mobile-ui-history">{(data?.history??[]).map(h=><div key={h.revision}><span><strong>v{h.revision}</strong><small>{new Date(h.publishedAt).toLocaleString('fr-FR')}{h.note?` · ${h.note}`:''}</small></span><button type="button" className="admin-btn" disabled={!!busy} onClick={()=>void rollback(h.revision)}>Restaurer</button></div>)}{!data?.history.length&&<p>Aucun historique de publication.</p>}</div></section>
   </div>
   <aside className="mobile-ui-preview-wrap"><div className="mobile-ui-preview-label">Aperçu en direct · {platformNames[platform]}</div><div className="mobile-ui-phone" style={{background:pc.theme.background,borderRadius:Math.max(24,pc.theme.cardRadius+8)}}>{pc.header.enabled&&<div className="mobile-ui-phone-header">{pc.header.showLogo?<b style={{color:pc.theme.primary}}>Petit Annonces</b>:<span/>}<div>{pc.header.showPostButton&&<i style={{background:pc.theme.primary}}>+</i>}{pc.header.showNotifications&&<i>🔔</i>}{pc.header.showAccount&&<i>👤</i>}</div></div>}<div className={`mobile-ui-phone-body ${pc.theme.density.toLowerCase()}`}>{blocks.filter(b=>b.enabled).map(b=><div className={`mobile-ui-preview-block ${b.variant.toLowerCase()}`} key={b.id} style={{borderRadius:pc.theme.cardRadius}}><small>{blockNames[b.id]}</small><strong>{b.title||blockNames[b.id]}</strong>{b.subtitle&&<span>{b.subtitle}</span>}{['latest','discover','more','vacation'].includes(b.id)&&<div className="mobile-ui-preview-cards"><i/><i/></div>}{b.id==='map'&&<div className="mobile-ui-preview-map">FRANCE</div>}{b.id==='categories'&&<div className="mobile-ui-preview-dots">● ● ● ● ●</div>}</div>)}</div>{pc.bottomNav.enabled&&<div className="mobile-ui-phone-nav">{nav.filter(n=>n.enabled).map(n=><span key={n.id}>{n.label}</span>)}</div>}</div></aside>
  </div>
 </>
}
