import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {AppIcon, type AppIconName} from "../../../components/app-icon";
import {CampaignLink} from "../../../components/campaign-link";
import styles from "../../campaign-landing.module.css";

type SectorKey="automobile"|"immobilier"|"high-tech"|"occasion";
type SectorConfig={
 label:string;eyebrow:string;icon:AppIconName;title:string;accent:string;description:string;
 pointA:string;pointB:string;pointC:string;stepA:string;stepADesc:string;stepB:string;stepBDesc:string;stepC:string;stepCDesc:string;
 trustTitle:string;trustText:string;campaign:string;ctaLabel?:string;microcopy?:string;
};
const SECTORS:Record<SectorKey,SectorConfig>={
 automobile:{label:"Garages & concessions",eyebrow:"Professionnels de l’automobile",icon:"car",title:"Publiez votre stock sans ressaisir chaque véhicule.",accent:"90 jours Pro offerts.",description:"Avec votre SIRET, créez votre vitrine garage, importez votre stock par CSV et publiez jusqu’à 250 annonces actives. Aucune carte bancaire n’est demandée pour l’offre de lancement.",pointA:"90 jours Pro offerts, sans carte",pointB:"Import CSV jusqu’à 200 véhicules",pointC:"Jusqu’à 250 annonces actives",stepA:"Créez votre vitrine garage",stepADesc:"Votre SIRET vérifie l’établissement et crée une identité professionnelle claire.",stepB:"Importez votre stock",stepBDesc:"Ajoutez jusqu’à 200 véhicules par fichier CSV puis complétez les photos et fiches avant publication.",stepC:"Publiez et centralisez les demandes",stepCDesc:"Vos annonces, messages et performances restent réunis dans l’Espace Pro.",trustTitle:"Votre stock visible dans une seule vitrine professionnelle.",trustText:"Réduisez la ressaisie, gardez votre catalogue regroupé et présentez clairement votre établissement aux acheteurs.",campaign:"pro_automobile",ctaLabel:"Créer ma vitrine Pro",microcopy:"SIRET requis · aucune carte bancaire · aucun prélèvement automatique à la fin des 90 jours"},
 immobilier:{label:"Agences immobilières",eyebrow:"Professionnels de l’immobilier",icon:"home",title:"Diffusez votre portefeuille depuis une seule vitrine.",accent:"90 jours Pro offerts.",description:"Avec votre SIRET, créez votre vitrine d’agence, importez vos biens par CSV et publiez jusqu’à 250 annonces actives. Aucune carte bancaire n’est demandée pour l’offre de lancement.",pointA:"90 jours Pro offerts, sans carte",pointB:"Import CSV jusqu’à 200 biens",pointC:"Jusqu’à 250 annonces actives",stepA:"Créez votre vitrine d’agence",stepADesc:"Votre SIRET vérifie l’agence et crée une identité professionnelle claire.",stepB:"Importez votre portefeuille",stepBDesc:"Ajoutez jusqu’à 200 biens par fichier CSV puis contrôlez les fiches avant publication.",stepC:"Diffusez et centralisez les demandes",stepCDesc:"Vos annonces, messages et performances restent réunis dans l’Espace Pro.",trustTitle:"Votre portefeuille regroupé sous l’identité de votre agence.",trustText:"Présentez ventes et locations dans une vitrine unique et réduisez la ressaisie grâce à l’import en masse.",campaign:"pro_immobilier",ctaLabel:"Créer ma vitrine d’agence",microcopy:"SIRET requis · aucune carte bancaire · aucun prélèvement automatique à la fin des 90 jours"},
 "high-tech":{label:"Téléphonie & informatique",eyebrow:"Magasins high-tech",icon:"laptop",title:"Mettez votre stock high-tech en ligne.",accent:"90 jours Pro offerts.",description:"Smartphones, ordinateurs, consoles et accessoires : importez votre catalogue et présentez votre magasin dans une vitrine professionnelle.",pointA:"Catalogue multi-produits",pointB:"Import CSV jusqu’à 200 articles",pointC:"Messages centralisés",stepA:"Ouvrez votre espace magasin",stepADesc:"Vérifiez votre entreprise et créez votre boutique Petit Annonces.",stepB:"Ajoutez votre stock",stepBDesc:"Importez en masse vos produits avec prix, ville, description et photos.",stepC:"Transformez les vues en contacts",stepCDesc:"Les acheteurs retrouvent vos annonces et vous contactent depuis la messagerie intégrée.",trustTitle:"Une vitrine simple pour vos produits disponibles maintenant.",trustText:"Idéal pour les magasins de téléphonie, informatique, gaming et électronique qui renouvellent régulièrement leur stock.",campaign:"pro_high_tech"},
 occasion:{label:"Commerces d’occasion",eyebrow:"Revendeurs & seconde main",icon:"store",title:"Publiez votre stock de seconde main.",accent:"90 jours Pro offerts.",description:"Mobilier, électroménager, mode, objets, équipements : importez votre catalogue et donnez une vraie vitrine à votre activité locale.",pointA:"Plusieurs catégories dans une boutique",pointB:"Import CSV jusqu’à 200 articles",pointC:"SIRET & identité vérifiés",stepA:"Créez votre vitrine",stepADesc:"Présentez votre commerce, votre ville et votre identité professionnelle.",stepB:"Importez vos articles",stepBDesc:"Chargez plusieurs catégories de produits sans créer chaque annonce une par une.",stepC:"Gardez le catalogue vivant",stepCDesc:"Suivez les brouillons, annonces publiées et ventes depuis le même espace.",trustTitle:"La seconde main mérite aussi une vitrine professionnelle.",trustText:"Petit Annonces permet aux brocanteurs, dépôts-vente et revendeurs locaux de structurer un catalogue visible partout en France.",campaign:"pro_occasion"}
};
const TRACKING_KEYS=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","fbclid","gclid","gbraid","wbraid","msclkid"] as const;
function first(value:string|string[]|undefined){return Array.isArray(value)?value[0]:value}
function isSector(value:string):value is SectorKey{return value in SECTORS}

export function generateStaticParams(){return Object.keys(SECTORS).map(sector=>({sector}))}
export async function generateMetadata({params}:{params:Promise<{sector:string}>}):Promise<Metadata>{const {sector}=await params;if(!isSector(sector))return{};const c=SECTORS[sector];const url=`https://petitannonces.fr/pro/${sector}`;return{title:`${c.label} : 90 jours Pro offerts | Petit Annonces`,description:`${c.description} Sans carte bancaire ni prélèvement automatique pendant l’offre de lancement.`,alternates:{canonical:url},openGraph:{title:`${c.label} · 90 jours Pro offerts`,description:c.description,url,type:"website"}}}

export default async function SectorProLanding({params,searchParams}:{params:Promise<{sector:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {sector}=await params;if(!isSector(sector))notFound();const c=SECTORS[sector];const query=await searchParams;const next=new URLSearchParams({type:"pro",sector});for(const key of TRACKING_KEYS){const value=first(query[key]);if(value)next.set(key,value)}const cta=`/inscription?${next.toString()}`;
 return <div className={styles.page}><main>
  <section className={styles.hero}><div className={styles.heroInner}>
   <div className={styles.copy}><span className={styles.kicker}><AppIcon name={c.icon}/> {c.eyebrow}</span><h1>{c.title} <em>{c.accent}</em></h1><p>{c.description}</p><div className={styles.points}><span><AppIcon name="circle-check"/> {c.pointA}</span><span><AppIcon name="list"/> {c.pointB}</span><span><AppIcon name="store"/> {c.pointC}</span></div><div className={styles.ctaRow}><CampaignLink className={styles.primary} href={cta} cta="hero_primary" landing={`/pro/${sector}`} campaign={c.campaign}>{c.ctaLabel??"Démarrer mes 90 jours offerts"} <AppIcon name="arrow-right"/></CampaignLink><small>{c.microcopy??"Sans carte bancaire. Aucun prélèvement automatique à la fin de l’offre."}</small></div></div>
   <div className={`${styles.visual} ${styles.proVisual}`} aria-label={`Aperçu Petit Annonces Pro pour ${c.label}`}><div className={styles.mockHeader}><b>{c.label}</b><span><AppIcon name="shield"/> Entreprise vérifiée</span></div><div className={styles.mockMain}><div className={`${styles.mockCard} ${styles.mockCardAccent}`}><span><AppIcon name={c.icon}/></span><div><strong>Votre catalogue professionnel</strong><small>Vos annonces regroupées dans une vitrine claire.</small></div></div><div className={styles.mockCard}><span><AppIcon name="list"/></span><div><strong>Import en masse</strong><small>Jusqu’à 200 annonces par fichier CSV.</small></div></div><div className={styles.mockCard}><span><AppIcon name="comments"/></span><div><strong>Contacts centralisés</strong><small>Messagerie et demandes réunies dans l’Espace Pro.</small></div></div><div className={styles.mockCard}><span><AppIcon name="gauge"/></span><div><strong>Suivi de l’activité</strong><small>Catalogue, visibilité et statistiques au même endroit.</small></div></div></div></div>
  </div></section>
  <section className={styles.steps}><div className={styles.shell}><div className={styles.sectionHead}><span>{c.label}</span><h2>Du SIRET au catalogue en trois étapes</h2><p>Le parcours est conçu pour réduire la ressaisie et accélérer la mise en ligne d’un stock professionnel.</p></div><div className={styles.stepGrid}><article><i>1</i><span><AppIcon name="user-shield"/></span><h3>{c.stepA}</h3><p>{c.stepADesc}</p></article><article><i>2</i><span><AppIcon name="list"/></span><h3>{c.stepB}</h3><p>{c.stepBDesc}</p></article><article><i>3</i><span><AppIcon name="comments"/></span><h3>{c.stepC}</h3><p>{c.stepCDesc}</p></article></div></div></section>
  <section className={styles.trust}><div className={styles.shell}><div className={styles.trustCopy}><span>Petit Annonces Pro</span><h2>{c.trustTitle}</h2><p>{c.trustText}</p><CampaignLink className={styles.secondary} href={cta} cta="trust_secondary" landing={`/pro/${sector}`} campaign={c.campaign}>Créer ma boutique professionnelle <AppIcon name="arrow-right"/></CampaignLink></div><div className={styles.trustCards}><article><AppIcon name="store"/><div><strong>Boutique dédiée</strong><small>Une identité professionnelle vérifiée autour de votre catalogue.</small></div></article><article><AppIcon name="list"/><div><strong>Import jusqu’à 200 annonces</strong><small>Créez les brouillons en masse puis vérifiez-les avant publication.</small></div></article><article><AppIcon name="shield"/><div><strong>90 jours sans engagement</strong><small>Aucune carte bancaire demandée et aucun prélèvement automatique.</small></div></article></div></div></section>
  <CampaignLink className={styles.mobileCta} href={cta} cta="mobile_sticky" landing={`/pro/${sector}`} campaign={c.campaign}>90 jours Pro offerts <AppIcon name="arrow-right"/></CampaignLink>
 </main></div>;
}
