"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AccountSidebar } from "../../../components/account-sidebar";
import styles from "../engagement.module.css";
import { disableNativePush, inspectNativePush, nativeShellMode, requestNativePush } from "../../../lib/native-shell";
import { fetchWithRetry } from "../../../lib/fetch-resilient";
import { navigateApp } from "../../../lib/app-navigation";

function api(){return (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"")}
function urlBase64ToUint8Array(value:string){const padding="=".repeat((4-(value.length%4))%4);const base64=(value+padding).replace(/-/g,"+").replace(/_/g,"/");const raw=atob(base64);return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)))}
type N={id:string;kind:string;title:string;body:string|null;actionUrl:string|null;metadata?:Record<string,unknown>|null;readAt:string|null;createdAt:string};
type Prefs={messages:boolean;offers:boolean;orders:boolean;promotions:boolean;savedSearches:boolean;security:boolean;favorites:boolean};
type Group="all"|"messages"|"searches"|"favorites"|"sales"|"system";
const defaultPrefs:Prefs={messages:true,offers:true,orders:true,promotions:false,savedSearches:true,security:true,favorites:true};
const kindLabel:Record<string,string>={MESSAGE:"Message",OFFER:"Offre",LISTING:"Annonce / vente",SYSTEM:"Système",WALLET:"Portefeuille",SECURITY:"Sécurité",SEARCH:"Recherche enregistrée"};
const groupLabels:Record<Group,string>={all:"Toutes",messages:"Messages",searches:"Recherches",favorites:"Favoris & suivis",sales:"Ventes",system:"Système"};
function safeActionUrl(value:string|null){if(!value||!value.startsWith("/")||value.startsWith("//"))return null;return value;}
function parisDateTime(value:string){return new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Paris"}).format(new Date(value))}
function groupFor(n:N):Exclude<Group,"all">{
  const marker=String(n.metadata?.source??n.metadata?.purpose??"").toUpperCase();
  if(n.kind==="MESSAGE")return"messages";
  if(n.kind==="SEARCH")return"searches";
  if(marker.includes("FAVORITE")||marker.includes("FOLLOWED"))return"favorites";
  if(n.kind==="OFFER"||n.kind==="WALLET"||n.kind==="LISTING")return"sales";
  return"system";
}
async function setBadge(count:number){
  const nav=navigator as Navigator&{setAppBadge?:(count:number)=>Promise<void>;clearAppBadge?:()=>Promise<void>};
  try{if(count>0&&nav.setAppBadge)await nav.setAppBadge(count);else{await nav.setAppBadge?.(0);await nav.clearAppBadge?.().catch(()=>undefined)}if(count===0&&"serviceWorker" in navigator){const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:"CLEAR_APP_BADGE"})}}catch{}
}

export default function NotificationsPage(){
  const router=useRouter();
  const [items,setItems]=useState<N[]>([]);const[unread,setUnread]=useState(0);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  const [filter,setFilter]=useState<Group>("all");const[prefs,setPrefs]=useState<Prefs>(defaultPrefs);const[prefsReady,setPrefsReady]=useState(false);const[savingGroup,setSavingGroup]=useState<Group|null>(null);
  const [pushEnabled,setPushEnabled]=useState(false);const[pushSupported,setPushSupported]=useState(true);const[pushChecking,setPushChecking]=useState(true);const[pushBusy,setPushBusy]=useState(false);const[pushStatus,setPushStatus]=useState("Vérification de cet appareil…");

  function publishCount(count:number){window.dispatchEvent(new CustomEvent("pa:notification-count",{detail:count}))}
  async function load(){setLoading(true);setError("");let r:Response;try{r=await fetchWithRetry(`${api()}/account/notifications`,{credentials:"include",cache:"no-store"},{timeoutMs:7000,retries:1})}catch{setError("Impossible de charger vos notifications.");setLoading(false);return}if(!r.ok){setError("Impossible de charger vos notifications.");setLoading(false);return}const p=await r.json();const rows=(p.notifications??[]) as N[];const count=Math.max(0,Number(p.unread??0));setItems(rows);setUnread(count);await setBadge(count);publishCount(count);setLoading(false)}
  async function loadPrefs(){let r:Response;try{r=await fetchWithRetry(`${api()}/notifications/preferences`,{credentials:"include",cache:"no-store"},{timeoutMs:7000,retries:1})}catch{return}if(r.status===401){navigateApp(router,"/connexion?next=%2Fmon-compte%2Fnotifications",{replace:true});return}if(!r.ok)return;const p=await r.json() as{preferences?:Partial<Prefs>};setPrefs({...defaultPrefs,...(p.preferences??{})});setPrefsReady(true)}
  async function registerExistingSubscription(subscription:PushSubscription){const json=subscription.toJSON();if(!json.keys?.p256dh||!json.keys?.auth)return false;const r=await fetch(`${api()}/notifications/push/subscribe`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({platform:"WEB",endpoint:subscription.endpoint,keys:json.keys,deviceLabel:navigator.platform||"Web"})});return r.ok}
  async function inspectPush(){setPushChecking(true);try{if(nativeShellMode()){const result=await inspectNativePush();setPushSupported(true);setPushEnabled(Boolean(result.enabled));setPushStatus(result.enabled?"Notifications activées sur cet appareil.":result.permission==="denied"?"Notifications bloquées dans les réglages de l’appareil.":"Notifications désactivées sur cet appareil.");return}if(!("serviceWorker" in navigator)||!("PushManager" in window)||!("Notification" in window)){setPushSupported(false);setPushEnabled(false);setPushStatus("Notifications non prises en charge sur cet appareil.");return}const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();if(!sub||Notification.permission!=="granted"){setPushEnabled(false);setPushStatus(Notification.permission==="denied"?"Notifications bloquées dans les réglages de l’appareil.":"Notifications désactivées sur cet appareil.");return}const sr=await fetch(`${api()}/notifications/push/status?endpoint=${encodeURIComponent(sub.endpoint)}`,{credentials:"include",cache:"no-store"});const sp=sr.ok?await sr.json() as{active?:boolean}:null;let active=Boolean(sp?.active);if(!active)active=await registerExistingSubscription(sub);setPushEnabled(active);setPushStatus(active?"Notifications activées sur cet appareil.":"L’abonnement push doit être réactivé sur cet appareil.")}catch{setPushStatus("Impossible de vérifier les notifications pour le moment.")}finally{setPushChecking(false)}}

  useEffect(()=>{void Promise.all([load(),loadPrefs(),inspectPush()])},[]);

  async function togglePush(){if(pushBusy||pushChecking||!pushSupported)return;setPushBusy(true);try{if(nativeShellMode()){if(pushEnabled){const result=await disableNativePush();if(!result.ok)throw new Error("unsubscribe_failed");setPushEnabled(false);setPushStatus("Notifications désactivées sur cet appareil.");return}const result=await requestNativePush();if(!result.ok){setPushStatus(result.permission==="denied"?"Notifications bloquées dans les réglages de l’appareil.":"Autorisation non accordée.");return}setPushEnabled(true);setPushStatus("Notifications activées sur cet appareil.");return}const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(pushEnabled){if(sub){const r=await fetch(`${api()}/notifications/push/unsubscribe`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({endpoint:sub.endpoint})});if(!r.ok)throw new Error("unsubscribe_failed");await sub.unsubscribe()}setPushEnabled(false);setPushStatus("Notifications désactivées sur cet appareil.");return}const keyResponse=await fetch(`${api()}/notifications/push/public-key`,{credentials:"include",cache:"no-store"});const kp=await keyResponse.json().catch(()=>({})) as{configured?:boolean;publicKey?:string|null};if(!keyResponse.ok||!kp.configured||!kp.publicKey)throw new Error("push_unavailable");const permission=Notification.permission==="granted"?"granted":await Notification.requestPermission();if(permission!=="granted"){setPushStatus(permission==="denied"?"Notifications bloquées dans les réglages de l’appareil.":"Autorisation non accordée.");return}if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(kp.publicKey)});if(!await registerExistingSubscription(sub))throw new Error("subscribe_failed");setPushEnabled(true);setPushStatus("Notifications activées sur cet appareil.")}catch{setPushStatus("Impossible de modifier les notifications pour le moment.")}finally{setPushBusy(false)}}

  function groupEnabled(group:Exclude<Group,"all">){if(group==="messages")return prefs.messages;if(group==="searches")return prefs.savedSearches;if(group==="favorites")return prefs.favorites;if(group==="sales")return prefs.offers&&prefs.orders;return prefs.security}
  async function toggleGroup(group:Exclude<Group,"all">){if(savingGroup)return;const previous=prefs;const target=!groupEnabled(group);const next={...prefs};if(group==="messages")next.messages=target;else if(group==="searches")next.savedSearches=target;else if(group==="favorites")next.favorites=target;else if(group==="sales"){next.offers=target;next.orders=target}else next.security=target;setPrefs(next);setSavingGroup(group);setError("");try{const r=await fetch(`${api()}/notifications/preferences`,{method:"PUT",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(next)});if(!r.ok)throw new Error("save_failed")}catch{setPrefs(previous);setError("Impossible d’enregistrer cette préférence.")}finally{setSavingGroup(null)}}

  async function read(id:string){const r=await fetch(`${api()}/account/notifications/${id}/read`,{method:"POST",credentials:"include",keepalive:true});if(!r.ok){setError("Impossible de mettre à jour cette notification.");return unread}const p=await r.json().catch(()=>({})) as{unread?:number};const next=Number.isFinite(p.unread)?Math.max(0,Number(p.unread)):Math.max(0,unread-1);setItems(v=>v.filter(x=>x.id!==id));setUnread(next);await setBadge(next);publishCount(next);return next}
  async function readAll(){const r=await fetch(`${api()}/account/notifications/read-all`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({confirm:"ALL"})});if(!r.ok){setError("Impossible de marquer les notifications comme lues.");return}setError("");setItems([]);setUnread(0);await setBadge(0);publishCount(0)}

  const counts=useMemo(()=>{const out:Record<Group,number>={all:items.length,messages:0,searches:0,favorites:0,sales:0,system:0};for(const item of items)out[groupFor(item)]++;return out},[items]);
  const visible=filter==="all"?items:items.filter(item=>groupFor(item)===filter);
  const prefCards:(Exclude<Group,"all">)[]=["messages","searches","favorites","sales","system"];

  return <div className={styles.page}><main className={styles.shell}><AccountSidebar/><section className={styles.accountContent}>
    <div className={styles.top}><div><span className={styles.eyebrow}>Mon compte</span><h1>Notifications</h1><p>Messages, recherches, favoris, ventes et alertes système au même endroit.</p></div><div className={styles.actions}><span className={styles.count}>{unread} non lue(s)</span>{unread>0&&<button type="button" className={styles.button} onClick={()=>void readAll()}>Tout marquer comme lu</button>}</div></div>
    <section className={styles.notificationSettings}>
      <div className={styles.pushStatusCard}><div><strong>Notifications sur cet appareil</strong><small>{pushStatus}</small></div><button type="button" className={`${styles.switch}${pushEnabled?` ${styles.switchOn}`:""}`} aria-pressed={pushEnabled} aria-label={pushEnabled?"Désactiver les notifications push":"Activer les notifications push"} disabled={pushBusy||pushChecking||!pushSupported} onClick={()=>void togglePush()}><span/></button></div>
      <div className={styles.preferenceGrid}>{prefCards.map(group=><article key={group} className={styles.preferenceCard}><div><strong>{groupLabels[group]}</strong><small>{group==="messages"?"Nouveaux messages":group==="searches"?"Recherches enregistrées":group==="favorites"?"Favoris et comptes suivis":group==="sales"?"Offres, annonces, commandes et portefeuille":"Sécurité et informations système"}</small></div><button type="button" className={`${styles.switch}${groupEnabled(group)?` ${styles.switchOn}`:""}`} aria-pressed={groupEnabled(group)} disabled={!prefsReady||savingGroup!==null} onClick={()=>void toggleGroup(group)}><span/></button></article>)}</div>
      <p className={styles.preferenceNote}>Les changements sont enregistrés automatiquement. Les e-mails transactionnels indispensables liés à la sécurité ou à un paiement peuvent rester envoyés.</p>
    </section>
    <nav className={styles.notificationFilters} aria-label="Filtrer les notifications">{(["all","messages","searches","favorites","sales","system"] as Group[]).map(group=><button key={group} type="button" className={filter===group?styles.filterActive:""} onClick={()=>setFilter(group)}>{groupLabels[group]} <span>{counts[group]}</span></button>)}</nav>
    <section className={styles.panel}>{error&&<div className={styles.errorState} role="alert">{error}<button type="button" className={styles.button} onClick={()=>void load()}>Réessayer</button></div>}<div className={styles.notificationList}>{loading?<div className={styles.notificationSkeleton}><i/><i/><i/></div>:visible.length===0?<div className={styles.emptyState}><span>✓</span><h2>{filter==="all"?"Vous êtes à jour":"Aucune notification dans cette catégorie"}</h2><p>{filter==="all"?"Aucune notification pour le moment.":"Vous pouvez choisir une autre catégorie ci-dessus."}</p></div>:visible.map(n=><article className={`${styles.row} ${!n.readAt?styles.unread:""}`} key={n.id}><div><span className={styles.kind}>{kindLabel[n.kind]??"Notification"}</span><h3>{n.title}</h3><p>{n.body}</p><p className={styles.meta}>{parisDateTime(n.createdAt)}</p></div><div className={styles.controls}>{safeActionUrl(n.actionUrl)&&<a className={styles.button} href={safeActionUrl(n.actionUrl)!} onClick={e=>{e.preventDefault();const target=safeActionUrl(n.actionUrl);if(!target)return;void (async()=>{if(!n.readAt)await read(n.id);navigateApp(router,target)})()}}>Ouvrir</a>}{!n.readAt&&<button type="button" className={styles.danger} onClick={()=>void read(n.id)}>Marquer comme lu</button>}</div></article>)}</div></section>
  </section></main></div>;
}
