"use client";

import { FormEvent, useEffect, useState } from "react";
import { SiteHeader } from "../../../components/site-header";
import styles from "./page.module.css";

function apiBase(){return (process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000").replace(/\/$/,"")}

type MePayload={user:{email:string;profile?:{displayName?:string|null;firstName?:string|null;lastName?:string|null;phone?:string|null}}};

export default function ProfilePage(){
  const [email,setEmail]=useState(""); const [displayName,setDisplayName]=useState(""); const [firstName,setFirstName]=useState(""); const [lastName,setLastName]=useState(""); const [phone,setPhone]=useState(""); const [message,setMessage]=useState("");
  useEffect(()=>{fetch(`${apiBase()}/auth/me`,{credentials:"include"}).then(r=>r.ok?r.json():Promise.reject()).then((p:MePayload)=>{setEmail(p.user.email);setDisplayName(p.user.profile?.displayName??"");setFirstName(p.user.profile?.firstName??"");setLastName(p.user.profile?.lastName??"");setPhone(p.user.profile?.phone??"")}).catch(()=>setMessage("Connectez-vous pour modifier votre profil."))},[]);
  async function save(e:FormEvent){e.preventDefault();const r=await fetch(`${apiBase()}/account/profile`,{method:"PATCH",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({displayName:displayName||null,firstName:firstName||null,lastName:lastName||null,phone:phone||null,locale:"fr-FR"})});setMessage(r.ok?"Profil enregistré.":"Impossible d’enregistrer le profil.")}
  return <div className={styles.page}><SiteHeader/><main className={styles.shell}><aside className={styles.side}><a href="/mon-compte">← Tableau de bord</a><a className={styles.active} href="/mon-compte/profil">Profil & vérification</a><a href="/mon-compte/adresses">Adresses</a><a href="/mon-compte/parametres">Paramètres & sécurité</a></aside><section className={styles.content}><div className={styles.heading}><span>Identité</span><h1>Profil & vérification</h1><p>Un profil complet rassure les acheteurs et vendeurs.</p></div>{message&&<div className={styles.message}>{message}</div>}<section className={styles.profileCard}><div className={styles.avatar}>{(displayName||email||"PA").slice(0,2).toUpperCase()}</div><div><h2>{displayName||"Mon profil"}</h2><p>{email}</p><div className={styles.badges}><span>✓ E-mail vérifié</span>{phone&&<span>✓ Téléphone renseigné</span>}</div></div></section><form className={styles.card} onSubmit={save}><div className={styles.grid}><label>Nom affiché<input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Nom visible sur les annonces"/></label><label>Prénom<input value={firstName} onChange={e=>setFirstName(e.target.value)}/></label><label>Nom<input value={lastName} onChange={e=>setLastName(e.target.value)}/></label><label>Téléphone<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+33 ..."/></label></div><button>Enregistrer le profil</button></form><section className={styles.card}><h2>Niveau de confiance</h2><div className={styles.checks}><div className={styles.done}>✓ Adresse e-mail vérifiée</div><div className={phone?styles.done:styles.todo}>{phone?"✓":"○"} Numéro de téléphone</div><div className={styles.todo}>○ Vérification d’identité</div><div className={styles.todo}>○ Adresse principale</div></div></section></section></main></div>
}
