"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {AppIcon} from "../../components/app-icon";
import {trackSiteConversion} from "../../components/site-telemetry";
import {getRegistrationAttribution} from "../../components/registration-attribution";
import styles from "../auth.module.css";

type Kind="PARTICULIER"|"PROFESSIONNEL";
type Company={legalName?:string;tradeName?:string|null;siren?:string;siret?:string;nafCode?:string|null;legalFormCode?:string|null;headquartersAddress?:string|null;headquartersCity?:string|null;headquartersPostalCode?:string|null;active?:boolean};
type Step="choice"|"particular"|"siret"|"pro-account"|"store"|"success";
type ProSectorChoice="automobile"|"immobilier"|"commerce"|"services"|"vacances"|"autre";
function api(){return(process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"")}
function errorText(code:string){const m:Record<string,string>={email_already_registered:"Un compte existe déjà avec cette adresse e-mail.",company_already_registered:"Cette entreprise est déjà associée à un compte professionnel Petit Annonces. Connectez-vous au compte existant ou contactez l’assistance.",rate_limited:"Trop de tentatives. Réessayez un peu plus tard.",invalid_siret:"Le numéro SIRET n’est pas valide.",siret_required:"Un SIRET de 14 chiffres est nécessaire.",company_not_found:"Cette entreprise n’a pas été trouvée dans le registre public.",company_inactive:"Cette entreprise est indiquée comme inactive.",registry_unavailable:"Le registre des entreprises est momentanément indisponible."};return m[code]??"Impossible de créer le compte. Vérifiez les informations saisies."}
export default function SignupWizard(){
 const[step,setStep]=useState<Step>("choice"),[direction,setDirection]=useState<"forward"|"back">("forward"),[kind,setKind]=useState<Kind|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[successTarget,setSuccessTarget]=useState(""),[returnPath,setReturnPath]=useState(""),[verificationRequired,setVerificationRequired]=useState(false),[selectedPlan,setSelectedPlan]=useState<"ESSENTIEL"|"PROFESSIONNEL"|"PREMIUM"|null>(null),[referralCode,setReferralCode]=useState(""),[trial,setTrial]=useState<{planCode:string;days:number;endsAt:string}|null>(null);
 const[personal,setPersonal]=useState({displayName:"",email:"",password:"",confirm:""}),[terms,setTerms]=useState(false);
 const[siret,setSiret]=useState(""),[company,setCompany]=useState<Company|null>(null),[lookupBusy,setLookupBusy]=useState(false);
 const[pro,setPro]=useState({displayName:"",email:"",phone:"",password:"",confirm:""});
 const[store,setStore]=useState({name:"",city:"",postalCode:""});
 const[proSector,setProSector]=useState<ProSectorChoice|"">("");
 const[oauthGoogle,setOauthGoogle]=useState(false);
 useEffect(()=>{let active=true;fetch(`${api()}/auth/oauth/providers`,{cache:"no-store"}).then(async r=>r.ok?await r.json() as {google?:boolean}:{} as {google?:boolean}).then(p=>{if(active)setOauthGoogle(Boolean(p.google))}).catch(()=>undefined);return()=>{active=false}},[]);
 useEffect(()=>{const q=new URLSearchParams(window.location.search);const requestedNext=q.get("next");if(requestedNext&&requestedNext.startsWith("/")&&!requestedNext.startsWith("//"))setReturnPath(requestedNext);const plan=q.get("plan");const ref=(q.get("ref")??"").trim().slice(0,40);const rawSector=(q.get("sector")??"").toLowerCase();const initialSector:ProSectorChoice|""=rawSector==="automobile"?"automobile":rawSector==="immobilier"?"immobilier":rawSector==="high-tech"||rawSector==="occasion"||rawSector==="commerce"?"commerce":rawSector==="services"?"services":rawSector==="vacances"?"vacances":"";if(initialSector)setProSector(initialSector);if(ref)setReferralCode(ref);if(plan==="ESSENTIEL"||plan==="PROFESSIONNEL"||plan==="PREMIUM")setSelectedPlan(plan);if(q.get("type")==="pro"){setKind("PROFESSIONNEL");go("siret")}},[]);
 useEffect(()=>{if(step!=="success"||!successTarget||verificationRequired)return;const t=window.setTimeout(()=>window.location.href=successTarget,1600);return()=>window.clearTimeout(t)},[step,successTarget,verificationRequired]);
 const steps=useMemo(()=>kind==="PROFESSIONNEL"?["Type de compte","SIRET","Identifiants","Boutique","Terminé"]:["Type de compte","Vos informations","Terminé"],[kind]);
 const current=kind==="PROFESSIONNEL"?({choice:0,siret:1,"pro-account":2,store:3,success:4,particular:0} as Record<Step,number>)[step]:({choice:0,particular:1,success:2,siret:0,"pro-account":0,store:0} as Record<Step,number>)[step];
 const stepRank:Record<Step,number>={choice:0,particular:1,siret:1,"pro-account":2,store:3,success:4};
 function go(next:Step){setDirection(stepRank[next]>=stepRank[step]?"forward":"back");setStep(next)}
 function choose(v:Kind){setKind(v);setError("");go(v==="PARTICULIER"?"particular":"siret")}
 async function verifySiret(){const id=siret.replace(/\D/g,"");setSiret(id);setError("");setCompany(null);if(id.length!==14){setError("Saisissez un numéro SIRET de 14 chiffres.");return}setLookupBusy(true);try{const r=await fetch(`${api()}/auth/register/pro/company-lookup?identifier=${encodeURIComponent(id)}`,{cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error??"registry_unavailable");const c=p.company as Company;if(c.active===false)throw new Error("company_inactive");setCompany(c);setSiret(c.siret??id);setStore(v=>({name:v.name||c.tradeName||c.legalName||"",city:v.city||c.headquartersCity||"",postalCode:v.postalCode||c.headquartersPostalCode||""}))}catch(e){setError(errorText(e instanceof Error?e.message:"registry_unavailable"))}finally{setLookupBusy(false)}}
 async function submitPersonal(e:FormEvent){e.preventDefault();setError("");if(personal.password!==personal.confirm){setError("Les mots de passe ne correspondent pas.");return}if(!terms){setError("Vous devez accepter les conditions générales et la politique de confidentialité.");return}setBusy(true);try{const attribution=getRegistrationAttribution();const r=await fetch(`${api()}/auth/register`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({email:personal.email,password:personal.password,displayName:personal.displayName,kind:"PARTICULIER",referralCode:referralCode||undefined,acquisitionSource:attribution.source,acquisitionMedium:attribution.medium,acquisitionCampaign:attribution.campaign,acquisitionLandingPath:attribution.landingPath,returnPath:returnPath||undefined,onboardingWizard:true})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error??"signup_failed");trackSiteConversion("SIGN_UP_COMPLETED","sign_up",{method:"PARTICULIER",verification_required:Boolean(p.verificationRequired)});setVerificationRequired(Boolean(p.verificationRequired));setSuccessTarget(p.nextAfterVerification||(returnPath||"/mon-compte"));go("success")}catch(e){setError(errorText(e instanceof Error?e.message:"signup_failed"))}finally{setBusy(false)}}
 function continueProAccount(e:FormEvent){e.preventDefault();setError("");if(pro.password!==pro.confirm){setError("Les mots de passe ne correspondent pas.");return}go("store")}
 async function submitPro(e:FormEvent){e.preventDefault();setError("");if(!company){go("siret");setError("Vérifiez d’abord votre SIRET.");return}if(!terms){setError("Vous devez accepter les conditions générales et la politique de confidentialité.");return}setBusy(true);try{const acquisition=new URLSearchParams(window.location.search);const attribution=getRegistrationAttribution();const r=await fetch(`${api()}/auth/register/pro`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({email:pro.email,password:pro.password,displayName:pro.displayName,phone:pro.phone||undefined,legalName:company.legalName||store.name,tradeName:company.tradeName||undefined,siren:company.siren,siret:company.siret||siret,city:company.headquartersCity||store.city,postalCode:company.headquartersPostalCode||store.postalCode,storeName:store.name,storeCity:store.city,storePostalCode:store.postalCode,planCode:selectedPlan??undefined,referralCode:referralCode||undefined,sector:proSector||acquisition.get("sector")||undefined,utmSource:acquisition.get("utm_source")||undefined,utmMedium:acquisition.get("utm_medium")||undefined,utmCampaign:acquisition.get("utm_campaign")||undefined,utmContent:acquisition.get("utm_content")||undefined,acquisitionSource:attribution.source,acquisitionMedium:attribution.medium,acquisitionCampaign:attribution.campaign,acquisitionLandingPath:attribution.landingPath,returnPath:returnPath||undefined,onboardingWizard:true})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error??"signup_failed");setTrial(p.trial??null);trackSiteConversion("SIGN_UP_COMPLETED","sign_up",{method:"PROFESSIONNEL",verification_required:Boolean(p.verificationRequired),plan:selectedPlan??p.trial?.planCode??"NONE",trial_started:Boolean(p.trial),trial_days:p.trial?.days??0});if(p.trial)trackSiteConversion("PRO_TRIAL_STARTED","pro_trial_started",{plan:p.trial?.planCode??selectedPlan??"PROFESSIONAL",trial_days:p.trial?.days??90,sector:proSector||acquisition.get("sector")||"general",value:0,currency:"EUR"});setVerificationRequired(Boolean(p.verificationRequired));setSuccessTarget(p.nextAfterVerification||(returnPath||(selectedPlan?`/espace-pro/abonnement?plan=${encodeURIComponent(selectedPlan)}`:"/espace-pro")));go("success")}catch(e){setError(errorText(e instanceof Error?e.message:"signup_failed"))}finally{setBusy(false)}}
 return <div className={styles.page}><main className={`${styles.main} ${styles.wizardMain}`}><div className={styles.wizardFrame}><section className={styles.wizardShell}>
   <div className={styles.wizardTop}><div><span className={styles.eyebrow}>Créer un compte</span><h1>{kind==="PROFESSIONNEL"?"Votre activité, prête en quelques étapes.":kind==="PARTICULIER"?"Votre compte personnel, simplement.":"Comment souhaitez-vous utiliser Petit Annonces ?"}</h1></div>{step!=="choice"&&step!=="success"&&<button type="button" className={styles.wizardReset} onClick={()=>{setDirection("back");setStep("choice");setKind(null);setCompany(null);setError("")}}>Changer de type</button>}</div>
   {kind&&<div className={styles.wizardProgress}>{steps.map((x,i)=><div key={x} className={i<=current?styles.wizardProgressActive:""}><i>{i<current?"✓":i+1}</i><span>{x}</span></div>)}</div>}
   {error&&<div className={styles.error}>{error}</div>}
   <div key={step} className={`${styles.wizardStage} ${direction==="forward"?styles.slideForward:styles.slideBack}`}>
   {step==="choice"&&<div className={styles.accountChoices}><button onClick={()=>choose("PARTICULIER")}><span><AppIcon name="user"/></span><div><small>Compte personnel</small><h2>Particulier</h2><p>Pour acheter, vendre ponctuellement, discuter et gérer vos favoris.</p><b>Continuer comme particulier →</b></div></button><button onClick={()=>choose("PROFESSIONNEL")}><span><AppIcon name="briefcase"/></span><div><small>Compte professionnel</small><h2>Professionnel</h2><p>Pour une entreprise avec SIRET, boutique publique et outils professionnels.</p><b>Créer mon espace Pro →</b></div></button></div>}
   {step==="particular"&&<form className={styles.wizardCard} onSubmit={submitPersonal}><div className={styles.wizardCardHead}><span><AppIcon name="user"/></span><div><h2>Vos informations</h2><p>Ces informations servent à créer votre espace personnel.</p></div></div>{oauthGoogle&&<><a className={styles.socialButton} href={`${api()}/auth/oauth/google/start?next=${encodeURIComponent(returnPath||"/mon-compte")}`}><span className={styles.googleMark}>G</span><b>Continuer avec Google</b></a><p className={styles.socialNote}>En continuant avec Google, vous acceptez les <a href="/conditions-generales">conditions générales</a> et la <a href="/confidentialite">politique de confidentialité</a>.</p><div className={styles.divider}>ou avec votre e-mail</div></>}<label className={styles.field}>Nom affiché<input value={personal.displayName} onChange={e=>setPersonal(v=>({...v,displayName:e.target.value}))} minLength={2} required autoFocus/></label><label className={styles.field}>Adresse e-mail<input type="email" autoComplete="email" value={personal.email} onChange={e=>setPersonal(v=>({...v,email:e.target.value}))} required/></label><div className={styles.twoCols}><label className={styles.field}>Mot de passe<input type="password" autoComplete="new-password" minLength={10} value={personal.password} onChange={e=>setPersonal(v=>({...v,password:e.target.value}))} required/></label><label className={styles.field}>Confirmer<input type="password" autoComplete="new-password" minLength={10} value={personal.confirm} onChange={e=>setPersonal(v=>({...v,confirm:e.target.value}))} required/></label></div><label className={styles.check}><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>J’accepte les <a className={styles.inlineLink} href="/conditions-generales">conditions générales</a> et la <a className={styles.inlineLink} href="/confidentialite">politique de confidentialité</a>.</span></label><button className={styles.primary} disabled={busy}>{busy?"Création du compte…":"Créer mon compte"}</button></form>}
   {step==="siret"&&<div className={styles.wizardCard}><div className={styles.wizardCardHead}><span><AppIcon name="user-shield"/></span><div><h2>Vérifiez votre entreprise</h2><p>Saisissez uniquement votre SIRET. Les données officielles seront récupérées automatiquement.</p></div></div><label className={styles.field}>Numéro SIRET<input inputMode="numeric" autoFocus maxLength={14} value={siret} onChange={e=>{setSiret(e.target.value.replace(/\D/g,"").slice(0,14));setCompany(null)}} placeholder="14 chiffres"/></label><button type="button" className={styles.primary} disabled={lookupBusy||siret.length!==14} onClick={()=>void verifySiret()}>{lookupBusy?"Vérification auprès du registre…":"Vérifier mon SIRET"}</button>{company&&<div className={styles.companyVerified}><span><AppIcon name="circle-check"/></span><div><small>Entreprise vérifiée</small><strong>{company.tradeName||company.legalName}</strong><p>{[company.headquartersAddress,company.headquartersPostalCode,company.headquartersCity].filter(Boolean).join(" · ")}</p><em>SIRET {company.siret||siret}{company.nafCode?` · NAF ${company.nafCode}`:""}</em></div></div>}{company&&<button type="button" className={styles.primary} onClick={()=>go("pro-account")}>Continuer avec cette entreprise</button>}</div>}
   {step==="pro-account"&&<form className={styles.wizardCard} onSubmit={continueProAccount}><div className={styles.wizardCardHead}><span><AppIcon name="briefcase"/></span><div><h2>Vos identifiants</h2><p>Les informations légales ont déjà été remplies grâce au SIRET.</p></div></div><div className={styles.companyMini}><b>{company?.tradeName||company?.legalName}</b><span>SIRET {company?.siret||siret} · vérifié</span></div><label className={styles.field}>Nom du responsable<input value={pro.displayName} onChange={e=>setPro(v=>({...v,displayName:e.target.value}))} minLength={2} required autoFocus/></label><div className={styles.twoCols}><label className={styles.field}>E-mail professionnel<input type="email" autoComplete="email" value={pro.email} onChange={e=>setPro(v=>({...v,email:e.target.value}))} required/></label><label className={styles.field}>Téléphone <small>(facultatif)</small><input value={pro.phone} onChange={e=>setPro(v=>({...v,phone:e.target.value}))}/></label></div><div className={styles.twoCols}><label className={styles.field}>Mot de passe<input type="password" minLength={10} autoComplete="new-password" value={pro.password} onChange={e=>setPro(v=>({...v,password:e.target.value}))} required/></label><label className={styles.field}>Confirmer<input type="password" minLength={10} autoComplete="new-password" value={pro.confirm} onChange={e=>setPro(v=>({...v,confirm:e.target.value}))} required/></label></div><div className={styles.wizardActions}><button type="button" className={styles.secondary} onClick={()=>go("siret")}>Retour</button><button className={styles.primary}>Continuer</button></div></form>}
   {step==="store"&&<form className={styles.wizardCard} onSubmit={submitPro}><div className={styles.wizardCardHead}><span><AppIcon name="store"/></span><div><h2>Créez votre boutique</h2><p>Votre vitrine publique sera créée avec votre compte Pro. Vous pourrez ajouter logo et couverture ensuite.</p></div></div><label className={styles.field}>Activité principale<select value={proSector} onChange={e=>setProSector(e.target.value as ProSectorChoice)} required autoFocus><option value="">Choisir votre activité</option><option value="automobile">Automobile / garage / concession</option><option value="immobilier">Immobilier / agence</option><option value="commerce">Commerce / high-tech / produits</option><option value="vacances">Hébergement / vacances</option><option value="services">Services professionnels</option><option value="autre">Autre activité</option></select><small>Votre Espace Pro sera adapté à cette activité.</small></label><label className={styles.field}>Nom de la boutique<input value={store.name} onChange={e=>setStore(v=>({...v,name:e.target.value}))} minLength={2} required/></label><div className={styles.twoCols}><label className={styles.field}>Ville<input value={store.city} onChange={e=>setStore(v=>({...v,city:e.target.value}))}/></label><label className={styles.field}>Code postal<input inputMode="numeric" value={store.postalCode} onChange={e=>setStore(v=>({...v,postalCode:e.target.value}))}/></label></div><div className={styles.storePreview}><span><AppIcon name="store"/></span><div><small>Votre vitrine</small><strong>{store.name||"Nom de votre boutique"}</strong><p>{store.city||company?.headquartersCity||"France"} · Entreprise SIRET vérifiée</p></div></div><label className={styles.check}><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>J’accepte les <a className={styles.inlineLink} href="/conditions-generales">conditions générales</a> et la <a className={styles.inlineLink} href="/confidentialite">politique de confidentialité</a>.</span></label><div className={styles.wizardActions}><button type="button" className={styles.secondary} onClick={()=>go("pro-account")}>Retour</button><button className={styles.primary} disabled={busy}>{busy?"Création de votre espace Pro…":"Créer mon compte Pro"}</button></div></form>}
   {step==="success"&&<div className={styles.signupSuccess}><span><AppIcon name="circle-check"/></span><h2>{verificationRequired?"Votre compte est presque prêt !":"Félicitations, votre compte est créé !"}</h2><p>{verificationRequired?"Un e-mail de vérification vient de vous être envoyé. Ouvrez le lien reçu pour activer votre compte et vous connecter.":kind==="PROFESSIONNEL"?"Votre entreprise a été vérifiée et votre boutique professionnelle est prête.":"Votre espace personnel Petit Annonces est prêt."}</p>{verificationRequired?<div className={styles.notice}>{kind==="PROFESSIONNEL"&&selectedPlan?`Votre choix ${selectedPlan} est conservé. Après validation de l’e-mail, vous arriverez directement sur l’abonnement sélectionné.`:kind==="PROFESSIONNEL"&&trial?`Vos ${trial.days} jours de la formule Professionnel sont réservés. Validez votre e-mail puis importez votre catalogue, sans carte bancaire ni prélèvement automatique.`:"L’accès au compte reste bloqué jusqu’à la validation de votre adresse e-mail."}</div>:<div className={styles.notice}>{kind==="PROFESSIONNEL"&&trial?`Vos ${trial.days} jours Professionnel sont actifs. Vous pouvez maintenant importer votre catalogue.`:"Votre compte est actif et prêt à être utilisé."}</div>}<a className={styles.primary} href={verificationRequired?"/connexion":successTarget}>{verificationRequired?"J’ai déjà vérifié mon e-mail":kind==="PROFESSIONNEL"?"Accéder à mon Espace Pro":"Accéder à mon compte"}</a><small>{verificationRequired?"Le lien reçu par e-mail activera automatiquement votre compte.":"Redirection automatique…"}</small></div>}
   </div>
   <p className={styles.footText}>Déjà membre ? <a href="/connexion">Se connecter</a></p>
  </section>
  <aside className={styles.wizardAside}>
   <div className={styles.asideGlow}/>
   <span className={styles.asideBadge}><AppIcon name="shield"/> Inscription sécurisée</span>
   <h2>{kind==="PROFESSIONNEL"?"Construisez une présence professionnelle crédible dès le départ.":kind==="PARTICULIER"?"Tout votre espace personnel, prêt à acheter et vendre.":"Un compte adapté à votre façon d’utiliser Petit Annonces."}</h2>
   <p>{kind==="PROFESSIONNEL"?"SIRET vérifié, boutique publique, messagerie, ventes et outils Pro réunis dans un même espace.":"Publiez, échangez, enregistrez vos favoris et suivez vos transactions depuis un espace simple et sécurisé."}</p>
   <div className={styles.asideFeatures}>
    <div><span><AppIcon name="circle-check"/></span><div><strong>{kind==="PROFESSIONNEL"?"SIRET vérifié":"Compte gratuit"}</strong><small>{kind==="PROFESSIONNEL"?"Données légales récupérées automatiquement":"Aucun abonnement nécessaire pour commencer"}</small></div></div>
    <div><span><AppIcon name={kind==="PROFESSIONNEL"?"store":"comments"}/></span><div><strong>{kind==="PROFESSIONNEL"?"Boutique professionnelle":"Messagerie intégrée"}</strong><small>{kind==="PROFESSIONNEL"?"Votre vitrine publique créée pendant l’inscription":"Discutez directement avec acheteurs et vendeurs"}</small></div></div>
    <div><span><AppIcon name="shield"/></span><div><strong>Confiance & sécurité</strong><small>Profil, modération et outils de protection Petit Annonces</small></div></div>
   </div>
   <div className={styles.asideTrust}>
    <div><b>1</b><span>compte unique</span></div>
    <div><b>FR</b><span>registre public</span></div>
    <div><b>24/7</b><span>accès à votre espace</span></div>
   </div>
   <div className={styles.asideFoot}><AppIcon name="lock"/><span>Vos données sont protégées et utilisées uniquement pour créer et sécuriser votre compte.</span></div>
  </aside>
 </div></main></div>
}
