import type { Metadata } from "next";
import { deepCatalog, findDeepCategory } from "@pa/types";
import { notFound, redirect } from "next/navigation";
import { CatalogFilterPanel } from "../../../components/catalog-filter-panel";
import { AppIcon } from "../../../components/app-icon";
import { MarketplaceListingCard } from "../../../components/marketplace-listing-card";
import { arrangePromotedFlow, type ListingPromotion } from "../../../lib/listing-promotions";
import styles from "./page.module.css";

export const revalidate=30;

type Props = { params: Promise<{ slug: string }>; searchParams: Promise<Record<string,string|string[]|undefined>> };
type TrailItem = { name: string; slug: string };
type CategoryNode={name:string;slug:string;domain:string;icon?:string;iconKey?:string|null;description?:string|null;filters?:Array<{key:string;label:string;unit?:string|null}>;children?:CategoryNode[]};
type FilterAttribute={key:string;label:string;type:"TEXT"|"NUMBER"|"SELECT"|"MULTISELECT"|"BOOLEAN"|"DATE";unit:string|null;options:Array<{value:string;label:string;count?:number}>;min?:number;max?:number;dependsOn?:string};
type ListingItem={id:string;slug:string|null;title:string|null;priceMinor:number|null;currency:string;city:string|null;publishedAt:string|null;createdAt:string;imageUrl:string|null;category:{name:string;slug:string;domain:string};vehicle?:{modelYear?:number|null;mileageKm?:number|null;fuel?:string|null}|null;property?:{surfaceM2?:number|null;rooms?:number|null;transactionType?:string|null}|null;commerce?:{securePaymentEnabled?:boolean;shippingEnabled?:boolean};sellerReputation?:{avatarUrl?:string|null;sellerName?:string|null;verified?:boolean;kind?:string;hasStore?:boolean;paymentReady?:boolean;reviewCount?:number;reviewAverage?:number|null;trust?:{reliableSeller?:boolean}};promotions?:ListingPromotion[]};
type ListingPayload={total:number;page?:number;limit?:number;items:ListingItem[]};
const PAGE_SIZE=25;
const SEO_COPY:Record<string,{title:string;description:string;intro:string;tips:string[];faq:Array<{q:string;a:string}>}>={
  vehicules:{title:"Véhicules d’occasion en France",description:"Trouvez des voitures, motos, utilitaires et véhicules d’occasion partout en France. Comparez les annonces de particuliers et professionnels sur Petit Annonces.",intro:"Achetez ou vendez un véhicule d’occasion partout en France. Retrouvez voitures, motos, utilitaires, camping-cars et pièces auto avec des critères adaptés pour comparer plus facilement les annonces.",tips:["Comparez le kilométrage, l’année et la motorisation avant de contacter le vendeur.","Privilégiez les annonces détaillées avec plusieurs photos et un historique clair.","Utilisez la ville et les filtres pour trouver les véhicules disponibles près de chez vous."],faq:[{q:"Comment trouver un véhicule d’occasion près de chez moi ?",a:"Utilisez la ville, le code postal et les filtres de la catégorie Véhicules pour afficher les annonces correspondant à votre zone."},{q:"Puis-je déposer gratuitement une annonce automobile ?",a:"Oui, les particuliers peuvent déposer leur annonce depuis le parcours de publication Petit Annonces, sous réserve des règles de modération du site."}]},
  motos:{title:"Petites annonces motos d’occasion en France",description:"Trouvez une moto d’occasion en France : motos, scooters, quads et deux-roues selon les annonces disponibles. Achetez ou vendez sur Petit Annonces.",intro:"Consultez les petites annonces de motos d’occasion disponibles en France. Comparez le modèle, l’année, le kilométrage, la cylindrée, l’état et le prix avant de contacter le vendeur, puis utilisez la localisation pour privilégier les offres proches de chez vous.",tips:["Vérifiez le kilométrage, l’entretien et les documents du véhicule avant tout déplacement.","Comparez les photos, l’état des pneus, des freins et les éventuels équipements inclus.","Utilisez la ville et les filtres pour cibler les motos disponibles près de chez vous."],faq:[{q:"Où trouver une moto d’occasion sur Petit Annonces ?",a:"La catégorie Motos regroupe les annonces actuellement disponibles. Utilisez la localisation et les filtres pour affiner les résultats."},{q:"Puis-je publier gratuitement une annonce de moto ?",a:"Oui, un particulier peut déposer une annonce de moto gratuitement, sous réserve des règles de publication et de modération de Petit Annonces."}]},
  immobilier:{title:"Immobilier en France : vente et location",description:"Consultez les annonces immobilières de vente et location en France : appartements, maisons, terrains et bureaux. Recherchez par ville sur Petit Annonces.",intro:"Découvrez les annonces immobilières disponibles à la vente ou à la location en France. Affinez votre recherche par ville, type de bien et critères utiles pour trouver un appartement, une maison, un terrain ou un local professionnel.",tips:["Vérifiez la surface, le nombre de pièces et la localisation du bien.","Pour une location, comparez le loyer et les informations énergétiques affichées.","Utilisez les pages par ville pour cibler directement le marché local qui vous intéresse."],faq:[{q:"Comment rechercher un logement dans une ville précise ?",a:"Choisissez la catégorie Immobilier puis utilisez la ville ou le code postal. Les pages locales regroupent les annonces disponibles dans la zone sélectionnée."},{q:"Les informations DPE sont-elles affichées ?",a:"Pour les biens concernés, Petit Annonces prévoit les informations de performance énergétique nécessaires dans le parcours immobilier."}]},
  "location-immobilier":{title:"Location immobilière en France : appartements et maisons",description:"Consultez les annonces de location immobilière en France : appartements, maisons et logements disponibles. Recherchez une location par ville sur Petit Annonces.",intro:"Trouvez un logement à louer parmi les annonces immobilières actuellement publiées sur Petit Annonces. Comparez le loyer, la surface, le nombre de pièces, la localisation et les informations utiles du bien avant de contacter l’annonceur.",tips:["Comparez le loyer, les charges et le dépôt de garantie lorsqu’ils sont indiqués.","Vérifiez la surface, le nombre de pièces, la localisation et les informations énergétiques applicables.","Ne versez jamais d’argent avant d’avoir vérifié l’annonce, l’identité de l’interlocuteur et les conditions de location."],faq:[{q:"Comment trouver un appartement ou une maison à louer ?",a:"Consultez la catégorie Location puis utilisez la ville, le code postal et les filtres immobiliers pour cibler les logements disponibles."},{q:"Puis-je publier une location immobilière sur Petit Annonces ?",a:"Oui, les annonces de location peuvent être publiées dans la catégorie Immobilier en renseignant les informations nécessaires sur le logement et sa localisation."}]},
  "high-tech":{title:"High-tech d’occasion en France",description:"Achetez et vendez du high-tech d’occasion en France : smartphones, ordinateurs, tablettes, TV, consoles, photo et audio. Annonces locales sur Petit Annonces.",intro:"Retrouvez du matériel high-tech neuf ou d’occasion proposé partout en France : smartphones, ordinateurs, consoles, téléviseurs, appareils photo et accessoires. Comparez l’état, les caractéristiques et la localisation avant achat.",tips:["Contrôlez l’état, la capacité, le modèle exact et les accessoires inclus.","Demandez des photos précises pour les appareils présentant des traces d’usage.","Pour les achats à distance, utilisez les options de transaction et de livraison disponibles."],faq:[{q:"Quels produits high-tech trouve-t-on sur Petit Annonces ?",a:"La catégorie regroupe notamment smartphones, ordinateurs, tablettes, téléviseurs, consoles, photo, vidéo, audio et accessoires."},{q:"Comment comparer plusieurs annonces ?",a:"Utilisez les sous-catégories, le prix, la ville et les caractéristiques indiquées dans chaque annonce pour réduire votre sélection."}]},
  "telephones-smartphones":{title:"Téléphones & smartphones d’occasion : petites annonces en France",description:"Trouvez des téléphones et smartphones d’occasion en France : iPhone, Samsung, Android et accessoires. Comparez prix, état et localisation sur Petit Annonces.",intro:"Consultez les petites annonces de téléphones et smartphones d’occasion en France. Comparez le modèle, la capacité, l’état, les accessoires, le prix et la localisation avant de contacter le vendeur.",tips:["Vérifiez le modèle exact, la capacité de stockage et l’état de la batterie.","Demandez si le téléphone est débloqué et si les accessoires sont inclus.","Contrôlez l’écran, les appareils photo, les connecteurs et les éventuelles traces d’usage."],faq:[{q:"Où trouver un smartphone d’occasion ?",a:"La catégorie Téléphones & smartphones regroupe les annonces actuellement disponibles. Utilisez la ville et les filtres pour trouver les offres proches de chez vous."},{q:"Puis-je vendre gratuitement mon téléphone ?",a:"Oui, les particuliers peuvent déposer gratuitement une annonce de téléphone avec des photos, le modèle, l’état et le prix."}]},
  "tablettes-liseuses":{title:"Tablettes & liseuses d’occasion : petites annonces en France",description:"Trouvez tablettes et liseuses d’occasion en France : iPad, tablettes Android et liseuses. Comparez état, capacité, prix et localisation sur Petit Annonces.",intro:"Parcourez les petites annonces de tablettes et liseuses d’occasion disponibles en France. Comparez la marque, le modèle, la capacité, l’état de l’écran, les accessoires et le prix avant de contacter le vendeur.",tips:["Vérifiez la capacité de stockage, l’autonomie et l’état de l’écran.","Demandez si le chargeur, le stylet ou la coque sont inclus.","Contrôlez le modèle exact et la compatibilité avec les applications ou accessoires recherchés."],faq:[{q:"Où trouver une tablette d’occasion ?",a:"La catégorie Tablettes & liseuses regroupe les annonces disponibles. Utilisez les filtres et la ville pour comparer les offres."},{q:"Puis-je vendre gratuitement une tablette ?",a:"Oui, les particuliers peuvent publier gratuitement une annonce avec le modèle, l’état, le prix et des photos claires."}]},
  "photo-video":{title:"Photo, audio & vidéo d’occasion : petites annonces en France",description:"Trouvez appareils photo, objectifs, vidéo et matériel audio d’occasion en France. Comparez les petites annonces sur Petit Annonces.",intro:"Consultez les petites annonces de matériel photo, audio et vidéo d’occasion en France. Comparez les références, l’état, les accessoires, le prix et la localisation avant de contacter le vendeur.",tips:["Vérifiez la référence exacte, l’état optique et les accessoires inclus.","Pour un appareil photo, demandez le nombre de déclenchements lorsque cette information est disponible.","Pour les objectifs et équipements audio, contrôlez la compatibilité avec votre matériel."],faq:[{q:"Quel matériel photo et vidéo trouve-t-on ?",a:"Selon les annonces publiées, vous pouvez trouver appareils photo, objectifs, accessoires, vidéo et matériel audio."},{q:"Comment comparer du matériel photo d’occasion ?",a:"Comparez la référence, l’état, les accessoires, la compatibilité, le prix et les photos fournies par le vendeur."}]},
  electromenager:{title:"Électroménager d’occasion : petites annonces en France",description:"Trouvez de l’électroménager d’occasion en France : réfrigérateurs, lave-linge, fours, lave-vaisselle et petits appareils sur Petit Annonces.",intro:"Parcourez les petites annonces d’électroménager d’occasion en France. Comparez les dimensions, l’état, la référence, l’ancienneté, le prix et la localisation avant de vous déplacer ou d’organiser la livraison.",tips:["Vérifiez les dimensions et l’espace disponible avant l’achat.","Demandez la référence, l’âge de l’appareil et son état de fonctionnement.","Pour un appareil volumineux, anticipez le retrait, le transport et l’accès au logement."],faq:[{q:"Quels appareils électroménagers peut-on trouver ?",a:"Selon les annonces publiées, vous pouvez trouver réfrigérateurs, lave-linge, lave-vaisselle, fours et autres appareils domestiques."},{q:"Comment acheter un électroménager d’occasion ?",a:"Comparez l’état, la référence, les dimensions et le prix, puis contactez le vendeur pour confirmer le fonctionnement et les modalités de remise."}]},
  "jeux-video":{title:"Petites annonces jeux vidéo d’occasion en France",description:"Trouvez des jeux vidéo d’occasion en France : PS5, PlayStation, Xbox, Nintendo Switch et jeux PC. Achetez ou vendez gratuitement sur Petit Annonces.",intro:"Parcourez les petites annonces de jeux vidéo d’occasion en France. Comparez la plateforme, l’édition, l’état, le prix et la localisation avant de contacter le vendeur.",tips:["Vérifiez la plateforme et la compatibilité avant l’achat.","Contrôlez l’état du disque, de la boîte ou du code lorsqu’il est mentionné.","Comparez les prix et privilégiez les annonces détaillées avec photos."],faq:[{q:"Où trouver des jeux vidéo d’occasion ?",a:"La catégorie Jeux vidéo regroupe les annonces disponibles pour consoles et PC. Utilisez la recherche et la localisation pour trouver les offres qui vous intéressent."},{q:"Puis-je vendre gratuitement un jeu vidéo ?",a:"Oui, les particuliers peuvent déposer gratuitement une annonce de jeu vidéo sur Petit Annonces, sous réserve des règles de publication."}]},
  "ordinateurs-portables":{title:"Petites annonces ordinateurs portables d’occasion",description:"Trouvez des ordinateurs portables d’occasion en France : PC portable, MacBook, Chromebook, ultrabook et PC gamer sur Petit Annonces.",intro:"Comparez les petites annonces d’ordinateurs portables d’occasion : PC, MacBook, Chromebook, ultrabook et modèles gamer. Vérifiez la configuration, l’état, l’autonomie et les accessoires avant achat.",tips:["Vérifiez le processeur, la mémoire RAM, le stockage et la taille d’écran.","Demandez l’état de la batterie et du chargeur lorsque l’information manque.","Comparez le modèle exact et l’état avant de choisir une annonce."],faq:[{q:"Comment choisir un ordinateur portable d’occasion ?",a:"Comparez la configuration, l’état, l’autonomie, les accessoires et le prix. Les sous-catégories permettent aussi de cibler MacBook, Chromebook, ultrabook ou PC gamer."},{q:"Peut-on vendre un ordinateur portable sur Petit Annonces ?",a:"Oui, vous pouvez publier une annonce en ajoutant le modèle, les caractéristiques, l’état, le prix et des photos claires."}]},
  "montres-bijoux":{title:"Petites annonces montres & bijoux d’occasion",description:"Achetez et vendez montres, bijoux et accessoires d’occasion en France. Comparez les petites annonces par prix, état et localisation sur Petit Annonces.",intro:"Découvrez les petites annonces de montres et bijoux d’occasion en France. Comparez les marques, matériaux, état, accessoires, prix et localisation avant de contacter le vendeur.",tips:["Demandez des photos détaillées du cadran, du bracelet, du fermoir ou du bijou.","Vérifiez les références, certificats ou accessoires lorsqu’ils sont annoncés.","Comparez plusieurs offres avant un achat de valeur."],faq:[{q:"Où trouver des montres et bijoux d’occasion ?",a:"Consultez la catégorie Montres & bijoux puis comparez les annonces disponibles selon le prix, l’état et la localisation."},{q:"Puis-je publier gratuitement une montre ou un bijou ?",a:"Oui, les particuliers peuvent déposer une annonce gratuitement en indiquant une description précise et des photos de l’article."}]},
  velos:{title:"Petites annonces vélos d’occasion en France",description:"Trouvez un vélo d’occasion en France : VTT, vélo de ville, route, enfant ou électrique. Comparez les annonces et vendez gratuitement sur Petit Annonces.",intro:"Consultez les petites annonces de vélos d’occasion en France. Comparez type de vélo, taille, état, équipements, prix et localisation pour trouver un vélo près de chez vous.",tips:["Vérifiez la taille du cadre, les freins, pneus et transmission.","Pour un vélo électrique, renseignez-vous sur la batterie et son autonomie.","Comparez l’état général et les équipements inclus avant de vous déplacer."],faq:[{q:"Où trouver un vélo ou un VTT d’occasion ?",a:"La catégorie Vélos regroupe les annonces actuellement publiées. Utilisez la ville et la recherche pour cibler les vélos disponibles près de chez vous."},{q:"Puis-je vendre gratuitement mon vélo ?",a:"Oui, vous pouvez déposer gratuitement une annonce de vélo avec des photos, un prix et une description précise."}]},
  "instruments-musique":{title:"Petites annonces instruments de musique d’occasion",description:"Trouvez guitares, pianos, claviers, batteries et instruments de musique d’occasion en France. Achetez ou vendez sur Petit Annonces.",intro:"Parcourez les petites annonces d’instruments de musique d’occasion en France : guitares, claviers, pianos, batteries et autres instruments disponibles selon les publications.",tips:["Précisez la marque, le modèle et l’état de l’instrument.","Pour un instrument amplifié, vérifiez les câbles, l’électronique et les accessoires.","Demandez des photos supplémentaires lorsque l’état n’est pas clairement visible."],faq:[{q:"Quels instruments d’occasion peut-on trouver ?",a:"Selon les annonces publiées, vous pouvez trouver guitares, claviers, pianos, batteries et autres instruments de musique."},{q:"Comment vendre un instrument de musique ?",a:"Publiez une annonce avec la marque, le modèle, l’état, le prix, la localisation et plusieurs photos claires."}]},
  "maison-jardin":{title:"Maison & jardin d’occasion en France",description:"Trouvez des meubles, de l’électroménager, de la décoration, du bricolage et des articles de jardin d’occasion partout en France sur Petit Annonces.",intro:"Equipez votre maison ou votre jardin grâce aux annonces locales de meubles, électroménager, décoration, bricolage et extérieur. La seconde main permet de trouver des articles utiles près de chez vous tout en favorisant le réemploi.",tips:["Vérifiez les dimensions avant d’acheter un meuble ou un appareil volumineux.","Comparez l’état et l’ancienneté de l’électroménager.","Privilégiez une remise adaptée pour les objets lourds ou encombrants."],faq:[{q:"Puis-je rechercher des meubles près de chez moi ?",a:"Oui. Sélectionnez la sous-catégorie souhaitée puis renseignez votre ville ou votre code postal pour consulter les annonces locales."},{q:"Quels articles sont inclus dans Maison & Jardin ?",a:"Vous y trouverez notamment meubles, électroménager, décoration, bricolage, jardin et équipements pour l’extérieur."}]},
  mode:{title:"Mode d’occasion en France",description:"Achetez et vendez vêtements, chaussures, sacs, montres, bijoux et accessoires de mode d’occasion en France sur Petit Annonces.",intro:"Donnez une seconde vie aux vêtements et accessoires grâce aux annonces de mode d’occasion. Recherchez vêtements femme et homme, chaussures, sacs, montres et bijoux selon vos besoins et votre localisation.",tips:["Indiquez la taille, la marque et l’état de l’article dans l’annonce.","Ajoutez des photos nettes des éventuels défauts ou signes d’usure.","Utilisez les sous-catégories pour accéder rapidement au type d’article recherché."],faq:[{q:"Peut-on vendre des vêtements d’occasion gratuitement ?",a:"Oui, les particuliers peuvent publier leurs articles de mode via le parcours de dépôt d’annonce, dans le respect des règles du site."},{q:"Comment trouver la bonne taille ?",a:"Consultez le titre, la description et les caractéristiques de chaque annonce et contactez le vendeur si une mesure manque."}]},
  "enfants-bebe":{title:"Petites annonces bébé, enfant & puériculture",description:"Trouvez poussettes, puériculture, jouets, vêtements bébé et enfant, sièges auto, mobilier et équipements d’occasion en France sur Petit Annonces.",intro:"Découvrez les petites annonces bébé, enfant et puériculture disponibles en France. Comparez poussettes, sièges auto, vêtements, jouets, mobilier et équipements selon l’état, le prix et la localisation.",tips:["Vérifiez l’état, les dimensions et la compatibilité des équipements avant achat.","Pour les sièges auto et articles de sécurité, contrôlez les références et l’historique d’utilisation.","Privilégiez des photos claires et une description précise pour les articles destinés aux enfants."],faq:[{q:"Où trouver des articles de puériculture d’occasion ?",a:"Consultez la catégorie Famille et ses sous-catégories Poussettes & puériculture, Équipement bébé, Sièges auto et Mobilier enfant."},{q:"Puis-je vendre gratuitement des articles pour bébé ?",a:"Oui, les particuliers peuvent déposer gratuitement une annonce avec des photos, un prix et une description précise, sous réserve des règles de publication."}]},
  emploi:{title:"Offres d’emploi en France",description:"Consultez des offres d’emploi et annonces de recrutement en France : commerce, transport, BTP, restauration, santé, informatique, administratif et services.",intro:"Explorez les offres d’emploi publiées sur Petit Annonces dans plusieurs secteurs d’activité en France. Recherchez une opportunité par métier, secteur et localisation, ou publiez une offre professionnelle adaptée à votre besoin.",tips:["Lisez attentivement le lieu, le métier et les conditions indiquées dans l’offre.","Ne transmettez jamais de données bancaires ou de paiement pour obtenir un emploi.","Utilisez les sous-catégories pour cibler rapidement votre secteur d’activité."],faq:[{q:"Quels secteurs d’emploi sont disponibles ?",a:"Les offres peuvent concerner notamment commerce, transport, BTP, hôtellerie-restauration, santé, informatique, administratif et services à la personne."},{q:"Comment rechercher un emploi localement ?",a:"Utilisez la ville ou le code postal dans la recherche afin de concentrer les résultats sur votre zone géographique."}]},
  services:{title:"Petites annonces de services en France",description:"Trouvez ou proposez des services près de chez vous : bâtiment, ménage, déménagement, informatique, cours, événementiel, beauté et bien-être.",intro:"Trouvez rapidement un prestataire ou proposez vos services localement. Les petites annonces de services regroupent bâtiment, ménage, transport, informatique, cours, événementiel, beauté et autres prestations de proximité.",tips:["Décrivez clairement la prestation, la zone d’intervention et les conditions proposées.","Comparez plusieurs profils ou offres lorsque le service nécessite un devis.","Évitez tout paiement hors cadre lorsqu’une situation vous paraît inhabituelle."],faq:[{q:"Quels types de services peut-on trouver ?",a:"Le site couvre notamment bâtiment, entretien, déménagement, informatique, cours, événementiel, beauté et bien-être."},{q:"Puis-je proposer mes services localement ?",a:"Oui. Choisissez la catégorie Services, décrivez votre prestation et renseignez la zone dans laquelle vous intervenez."}]},
  "services-menage-entretien":{title:"Ménage & entretien : services près de chez vous",description:"Trouvez ou proposez des services de ménage et d’entretien en France. Consultez les petites annonces locales sur Petit Annonces.",intro:"Consultez les annonces de ménage et d’entretien disponibles près de chez vous. Comparez la zone d’intervention, les prestations proposées et les informations indiquées avant de contacter un prestataire.",tips:["Vérifiez la zone d’intervention et le type de prestation proposé.","Demandez un détail clair des tâches et des conditions avant de convenir d’un rendez-vous.","Privilégiez les échanges via la messagerie de la plateforme lorsque cela est possible."],faq:[{q:"Comment trouver un service de ménage près de chez moi ?",a:"Utilisez la ville et la catégorie Ménage & entretien pour consulter les annonces disponibles dans votre zone."},{q:"Puis-je proposer un service de ménage ?",a:"Oui, vous pouvez publier une annonce de service en précisant la prestation et la zone dans laquelle vous intervenez."}]},
  "sports-loisirs":{title:"Sports & loisirs d’occasion en France",description:"Trouvez des petites annonces de sports et loisirs d’occasion en France : vélos, fitness, camping, instruments, équipements et objets de loisirs ou de collection.",intro:"Découvrez les annonces de sports et loisirs d’occasion publiées partout en France : vélos, fitness, randonnée, camping, instruments de musique et autres équipements de loisirs. Les objets de collection apparaissent lorsqu’ils sont disponibles, avec des annonces locales à comparer selon le prix et l’état.",tips:["Vérifiez l’état, les dimensions et les accessoires inclus avant d’acheter un équipement.","Pour les vélos et matériels techniques, demandez des précisions sur l’entretien et l’usage.","Utilisez la ville et les sous-catégories pour trouver les annonces disponibles près de chez vous."],faq:[{q:"Quels articles de sports et loisirs trouve-t-on sur Petit Annonces ?",a:"Selon les annonces disponibles, vous pouvez trouver vélos, matériel de fitness, camping, randonnée, instruments de musique, équipements sportifs et objets de loisirs ou de collection."},{q:"Comment trouver du matériel d’occasion près de chez moi ?",a:"Choisissez une sous-catégorie puis utilisez la ville ou le code postal pour afficher les annonces locales correspondant à votre recherche."}]},
  collection:{title:"Petites annonces objets de collection d’occasion en France",description:"Achetez et vendez des objets de collection d’occasion en France : objets vintage, souvenirs, miniatures, pièces et collections proposés par particuliers et professionnels.",intro:"Découvrez les petites annonces d’objets de collection d’occasion disponibles partout en France. Comparez le prix, l’état, les photos et la localisation pour trouver des objets vintage, souvenirs, miniatures ou pièces de collection près de chez vous ou à distance.",tips:["Comparez plusieurs annonces et les prix avant d’acheter un objet de collection.","Vérifiez l’état, l’authenticité annoncée et les éventuels défauts sur les photos.","Demandez des précisions au vendeur lorsque l’origine, la référence ou les dimensions de l’objet ne sont pas claires."],faq:[{q:"Où trouver des petites annonces d’objets de collection ?",a:"Consultez la catégorie Collection de Petit Annonces pour comparer les objets de collection d’occasion disponibles en France selon le prix, l’état et la localisation."},{q:"Comment acheter un objet de collection d’occasion à petit prix ?",a:"Comparez plusieurs annonces, l’état et les prix demandés, puis utilisez la localisation et les filtres disponibles pour repérer les offres qui correspondent à votre budget."},{q:"Peut-on vendre un objet de collection sur Petit Annonces ?",a:"Oui, vous pouvez publier une annonce dans la catégorie Collection en ajoutant des photos précises, un prix et une description détaillée de l’objet."}]},
  animaux:{title:"Petites annonces animaux et accessoires en France",description:"Consultez les petites annonces animaux en France : chiens, chats, chevaux, oiseaux, petits animaux, accessoires et services selon les règles applicables.",intro:"Retrouvez les petites annonces concernant les animaux et leurs accessoires partout en France. Les publications doivent respecter la réglementation applicable, le bien-être animal et les règles de modération de Petit Annonces.",tips:["Vérifiez les informations obligatoires et la conformité de l’annonce avant tout échange.","N’acceptez pas une transaction suspecte ou un transport non conforme au bien-être animal.","Utilisez la localisation pour privilégier des échanges responsables et adaptés."],faq:[{q:"Quelles annonces animales sont proposées ?",a:"Selon les règles applicables, la catégorie peut regrouper chiens, chats, chevaux, oiseaux, petits animaux et accessoires."},{q:"Les annonces sont-elles modérées ?",a:"Oui, Petit Annonces applique des règles de publication et peut contrôler les annonces avant leur mise en ligne."}]},
  chats:{title:"Petites annonces chats et accessoires en France",description:"Consultez les petites annonces liées aux chats en France : animaux et accessoires selon les publications disponibles et les règles applicables.",intro:"Retrouvez les annonces liées aux chats et à leurs accessoires disponibles sur Petit Annonces. Vérifiez toujours les informations obligatoires, l’origine, les conditions de cession et le respect des règles de bien-être animal avant tout échange.",tips:["Vérifiez que l’annonce contient les informations exigées par la réglementation applicable.","Privilégiez un échange responsable et posez toutes les questions nécessaires avant de vous déplacer.","Pour les accessoires, comparez les dimensions, l’état et la compatibilité avec votre animal."],faq:[{q:"Comment consulter les annonces de chats ?",a:"La catégorie Chats regroupe les publications actuellement disponibles. Utilisez la localisation pour voir les annonces proches de chez vous."},{q:"Les annonces concernant les chats sont-elles encadrées ?",a:"Oui. Les publications doivent respecter les règles applicables, les obligations d’information et la politique de modération de Petit Annonces."}]},
  "materiel-professionnel":{title:"Matériel professionnel d’occasion",description:"Achetez et vendez du matériel professionnel d’occasion : BTP, commerce, restauration, bureautique, industrie et atelier sur Petit Annonces.",intro:"Trouvez du matériel professionnel neuf ou d’occasion pour équiper une activité : chantier, commerce, restauration, bureau, industrie ou atelier. Comparez les caractéristiques techniques et la localisation des équipements disponibles.",tips:["Vérifiez les références, dimensions, puissance ou capacité de l’équipement.","Demandez l’historique d’entretien pour les machines et matériels techniques.","Prévoyez le transport ou l’enlèvement avant de finaliser un achat volumineux."],faq:[{q:"Quels équipements professionnels trouve-t-on ?",a:"La catégorie couvre notamment matériel BTP, commerce-restauration, bureautique, industrie et atelier."},{q:"Les professionnels peuvent-ils publier plusieurs annonces ?",a:"Oui, les comptes professionnels disposent d’outils adaptés pour gérer leurs annonces et leur vitrine selon leur formule."}]},
  agriculture:{title:"Matériel agricole et tracteurs d’occasion",description:"Trouvez tracteurs, matériel agricole et équipements d’élevage d’occasion en France. Consultez les annonces agricoles sur Petit Annonces.",intro:"Consultez des annonces de tracteurs, machines, équipements agricoles et matériel d’élevage disponibles en France. Comparez l’état, les caractéristiques et la localisation avant de prendre contact avec le vendeur.",tips:["Contrôlez les heures d’utilisation et l’entretien des machines motorisées.","Vérifiez la compatibilité des outils avec votre matériel existant.","Anticipez les contraintes de transport pour les équipements volumineux."],faq:[{q:"Peut-on trouver des tracteurs d’occasion ?",a:"Oui, la catégorie Agriculture comprend notamment tracteurs, matériel agricole et équipements liés à l’élevage."},{q:"Comment rechercher du matériel agricole près de chez moi ?",a:"Utilisez la ville ou le code postal pour limiter la recherche aux annonces publiées dans votre région ou à proximité."}]}
};
function categorySeo(slug:string,name:string,description?:string|null){const x=SEO_COPY[slug];return x??{title:`${name} : petites annonces en France`,description:description??`Découvrez les petites annonces ${name.toLowerCase()} partout en France sur Petit Annonces.`,intro:description??`Découvrez les annonces ${name.toLowerCase()} disponibles partout en France.`,tips:[],faq:[]};}
const SEO_H1:Record<string,string>={"jeux-video":"Petites annonces jeux vidéo","ordinateurs-portables":"Petites annonces ordinateurs portables","montres-bijoux":"Petites annonces montres & bijoux",velos:"Petites annonces vélos d’occasion",motos:"Petites annonces motos d’occasion",animaux:"Petites annonces animaux",chats:"Petites annonces chats","enfants-bebe":"Petites annonces bébé, enfant & puériculture",services:"Petites annonces de services","services-menage-entretien":"Services de ménage & entretien","instruments-musique":"Petites annonces instruments de musique",collection:"Petites annonces de collection",electromenager:"Petites annonces électroménager d’occasion","telephones-smartphones":"Petites annonces téléphones & smartphones","tablettes-liseuses":"Petites annonces tablettes & liseuses","photo-video":"Petites annonces photo, audio & vidéo"};
const GUIDE_LINKS:Record<string,Array<{href:string;label:string}>>={
  immobilier:[{href:"/blog/rediger-annonce-immobiliere",label:"Rédiger une annonce immobilière entre particuliers"},{href:"/blog/vendre-entre-particuliers",label:"Checklist de vente entre particuliers"}],
  "location-immobilier":[{href:"/blog/rediger-annonce-immobiliere",label:"Bien rédiger une annonce immobilière"}],
  "high-tech":[{href:"/blog/acheter-smartphone-occasion",label:"Acheter un smartphone d’occasion"},{href:"/blog/acheter-occasion-securite",label:"Acheter d’occasion en sécurité"}],
  "telephones-smartphones":[{href:"/blog/acheter-smartphone-occasion",label:"Checklist smartphone d’occasion"},{href:"/blog/acheter-occasion-securite",label:"Vérifications avant achat"}],
  collection:[{href:"/blog/vendre-objet-occasion",label:"Vendre un objet d’occasion"},{href:"/blog/acheter-occasion-securite",label:"Acheter d’occasion en sécurité"}],
  "maison-jardin":[{href:"/blog/vendre-objet-occasion",label:"Vendre un objet d’occasion"},{href:"/blog/rediger-annonce-efficace",label:"Rédiger une annonce efficace"}],
  mode:[{href:"/blog/vendre-objet-occasion",label:"Vendre d’occasion en ligne"}],
  vehicules:[{href:"/vendre-voiture",label:"Vendre une voiture d’occasion"},{href:"/blog/vendre-entre-particuliers",label:"Vendre entre particuliers"}]
};
const PRODUCT_LONGTAIL_LINKS:Record<string,Array<{href:string;label:string}>>={
  "high-tech":[{href:"/occasion/ps5",label:"PS5 d’occasion"},{href:"/occasion/xbox",label:"Xbox d’occasion"},{href:"/occasion/samsung-galaxy",label:"Samsung Galaxy"}],
  "jeux-video":[{href:"/occasion/ps5",label:"PS5 d’occasion"},{href:"/occasion/xbox",label:"Xbox d’occasion"}],
  consoles:[{href:"/occasion/ps5",label:"PS5 d’occasion"},{href:"/occasion/xbox",label:"Xbox d’occasion"}],
  "jeux-video-consoles":[{href:"/occasion/ps5",label:"PS5 d’occasion"},{href:"/occasion/xbox",label:"Xbox d’occasion"}],
  "samsung-galaxy":[{href:"/occasion/samsung-galaxy",label:"Toutes les annonces Samsung Galaxy"}],
};

const apiBase=()=> (process.env.API_INTERNAL_URL??process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000").replace(/\/$/,"");
async function liveCategoryTree():Promise<CategoryNode[]>{try{const r=await fetch(`${apiBase()}/categories/tree`,{next:{revalidate:300}});if(!r.ok)return deepCatalog as unknown as CategoryNode[];const p=await r.json() as {categories?:CategoryNode[]};return p.categories??[]}catch{return deepCatalog as unknown as CategoryNode[]}}
function findCategoryNode(slug:string,nodes:CategoryNode[]):CategoryNode|null{for(const node of nodes){if(node.slug===slug)return node;const child=findCategoryNode(slug,node.children??[]);if(child)return child}return null}
async function liveFilterAttributes(slug:string):Promise<FilterAttribute[]>{try{const r=await fetch(`${apiBase()}/categories/${encodeURIComponent(slug)}/filter-attributes`,{next:{revalidate:300}});if(!r.ok)return[];const p=await r.json() as {attributes?:FilterAttribute[]};return p.attributes??[]}catch{return[]}}
async function categoryListings(slug:string,page:number):Promise<ListingPayload>{try{const r=await fetch(`${apiBase()}/search?category=${encodeURIComponent(slug)}&page=${page}&limit=${PAGE_SIZE}`,{next:{revalidate:30}});if(!r.ok)return{total:0,page,limit:PAGE_SIZE,items:[]};return r.json()}catch{return{total:0,page,limit:PAGE_SIZE,items:[]}}}
async function categoryCities(slug:string):Promise<Array<{city:string;count:number}>>{try{const r=await fetch(`${apiBase()}/seo/category/${encodeURIComponent(slug)}/cities`,{next:{revalidate:900}});if(!r.ok)return[];const p=await r.json() as {cities?:Array<{city:string;count:number}>};return p.cities??[]}catch{return[]}}
function citySlug(city:string){return city.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function safeJsonLd(value:unknown){return JSON.stringify(value).replace(/</g,"\\u003c")}
function age(date:string|null){if(!date)return"Annonce récente";const ms=Date.now()-new Date(date).getTime();const h=Math.max(1,Math.floor(ms/3600000));if(h<24)return`Il y a ${h} h`;const d=Math.floor(h/24);return d===1?"Hier":`Il y a ${d} j`}
function findTrail(slug:string,nodes:CategoryNode[]=deepCatalog as unknown as CategoryNode[],trail:TrailItem[]=[]):TrailItem[]|null{for(const node of nodes){const next=[...trail,{name:node.name,slug:node.slug}];if(node.slug===slug)return next;const nested=findTrail(slug,node.children??[],next);if(nested)return nested}return null}
function pageHref(slug:string,page:number){return page<=1?`/categorie/${slug}`:`/categorie/${slug}?page=${page}`}

function seoSlug(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
async function longtailFacets(domain:string){try{if(domain==="VEHICLE"){const r=await fetch(`${apiBase()}/seo/vehicle-facets`,{next:{revalidate:300}});if(!r.ok)return[];const d=await r.json() as {makes:Array<{make:string;count:number;models:Array<{model:string;count:number}>}>};return d.makes.filter(x=>x.count>=3).slice(0,10).map(x=>({href:`/vehicules/${seoSlug(x.make)}`,label:`${x.make} d’occasion`,count:x.count,children:x.models.filter(m=>m.count>=3).slice(0,4).map(m=>({href:`/vehicules/${seoSlug(x.make)}/${seoSlug(m.model)}`,label:`${x.make} ${m.model}`,count:m.count}))}))}if(domain==="REAL_ESTATE"){const r=await fetch(`${apiBase()}/seo/property-facets`,{next:{revalidate:300}});if(!r.ok)return[];const d=await r.json() as {items:Array<{transactionType:string;city:string;count:number}>};return d.items.filter(x=>x.count>=3).slice(0,14).map(x=>({href:`/immobilier/${x.transactionType==="SALE"?"vente":"location"}/${seoSlug(x.city)}`,label:`${x.transactionType==="SALE"?"À vendre":"À louer"} à ${x.city}`,count:x.count,children:[]}))}return[]}catch{return[]}}

export async function generateMetadata({params,searchParams}:Props):Promise<Metadata>{const{slug}=await params;const query=await searchParams;const tree=await liveCategoryTree();const live=findCategoryNode(slug,tree);const fallback=findDeepCategory(slug);const category=live??(fallback as unknown as CategoryNode|null);if(!category)return{title:"Catégorie | Petit Annonces"};const page=Math.max(1,Number.parseInt(String(query.page??"1"),10)||1);const extraParams=Object.keys(query).filter(key=>key!=="page"&&query[key]!==undefined);const canonical=page>1?`/categorie/${slug}?page=${page}`:`/categorie/${slug}`;const seo=categorySeo(slug,category.name,fallback?.description??category.description);const inventory=await categoryListings(slug,page);const maxPage=Math.max(1,Math.ceil(inventory.total/PAGE_SIZE));const indexable=inventory.total>0&&page<=maxPage&&extraParams.length===0;return{title:`${seo.title}${page>1?` - Page ${page}`:""}`,description:seo.description,alternates:{canonical},robots:{index:indexable,follow:true},openGraph:{type:"website",url:canonical,title:seo.title,description:seo.description}}}

export default async function CategoryLandingPage({params,searchParams}:Props){
 const{slug}=await params;if(slug==="vacances")redirect("/vacances");const query=await searchParams;const tree=await liveCategoryTree();const live=findCategoryNode(slug,tree);const fallback=findDeepCategory(slug);const category=live??(fallback as unknown as CategoryNode|null);if(!category)notFound();
 const seo=categorySeo(category.slug,category.name,fallback?.description??category.description);
 const requestedPage=Math.max(1,Number.parseInt(String(query.page??"1"),10)||1);
 const trail=findTrail(slug,tree)??[{name:category.name,slug:category.slug}];const root=tree.find(item=>item.slug===trail[0]?.slug);const children=category.children??[];const productLongtailLinks=PRODUCT_LONGTAIL_LINKS[category.slug]??[];const guideLinks=GUIDE_LINKS[category.slug]??GUIDE_LINKS[trail[0]?.slug??""]??[{href:"/blog/rediger-annonce-efficace",label:"Rédiger une annonce efficace"},{href:"/blog/vendre-entre-particuliers",label:"Conseils entre particuliers"}];
 const [listings,cities,longtails,filters]=await Promise.all([categoryListings(category.slug,requestedPage),categoryCities(category.slug),longtailFacets(category.domain),liveFilterAttributes(category.slug)]);const totalPages=Math.max(1,Math.ceil(listings.total/PAGE_SIZE));const page=Math.min(requestedPage,totalPages);if(requestedPage!==page)redirect(pageHref(category.slug,page));const listingFlow=arrangePromotedFlow(listings.items);
 const start=listings.total?((page-1)*PAGE_SIZE)+1:0;const end=Math.min(page*PAGE_SIZE,listings.total);
 const canonical=`https://petitannonces.fr${pageHref(category.slug,page)}`;
 const breadcrumbJsonLd={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Accueil",item:"https://petitannonces.fr/"},...trail.map((item,index)=>({"@type":"ListItem",position:index+2,name:item.name,item:`https://petitannonces.fr/categorie/${item.slug}`}))]};
 const itemListJsonLd={"@context":"https://schema.org","@type":"ItemList",name:`${category.name} - annonces`,url:canonical,numberOfItems:listings.total,itemListElement:listingFlow.filter(({item})=>Boolean(item.slug)).map(({item},index)=>({"@type":"ListItem",position:start+index,url:`https://petitannonces.fr/annonce/${item.slug}`,name:item.title??item.category.name}))};
 const collectionJsonLd={"@context":"https://schema.org","@type":"CollectionPage",name:SEO_H1[category.slug]??`${category.name} : petites annonces`,url:canonical,description:seo.description,mainEntity:itemListJsonLd};
 const pagination=Array.from({length:totalPages},(_,i)=>i+1).filter(n=>n===1||n===totalPages||Math.abs(n-page)<=2);
 return <div className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(breadcrumbJsonLd)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(itemListJsonLd)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(collectionJsonLd)}}/><main className={styles.shell}>
  <nav className={styles.breadcrumb} aria-label="Fil d’Ariane"><a href="/">Accueil</a>{trail.map((item,index)=><span key={item.slug}> › {index===trail.length-1?item.name:<a href={`/categorie/${item.slug}`}>{item.name}</a>}</span>)}</nav>

  <section className={styles.hero}>
   <div className={styles.heroCopy}><p className={styles.eyebrow}>{root?.icon??"•"} Catégorie</p><h1>{SEO_H1[category.slug]??category.name}</h1><p>{seo.intro}</p></div>
   <form action="/recherche" className={styles.search}>
    <input type="hidden" name="category" value={category.slug}/>
    <div className={styles.searchField}><AppIcon name="search"/><input name="q" placeholder={`Que recherchez-vous dans ${category.name} ?`}/></div>
    <div className={styles.searchField}><AppIcon name="location"/><input name="city" placeholder="Ville ou code postal"/></div>
    <button type="submit"><AppIcon name="search"/>Rechercher</button>
   </form>
  </section>

  {children.length>0&&<section className={styles.categoryRailWrap} aria-label="Sous-catégories"><div className={styles.categoryRailLabel}><span>Sous-catégories</span><small>{children.length} choix</small></div><div className={styles.categoryRail}>{children.map(child=><a key={child.slug} href={`/categorie/${child.slug}`}><span>{child.name}</span><AppIcon name="chevron-right"/></a>)}</div></section>}

  {productLongtailLinks.length>0&&<section className={styles.categoryRailWrap} aria-label="Recherches populaires"><div className={styles.categoryRailLabel}><span>Recherches populaires</span><small>Occasion</small></div><div className={styles.categoryRail}>{productLongtailLinks.map(item=><a key={item.href} href={item.href}><span>{item.label}</span><AppIcon name="chevron-right"/></a>)}</div></section>}

  {filters.length>0&&<section className={`${styles.section} ${styles.filterSection}`}><div className={styles.sectionHead}><div><span>Affiner</span><h2>Critères utiles</h2><p>Les filtres disponibles s’adaptent automatiquement à cette catégorie.</p></div><small>{filters.length} filtres</small></div><div className={styles.filtergrid}>{filters.map((filter,index)=><span key={`${filter.key}-${index}`}>{filter.label}{filter.unit?` · ${filter.unit}`:""}</span>)}</div></section>}

  <div className={styles.mobileFilterWrap}><CatalogFilterPanel category={category.slug} initialCategoryTree={tree} initialAttributes={filters}/></div>

  <div className={styles.catalogLayout}>
   <aside className={styles.desktopFilterWrap}><CatalogFilterPanel category={category.slug} initialCategoryTree={tree} initialAttributes={filters}/></aside>
   <section className={`${styles.section} ${styles.listingSection}`}>
   <div className={styles.listingHeader}><div><span className={styles.listingEyebrow}>Annonces</span><h2>{category.name}</h2><p>{listings.total?`${start}–${end} sur ${listings.total} annonces`:`Aucune annonce publiée pour le moment.`}</p></div><a className={styles.advancedSearch} href={`/recherche?category=${encodeURIComponent(category.slug)}`}><AppIcon name="list"/>Filtres & tri</a></div>
   {!listings.items.length?<div className={styles.emptyListings}>Aucune annonce publiée dans cette catégorie pour le moment.</div>:<div className={styles.listingGrid}>{listingFlow.map(({item})=><MarketplaceListingCard key={item.id} item={item}/>)}</div>}
   {totalPages>1&&<nav className={styles.pagination} aria-label="Pagination des annonces"><a className={page<=1?styles.disabled:""} aria-disabled={page<=1} href={pageHref(category.slug,Math.max(1,page-1))}>← Précédent</a><div>{pagination.map((n,index)=>{const prev=pagination[index-1];return <span key={n}>{prev&&n-prev>1&&<i>…</i>}<a className={n===page?styles.activePage:""} aria-current={n===page?"page":undefined} href={pageHref(category.slug,n)}>{n}</a></span>})}</div><a className={page>=totalPages?styles.disabled:""} aria-disabled={page>=totalPages} href={pageHref(category.slug,Math.min(totalPages,page+1))}>Suivant →</a></nav>}
   </section>
  </div>

  {cities.some(x=>x.count>=3)&&<section className={styles.categoryRailWrap} aria-label="Annonces par ville"><div className={styles.categoryRailLabel}><span>Annonces par ville</span><small>Liens locaux populaires</small></div><div className={styles.categoryRail}>{cities.filter(x=>x.count>=3).map(x=><a key={x.city} href={`/c/${category.slug}/${citySlug(x.city)}`}><span>{category.name} à {x.city}</span><small>{x.count} annonce{x.count>1?"s":""}</small><AppIcon name="chevron-right"/></a>)}</div></section>}


  {longtails.length>0&&<section className={styles.section}><div className={styles.sectionHead}><div><span>Recherches populaires</span><h2>{category.domain==="VEHICLE"?"Marques et modèles d’occasion":"Immobilier par ville"}</h2><p>Accédez directement aux sélections qui contiennent réellement des annonces publiées.</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:10}}>{longtails.map((x:any)=><div key={x.href} style={{border:"1px solid #e7e7ee",borderRadius:16,background:"#fff",padding:14}}><a href={x.href} style={{display:"flex",justifyContent:"space-between",gap:10,color:"#252535",fontWeight:850,textDecoration:"none"}}><span>{x.label}</span><small style={{color:"#777887"}}>{x.count}</small></a>{x.children?.length>0&&<div style={{display:"flex",flexWrap:"wrap",gap:7,marginTop:10}}>{x.children.map((c:any)=><a key={c.href} href={c.href} style={{fontSize:11,padding:"6px 8px",borderRadius:999,background:"#f3f1ff",color:"#5b4cf0",textDecoration:"none",fontWeight:750}}>{c.label} · {c.count}</a>)}</div>}</div>)}</div></section>}

  {guideLinks.length>0&&<section className={styles.categoryRailWrap} aria-label="Guides utiles"><div className={styles.categoryRailLabel}><span>Guides utiles</span><small>Conseils pratiques</small></div><div className={styles.categoryRail}>{guideLinks.map(item=><a key={item.href} href={item.href}><span>{item.label}</span><AppIcon name="chevron-right"/></a>)}<a href="/observatoire"><span>Observatoire des petites annonces</span><AppIcon name="chevron-right"/></a></div></section>}

  {(seo.tips.length>0||seo.faq.length>0)&&<section className={styles.seoGuide} aria-label={`Guide ${category.name}`}><div className={styles.seoGuideIntro}><span>Bien choisir</span><h2>Conseils pour vos annonces {category.name.toLowerCase()}</h2><p>{seo.intro}</p>{seo.tips.length>0&&<ul>{seo.tips.map(t=><li key={t}><AppIcon name="circle-check"/><span>{t}</span></li>)}</ul>}</div>{seo.faq.length>0&&<div className={styles.seoFaq}><span>Questions fréquentes</span>{seo.faq.map(item=><details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</div>}<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"FAQPage",mainEntity:seo.faq.map(item=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))})}}/></section>}

  <section className={styles.seoCta} aria-label="Publier une annonce gratuite"><div><span>Publication gratuite</span><h2>Déposer une annonce gratuite dans {category.name}</h2><p>Publiez votre petite annonce gratuitement en France, ajoutez vos photos, votre prix et votre ville, puis laissez les acheteurs vous contacter directement sur Petit Annonces.</p></div><div className={styles.seoCtaActions}><a className={styles.seoCtaPrimary} href="/deposer-annonce-gratuite"><AppIcon name="plus"/>Déposer une annonce gratuite</a><a className={styles.seoCtaSecondary} href="/">Voir les petites annonces gratuites en France <AppIcon name="arrow-right"/></a></div></section>

  <section className={styles.trust}><div><i><AppIcon name="location"/></i><p><b>Recherche locale</b><span>Ville, code postal et distance.</span></p></div><div><i><AppIcon name="list"/></i><p><b>Filtres adaptés</b><span>Uniquement les critères utiles à cette catégorie.</span></p></div><div><i><AppIcon name="shield"/></i><p><b>Transaction sécurisée</b><span>Paiement, livraison et suivi lorsque disponibles.</span></p></div></section>
 </main></div>
}
