import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import { spawn } from "node:child_process";
import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { requireAdminRoles } from "./rbac.js";

const MBOX_PATH=process.env.ADMIN_INBOX_MBOX_PATH??"/var/mail/petitannonces";
const STATE_PATH=process.env.ADMIN_INBOX_STATE_PATH??"/var/www/petitannonces/shared/admin-inbox-state.json";
const INBOX_ADDRESS=(process.env.ADMIN_INBOX_ADDRESS??"info@petitannonces.fr").trim().toLowerCase();
const INBOX_ROLES=["SUPER_ADMIN","ADMIN","SUPPORT"] as const;

type InboxState={read:string[];deleted:string[]};
type MailMessage={id:string;from:string;to:string;replyTo:string;messageId:string|null;subject:string;date:string|null;preview:string;body:string;read:boolean};
type MimeText={plain:string;html:string};

function charsetOf(contentType:string){return /charset\s*=\s*"?([^";\s]+)/i.exec(contentType)?.[1]?.trim().toLowerCase()??"utf-8";}
function decodeBuffer(buffer:Buffer,charset:string){const normalized=charset.replace(/^utf8$/,"utf-8").replace(/^iso8859-1$/,"iso-8859-1");try{return new TextDecoder(normalized).decode(buffer)}catch{return buffer.toString("utf8")}}
function decodeQuotedPrintableBytes(input:string){const clean=input.replace(/=\r?\n/g,"");const bytes:number[]=[];for(let i=0;i<clean.length;i++){if(clean[i]==="="&&/^[0-9a-f]{2}$/i.test(clean.slice(i+1,i+3))){bytes.push(parseInt(clean.slice(i+1,i+3),16));i+=2;continue}const cp=clean.codePointAt(i)??32;const encoded=Buffer.from(String.fromCodePoint(cp),"utf8");bytes.push(...encoded);if(cp>0xffff)i++}return Buffer.from(bytes)}
function decodeTransfer(input:string,encoding:string,charset:string){const enc=encoding.trim().toLowerCase();if(enc==="base64"){try{return decodeBuffer(Buffer.from(input.replace(/\s+/g,""),"base64"),charset)}catch{return input}}if(enc==="quoted-printable")return decodeBuffer(decodeQuotedPrintableBytes(input),charset);return input;}
function decodeHeader(value:string){return value.replace(/=\?([^?]+)\?([bq])\?([^?]*)\?=/gi,(_all,charset,mode,data)=>{try{const bytes=String(mode).toLowerCase()==="b"?Buffer.from(String(data),"base64"):decodeQuotedPrintableBytes(String(data).replace(/_/g," "));return decodeBuffer(bytes,String(charset))}catch{return String(_all)}}).replace(/\?=\s+=\?/g,"?==?");}
function headersOf(raw:string){const idx=raw.search(/\r?\n\r?\n/);const head=idx>=0?raw.slice(0,idx):raw;const unfolded=head.replace(/\r?\n[ \t]+/g," ");const map=new Map<string,string>();for(const line of unfolded.split(/\r?\n/)){const i=line.indexOf(":");if(i>0)map.set(line.slice(0,i).trim().toLowerCase(),decodeHeader(line.slice(i+1).trim()));}return{map,body:idx>=0?raw.slice(idx).replace(/^\r?\n\r?\n/,""):""};}
function stripHtml(s:string){return s.replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<head[\s\S]*?<\/head>/gi," ").replace(/<br\s*\/?\s*>/gi,"\n").replace(/<\/p>/gi,"\n").replace(/<\/div>/gi,"\n").replace(/<li[^>]*>/gi,"• ").replace(/<\/li>/gi,"\n").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&#(\d+);/g,(_m,n)=>String.fromCodePoint(Number(n)||32)).replace(/[ \t]+/g," ").replace(/\n[ \t]+/g,"\n").replace(/\n{3,}/g,"\n\n").trim();}
function splitMultipart(body:string,boundary:string){const marker=`--${boundary}`;return body.split(marker).slice(1).map(part=>part.replace(/^\r?\n/,"")).filter(part=>{const t=part.trim();return Boolean(t)&&t!=="--"&&!t.startsWith("--\r")&&!t.startsWith("--\n")});}
function parseMime(map:Map<string,string>,body:string,depth=0):MimeText{if(depth>8)return{plain:"",html:""};const contentType=map.get("content-type")??"text/plain; charset=utf-8";const lower=contentType.toLowerCase();const disposition=(map.get("content-disposition")??"").toLowerCase();if(disposition.includes("attachment"))return{plain:"",html:""};if(lower.includes("multipart/")){const boundary=/boundary\s*=\s*"?([^";]+)"?/i.exec(contentType)?.[1];if(!boundary)return{plain:"",html:""};let plain="",html="";for(const part of splitMultipart(body,boundary)){const parsed=headersOf(part);const nested=parseMime(parsed.map,parsed.body,depth+1);if(!plain&&nested.plain.trim())plain=nested.plain;if(!html&&nested.html.trim())html=nested.html;if(plain&&html)break}return{plain,html};}if(lower.includes("message/rfc822")){const nested=headersOf(body);return parseMime(nested.map,nested.body,depth+1)}const decoded=decodeTransfer(body,map.get("content-transfer-encoding")??"",charsetOf(contentType)).trim();if(lower.includes("text/plain"))return{plain:decoded,html:""};if(lower.includes("text/html"))return{plain:"",html:stripHtml(decoded)};return{plain:"",html:""};}
function extractBody(map:Map<string,string>,body:string){const parsed=parseMime(map,body);const text=(parsed.plain.trim()||parsed.html.trim()||"(Contenu non textuel)").replace(/\u0000/g,"");return text.slice(0,50000);}
function splitMbox(raw:string){const normalized=raw.startsWith("From ")?raw:`From local\n${raw}`;return normalized.split(/\n(?=From [^\n]+\n)/).map(x=>x.replace(/^From [^\n]*\n/,"")).filter(Boolean);}
function extractEmail(value:string){const angle=/<([^<>\s]+@[^<>\s]+)>/.exec(value)?.[1];const bare=/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i.exec(value)?.[0];return (angle??bare??"").trim().toLowerCase();}
function encodeHeader(value:string){return `=?UTF-8?B?${Buffer.from(value,"utf8").toString("base64")}?=`;}
function cleanHeader(value:string){return value.replace(/[\r\n]+/g," ").trim();}
function sendReply(args:{to:string;subject:string;body:string;inReplyTo?:string|null}){return new Promise<void>((resolve,reject)=>{const refs=args.inReplyTo?cleanHeader(args.inReplyTo):"";const message=[`From: Petit Annonces <${INBOX_ADDRESS}>`,`To: ${cleanHeader(args.to)}`,`Subject: ${encodeHeader(cleanHeader(args.subject))}`,`Date: ${new Date().toUTCString()}`,`Message-ID: <pa-${Date.now()}-${Math.random().toString(16).slice(2)}@petitannonces.fr>`,refs?`In-Reply-To: ${refs}`:"",refs?`References: ${refs}`:"","MIME-Version: 1.0","Content-Type: text/plain; charset=UTF-8","Content-Transfer-Encoding: base64","",Buffer.from(args.body,"utf8").toString("base64"),""].filter(Boolean).join("\r\n");const child=spawn("/usr/sbin/sendmail",["-i","-f",INBOX_ADDRESS,"-t"],{stdio:["pipe","ignore","pipe"]});let stderr="";child.stderr.setEncoding("utf8");child.stderr.on("data",chunk=>stderr+=chunk);child.on("error",reject);child.on("close",code=>code===0?resolve():reject(new Error(`sendmail_${code}_${stderr.slice(0,300)}`)));child.stdin.end(message);});}
function normalizedState(value:unknown):InboxState{const x=(value&&typeof value==="object"?value:{}) as {read?:unknown;deleted?:unknown};return{read:Array.isArray(x.read)?[...new Set(x.read.filter((id):id is string=>typeof id==="string"))].slice(-3000):[],deleted:Array.isArray(x.deleted)?[...new Set(x.deleted.filter((id):id is string=>typeof id==="string"))].slice(-3000):[]}}
async function loadState():Promise<InboxState>{try{return normalizedState(JSON.parse(await fs.readFile(STATE_PATH,"utf8")))}catch{return{read:[],deleted:[]}}}
async function saveState(state:InboxState){await fs.mkdir(STATE_PATH.slice(0,STATE_PATH.lastIndexOf("/")),{recursive:true});await fs.writeFile(STATE_PATH,JSON.stringify(normalizedState(state)),{mode:0o600});}
async function readMessages(includeDeleted=false){let raw="";try{raw=await fs.readFile(MBOX_PATH,"utf8")}catch{return[] as MailMessage[]}const state=await loadState();const deleted=new Set(state.deleted);const messages:MailMessage[]=[];for(const chunk of splitMbox(raw).slice(-300)){const {map,body}=headersOf(chunk);const text=extractBody(map,body);const rawMessageId=map.get("message-id")??null;const stable=rawMessageId??createHash("sha256").update(chunk).digest("hex");const id=createHash("sha256").update(stable).digest("hex").slice(0,32);if(!includeDeleted&&deleted.has(id))continue;const from=map.get("from")??"Expéditeur inconnu";const replyTo=extractEmail(map.get("reply-to")??from);messages.push({id,from,to:map.get("to")??INBOX_ADDRESS,replyTo,messageId:rawMessageId,subject:map.get("subject")??"(Sans objet)",date:map.get("date")??null,preview:text.replace(/\s+/g," ").slice(0,180),body:text,read:state.read.includes(id)});}return messages.reverse();}

export async function registerAdminInboxRoutes(app:FastifyInstance){
 app.get("/admin/inbox",{preHandler:requireAdminRoles([...INBOX_ROLES])},async()=>{const messages=await readMessages();return{address:INBOX_ADDRESS,messages,unread:messages.filter(x=>!x.read).length};});
 app.post("/admin/inbox/:id/read",{preHandler:requireAdminRoles([...INBOX_ROLES])},async(request,reply)=>{const id=String((request.params as {id?:string}).id??"");const messages=await readMessages();if(!messages.some(x=>x.id===id))return reply.code(404).send({error:"message_not_found"});const state=await loadState();if(!state.read.includes(id)){state.read.push(id);await saveState(state);}return{ok:true};});
 app.delete("/admin/inbox/:id",{preHandler:requireAdminRoles([...INBOX_ROLES])},async(request,reply)=>{const id=String((request.params as {id?:string}).id??"");const messages=await readMessages(true);if(!messages.some(x=>x.id===id))return reply.code(404).send({error:"message_not_found"});const state=await loadState();if(!state.deleted.includes(id))state.deleted.push(id);state.read=state.read.filter(item=>item!==id);await saveState(state);return reply.code(204).send();});
 app.post("/admin/inbox/:id/reply",{preHandler:requireAdminRoles([...INBOX_ROLES])},async(request,reply)=>{const id=String((request.params as {id?:string}).id??"");const parsed=z.object({body:z.string().trim().min(1).max(20000)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"invalid_reply"});const messages=await readMessages();const original=messages.find(x=>x.id===id);if(!original)return reply.code(404).send({error:"message_not_found"});if(!original.replyTo||!z.string().email().safeParse(original.replyTo).success)return reply.code(400).send({error:"invalid_recipient"});const subject=/^re\s*:/i.test(original.subject)?original.subject:`Re: ${original.subject}`;await sendReply({to:original.replyTo,subject,body:parsed.data.body,inReplyTo:original.messageId});return{ok:true,to:original.replyTo,from:INBOX_ADDRESS,subject};});
}
