import { createHash, randomUUID } from "node:crypto";
import { prisma } from "@pa/database";
import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { requireAdminRoles } from "./rbac.js";
import { getEmailProviderStatus, sendHostingerSmtpOnly } from "./email-provider.js";

const ROLES=["SUPER_ADMIN","ADMIN","MARKETING","SUPPORT"] as const;
const templateKey=z.enum(["AUTH_VERIFY_EMAIL","AUTH_PASSWORD_RESET","AUTH_WELCOME","AUTH_PASSWORD_CHANGED","LISTING_APPROVED","LISTING_REJECTED"]);
const settingsSchema=z.object({
 buttonLabel:z.string().trim().min(1).max(40).default("Continuer"),
 transactionalFooter:z.string().trim().min(5).max(320).default("Cet e-mail est nécessaire pour la sécurité ou l’accès à votre compte Petit Annonces."),
 generalFooter:z.string().trim().min(5).max(320).default("Vous recevez cet e-mail selon vos préférences de notification Petit Annonces."),
 templates:z.record(templateKey,z.object({enabled:z.boolean().default(true),subject:z.string().trim().min(3).max(160),body:z.string().trim().min(10).max(1200)})),
});
const DEFAULTS={buttonLabel:"Ouvrir Petit Annonces",transactionalFooter:"Message automatique lié à la sécurité ou au fonctionnement de votre compte Petit Annonces. Ne transmettez jamais vos codes ni vos mots de passe.",generalFooter:"Vous recevez cet e-mail selon vos préférences de notification Petit Annonces.",templates:{AUTH_VERIFY_EMAIL:{enabled:true,subject:"Confirmez votre adresse e-mail",body:"Bienvenue sur Petit Annonces. Confirmez votre adresse e-mail pour activer votre compte. Le lien est valable 24 heures."},AUTH_PASSWORD_RESET:{enabled:true,subject:"Réinitialisez votre mot de passe",body:"Une demande de réinitialisation de votre mot de passe a été reçue. Le lien est valable 30 minutes. Si vous n’êtes pas à l’origine de cette demande, ignorez cet e-mail."},AUTH_WELCOME:{enabled:true,subject:"Bienvenue sur Petit Annonces 🎉",body:"Votre adresse e-mail est confirmée et votre compte est maintenant actif. Un crédit de bienvenue de 5,00 € a été ajouté à votre compte pour les services Petit Annonces."},AUTH_PASSWORD_CHANGED:{enabled:true,subject:"Votre mot de passe a été modifié",body:"Le mot de passe de votre compte Petit Annonces vient d’être modifié et vos anciennes sessions ont été déconnectées. Si vous n’êtes pas à l’origine de cette action, contactez immédiatement le support."},LISTING_APPROVED:{enabled:true,subject:"Votre annonce est en ligne",body:"Bonne nouvelle : votre annonce a été validée par notre équipe et elle est maintenant visible sur Petit Annonces."},LISTING_REJECTED:{enabled:true,subject:"Mise à jour concernant votre annonce",body:"Votre annonce n’a pas pu être publiée dans son état actuel. Consultez votre espace personnel pour connaître la décision de modération et effectuer les corrections nécessaires."}}} as const;
let cache:{at:number;value:z.infer<typeof settingsSchema>}|null=null;
function sha(v:string){return createHash("sha256").update(v).digest("hex")}
async function actorId(request:any){const token=request.cookies?.pa_session;if(!token)return null;const row=await prisma.session.findUnique({where:{tokenHash:sha(token)},select:{userId:true,revokedAt:true,expiresAt:true}});return row&&!row.revokedAt&&row.expiresAt>new Date()?row.userId:null}
async function audit(request:any,action:string,entityId:string,metadata?:unknown){const actor=await actorId(request);if(!actor)return;await prisma.$executeRawUnsafe(`INSERT INTO "AdminAuditEvent" ("id","actorUserId","action","entityType","entityId","metadata") VALUES ($1,$2,$3,'NOTIFICATION',$4,$5::jsonb)`,randomUUID(),actor,action,entityId,metadata?JSON.stringify(metadata):null)}
async function load(){if(cache&&Date.now()-cache.at<15000)return cache.value;const rows=await prisma.$queryRawUnsafe<Array<{value:unknown}>>(`SELECT "value" FROM "AdminSetting" WHERE "key"='notification.settings' LIMIT 1`);const parsed=settingsSchema.safeParse(rows[0]?.value??DEFAULTS);const value=parsed.success?parsed.data:settingsSchema.parse(DEFAULTS);cache={at:Date.now(),value};return value}
async function save(value:z.infer<typeof settingsSchema>,request:any){const actor=await actorId(request);await prisma.$executeRawUnsafe(`INSERT INTO "AdminSetting" ("key","value","updatedByUserId","updatedAt") VALUES ('notification.settings',$1::jsonb,$2,CURRENT_TIMESTAMP) ON CONFLICT ("key") DO UPDATE SET "value"=EXCLUDED."value","updatedByUserId"=EXCLUDED."updatedByUserId","updatedAt"=CURRENT_TIMESTAMP`,JSON.stringify(value),actor);cache={at:Date.now(),value}}

export async function getNotificationPresentation(){return load()}
export async function managedTransactionalCopy(eventKind:string,fallback:{title:string;body:string}){const settings=await load();const key=templateKey.safeParse(eventKind);if(!key.success)return fallback;const t=settings.templates[key.data];return t?.enabled?{title:t.subject,body:t.body}:fallback}

export async function registerAdminNotificationRoutes(app:FastifyInstance){
 app.get("/admin/notifications/settings",{preHandler:requireAdminRoles([...ROLES])},async(_request,reply)=>reply.send({settings:await load()}));
 app.put("/admin/notifications/settings",{preHandler:requireAdminRoles([...ROLES])},async(request,reply)=>{const parsed=settingsSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"invalid_notification_settings",details:parsed.error.flatten()});await save(parsed.data,request);await audit(request,"NOTIFICATION_SETTINGS_UPDATED","notification.settings",{templates:Object.keys(parsed.data.templates)});return reply.send({saved:true,settings:parsed.data})});
 app.get("/admin/notifications/outbox",{preHandler:requireAdminRoles([...ROLES])},async(request,reply)=>{const q=z.object({status:z.enum(["PENDING","PROCESSING","SENT","FAILED"]).optional(),limit:z.coerce.number().int().min(10).max(200).default(100)}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:"invalid_request"});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT o."id",o."eventKind",o."channel",o."status",o."attempts",o."lastError",o."sentAt",o."createdAt",o."provider",o."providerMessageId",o."deliveryStatus",o."acceptedAt",o."deliveredAt",o."lastProviderEventAt",o."providerError",u."email",COALESCE(p."displayName",p."firstName",u."email") AS "userName" FROM "NotificationDeliveryOutbox" o JOIN "User" u ON u."id"=o."userId" LEFT JOIN "UserProfile" p ON p."userId"=u."id" WHERE ($1::text IS NULL OR o."status"=$1) ORDER BY o."createdAt" DESC LIMIT $2`,q.data.status??null,q.data.limit);const summary=await prisma.$queryRawUnsafe<Array<{status:string;channel:string;count:bigint}>>(`SELECT "status","channel",COUNT(*)::bigint AS count FROM "NotificationDeliveryOutbox" GROUP BY "status","channel" ORDER BY "status","channel"`);const delivery=await prisma.$queryRawUnsafe<Array<{deliveryStatus:string;count:bigint}>>(`SELECT COALESCE("deliveryStatus",'UNKNOWN') AS "deliveryStatus",COUNT(*)::bigint AS count FROM "NotificationDeliveryOutbox" WHERE "channel"='EMAIL' GROUP BY 1 ORDER BY 1`);return reply.send({items:rows,summary:summary.map(x=>({...x,count:Number(x.count)})),delivery:delivery.map(x=>({...x,count:Number(x.count)}))})});
 app.get("/admin/notifications/health",{preHandler:requireAdminRoles([...ROLES])},async(_request,reply)=>{const email=await getEmailProviderStatus();return reply.send({provider:email.primary,workerEnabled:process.env.NOTIFICATION_WORKER_ENABLED==="true",fromConfigured:email.fromConfigured,smtpConfigured:email.smtpConfigured})});
 app.post("/admin/notifications/outbox/:id/retry",{preHandler:requireAdminRoles([...ROLES])},async(request,reply)=>{const p=z.object({id:z.string().min(1)}).safeParse(request.params);if(!p.success)return reply.code(400).send({error:"invalid_request"});const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`UPDATE "NotificationDeliveryOutbox" SET "status"='PENDING',"attempts"=0,"availableAt"=CURRENT_TIMESTAMP,"lastError"=NULL,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=$1 AND "status"='FAILED' RETURNING "id"`,p.data.id);if(!rows[0])return reply.code(409).send({error:"notification_not_retryable"});await audit(request,"NOTIFICATION_RETRIED",p.data.id);return reply.send({queued:true})});
 app.post("/admin/integrations/hostinger-mail/test",{preHandler:requireAdminRoles(["SUPER_ADMIN","ADMIN"])},async(request,reply)=>{
 const actor=await actorId(request);if(!actor)return reply.code(401).send({error:"unauthorized"});
 const admin=await prisma.user.findUnique({where:{id:actor},select:{email:true}});
 const to=String(admin?.email??"").trim().toLowerCase();if(!to)return reply.code(409).send({error:"admin_email_missing"});
 try{
 const sent=await sendHostingerSmtpOnly({to,subject:"Test Hostinger Mail · Petit Annonces",text:"Le SMTP Hostinger de Petit Annonces fonctionne correctement.",html:`<!doctype html><html><body style="font-family:Arial,Helvetica,sans-serif"><h2>Petit Annonces</h2><p>Le SMTP Hostinger fonctionne correctement.</p></body></html>`});
 await audit(request,"HOSTINGER_SMTP_TEST_SENT","hostinger-mail",{provider:sent.provider});
 return reply.send({ok:true,provider:sent.provider,to});
 }catch(error){
 const detail=String(error instanceof Error?error.message:error).slice(0,220);
 return reply.code(detail==="hostinger_smtp_not_configured"?409:502).send({error:detail==="hostinger_smtp_not_configured"?"hostinger_smtp_not_configured":"hostinger_smtp_connection_failed",detail});
 }
 });
 app.post("/admin/notifications/test-email",{preHandler:requireAdminRoles([...ROLES])},async(request,reply)=>{const actor=await actorId(request);if(!actor)return reply.code(401).send({error:"unauthorized"});const body=z.object({subject:z.string().trim().min(3).max(160).default("Test Petit Annonces"),body:z.string().trim().min(5).max(1000).default("Ceci est un e-mail de test envoyé depuis le panneau d’administration.")}).safeParse(request.body);if(!body.success)return reply.code(400).send({error:"invalid_request"});await prisma.$executeRawUnsafe(`INSERT INTO "NotificationDeliveryOutbox" ("id","userId","notificationId","eventKind","channel","payload") VALUES ($1,$2,NULL,'ADMIN_TEST_EMAIL','EMAIL',$3::jsonb)`,randomUUID(),actor,JSON.stringify({title:body.data.subject,body:body.data.body,actionUrl:"/",metadata:{transactional:true,adminTest:true}}));await audit(request,"TEST_EMAIL_QUEUED","ADMIN_TEST_EMAIL");return reply.code(202).send({queued:true})});
}
