import { createHash, randomBytes } from "node:crypto";
import { hash, verify } from "@node-rs/argon2";
import { prisma } from "@pa/database";
import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { z } from "zod";
import { clearAuthRateLimit, enforceAuthRateLimit } from "./auth-rate-limit.js";
import { nativeVerificationActionUrl, queueAdminRoleEmail, queueTransactionalEmail, verificationActionUrl } from "./transactional-email.js";
import { createTwoFactorLoginChallenge, isTwoFactorEnabled, verifyTwoFactorLoginChallenge } from "./two-factor.js";
import { getSiteSettings } from "./admin-control.js";
import { grantWelcomeSiteCredit, WELCOME_SITE_CREDIT_MINOR } from "./site-credit.js";
import { applyReferralCodeForUser, rewardReferralAfterEmailVerification } from "./referrals.js";
import { recordUserRiskEvent } from "./risk-engine.js";
import { getBlockingSpamHold } from "./listing-content-policy.js";
import { recordRegistrationAcquisition } from "./registration-acquisition.js";


async function isLegacyMigratedUser(userId:string){
  try{
    const table=await prisma.$queryRawUnsafe<Array<{exists:boolean}>>(`SELECT to_regclass('public."LegacyMigrationLedger"') IS NOT NULL AS exists`);
    if(!table[0]?.exists)return false;
    const rows=await prisma.$queryRawUnsafe<Array<{found:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "LegacyMigrationLedger" WHERE "source"='flynax' AND "entityType"='user' AND "newId"=$1) AS found`,userId);
    return Boolean(rows[0]?.found);
  }catch{return false}
}
const SESSION_COOKIE="pa_session";const SESSION_TTL_MS=1000*60*60*24*30;const SESSION_SHORT_TTL_MS=1000*60*60*24;const EMAIL_TOKEN_TTL_MS=1000*60*60*24;
const EMAIL_VERIFICATION_REQUIRED=process.env.AUTH_EMAIL_VERIFICATION_REQUIRED!=="false";
const registerSchema=z.object({email:z.string().trim().toLowerCase().email(),password:z.string().min(10).max(128),displayName:z.string().trim().min(2).max(80).optional(),kind:z.enum(["PARTICULIER","PROFESSIONNEL"]).default("PARTICULIER"),referralCode:z.string().trim().min(4).max(40).optional(),acquisitionSource:z.string().trim().max(40).optional(),acquisitionMedium:z.string().trim().max(40).optional(),acquisitionCampaign:z.string().trim().max(160).optional(),acquisitionLandingPath:z.string().trim().max(300).optional(),returnPath:z.string().trim().max(500).optional(),onboardingWizard:z.boolean().optional().default(false)});
const loginSchema=z.object({email:z.string().trim().toLowerCase().email(),password:z.string().min(1).max(128),remember:z.boolean().default(true)});
function safeReturnPath(value:unknown){const v=typeof value==="string"?value.trim():"";return v.startsWith("/")&&!v.startsWith("//")?v:null}
function sha256(v:string){return createHash("sha256").update(v).digest("hex")}function newOpaqueToken(bytes=32){return randomBytes(bytes).toString("base64url")}
async function hashPassword(password:string){return hash(password,{algorithm:2,memoryCost:19456,timeCost:2,parallelism:1})}
async function createSessionToken(userId:string,request:FastifyRequest,remember=true){const token=newOpaqueToken();const expiresAt=new Date(Date.now()+(remember?SESSION_TTL_MS:SESSION_SHORT_TTL_MS));await prisma.session.create({data:{userId,tokenHash:sha256(token),userAgent:request.headers["user-agent"]?.slice(0,500),expiresAt}});return{token,expiresAt}}
export async function issueSession(userId:string,request:FastifyRequest,reply:FastifyReply,remember=true){const session=await createSessionToken(userId,request,remember);reply.setCookie(SESSION_COOKIE,session.token,{httpOnly:true,secure:request.protocol==="https",sameSite:"lax",path:"/",...(remember?{expires:session.expiresAt}:{})});return session}
function bearerToken(request:FastifyRequest){const value=request.headers.authorization;if(typeof value!=="string")return null;const match=/^Bearer\s+(.+)$/i.exec(value.trim());return match?.[1]?.trim()||null}
function requestSessionToken(request:FastifyRequest){return bearerToken(request)??request.cookies[SESSION_COOKIE]??null}
async function getCurrentUser(request:FastifyRequest){const token=requestSessionToken(request);if(!token)return null;const session=await prisma.session.findUnique({where:{tokenHash:sha256(token)},include:{user:{include:{profile:true,roles:true}}}});if(!session||session.revokedAt||session.expiresAt<=new Date()||session.user.status!=="ACTIVE")return null;return{session,user:session.user}}
async function issueVerificationEmail(userId:string,email:string,client:"WEB"|"NATIVE"="WEB",next?:string|null){const verificationToken=newOpaqueToken();await prisma.emailVerificationToken.updateMany({where:{userId,usedAt:null},data:{usedAt:new Date()}});await prisma.emailVerificationToken.create({data:{userId,tokenHash:sha256(verificationToken),expiresAt:new Date(Date.now()+EMAIL_TOKEN_TTL_MS)}});await queueTransactionalEmail({userId,eventKind:"AUTH_VERIFY_EMAIL",title:"Confirmez votre adresse e-mail",body:`Confirmez l’adresse ${email} pour activer votre compte Petit Annonces. Ce lien est valable 24 heures.`,actionUrl:client==="NATIVE"?nativeVerificationActionUrl(verificationToken):verificationActionUrl(verificationToken,next),metadata:{purpose:"EMAIL_VERIFICATION",client}});return verificationToken}
async function notifyAdminsNewRegistration(user:{id:string;email:string;kind:string;status:string},displayName:string|undefined,channel:"WEB"|"NATIVE"){
  const label=displayName?.trim()||user.email;
  return queueAdminRoleEmail({roles:["SUPER_ADMIN","ADMIN"],eventKind:"ADMIN_NEW_REGISTRATION",title:"Nouvelle inscription sur Petit Annonces",body:`Un nouveau membre vient de créer un compte : ${label} · ${user.email} · ${user.kind}. Statut : ${user.status}.`,actionUrl:`https://admin.petitannonces.fr/users?search=${encodeURIComponent(user.email)}`,metadata:{purpose:"ADMIN_NEW_REGISTRATION",userId:user.id,kind:user.kind,status:user.status,channel}});
}

export async function registerAuthRoutes(app:FastifyInstance){
 app.post("/auth/register",async(request,reply)=>{const site=await getSiteSettings();if(!site.allowRegistrations)return reply.code(503).send({error:"registrations_disabled"});const parsed=registerSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"invalid_request",details:parsed.error.flatten()});const blockedIp=await getBlockingSpamHold(request,null);if(blockedIp)return reply.code(423).send({error:"account_security_hold",redirect:"/compte-suspendu"});const{email,password,displayName,kind,referralCode,onboardingWizard}=parsed.data;const requestedReturn=safeReturnPath(parsed.data.returnPath);if(!await enforceAuthRateLimit({request,reply,action:"REGISTER",identity:email,limit:5,windowMs:60*60*1000}))return;const existing=await prisma.user.findUnique({where:{email}});if(existing)return reply.code(409).send({error:"email_already_registered"});const passwordHash=await hashPassword(password);const user=await prisma.user.create({data:{email,passwordHash,kind,status:EMAIL_VERIFICATION_REQUIRED?"PENDING_VERIFICATION":"ACTIVE",emailVerifiedAt:EMAIL_VERIFICATION_REQUIRED?null:new Date(),profile:{create:{displayName,locale:"fr-FR",countryCode:"FR"}}},select:{id:true,email:true,kind:true,status:true}});await applyReferralCodeForUser(user.id,referralCode);await recordRegistrationAcquisition({userId:user.id,accountKind:kind,source:parsed.data.acquisitionSource,medium:parsed.data.acquisitionMedium,campaign:parsed.data.acquisitionCampaign,landingPath:parsed.data.acquisitionLandingPath,channel:"WEB"}).catch(()=>undefined);await notifyAdminsNewRegistration(user,displayName,"WEB").catch(error=>request.log.warn({error,userId:user.id},"admin registration email queue failed"));if(EMAIL_VERIFICATION_REQUIRED){const verificationToken=await issueVerificationEmail(user.id,user.email,"WEB",requestedReturn);return reply.code(201).send({user,verificationRequired:true,authenticated:false,nextAfterVerification:requestedReturn??(onboardingWizard?"/bienvenue":"/connexion"),...(process.env.NODE_ENV!=="production"?{devVerificationToken:verificationToken}:{})})}const credit=await grantWelcomeSiteCredit(user.id);await issueSession(user.id,request,reply);return reply.code(201).send({user,verificationRequired:false,authenticated:true,welcomeCreditMinor:credit.grantedMinor,nextAfterVerification:requestedReturn??"/mon-compte"})});
 app.post("/auth/resend-verification",async(request,reply)=>{const body=z.object({email:z.string().trim().toLowerCase().email(),client:z.enum(["WEB","NATIVE"]).default("WEB")}).safeParse(request.body);if(!body.success)return reply.code(400).send({error:"invalid_request"});if(!EMAIL_VERIFICATION_REQUIRED)return reply.send({requested:false,verificationDisabled:true});if(!await enforceAuthRateLimit({request,reply,action:"RESEND_VERIFICATION",identity:body.data.email,limit:3,windowMs:15*60*1000,blockMs:15*60*1000}))return;const user=await prisma.user.findUnique({where:{email:body.data.email},select:{id:true,email:true,status:true,emailVerifiedAt:true}});if(user&&user.status==="PENDING_VERIFICATION"&&!user.emailVerifiedAt)await issueVerificationEmail(user.id,user.email,body.data.client);return reply.send({requested:true,cooldownSeconds:300})});
 app.post("/auth/verify-email",async(request,reply)=>{const body=z.object({token:z.string().min(20)}).safeParse(request.body);if(!body.success)return reply.code(400).send({error:"invalid_token"});if(!await enforceAuthRateLimit({request,reply,action:"VERIFY_EMAIL",limit:20,windowMs:15*60*1000}))return;const record=await prisma.emailVerificationToken.findUnique({where:{tokenHash:sha256(body.data.token)}});if(!record||record.usedAt||record.expiresAt<=new Date())return reply.code(400).send({error:"invalid_or_expired_token"});await prisma.$transaction(async tx=>{await tx.emailVerificationToken.update({where:{id:record.id},data:{usedAt:new Date()}});await tx.user.update({where:{id:record.userId},data:{status:"ACTIVE",emailVerifiedAt:new Date()}});await tx.$executeRawUnsafe(`UPDATE "Referral" SET "status"='QUALIFIED',"qualifiedAt"=COALESCE("qualifiedAt",CURRENT_TIMESTAMP) WHERE "referredUserId"=$1 AND "status"='PENDING'`,record.userId);const business=await tx.businessProfile.findUnique({where:{userId:record.userId},select:{verificationStatus:true}});if(business?.verificationStatus==="VERIFIED")await tx.store.updateMany({where:{ownerId:record.userId,status:"DRAFT"},data:{status:"ACTIVE",isVerified:true,publishedAt:new Date()}})});await rewardReferralAfterEmailVerification(record.userId).catch(()=>undefined);const credit=await grantWelcomeSiteCredit(record.userId);await queueTransactionalEmail({userId:record.userId,eventKind:"AUTH_WELCOME",title:"Bienvenue sur Petit Annonces 🎉",body:"Votre compte est actif. Un crédit de bienvenue de 5,00 € a été ajouté à votre compte, utilisable uniquement pour les services Petit Annonces.",actionUrl:"/mon-compte/portefeuille",metadata:{purpose:"WELCOME",welcomeCreditMinor:WELCOME_SITE_CREDIT_MINOR}});await issueSession(record.userId,request,reply,true);return reply.send({verified:true,authenticated:true,welcomeCreditMinor:credit.grantedMinor})});
 app.post("/auth/login",async(request,reply)=>{const parsed=loginSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"invalid_request"});if(!await enforceAuthRateLimit({request,reply,action:"LOGIN",identity:parsed.data.email,limit:20,windowMs:15*60*1000,blockMs:15*60*1000}))return;const user=await prisma.user.findUnique({where:{email:parsed.data.email}});if(!user)return reply.code(401).send({error:"invalid_credentials"});if(user.lockedUntil&&user.lockedUntil>new Date())return reply.code(423).send({error:"account_temporarily_locked"});const valid=await verify(user.passwordHash,parsed.data.password);if(!valid){if(await isLegacyMigratedUser(user.id))return reply.code(403).send({error:"password_reset_required"});const attempts=user.failedLoginAttempts+1;await prisma.user.update({where:{id:user.id},data:{failedLoginAttempts:attempts>=5?0:attempts,lockedUntil:attempts>=5?new Date(Date.now()+15*60*1000):null}});if(attempts>=3)await recordUserRiskEvent({userId:user.id,eventType:attempts>=5?"ACCOUNT_LOGIN_LOCK":"FAILED_LOGIN_BURST",weight:attempts>=5?10:4,metadata:{attempts,locked:attempts>=5}}).catch(()=>undefined);return reply.code(401).send({error:"invalid_credentials"})}if(user.status!=="ACTIVE")return reply.code(403).send({error:user.status==="PENDING_VERIFICATION"?"email_verification_required":"account_unavailable"});await prisma.user.update({where:{id:user.id},data:{failedLoginAttempts:0,lockedUntil:null}});if(await isTwoFactorEnabled(user.id)){const challengeToken=await createTwoFactorLoginChallenge(user.id);return reply.send({authenticated:false,twoFactorRequired:true,challengeToken,remember:parsed.data.remember,expiresInSeconds:300})}await prisma.user.update({where:{id:user.id},data:{lastLoginAt:new Date()}});await clearAuthRateLimit("LOGIN",request,parsed.data.email);await issueSession(user.id,request,reply,parsed.data.remember);return reply.send({authenticated:true})});
 app.post("/auth/2fa/complete",async(request,reply)=>{const body=z.object({challengeToken:z.string().min(20),code:z.string().trim().min(6).max(32),remember:z.boolean().default(true)}).safeParse(request.body);if(!body.success)return reply.code(400).send({error:"invalid_request"});if(!await enforceAuthRateLimit({request,reply,action:"LOGIN_2FA",limit:12,windowMs:15*60*1000,blockMs:15*60*1000}))return;const userId=await verifyTwoFactorLoginChallenge(body.data.challengeToken,body.data.code);if(!userId)return reply.code(401).send({error:"invalid_two_factor_code"});await prisma.user.update({where:{id:userId},data:{lastLoginAt:new Date(),failedLoginAttempts:0,lockedUntil:null}});await issueSession(userId,request,reply,body.data.remember);return reply.send({authenticated:true})});
 app.post("/auth/logout",async(request,reply)=>{const token=request.cookies[SESSION_COOKIE];if(token)await prisma.session.updateMany({where:{tokenHash:sha256(token),revokedAt:null},data:{revokedAt:new Date()}});reply.clearCookie(SESSION_COOKIE,{path:"/"});return reply.code(204).send()});
 app.get("/auth/me",async(request,reply)=>{const auth=await getCurrentUser(request);if(!auth)return reply.code(401).send({error:"unauthenticated"});return reply.send({user:{id:auth.user.id,email:auth.user.email,kind:auth.user.kind,profile:auth.user.profile,roles:auth.user.roles.map((entry:{role:string})=>entry.role)}})})

 // Native apps use bearer sessions stored in the OS secure credential store.
 app.post("/auth/mobile/register",async(request,reply)=>{const site=await getSiteSettings();if(!site.allowRegistrations)return reply.code(503).send({error:"registrations_disabled"});const parsed=registerSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"invalid_request",details:parsed.error.flatten()});const blockedIp=await getBlockingSpamHold(request,null);if(blockedIp)return reply.code(423).send({error:"account_security_hold"});const{email,password,displayName,kind,referralCode}=parsed.data;if(!await enforceAuthRateLimit({request,reply,action:"REGISTER",identity:email,limit:5,windowMs:60*60*1000}))return;const existing=await prisma.user.findUnique({where:{email}});if(existing)return reply.code(409).send({error:"email_already_registered"});const passwordHash=await hashPassword(password);const user=await prisma.user.create({data:{email,passwordHash,kind,status:EMAIL_VERIFICATION_REQUIRED?"PENDING_VERIFICATION":"ACTIVE",emailVerifiedAt:EMAIL_VERIFICATION_REQUIRED?null:new Date(),profile:{create:{displayName,locale:"fr-FR",countryCode:"FR"}}},select:{id:true,email:true,kind:true,status:true}});await applyReferralCodeForUser(user.id,referralCode);await recordRegistrationAcquisition({userId:user.id,accountKind:kind,source:parsed.data.acquisitionSource??"native",medium:parsed.data.acquisitionMedium??"app",campaign:parsed.data.acquisitionCampaign,landingPath:parsed.data.acquisitionLandingPath,channel:"NATIVE"}).catch(()=>undefined);await notifyAdminsNewRegistration(user,displayName,"NATIVE").catch(error=>request.log.warn({error,userId:user.id},"admin registration email queue failed"));if(EMAIL_VERIFICATION_REQUIRED){await issueVerificationEmail(user.id,user.email,"NATIVE");return reply.code(201).send({user,verificationRequired:true,authenticated:false})}const credit=await grantWelcomeSiteCredit(user.id);const nativeSession=await createSessionToken(user.id,request,true);return reply.code(201).send({user,verificationRequired:false,authenticated:true,sessionToken:nativeSession.token,expiresAt:nativeSession.expiresAt.toISOString(),welcomeCreditMinor:credit.grantedMinor})});

 app.post("/auth/mobile/verify-email",async(request,reply)=>{const body=z.object({token:z.string().min(20)}).safeParse(request.body);if(!body.success)return reply.code(400).send({error:"invalid_token"});if(!await enforceAuthRateLimit({request,reply,action:"VERIFY_EMAIL",limit:20,windowMs:15*60*1000}))return;const record=await prisma.emailVerificationToken.findUnique({where:{tokenHash:sha256(body.data.token)}});if(!record||record.usedAt||record.expiresAt<=new Date())return reply.code(400).send({error:"invalid_or_expired_token"});await prisma.$transaction(async tx=>{await tx.emailVerificationToken.update({where:{id:record.id},data:{usedAt:new Date()}});await tx.user.update({where:{id:record.userId},data:{status:"ACTIVE",emailVerifiedAt:new Date()}});await tx.$executeRawUnsafe(`UPDATE "Referral" SET "status"='QUALIFIED',"qualifiedAt"=COALESCE("qualifiedAt",CURRENT_TIMESTAMP) WHERE "referredUserId"=$1 AND "status"='PENDING'`,record.userId);const business=await tx.businessProfile.findUnique({where:{userId:record.userId},select:{verificationStatus:true}});if(business?.verificationStatus==="VERIFIED")await tx.store.updateMany({where:{ownerId:record.userId,status:"DRAFT"},data:{status:"ACTIVE",isVerified:true,publishedAt:new Date()}})});await rewardReferralAfterEmailVerification(record.userId).catch(()=>undefined);const credit=await grantWelcomeSiteCredit(record.userId);await queueTransactionalEmail({userId:record.userId,eventKind:"AUTH_WELCOME",title:"Bienvenue sur Petit Annonces 🎉",body:"Votre compte est actif. Un crédit de bienvenue de 5,00 € a été ajouté à votre compte, utilisable uniquement pour les services Petit Annonces.",actionUrl:"/mon-compte/portefeuille",metadata:{purpose:"WELCOME",welcomeCreditMinor:WELCOME_SITE_CREDIT_MINOR}});const user=await prisma.user.findUnique({where:{id:record.userId},include:{profile:true,roles:true}});if(!user)return reply.code(404).send({error:"user_not_found"});const nativeSession=await createSessionToken(user.id,request,true);return reply.send({verified:true,authenticated:true,sessionToken:nativeSession.token,expiresAt:nativeSession.expiresAt.toISOString(),welcomeCreditMinor:credit.grantedMinor,user:{id:user.id,email:user.email,kind:user.kind,profile:user.profile,roles:user.roles.map(entry=>entry.role)}})});

 app.post("/auth/mobile/login",async(request,reply)=>{const parsed=loginSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"invalid_request"});if(!await enforceAuthRateLimit({request,reply,action:"LOGIN",identity:parsed.data.email,limit:20,windowMs:15*60*1000,blockMs:15*60*1000}))return;const user=await prisma.user.findUnique({where:{email:parsed.data.email},include:{profile:true,roles:true}});if(!user)return reply.code(401).send({error:"invalid_credentials"});if(user.lockedUntil&&user.lockedUntil>new Date())return reply.code(423).send({error:"account_temporarily_locked"});const valid=await verify(user.passwordHash,parsed.data.password);if(!valid){if(await isLegacyMigratedUser(user.id))return reply.code(403).send({error:"password_reset_required"});const attempts=user.failedLoginAttempts+1;await prisma.user.update({where:{id:user.id},data:{failedLoginAttempts:attempts>=5?0:attempts,lockedUntil:attempts>=5?new Date(Date.now()+15*60*1000):null}});if(attempts>=3)await recordUserRiskEvent({userId:user.id,eventType:attempts>=5?"ACCOUNT_LOGIN_LOCK":"FAILED_LOGIN_BURST",weight:attempts>=5?10:4,metadata:{attempts,locked:attempts>=5}}).catch(()=>undefined);return reply.code(401).send({error:"invalid_credentials"})}if(user.status!=="ACTIVE")return reply.code(403).send({error:user.status==="PENDING_VERIFICATION"?"email_verification_required":"account_unavailable"});await prisma.user.update({where:{id:user.id},data:{failedLoginAttempts:0,lockedUntil:null}});if(await isTwoFactorEnabled(user.id)){const challengeToken=await createTwoFactorLoginChallenge(user.id);return reply.send({authenticated:false,twoFactorRequired:true,challengeToken,remember:parsed.data.remember,expiresInSeconds:300})}await prisma.user.update({where:{id:user.id},data:{lastLoginAt:new Date()}});await clearAuthRateLimit("LOGIN",request,parsed.data.email);const nativeSession=await createSessionToken(user.id,request,parsed.data.remember);return reply.send({authenticated:true,sessionToken:nativeSession.token,expiresAt:nativeSession.expiresAt.toISOString(),user:{id:user.id,email:user.email,kind:user.kind,profile:user.profile,roles:user.roles.map(entry=>entry.role)}})});

 app.post("/auth/mobile/2fa/complete",async(request,reply)=>{const body=z.object({challengeToken:z.string().min(20),code:z.string().trim().min(6).max(32),remember:z.boolean().default(true)}).safeParse(request.body);if(!body.success)return reply.code(400).send({error:"invalid_request"});if(!await enforceAuthRateLimit({request,reply,action:"LOGIN_2FA",limit:12,windowMs:15*60*1000,blockMs:15*60*1000}))return;const userId=await verifyTwoFactorLoginChallenge(body.data.challengeToken,body.data.code);if(!userId)return reply.code(401).send({error:"invalid_two_factor_code"});await prisma.user.update({where:{id:userId},data:{lastLoginAt:new Date(),failedLoginAttempts:0,lockedUntil:null}});const nativeSession=await createSessionToken(userId,request,body.data.remember);return reply.send({authenticated:true,sessionToken:nativeSession.token,expiresAt:nativeSession.expiresAt.toISOString()})});

 app.get("/auth/mobile/me",async(request,reply)=>{const auth=await getCurrentUser(request);if(!auth||!bearerToken(request))return reply.code(401).send({error:"unauthenticated"});return reply.send({user:{id:auth.user.id,email:auth.user.email,kind:auth.user.kind,profile:auth.user.profile,roles:auth.user.roles.map((entry:{role:string})=>entry.role)}})});

 app.post("/auth/mobile/logout",async(request,reply)=>{const token=bearerToken(request);if(token)await prisma.session.updateMany({where:{tokenHash:sha256(token),revokedAt:null},data:{revokedAt:new Date()}});return reply.code(204).send()});
}
