import cookie from "@fastify/cookie";
import Fastify from "fastify";
import { registerAccountRoutes } from "./account.js";
import { registerAccountActivityRoutes } from "./account-activity.js";
import { registerAccountDashboardRoutes } from "./account-dashboard.js";
import { registerAccountEngagementRoutes } from "./account-engagement.js";
import { registerAccountListingRoutes } from "./account-listings.js";
import { registerAccountOrderRoutes } from "./account-orders.js";
import { registerAccountSettingsRoutes } from "./account-settings.js";
import { registerAuthRecoveryRoutes } from "./auth-recovery.js";
import { registerAuthRoutes } from "./auth.js";
import { registerCheckoutListingRoutes } from "./checkout-listing.js";
import { registerComplianceRoutes } from "./compliance.js";
import { registerDsaComplianceRoutes } from "./dsa-compliance.js";
import { registerDisputeRoutes } from "./disputes.js";
import { registerGrowthAdminRoutes } from "./growth-admin.js";
import { registerGrowthRoutes } from "./growth.js";
import { registerHealthRoutes } from "./health.js";
import { registerListingCommerceRoutes } from "./listing-commerce.js";
import { registerListingRoutes } from "./listings.js";
import { registerMediaRoutes } from "./media.js";
import { registerMessagingRoutes } from "./messaging.js";
import { registerMobilePushRoutes } from "./mobile-push.js";
import { registerModerationRoutes } from "./moderation.js";
import { registerOperationsRoutes } from "./operations.js";
import { registerOrderFulfillmentRoutes } from "./order-fulfillment.js";
import { registerPaymentRoutes } from "./payments.js";
import { registerProfessionalRoutes } from "./professional.js";
import { registerProfessionalRegistrationRoutes } from "./pro-registration.js";
import { registerPublicationRoutes } from "./publication.js";
import { registerPublicListingRoutes } from "./public-listings.js";
import { requireAdminRoles } from "./rbac.js";
import { registerSearchRoutes } from "./search.js";
import { registerSecurityRoutes } from "./security.js";
import { registerShippingRoutes } from "./shipping.js";

const app = Fastify({ logger: true, trustProxy: true, bodyLimit: 1024 * 1024 });
await app.register(cookie);
await registerHealthRoutes(app);
await registerAuthRoutes(app);
await registerAuthRecoveryRoutes(app);
await registerProfessionalRegistrationRoutes(app);
await registerAccountRoutes(app);
await registerAccountActivityRoutes(app);
await registerAccountDashboardRoutes(app);
await registerAccountEngagementRoutes(app);
await registerAccountListingRoutes(app);
await registerAccountOrderRoutes(app);
await registerAccountSettingsRoutes(app);
await registerSecurityRoutes(app);
await registerListingRoutes(app);
await registerListingCommerceRoutes(app);
await registerMediaRoutes(app);
await registerPublicationRoutes(app);
await registerPublicListingRoutes(app);
await registerSearchRoutes(app);
await registerMessagingRoutes(app);
await registerProfessionalRoutes(app);
await registerCheckoutListingRoutes(app);
await registerPaymentRoutes(app);
await registerOrderFulfillmentRoutes(app);
await registerShippingRoutes(app);
await registerDisputeRoutes(app);
await registerModerationRoutes(app);
await registerComplianceRoutes(app);
await registerDsaComplianceRoutes(app);
await registerOperationsRoutes(app);
await registerGrowthRoutes(app);
await registerGrowthAdminRoutes(app);
await registerMobilePushRoutes(app);
app.get("/admin/session-check", { preHandler: requireAdminRoles(["SUPER_ADMIN", "ADMIN", "MODERATOR", "SUPPORT", "FINANCE", "COMPLIANCE", "MARKETING"]) }, async () => ({ authorized: true }));
const port = Number(process.env.API_PORT ?? 4000);
try { await app.listen({ port, host: "0.0.0.0" }); } catch (error) { app.log.error(error); process.exit(1); }
