import cookie from "@fastify/cookie";
import Fastify from "fastify";
import rawBody from "fastify-raw-body";
import { registerAccountRoutes } from "./account.js";
import { ensureAutoApprovalSchema, registerAutoApprovalAdminRoutes, startAutoApprovalWorker } from "./auto-approval.js";
import { registerAdminControlRoutes } from "./admin-control.js";
import { registerAdminSystemRoutes } from "./admin-system.js";
import { registerAdminSeoRoutes } from "./admin-seo.js";
import { registerAdminNotificationRoutes } from "./admin-notifications.js";
import { registerAdminCommercialRoutes } from "./admin-commercial.js";
import { registerAdminAnalyticsRoutes } from "./admin-analytics.js";
import { registerAdminImportHealthRoutes } from "./admin-import-health.js";
import { registerAdminAuditRoutes } from "./admin-audit.js";
import { registerAdminInboxRoutes } from "./admin-inbox.js";
import { registerAdminMobileReleaseRoutes } from "./admin-mobile-release.js";
import { registerAccountActivityRoutes } from "./account-activity.js";
import { registerAccountDashboardRoutes } from "./account-dashboard.js";
import { registerAccountEngagementRoutes } from "./account-engagement.js";
import { registerAccountListingRoutes } from "./account-listings.js";
import { registerAccountOrderRoutes } from "./account-orders.js";
import { registerAccountReviewRoutes } from "./account-reviews.js";
import { registerListingImportRoutes } from "./listing-import.js";
import { registerAccountSettingsRoutes } from "./account-settings.js";
import { registerAuthRecoveryRoutes } from "./auth-recovery.js";
import { registerAuthRoutes } from "./auth.js";
import { registerOAuthRoutes } from "./oauth.js";
import { registerCheckoutListingRoutes } from "./checkout-listing.js";
import { registerCategoryAdminRoutes } from "./category-admin.js";
import { registerComplianceRoutes } from "./compliance.js";
import { registerDsaComplianceRoutes } from "./dsa-compliance.js";
import { registerDisputeRoutes } from "./disputes.js";
import { startAbandonedDraftCleanupWorker } from "./draft-cleanup.js";
import { registerGrowthAdminRoutes } from "./growth-admin.js";
import { registerGrowthRoutes } from "./growth.js";
import { registerGoogleAdsDirectRoutes, testGoogleAdsConnection } from "./google-ads-direct.js";
import { ensureFollowingSchema, registerFollowingRoutes } from "./following.js";
import { registerProOutreachRoutes } from "./pro-outreach.js";
import { registerHealthRoutes } from "./health.js";
import { registerListingCommerceRoutes } from "./listing-commerce.js";
import { ensureMarketplaceFeeSchema } from "./marketplace-fees.js";
import { ensureListingContentPolicySchema, registerListingContentPolicyRoutes, spamHoldPreHandler } from "./listing-content-policy.js";
import { ensureListingLifecycleSchema, startListingExpiryWorker } from "./listing-lifecycle.js";
import { registerListingRoutes } from "./listings.js";
import { registerLocationRoutes } from "./locations.js";
import { registerMediaRoutes } from "./media.js";
import { registerMessagingRoutes } from "./messaging.js";
import { startAcceptedOfferPaymentWindowWorker } from "./offer-lifecycle.js";
import { registerMobilePushRoutes } from "./mobile-push.js";
import { registerMobileUiRoutes } from "./mobile-ui.js";
import { registerModerationRoutes } from "./moderation.js";
import { registerNotificationWorkerRoutes } from "./notification-worker-routes.js";
import { startNotificationWorker } from "./notification-worker.js";
import { registerCheckoutRecoveryRoutes, startCheckoutRecoveryWorker } from "./checkout-recovery.js";
import { ensureUserRecoverySchema, registerUserRecoveryRoutes, startDraftRecoveryWorker } from "./user-recovery.js";
import { registerOperationsRoutes } from "./operations.js";
import { registerOrderFulfillmentRoutes } from "./order-fulfillment.js";
import { registerPaymentRoutes } from "./payments.js";
import { registerPayPalWebhookRoutes } from "./paypal-webhooks.js";
import { registerPhoneVerificationRoutes } from "./phone-verification.js";
import { registerProfessionalRoutes } from "./professional.js";
import { registerProfessionalDashboardRoutes } from "./pro-dashboard.js";
import { registerProfessionalImportRoutes } from "./pro-import.js";
import { registerProSuiteRoutes } from "./pro-suite.js";
import { registerProMessageToolRoutes } from "./pro-message-tools.js";
import { registerProfessionalRegistrationRoutes } from "./pro-registration.js";
import { registerPublicationRoutes } from "./publication.js";
import { registerPublicListingRoutes } from "./public-listings.js";
import { requireAdminRoles } from "./rbac.js";
import { registerSearchRoutes } from "./search.js";
import { registerSeoPublicRoutes } from "./seo-public.js";
import { registerSiteAnalyticsRoutes } from "./site-analytics.js";
import { registerMetaConversionRoutes } from "./meta-conversions.js";
import { registerSecurityRoutes } from "./security.js";
import { registerRiskRoutes, startRiskSweepWorker } from "./risk-engine.js";
import { ensureReputationSchema, startReputationWorker } from "./reputation.js";
import { registerCommerceRiskRoutes } from "./commerce-risk.js";
import { registerSendcloudWebhookRoutes } from "./sendcloud-webhooks.js";
import { registerShippingRoutes } from "./shipping.js";
import { registerStripeBillingRoutes } from "./stripe-billing.js";
import { startProSubscriptionReminderWorker } from "./pro-subscription-notifications.js";
import { registerMarketplaceStripeRoutes } from "./marketplace-stripe.js";
import { registerMarketplaceFlowSimulatorRoutes } from "./marketplace-flow-simulator.js";
import { registerMangopayMarketplaceRoutes } from "./marketplace-mangopay.js";
import { registerTwoFactorRoutes } from "./two-factor.js";
import { ensureVacationSchema, registerVacationRoutes } from "./vacation.js";
import { registerHbxHotelRoutes, startHbxBookingReconciliationWorker, startHbxContentRefreshWorker } from "./hbx-hotels.js";
import { ensureVacationPaymentSchema, registerVacationPaymentRoutes, startVacationDepositPayoutWorker } from "./vacation-payments.js";
import { ensureVacationIcalSchema, registerVacationIcalRoutes, startVacationIcalSyncWorker } from "./vacation-ical.js";
import { ensureVacationReviewSchema, registerVacationReviewRoutes } from "./vacation-reviews.js";
import { ensureVacationStayOperationsSchema, registerVacationStayOperationsRoutes, startVacationPreArrivalWorker } from "./vacation-stay-operations.js";
import { ensureVacationStayLifecycleSchema, registerVacationStayLifecycleRoutes } from "./vacation-stay-lifecycle.js";
import { ensureVacationTaxSchema, registerVacationTaxRoutes } from "./vacation-tax.js";

const app = Fastify({ logger: true, trustProxy: true, bodyLimit: 1024 * 1024 });
await app.register(cookie);
await app.register(rawBody,{field:"rawBody",global:false,encoding:"utf8",runFirst:true});

// Admin mutations use a host-only session cookie. Enforce same-origin requests as a
// second CSRF boundary on top of SameSite=Lax and RBAC. Native/bearer API calls are
// unaffected because this check applies only to cookie-authenticated /admin writes.
app.addHook("preHandler",async(request,reply)=>{
  if(!["POST","PUT","PATCH","DELETE"].includes(request.method))return;
  if(!request.url.startsWith("/admin/"))return;
  if(!request.cookies.pa_session)return;
  let source:string|null=null;
  try{
    const raw=typeof request.headers.origin==="string"?request.headers.origin:typeof request.headers.referer==="string"?request.headers.referer:null;
    if(raw)source=new URL(raw).origin;
  }catch{source=null}
  const allowed=process.env.NODE_ENV==="production"
    ? new Set(["https://admin.petitannonces.fr"])
    : new Set(["https://admin.petitannonces.fr","http://localhost:3001","http://127.0.0.1:3001"]);
  if(!source||!allowed.has(source))return reply.code(403).send({error:"invalid_request_origin"});
});
app.addHook("preHandler",spamHoldPreHandler);
await registerHealthRoutes(app);
await registerListingContentPolicyRoutes(app);
await registerAdminControlRoutes(app);
await registerGoogleAdsDirectRoutes(app);
await registerAutoApprovalAdminRoutes(app);
await registerAdminSystemRoutes(app);
await registerAdminSeoRoutes(app);
await registerAdminNotificationRoutes(app);
await registerAdminCommercialRoutes(app);
await registerAdminAnalyticsRoutes(app);
await registerAdminImportHealthRoutes(app);
await registerAdminAuditRoutes(app);
await registerAdminInboxRoutes(app);
await registerAdminMobileReleaseRoutes(app);
await registerCategoryAdminRoutes(app);
await registerAuthRoutes(app);
await registerOAuthRoutes(app);
await registerAuthRecoveryRoutes(app);
await registerProfessionalRegistrationRoutes(app);
await registerAccountRoutes(app);
await registerAccountActivityRoutes(app);
await registerAccountDashboardRoutes(app);
await registerAccountEngagementRoutes(app);
await registerFollowingRoutes(app);
await registerAccountListingRoutes(app);
await registerAccountOrderRoutes(app);
await registerAccountReviewRoutes(app);
await registerListingImportRoutes(app);
await registerAccountSettingsRoutes(app);
await registerPhoneVerificationRoutes(app);
await registerTwoFactorRoutes(app);
await registerSecurityRoutes(app);
await registerRiskRoutes(app);
await registerCommerceRiskRoutes(app);
await registerLocationRoutes(app);
await registerListingRoutes(app);
await registerListingCommerceRoutes(app);
await registerMediaRoutes(app);
await registerPublicationRoutes(app);
await registerPublicListingRoutes(app);
await registerVacationRoutes(app);
await registerHbxHotelRoutes(app);
await registerVacationPaymentRoutes(app);
await registerVacationIcalRoutes(app);
await registerVacationReviewRoutes(app);
await registerVacationStayOperationsRoutes(app);
await registerVacationStayLifecycleRoutes(app);
await registerVacationTaxRoutes(app);
await registerSearchRoutes(app);
await registerSeoPublicRoutes(app);
await registerSiteAnalyticsRoutes(app);
await registerMetaConversionRoutes(app);
await registerMessagingRoutes(app);
await registerProfessionalRoutes(app);
await registerProSuiteRoutes(app);
await registerProMessageToolRoutes(app);
await registerProfessionalDashboardRoutes(app);
await registerProfessionalImportRoutes(app);
await registerCheckoutListingRoutes(app);
await registerPaymentRoutes(app);
await registerPayPalWebhookRoutes(app);
await registerCheckoutRecoveryRoutes(app);
await registerUserRecoveryRoutes(app);
await registerOrderFulfillmentRoutes(app);
await registerShippingRoutes(app);
await registerStripeBillingRoutes(app);
  await registerMarketplaceStripeRoutes(app);
  await registerMarketplaceFlowSimulatorRoutes(app);
  await registerMangopayMarketplaceRoutes(app);
await registerSendcloudWebhookRoutes(app);
await registerDisputeRoutes(app);
await registerModerationRoutes(app);
await registerComplianceRoutes(app);
await registerDsaComplianceRoutes(app);
await registerOperationsRoutes(app);
await registerGrowthRoutes(app);
await registerProOutreachRoutes(app);
await registerGrowthAdminRoutes(app);
await registerMobilePushRoutes(app);
await registerMobileUiRoutes(app);
await registerNotificationWorkerRoutes(app);
app.get("/admin/session-check", { preHandler: requireAdminRoles(["SUPER_ADMIN", "ADMIN", "MODERATOR", "SUPPORT", "FINANCE", "COMPLIANCE", "MARKETING"]) }, async () => ({ authorized: true }));
const port = Number(process.env.API_PORT ?? 4000);
const host = process.env.API_HOST ?? "127.0.0.1";

try {
  await ensureListingLifecycleSchema();
  await ensureAutoApprovalSchema();
  await ensureMarketplaceFeeSchema();
  await ensureListingContentPolicySchema();
  await ensureUserRecoverySchema();
  await ensureReputationSchema();
  await ensureFollowingSchema();
  await ensureVacationSchema();
  await ensureVacationPaymentSchema();
  await ensureVacationIcalSchema();
  await ensureVacationReviewSchema();
  await ensureVacationStayOperationsSchema();
  await ensureVacationStayLifecycleSchema();
  await ensureVacationTaxSchema();
  await app.listen({ port, host });
  startNotificationWorker(app.log);
  startCheckoutRecoveryWorker(app.log);
  startDraftRecoveryWorker(app.log);
  startAcceptedOfferPaymentWindowWorker(app.log);
  startProSubscriptionReminderWorker(app.log);
  startListingExpiryWorker(app.log);
  startAutoApprovalWorker(app.log);
  startAbandonedDraftCleanupWorker(app.log);
  startRiskSweepWorker(app.log);
  startReputationWorker(app.log);
  startVacationDepositPayoutWorker(app.log);
  startVacationIcalSyncWorker(app.log);
  startVacationPreArrivalWorker(app.log);
  startHbxBookingReconciliationWorker(app.log);
  startHbxContentRefreshWorker(app.log);
} catch (error) {
  app.log.error(error);
  process.exit(1);
}
