import { randomUUID } from "node:crypto";
import { prisma } from "@pa/database";
import { copyStoredObject, deleteStoredObject } from "./storage.js";

type EditSession={originalListingId:string;workingListingId:string;userId:string;previousStatus:string;createdAt:Date;updatedAt:Date};

export async function ensureListingEditSessionTable(){
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "ListingEditSession" (
    "originalListingId" TEXT PRIMARY KEY REFERENCES "Listing"("id") ON DELETE CASCADE,
    "workingListingId" TEXT NOT NULL UNIQUE REFERENCES "Listing"("id") ON DELETE CASCADE,
    "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
    "previousStatus" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`);
  await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "ListingEditSession_user_idx" ON "ListingEditSession" ("userId","updatedAt" DESC)`);
}

export async function editSessionByWorkingId(workingListingId:string,userId?:string){
  await ensureListingEditSessionTable();
  const rows=await prisma.$queryRawUnsafe<EditSession[]>(`SELECT * FROM "ListingEditSession" WHERE "workingListingId"=$1 ${userId?`AND "userId"=$2`:``} LIMIT 1`,...(userId?[workingListingId,userId]:[workingListingId]));
  return rows[0]??null;
}

export async function hiddenEditWorkingIds(userId:string){
  await ensureListingEditSessionTable();
  const rows=await prisma.$queryRawUnsafe<Array<{workingListingId:string}>>(`SELECT "workingListingId" FROM "ListingEditSession" WHERE "userId"=$1`,userId);
  return rows.map(x=>x.workingListingId);
}

async function cloneRawConfiguration(originalId:string,workingId:string){
  const media=await prisma.$queryRawUnsafe<Array<any>>(`SELECT "objectKey","publicUrl","mimeType","sizeBytes","width","height","status","sortOrder","isCover","altText" FROM "ListingMedia" WHERE "listingId"=$1 ORDER BY "sortOrder","createdAt"`,originalId).catch(()=>[]);
  for(const m of media){
    const clonedKey=`listing-edits/${workingId}/${randomUUID()}`;
    const clonedUrl=await copyStoredObject(m.objectKey,clonedKey);
    try{
      await prisma.$executeRawUnsafe(`INSERT INTO "ListingMedia" ("id","listingId","objectKey","publicUrl","mimeType","sizeBytes","width","height","status","sortOrder","isCover","altText","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NOW(),NOW())`,randomUUID(),workingId,clonedKey,clonedUrl,m.mimeType,m.sizeBytes,m.width,m.height,m.status,m.sortOrder,m.isCover,m.altText);
    }catch(error){
      await deleteStoredObject(clonedKey).catch(()=>undefined);
      throw error;
    }
  }
  const commerce=await prisma.$queryRawUnsafe<Array<any>>(`SELECT "acceptsOffers","securePaymentEnabled","commissionPayer","handDeliveryEnabled","mondialRelayEnabled","colissimoEnabled","packageWeightG","packageLengthCm","packageWidthCm","packageHeightCm" FROM "ListingCommerceSettings" WHERE "listingId"=$1 LIMIT 1`,originalId).catch(()=>[]);
  if(commerce[0]){const c=commerce[0];await prisma.$executeRawUnsafe(`INSERT INTO "ListingCommerceSettings" ("listingId","acceptsOffers","securePaymentEnabled","commissionPayer","handDeliveryEnabled","mondialRelayEnabled","colissimoEnabled","packageWeightG","packageLengthCm","packageWidthCm","packageHeightCm","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NOW(),NOW()) ON CONFLICT ("listingId") DO NOTHING`,workingId,c.acceptsOffers,c.securePaymentEnabled,c.commissionPayer,c.handDeliveryEnabled,c.mondialRelayEnabled,c.colissimoEnabled,c.packageWeightG,c.packageLengthCm,c.packageWidthCm,c.packageHeightCm).catch(()=>undefined)}
  const report=await prisma.$queryRawUnsafe<Array<{histovecUrl:string|null}>>(`SELECT "histovecUrl" FROM "VehicleOfficialReport" WHERE "listingId"=$1 LIMIT 1`,originalId).catch(()=>[]);if(report[0])await prisma.$executeRawUnsafe(`INSERT INTO "VehicleOfficialReport" ("listingId","histovecUrl","createdAt","updatedAt") VALUES ($1,$2,NOW(),NOW()) ON CONFLICT ("listingId") DO UPDATE SET "histovecUrl"=EXCLUDED."histovecUrl","updatedAt"=NOW()`,workingId,report[0].histovecUrl).catch(()=>undefined);
  const history=await prisma.$queryRawUnsafe<Array<any>>(`SELECT "registrationPlateHash","source","checkedAt","historyJson" FROM "VehicleHistorySnapshot" WHERE "listingId"=$1 LIMIT 1`,originalId).catch(()=>[]);if(history[0]){const h=history[0];await prisma.$executeRawUnsafe(`INSERT INTO "VehicleHistorySnapshot" ("listingId","registrationPlateHash","source","checkedAt","historyJson","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5::jsonb,NOW(),NOW()) ON CONFLICT ("listingId") DO UPDATE SET "registrationPlateHash"=EXCLUDED."registrationPlateHash","source"=EXCLUDED."source","checkedAt"=EXCLUDED."checkedAt","historyJson"=EXCLUDED."historyJson","updatedAt"=NOW()`,workingId,h.registrationPlateHash,h.source,h.checkedAt,JSON.stringify(h.historyJson??{})).catch(()=>undefined)}
  const safety=await prisma.$queryRawUnsafe<Array<any>>(`SELECT "manufacturerName","manufacturerPostalAddress","manufacturerEmail","responsiblePersonName","responsiblePersonPostalAddress","responsiblePersonEmail","productIdentifier","model","ean","ceMarked","safetyWarning" FROM "ListingProductSafety" WHERE "listingId"=$1 LIMIT 1`,originalId).catch(()=>[]);if(safety[0]){const s=safety[0];await prisma.$executeRawUnsafe(`INSERT INTO "ListingProductSafety" ("id","listingId","manufacturerName","manufacturerPostalAddress","manufacturerEmail","responsiblePersonName","responsiblePersonPostalAddress","responsiblePersonEmail","productIdentifier","model","ean","ceMarked","safetyWarning") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT ("listingId") DO UPDATE SET "manufacturerName"=EXCLUDED."manufacturerName","manufacturerPostalAddress"=EXCLUDED."manufacturerPostalAddress","manufacturerEmail"=EXCLUDED."manufacturerEmail","responsiblePersonName"=EXCLUDED."responsiblePersonName","responsiblePersonPostalAddress"=EXCLUDED."responsiblePersonPostalAddress","responsiblePersonEmail"=EXCLUDED."responsiblePersonEmail","productIdentifier"=EXCLUDED."productIdentifier","model"=EXCLUDED."model","ean"=EXCLUDED."ean","ceMarked"=EXCLUDED."ceMarked","safetyWarning"=EXCLUDED."safetyWarning","updatedAt"=NOW()`,randomUUID(),workingId,s.manufacturerName,s.manufacturerPostalAddress,s.manufacturerEmail,s.responsiblePersonName,s.responsiblePersonPostalAddress,s.responsiblePersonEmail,s.productIdentifier,s.model,s.ean,s.ceMarked,s.safetyWarning).catch(()=>undefined)}
  const disclosure=await prisma.$queryRawUnsafe<Array<any>>(`SELECT "sellerIsTrader","withdrawalRightApplies","withdrawalPeriodDays","withdrawalExceptionCode","legalGuaranteeNotice","mediationEntityName","mediationEntityUrl" FROM "TraderConsumerDisclosure" WHERE "listingId"=$1 LIMIT 1`,originalId).catch(()=>[]);if(disclosure[0]){const d=disclosure[0];await prisma.$executeRawUnsafe(`INSERT INTO "TraderConsumerDisclosure" ("id","listingId","sellerIsTrader","withdrawalRightApplies","withdrawalPeriodDays","withdrawalExceptionCode","legalGuaranteeNotice","mediationEntityName","mediationEntityUrl") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT ("listingId") DO UPDATE SET "sellerIsTrader"=EXCLUDED."sellerIsTrader","withdrawalRightApplies"=EXCLUDED."withdrawalRightApplies","withdrawalPeriodDays"=EXCLUDED."withdrawalPeriodDays","withdrawalExceptionCode"=EXCLUDED."withdrawalExceptionCode","legalGuaranteeNotice"=EXCLUDED."legalGuaranteeNotice","mediationEntityName"=EXCLUDED."mediationEntityName","mediationEntityUrl"=EXCLUDED."mediationEntityUrl","updatedAt"=NOW()`,randomUUID(),workingId,d.sellerIsTrader,d.withdrawalRightApplies,d.withdrawalPeriodDays,d.withdrawalExceptionCode,d.legalGuaranteeNotice,d.mediationEntityName,d.mediationEntityUrl).catch(()=>undefined)}
  const settings=await prisma.$queryRawUnsafe<Array<any>>(`SELECT * FROM "VacationBookingSettings" WHERE "listingId"=$1 LIMIT 1`,originalId).catch(()=>[]);if(settings[0]){const s=settings[0];await prisma.$executeRawUnsafe(`INSERT INTO "VacationBookingSettings" ("listingId","depositEnabled","depositMode","depositPercent","depositFixedMinor","cancellationPolicy","instantBooking","cleaningFeeMinor","extraGuestFeeMinor","baseGuestsIncluded","weekendNightlyPriceMinor","weeklyDiscountPercent","monthlyDiscountPercent","checkInTime","checkOutTime","minAdvanceDays","maxStayNights","sameDayBooking","checkInWeekdays","checkOutWeekdays","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19::jsonb,$20::jsonb,NOW(),NOW()) ON CONFLICT ("listingId") DO NOTHING`,workingId,s.depositEnabled,s.depositMode,s.depositPercent,s.depositFixedMinor,s.cancellationPolicy,s.instantBooking,s.cleaningFeeMinor,s.extraGuestFeeMinor,s.baseGuestsIncluded,s.weekendNightlyPriceMinor,s.weeklyDiscountPercent,s.monthlyDiscountPercent,s.checkInTime,s.checkOutTime,s.minAdvanceDays,s.maxStayNights,s.sameDayBooking,JSON.stringify(s.checkInWeekdays??[0,1,2,3,4,5,6]),JSON.stringify(s.checkOutWeekdays??[0,1,2,3,4,5,6])).catch(()=>undefined)}
  const rates=await prisma.$queryRawUnsafe<Array<any>>(`SELECT "label","startDate","endDate","nightlyPriceMinor","minimumNights" FROM "VacationSeasonalRate" WHERE "listingId"=$1`,originalId).catch(()=>[]);for(const r of rates)await prisma.$executeRawUnsafe(`INSERT INTO "VacationSeasonalRate" ("id","listingId","label","startDate","endDate","nightlyPriceMinor","minimumNights","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,NOW(),NOW())`,randomUUID(),workingId,r.label,r.startDate,r.endDate,r.nightlyPriceMinor,r.minimumNights).catch(()=>undefined);
  const blocks=await prisma.$queryRawUnsafe<Array<any>>(`SELECT "startDate","endDate","note" FROM "VacationAvailabilityBlock" WHERE "listingId"=$1 AND COALESCE("sourceType",'MANUAL')='MANUAL'`,originalId).catch(()=>[]);for(const b of blocks)await prisma.$executeRawUnsafe(`INSERT INTO "VacationAvailabilityBlock" ("id","listingId","startDate","endDate","note","sourceType","sourceId","externalUid","createdAt") VALUES ($1,$2,$3,$4,$5,'MANUAL',NULL,NULL,NOW())`,randomUUID(),workingId,b.startDate,b.endDate,b.note).catch(()=>undefined);
}

export async function openListingEditSession(originalId:string,userId:string){
  await ensureListingEditSessionTable();
  const original=await prisma.listing.findFirst({where:{id:originalId,sellerId:userId,status:{in:["DRAFT","PUBLISHED","SUSPENDED","EXPIRED"]}},include:{attributes:true,vehicle:true,property:true,energy:true}});
  if(!original)return null;
  if(original.status==="DRAFT")return{workingListingId:original.id,originalListingId:original.id,previousStatus:"DRAFT",session:false};
  const existing=await prisma.$queryRawUnsafe<EditSession[]>(`SELECT * FROM "ListingEditSession" WHERE "originalListingId"=$1 AND "userId"=$2 LIMIT 1`,original.id,userId);
  if(existing[0])await discardListingEditSession(existing[0].workingListingId,userId).catch(()=>undefined);
  const working=await prisma.listing.create({data:{title:original.title,description:original.description,priceMinor:original.priceMinor,currency:original.currency,status:"DRAFT",sellerId:original.sellerId,categoryId:original.categoryId,storeId:original.storeId,city:original.city,postalCode:original.postalCode,region:original.region,latitude:original.latitude,longitude:original.longitude,draftSavedAt:null}});
  if(original.attributes.length)await prisma.listingAttributeValue.createMany({data:original.attributes.map(a=>({listingId:working.id,attributeId:a.attributeId,valueText:a.valueText,valueNumber:a.valueNumber,valueBoolean:a.valueBoolean,valueJson:a.valueJson as any}))});
  if(original.vehicle){const v=original.vehicle;await prisma.vehicleDetails.create({data:{listingId:working.id,registrationPlateHash:v.registrationPlateHash,registrationPlateLast4:v.registrationPlateLast4,dataSource:v.dataSource,dataVerifiedAt:v.dataVerifiedAt,make:v.make,model:v.model,version:v.version,firstRegistrationDate:v.firstRegistrationDate,modelYear:v.modelYear,fuel:v.fuel,transmission:v.transmission,bodyType:v.bodyType,powerKw:v.powerKw,fiscalPowerCv:v.fiscalPowerCv,co2GKm:v.co2GKm,euroStandard:v.euroStandard,seats:v.seats,doors:v.doors,color:v.color,mileageKm:v.mileageKm}})}
  if(original.property){const p=original.property;await prisma.propertyDetails.create({data:{listingId:working.id,transactionType:p.transactionType,propertyType:p.propertyType,surfaceM2:p.surfaceM2,rooms:p.rooms,bedrooms:p.bedrooms,furnished:p.furnished,floor:p.floor,totalFloors:p.totalFloors,landM2:p.landM2,postalCode:p.postalCode,city:p.city,countryCode:p.countryCode}})}
  if(original.energy){const e=original.energy;await prisma.propertyEnergyPerformance.create({data:{listingId:working.id,dpeNumber:e.dpeNumber,dpeDate:e.dpeDate,validUntil:e.validUntil,isExempt:e.isExempt,exemptionReason:e.exemptionReason,energyClass:e.energyClass,climateClass:e.climateClass,energyConsumptionKwhM2Year:e.energyConsumptionKwhM2Year,ghgKgCo2M2Year:e.ghgKgCo2M2Year,annualCostMinMinor:e.annualCostMinMinor,annualCostMaxMinor:e.annualCostMaxMinor,energyPriceReferenceYears:e.energyPriceReferenceYears,excessiveConsumption:e.excessiveConsumption}})}
  try{
    await cloneRawConfiguration(original.id,working.id);
    await prisma.$executeRawUnsafe(`INSERT INTO "ListingEditSession" ("originalListingId","workingListingId","userId","previousStatus","createdAt","updatedAt") VALUES ($1,$2,$3,$4,NOW(),NOW())`,original.id,working.id,userId,original.status);
  }catch(error){
    const orphanMedia=await prisma.$queryRawUnsafe<Array<{objectKey:string}>>(`SELECT "objectKey" FROM "ListingMedia" WHERE "listingId"=$1`,working.id).catch(()=>[]);
    await prisma.listing.delete({where:{id:working.id}}).catch(()=>undefined);
    await cleanupUnreferencedObjects(orphanMedia.map(x=>x.objectKey));
    throw error;
  }
  return{workingListingId:working.id,originalListingId:original.id,previousStatus:original.status,session:true};
}

async function cleanupUnreferencedObjects(keys:string[]){for(const key of [...new Set(keys.filter(Boolean))]){const rows=await prisma.$queryRawUnsafe<Array<{count:bigint}>>(`SELECT COUNT(*)::bigint AS count FROM "ListingMedia" WHERE "objectKey"=$1`,key).catch(()=>[]);if(Number(rows[0]?.count??0n)===0)await deleteStoredObject(key).catch(()=>undefined)}}

export async function discardListingEditSession(workingListingId:string,userId:string){
  const session=await editSessionByWorkingId(workingListingId,userId);if(!session)return false;
  const media=await prisma.$queryRawUnsafe<Array<{objectKey:string}>>(`SELECT "objectKey" FROM "ListingMedia" WHERE "listingId"=$1`,workingListingId).catch(()=>[]);
  await prisma.$transaction(async tx=>{await tx.$executeRawUnsafe(`DELETE FROM "ListingEditSession" WHERE "workingListingId"=$1 AND "userId"=$2`,workingListingId,userId);await tx.listing.deleteMany({where:{id:workingListingId,sellerId:userId,status:"DRAFT"}})});
  await cleanupUnreferencedObjects(media.map(x=>x.objectKey));return true;
}

export async function applyWorkingCopyToOriginal(tx:any,session:EditSession){
  const working=await tx.listing.findUnique({where:{id:session.workingListingId},include:{attributes:true,vehicle:true,property:true,energy:true}});if(!working)throw new Error("edit_working_copy_missing");
  const original=await tx.listing.findUnique({where:{id:session.originalListingId}});if(!original||original.sellerId!==session.userId)throw new Error("edit_original_missing");
  await tx.listing.update({where:{id:original.id},data:{title:working.title,description:working.description,priceMinor:working.priceMinor,currency:working.currency,categoryId:working.categoryId,city:working.city,postalCode:working.postalCode,region:working.region,latitude:working.latitude,longitude:working.longitude}});
  await tx.listingAttributeValue.deleteMany({where:{listingId:original.id}});if(working.attributes.length)await tx.listingAttributeValue.createMany({data:working.attributes.map((a:any)=>({listingId:original.id,attributeId:a.attributeId,valueText:a.valueText,valueNumber:a.valueNumber,valueBoolean:a.valueBoolean,valueJson:a.valueJson}))});
  await tx.vehicleDetails.deleteMany({where:{listingId:original.id}});if(working.vehicle){const v=working.vehicle;await tx.vehicleDetails.create({data:{listingId:original.id,registrationPlateHash:v.registrationPlateHash,registrationPlateLast4:v.registrationPlateLast4,dataSource:v.dataSource,dataVerifiedAt:v.dataVerifiedAt,make:v.make,model:v.model,version:v.version,firstRegistrationDate:v.firstRegistrationDate,modelYear:v.modelYear,fuel:v.fuel,transmission:v.transmission,bodyType:v.bodyType,powerKw:v.powerKw,fiscalPowerCv:v.fiscalPowerCv,co2GKm:v.co2GKm,euroStandard:v.euroStandard,seats:v.seats,doors:v.doors,color:v.color,mileageKm:v.mileageKm}})}
  await tx.propertyEnergyPerformance.deleteMany({where:{listingId:original.id}});if(working.energy){const e=working.energy;await tx.propertyEnergyPerformance.create({data:{listingId:original.id,dpeNumber:e.dpeNumber,dpeDate:e.dpeDate,validUntil:e.validUntil,isExempt:e.isExempt,exemptionReason:e.exemptionReason,energyClass:e.energyClass,climateClass:e.climateClass,energyConsumptionKwhM2Year:e.energyConsumptionKwhM2Year,ghgKgCo2M2Year:e.ghgKgCo2M2Year,annualCostMinMinor:e.annualCostMinMinor,annualCostMaxMinor:e.annualCostMaxMinor,energyPriceReferenceYears:e.energyPriceReferenceYears,excessiveConsumption:e.excessiveConsumption}})}
  await tx.propertyDetails.deleteMany({where:{listingId:original.id}});if(working.property){const p=working.property;await tx.propertyDetails.create({data:{listingId:original.id,transactionType:p.transactionType,propertyType:p.propertyType,surfaceM2:p.surfaceM2,rooms:p.rooms,bedrooms:p.bedrooms,furnished:p.furnished,floor:p.floor,totalFloors:p.totalFloors,landM2:p.landM2,postalCode:p.postalCode,city:p.city,countryCode:p.countryCode}})}
  const oldMedia=(await tx.$queryRawUnsafe(`SELECT "objectKey" FROM "ListingMedia" WHERE "listingId"=$1`,original.id).catch(()=>[])) as Array<{objectKey:string}>;
  const newMedia=(await tx.$queryRawUnsafe(`SELECT "objectKey" FROM "ListingMedia" WHERE "listingId"=$1 ORDER BY "sortOrder","createdAt"`,working.id).catch(()=>[])) as Array<{objectKey:string}>;
  if(newMedia.length){
    await tx.$executeRawUnsafe(`DELETE FROM "ListingMedia" WHERE "listingId"=$1`,original.id);
    await tx.$executeRawUnsafe(`UPDATE "ListingMedia" SET "listingId"=$1,"updatedAt"=NOW() WHERE "listingId"=$2`,original.id,working.id);
  }
  await tx.$executeRawUnsafe(`DELETE FROM "ListingCommerceSettings" WHERE "listingId"=$1`,original.id).catch(()=>undefined);await tx.$executeRawUnsafe(`INSERT INTO "ListingCommerceSettings" ("listingId","acceptsOffers","securePaymentEnabled","commissionPayer","handDeliveryEnabled","mondialRelayEnabled","colissimoEnabled","packageWeightG","packageLengthCm","packageWidthCm","packageHeightCm","createdAt","updatedAt") SELECT $1,"acceptsOffers","securePaymentEnabled","commissionPayer","handDeliveryEnabled","mondialRelayEnabled","colissimoEnabled","packageWeightG","packageLengthCm","packageWidthCm","packageHeightCm",NOW(),NOW() FROM "ListingCommerceSettings" WHERE "listingId"=$2`,original.id,working.id).catch(()=>undefined);
  await tx.$executeRawUnsafe(`DELETE FROM "VehicleOfficialReport" WHERE "listingId"=$1`,original.id).catch(()=>undefined);await tx.$executeRawUnsafe(`INSERT INTO "VehicleOfficialReport" ("listingId","histovecUrl","createdAt","updatedAt") SELECT $1,"histovecUrl",NOW(),NOW() FROM "VehicleOfficialReport" WHERE "listingId"=$2`,original.id,working.id).catch(()=>undefined);
  await tx.$executeRawUnsafe(`DELETE FROM "VehicleHistorySnapshot" WHERE "listingId"=$1`,original.id).catch(()=>undefined);await tx.$executeRawUnsafe(`INSERT INTO "VehicleHistorySnapshot" ("listingId","registrationPlateHash","source","checkedAt","historyJson","createdAt","updatedAt") SELECT $1,"registrationPlateHash","source","checkedAt","historyJson",NOW(),NOW() FROM "VehicleHistorySnapshot" WHERE "listingId"=$2`,original.id,working.id).catch(()=>undefined);
  await tx.$executeRawUnsafe(`DELETE FROM "ListingProductSafety" WHERE "listingId"=$1`,original.id).catch(()=>undefined);const safetyRows=(await tx.$queryRawUnsafe(`SELECT "manufacturerName","manufacturerPostalAddress","manufacturerEmail","responsiblePersonName","responsiblePersonPostalAddress","responsiblePersonEmail","productIdentifier","model","ean","ceMarked","safetyWarning" FROM "ListingProductSafety" WHERE "listingId"=$1 LIMIT 1`,working.id).catch(()=>[])) as Array<any>;if(safetyRows[0]){const s=safetyRows[0];await tx.$executeRawUnsafe(`INSERT INTO "ListingProductSafety" ("id","listingId","manufacturerName","manufacturerPostalAddress","manufacturerEmail","responsiblePersonName","responsiblePersonPostalAddress","responsiblePersonEmail","productIdentifier","model","ean","ceMarked","safetyWarning") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,randomUUID(),original.id,s.manufacturerName,s.manufacturerPostalAddress,s.manufacturerEmail,s.responsiblePersonName,s.responsiblePersonPostalAddress,s.responsiblePersonEmail,s.productIdentifier,s.model,s.ean,s.ceMarked,s.safetyWarning)}
  await tx.$executeRawUnsafe(`DELETE FROM "TraderConsumerDisclosure" WHERE "listingId"=$1`,original.id).catch(()=>undefined);const disclosureRows=(await tx.$queryRawUnsafe(`SELECT "sellerIsTrader","withdrawalRightApplies","withdrawalPeriodDays","withdrawalExceptionCode","legalGuaranteeNotice","mediationEntityName","mediationEntityUrl" FROM "TraderConsumerDisclosure" WHERE "listingId"=$1 LIMIT 1`,working.id).catch(()=>[])) as Array<any>;if(disclosureRows[0]){const d=disclosureRows[0];await tx.$executeRawUnsafe(`INSERT INTO "TraderConsumerDisclosure" ("id","listingId","sellerIsTrader","withdrawalRightApplies","withdrawalPeriodDays","withdrawalExceptionCode","legalGuaranteeNotice","mediationEntityName","mediationEntityUrl") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,randomUUID(),original.id,d.sellerIsTrader,d.withdrawalRightApplies,d.withdrawalPeriodDays,d.withdrawalExceptionCode,d.legalGuaranteeNotice,d.mediationEntityName,d.mediationEntityUrl)}
  await tx.$executeRawUnsafe(`DELETE FROM "VacationBookingSettings" WHERE "listingId"=$1`,original.id).catch(()=>undefined);await tx.$executeRawUnsafe(`INSERT INTO "VacationBookingSettings" ("listingId","depositEnabled","depositMode","depositPercent","depositFixedMinor","cancellationPolicy","instantBooking","cleaningFeeMinor","extraGuestFeeMinor","baseGuestsIncluded","weekendNightlyPriceMinor","weeklyDiscountPercent","monthlyDiscountPercent","checkInTime","checkOutTime","minAdvanceDays","maxStayNights","sameDayBooking","checkInWeekdays","checkOutWeekdays","createdAt","updatedAt") SELECT $1,"depositEnabled","depositMode","depositPercent","depositFixedMinor","cancellationPolicy","instantBooking","cleaningFeeMinor","extraGuestFeeMinor","baseGuestsIncluded","weekendNightlyPriceMinor","weeklyDiscountPercent","monthlyDiscountPercent","checkInTime","checkOutTime","minAdvanceDays","maxStayNights","sameDayBooking","checkInWeekdays","checkOutWeekdays",NOW(),NOW() FROM "VacationBookingSettings" WHERE "listingId"=$2`,original.id,working.id).catch(()=>undefined);
  await tx.$executeRawUnsafe(`DELETE FROM "VacationSeasonalRate" WHERE "listingId"=$1`,original.id).catch(()=>undefined);const rates=(await tx.$queryRawUnsafe(`SELECT "label","startDate","endDate","nightlyPriceMinor","minimumNights" FROM "VacationSeasonalRate" WHERE "listingId"=$1`,working.id).catch(()=>[])) as Array<any>;for(const r of rates)await tx.$executeRawUnsafe(`INSERT INTO "VacationSeasonalRate" ("id","listingId","label","startDate","endDate","nightlyPriceMinor","minimumNights","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,NOW(),NOW())`,randomUUID(),original.id,r.label,r.startDate,r.endDate,r.nightlyPriceMinor,r.minimumNights);
  await tx.$executeRawUnsafe(`DELETE FROM "VacationAvailabilityBlock" WHERE "listingId"=$1 AND COALESCE("sourceType",'MANUAL')='MANUAL'`,original.id).catch(()=>undefined);const blocks=(await tx.$queryRawUnsafe(`SELECT "startDate","endDate","note" FROM "VacationAvailabilityBlock" WHERE "listingId"=$1 AND COALESCE("sourceType",'MANUAL')='MANUAL'`,working.id).catch(()=>[])) as Array<any>;for(const b of blocks)await tx.$executeRawUnsafe(`INSERT INTO "VacationAvailabilityBlock" ("id","listingId","startDate","endDate","note","sourceType","sourceId","externalUid","createdAt") VALUES ($1,$2,$3,$4,$5,'MANUAL',NULL,NULL,NOW())`,randomUUID(),original.id,b.startDate,b.endDate,b.note);
  return{original,working,oldMediaKeys:oldMedia.map((x:any)=>x.objectKey)};
}

export async function finalizeEditSessionCleanup(workingListingId:string,userId:string,oldMediaKeys:string[]){await cleanupUnreferencedObjects(oldMediaKeys);}
