import { createHash, randomInt, randomUUID } from "node:crypto";
import { prisma } from "@pa/database";
import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { z } from "zod";
import { enforceAuthRateLimit } from "./auth-rate-limit.js";

const SESSION_COOKIE = "pa_session";
const OTP_TTL_MS = 10 * 60 * 1000;
function sha256(value:string){return createHash("sha256").update(value).digest("hex")}
function normalizePhone(value:string){const compact=value.replace(/[\s().-]/g,"");return compact.startsWith("00")?`+${compact.slice(2)}`:compact}
async function requireUser(request:FastifyRequest,reply:FastifyReply){const token=request.cookies[SESSION_COOKIE];if(!token){reply.code(401).send({error:"unauthenticated"});return null}const session=await prisma.session.findUnique({where:{tokenHash:sha256(token)},include:{user:{include:{profile:true}}}});if(!session||session.revokedAt||session.expiresAt<=new Date()||session.user.status!=="ACTIVE"){reply.code(401).send({error:"unauthenticated"});return null}return{session,user:session.user}}

async function sendSms(phone:string,code:string){
  const gateway=process.env.SMS_GATEWAY_URL;
  if(!gateway){if(process.env.NODE_ENV!=="production")return{mock:true};throw new Error("sms_provider_not_configured")}
  const response=await fetch(gateway,{method:"POST",headers:{"content-type":"application/json",...(process.env.SMS_GATEWAY_TOKEN?{authorization:`Bearer ${process.env.SMS_GATEWAY_TOKEN}`}:{})},body:JSON.stringify({to:phone,body:`Petit Annonces : votre code de vérification est ${code}. Il expire dans 10 minutes.`,sender:process.env.SMS_SENDER??"PetitAnnonces"})});
  if(!response.ok)throw new Error(`sms_gateway_${response.status}_${(await response.text()).slice(0,200)}`);
  return{mock:false};
}

export async function registerPhoneVerificationRoutes(app:FastifyInstance){
  app.get("/account/security",async(request,reply)=>{const auth=await requireUser(request,reply);if(!auth)return;const sessions=await prisma.session.findMany({where:{userId:auth.user.id,revokedAt:null,expiresAt:{gt:new Date()}},select:{id:true,userAgent:true,createdAt:true,lastSeenAt:true,expiresAt:true,tokenHash:true},orderBy:{lastSeenAt:"desc"},take:20});const profileRows=await prisma.$queryRawUnsafe<Array<{phone:string|null;phoneVerifiedAt:Date|null}>>(`SELECT "phone","phoneVerifiedAt" FROM "UserProfile" WHERE "userId"=$1 LIMIT 1`,auth.user.id);const profile=profileRows[0]??{phone:null,phoneVerifiedAt:null};return reply.send({security:{email:auth.user.email,emailVerified:Boolean(auth.user.emailVerifiedAt),phone:profile.phone,phoneVerified:Boolean(profile.phoneVerifiedAt),phoneVerifiedAt:profile.phoneVerifiedAt,lastLoginAt:auth.user.lastLoginAt,failedLoginAttempts:auth.user.failedLoginAttempts,lockedUntil:auth.user.lockedUntil},sessions:sessions.map(({tokenHash,...s})=>({...s,current:tokenHash===auth.session.tokenHash}))})});

  app.post("/account/phone-verification/request",async(request,reply)=>{const auth=await requireUser(request,reply);if(!auth)return;const body=z.object({phone:z.string().trim().min(8).max(24)}).safeParse(request.body);if(!body.success)return reply.code(400).send({error:"invalid_phone"});const phone=normalizePhone(body.data.phone);if(!/^\+[1-9]\d{7,14}$/.test(phone))return reply.code(400).send({error:"invalid_phone"});if(!(await enforceAuthRateLimit({request,reply,action:"phone_otp_request",identity:`${auth.user.id}:${phone}`,limit:3,windowMs:15*60*1000,blockMs:30*60*1000})))return;const code=String(randomInt(100000,1000000));let delivery:{mock:boolean};try{delivery=await sendSms(phone,code)}catch(error){const message=error instanceof Error?error.message:"sms_delivery_failed";return reply.code(message==="sms_provider_not_configured"?503:502).send({error:message})}await prisma.$executeRawUnsafe(`UPDATE "PhoneVerificationChallenge" SET "consumedAt"=CURRENT_TIMESTAMP WHERE "userId"=$1 AND "consumedAt" IS NULL`,auth.user.id);await prisma.$executeRawUnsafe(`INSERT INTO "PhoneVerificationChallenge" ("id","userId","phone","codeHash","expiresAt") VALUES ($1,$2,$3,$4,$5)`,randomUUID(),auth.user.id,phone,sha256(code),new Date(Date.now()+OTP_TTL_MS));return reply.send({requested:true,expiresInSeconds:600,...(delivery.mock?{devOtp:code}:{})})});

  app.post("/account/phone-verification/confirm",async(request,reply)=>{const auth=await requireUser(request,reply);if(!auth)return;const body=z.object({phone:z.string().trim().min(8).max(24),code:z.string().regex(/^\d{6}$/)}).safeParse(request.body);if(!body.success)return reply.code(400).send({error:"invalid_request"});const phone=normalizePhone(body.data.phone);if(!(await enforceAuthRateLimit({request,reply,action:"phone_otp_confirm",identity:`${auth.user.id}:${phone}`,limit:6,windowMs:15*60*1000,blockMs:30*60*1000})))return;const rows=await prisma.$queryRawUnsafe<Array<{id:string;codeHash:string;attempts:number;expiresAt:Date;consumedAt:Date|null}>>(`SELECT "id","codeHash","attempts","expiresAt","consumedAt" FROM "PhoneVerificationChallenge" WHERE "userId"=$1 AND "phone"=$2 ORDER BY "createdAt" DESC LIMIT 1`,auth.user.id,phone);const challenge=rows[0];if(!challenge||challenge.consumedAt||new Date(challenge.expiresAt)<=new Date())return reply.code(400).send({error:"invalid_or_expired_code"});if(challenge.attempts>=5)return reply.code(429).send({error:"too_many_code_attempts"});if(challenge.codeHash!==sha256(body.data.code)){await prisma.$executeRawUnsafe(`UPDATE "PhoneVerificationChallenge" SET "attempts"="attempts"+1 WHERE "id"=$1`,challenge.id);return reply.code(400).send({error:"invalid_code"})}await prisma.$transaction([prisma.$executeRawUnsafe(`UPDATE "PhoneVerificationChallenge" SET "consumedAt"=CURRENT_TIMESTAMP WHERE "id"=$1`,challenge.id),prisma.$executeRawUnsafe(`UPDATE "UserProfile" SET "phone"=$2,"phoneVerifiedAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE "userId"=$1`,auth.user.id,phone)]);return reply.send({verified:true,phone})});
}
