import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { prisma } from "@pa/database";
import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { z } from "zod";

const SESSION_COOKIE="pa_session";
const CHALLENGE_TTL_MS=5*60*1000;
const BASE32="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
function sha256(v:string){return createHash("sha256").update(v).digest("hex")}
function b32encode(buf:Buffer){let bits=0,value=0,out="";for(const byte of buf){value=(value<<8)|byte;bits+=8;while(bits>=5){out+=BASE32[(value>>>(bits-5))&31];bits-=5}}if(bits>0)out+=BASE32[(value<<(5-bits))&31];return out}
function b32decode(input:string){const s=input.replace(/=+$/g,"").toUpperCase().replace(/[^A-Z2-7]/g,"");let bits=0,value=0;const out:number[]=[];for(const c of s){const n=BASE32.indexOf(c);if(n<0)continue;value=(value<<5)|n;bits+=5;if(bits>=8){out.push((value>>>(bits-8))&255);bits-=8}}return Buffer.from(out)}
function key(){const raw=process.env.TWO_FACTOR_ENCRYPTION_KEY;if(!raw&&process.env.NODE_ENV==="production")throw new Error("two_factor_encryption_key_missing");return createHash("sha256").update(raw||"petitannonces-development-2fa-key").digest()}
function encrypt(secret:string){const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",key(),iv);const body=Buffer.concat([cipher.update(secret,"utf8"),cipher.final()]);const tag=cipher.getAuthTag();return Buffer.concat([iv,tag,body]).toString("base64url")}
function decrypt(value:string){const buf=Buffer.from(value,"base64url");const iv=buf.subarray(0,12),tag=buf.subarray(12,28),body=buf.subarray(28);const decipher=createDecipheriv("aes-256-gcm",key(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(body),decipher.final()]).toString("utf8")}
function totp(secret:string,step=Math.floor(Date.now()/30000)){const msg=Buffer.alloc(8);msg.writeBigUInt64BE(BigInt(step));const h=createHmac("sha1",b32decode(secret)).update(msg).digest();const off=h[h.length-1]&15;const n=((h[off]&127)<<24)|((h[off+1]&255)<<16)|((h[off+2]&255)<<8)|(h[off+3]&255);return String(n%1_000_000).padStart(6,"0")}
function safeEq(a:string,b:string){const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&timingSafeEqual(aa,bb)}
function validTotp(secret:string,code:string,lastUsedStep?:bigint|null){const current=Math.floor(Date.now()/30000);for(const step of [current-1,current,current+1]){if(lastUsedStep!=null&&BigInt(step)<=lastUsedStep)continue;if(safeEq(totp(secret,step),code))return BigInt(step)}return null}
function recoveryCode(){return `${randomBytes(4).toString("hex").toUpperCase()}-${randomBytes(4).toString("hex").toUpperCase()}`}
async function requireUser(request:FastifyRequest,reply:FastifyReply){const token=request.cookies[SESSION_COOKIE];if(!token){reply.code(401).send({error:"unauthenticated"});return null}const s=await prisma.session.findUnique({where:{tokenHash:sha256(token)},include:{user:true}});if(!s||s.revokedAt||s.expiresAt<=new Date()||s.user.status!=="ACTIVE"){reply.code(401).send({error:"unauthenticated"});return null}return{s,user:s.user}}

type TwoFactorRow={userId:string;enabled:boolean;secretEncrypted:string|null;lastUsedStep:bigint|null;enabledAt:Date|null};
export async function isTwoFactorEnabled(userId:string){const rows=await prisma.$queryRawUnsafe<TwoFactorRow[]>(`SELECT "userId","enabled","secretEncrypted","lastUsedStep","enabledAt" FROM "UserTwoFactor" WHERE "userId"=$1 LIMIT 1`,userId);return rows[0]?.enabled===true}
export async function createTwoFactorLoginChallenge(userId:string){const token=randomBytes(32).toString("base64url");await prisma.$executeRawUnsafe(`INSERT INTO "TwoFactorLoginChallenge" ("id","userId","tokenHash","expiresAt") VALUES ($1,$2,$3,$4)`,randomUUID(),userId,sha256(token),new Date(Date.now()+CHALLENGE_TTL_MS));return token}
export async function verifyTwoFactorLoginChallenge(token:string,code:string){const rows=await prisma.$queryRawUnsafe<Array<{id:string;userId:string;expiresAt:Date;usedAt:Date|null;attempts:number}>>(`SELECT "id","userId","expiresAt","usedAt","attempts" FROM "TwoFactorLoginChallenge" WHERE "tokenHash"=$1 LIMIT 1`,sha256(token));const c=rows[0];if(!c||c.usedAt||c.expiresAt<=new Date()||c.attempts>=6)return null;const trows=await prisma.$queryRawUnsafe<TwoFactorRow[]>(`SELECT "userId","enabled","secretEncrypted","lastUsedStep","enabledAt" FROM "UserTwoFactor" WHERE "userId"=$1 LIMIT 1`,c.userId);const tf=trows[0];if(!tf?.enabled||!tf.secretEncrypted)return null;let ok=false;let usedStep:bigint|null=null;if(/^\d{6}$/.test(code)){usedStep=validTotp(decrypt(tf.secretEncrypted),code,tf.lastUsedStep);ok=usedStep!=null}else{const hash=sha256(code.trim().toUpperCase());const used=await prisma.$executeRawUnsafe(`UPDATE "TwoFactorRecoveryCode" SET "usedAt"=CURRENT_TIMESTAMP WHERE "userId"=$1 AND "codeHash"=$2 AND "usedAt" IS NULL`,c.userId,hash);ok=used>0}if(!ok){await prisma.$executeRawUnsafe(`UPDATE "TwoFactorLoginChallenge" SET "attempts"="attempts"+1 WHERE "id"=$1`,c.id);return null}await prisma.$transaction(async(tx:any)=>{await tx.$executeRawUnsafe(`UPDATE "TwoFactorLoginChallenge" SET "usedAt"=CURRENT_TIMESTAMP WHERE "id"=$1`,c.id);if(usedStep!=null)await tx.$executeRawUnsafe(`UPDATE "UserTwoFactor" SET "lastUsedStep"=$2,"updatedAt"=CURRENT_TIMESTAMP WHERE "userId"=$1`,c.userId,usedStep)});return c.userId}

export async function registerTwoFactorRoutes(app:FastifyInstance){
 app.get("/account/2fa",async(req,reply)=>{const auth=await requireUser(req,reply);if(!auth)return;const rows=await prisma.$queryRawUnsafe<TwoFactorRow[]>(`SELECT "userId","enabled","secretEncrypted","lastUsedStep","enabledAt" FROM "UserTwoFactor" WHERE "userId"=$1 LIMIT 1`,auth.user.id);const remaining=await prisma.$queryRawUnsafe<Array<{count:bigint}>>(`SELECT COUNT(*)::bigint AS count FROM "TwoFactorRecoveryCode" WHERE "userId"=$1 AND "usedAt" IS NULL`,auth.user.id);return reply.send({enabled:rows[0]?.enabled===true,enabledAt:rows[0]?.enabledAt??null,recoveryCodesRemaining:Number(remaining[0]?.count??0)})});
 app.post("/account/2fa/setup",async(req,reply)=>{const auth=await requireUser(req,reply);if(!auth)return;if(!process.env.TWO_FACTOR_ENCRYPTION_KEY&&process.env.NODE_ENV==="production")return reply.code(503).send({error:"two_factor_not_configured"});const secret=b32encode(randomBytes(20));await prisma.$executeRawUnsafe(`INSERT INTO "UserTwoFactor" ("userId","enabled","secretEncrypted","updatedAt") VALUES ($1,FALSE,$2,CURRENT_TIMESTAMP) ON CONFLICT ("userId") DO UPDATE SET "enabled"=FALSE,"secretEncrypted"=EXCLUDED."secretEncrypted","updatedAt"=CURRENT_TIMESTAMP`,auth.user.id,encrypt(secret));const label=encodeURIComponent(auth.user.email);const issuer=encodeURIComponent("Petit Annonces");return reply.send({secret,otpauthUrl:`otpauth://totp/Petit%20Annonces:${label}?secret=${secret}&issuer=${issuer}&algorithm=SHA1&digits=6&period=30`})});
 app.post("/account/2fa/enable",async(req,reply)=>{const auth=await requireUser(req,reply);if(!auth)return;const body=z.object({code:z.string().regex(/^\d{6}$/)}).safeParse(req.body);if(!body.success)return reply.code(400).send({error:"invalid_request"});const rows=await prisma.$queryRawUnsafe<TwoFactorRow[]>(`SELECT "userId","enabled","secretEncrypted","lastUsedStep","enabledAt" FROM "UserTwoFactor" WHERE "userId"=$1 LIMIT 1`,auth.user.id);const tf=rows[0];if(!tf?.secretEncrypted)return reply.code(400).send({error:"setup_required"});const step=validTotp(decrypt(tf.secretEncrypted),body.data.code,null);if(step==null)return reply.code(400).send({error:"invalid_code"});const codes=Array.from({length:10},()=>recoveryCode());await prisma.$transaction(async(tx:any)=>{await tx.$executeRawUnsafe(`UPDATE "UserTwoFactor" SET "enabled"=TRUE,"enabledAt"=CURRENT_TIMESTAMP,"lastUsedStep"=$2,"updatedAt"=CURRENT_TIMESTAMP WHERE "userId"=$1`,auth.user.id,step);await tx.$executeRawUnsafe(`DELETE FROM "TwoFactorRecoveryCode" WHERE "userId"=$1`,auth.user.id);for(const code of codes)await tx.$executeRawUnsafe(`INSERT INTO "TwoFactorRecoveryCode" ("id","userId","codeHash") VALUES ($1,$2,$3)`,randomUUID(),auth.user.id,sha256(code))});return reply.send({enabled:true,recoveryCodes:codes})});
 app.post("/account/2fa/disable",async(req,reply)=>{const auth=await requireUser(req,reply);if(!auth)return;const body=z.object({code:z.string().min(6).max(32)}).safeParse(req.body);if(!body.success)return reply.code(400).send({error:"invalid_request"});const rows=await prisma.$queryRawUnsafe<TwoFactorRow[]>(`SELECT "userId","enabled","secretEncrypted","lastUsedStep","enabledAt" FROM "UserTwoFactor" WHERE "userId"=$1 LIMIT 1`,auth.user.id);const tf=rows[0];if(!tf?.enabled||!tf.secretEncrypted)return reply.code(400).send({error:"two_factor_not_enabled"});const code=body.data.code.trim();const otp=/^\d{6}$/.test(code)?validTotp(decrypt(tf.secretEncrypted),code,tf.lastUsedStep):null;let ok=otp!=null;if(!ok){const hash=sha256(code.toUpperCase());const rows2=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "TwoFactorRecoveryCode" WHERE "userId"=$1 AND "codeHash"=$2 AND "usedAt" IS NULL LIMIT 1`,auth.user.id,hash);ok=rows2.length>0}if(!ok)return reply.code(400).send({error:"invalid_code"});await prisma.$transaction(async(tx:any)=>{await tx.$executeRawUnsafe(`UPDATE "UserTwoFactor" SET "enabled"=FALSE,"secretEncrypted"=NULL,"lastUsedStep"=NULL,"updatedAt"=CURRENT_TIMESTAMP WHERE "userId"=$1`,auth.user.id);await tx.$executeRawUnsafe(`DELETE FROM "TwoFactorRecoveryCode" WHERE "userId"=$1`,auth.user.id)});return reply.send({disabled:true})});
}