import { createHash, randomUUID } from "node:crypto";
import { prisma } from "@pa/database";
import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { requireListingUser } from "./listing-auth.js";
import { requireAdminRoles } from "./rbac.js";
import { deliverUserEvent } from "./notification-delivery.js";
import { createPresignedDownload, deleteStoredObject, storageConfigured, uploadPrivateStoredObject } from "./storage.js";

const incidentTypes=["DAMAGE","ACCESS","CLEANLINESS","SAFETY","BEHAVIOR","NO_SHOW","OTHER"] as const;
const EVIDENCE_MIME_TYPES=new Set(["image/jpeg","image/png","image/webp","image/avif","application/pdf"]);
const MAX_EVIDENCE_BYTES=10*1024*1024;
type IncidentType=typeof incidentTypes[number];
type StayState="UPCOMING"|"CHECKED_IN"|"NO_SHOW"|"CHECKED_OUT";
type ParticipantRole="HOST"|"GUEST";
type ClaimStatus="NONE"|"REQUESTED"|"UNDER_REVIEW"|"APPROVED"|"REJECTED";

type ReservationRow={id:string;listingId:string;guestId:string;hostId:string;status:string;checkIn:Date|string;checkOut:Date|string;title:string|null;checkInFrom:string|null;checkOutUntil:string|null};
type LifecycleRow={reservationId:string;state:StayState;checkedInAt:Date|null;checkedInById:string|null;noShowAt:Date|null;noShowById:string|null;checkedOutAt:Date|null;checkedOutById:string|null;updatedAt:Date};
type IncidentRow={id:string;reservationId:string;openedById:string;type:IncidentType;summary:string;status:"OPEN"|"UNDER_REVIEW"|"RESOLVED"|"CLOSED";supportTicketId:string|null;supportReference:string|null;resolution:string|null;claimStatus:ClaimStatus;claimedAmountMinor:number|null;approvedAmountMinor:number|null;currency:string;claimDecisionNote:string|null;createdAt:Date;updatedAt:Date;resolvedAt:Date|null};
type EvidenceRow={id:string;incidentId:string;uploadedById:string|null;fileName:string;mimeType:string;sizeBytes:number;objectKey:string;createdAt:Date};

const SESSION_COOKIE="pa_session";
function sha256(value:string){return createHash("sha256").update(value).digest("hex")}
async function adminUserId(request:FastifyRequest){const token=request.cookies[SESSION_COOKIE];if(!token)return null;const session=await prisma.session.findUnique({where:{tokenHash:sha256(token)},select:{userId:true}}).catch(()=>null);return session?.userId??null}
function dateOnly(value:Date|string){return value instanceof Date?value.toISOString().slice(0,10):String(value).slice(0,10)}
function parisToday(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const get=(t:string)=>parts.find(p=>p.type===t)?.value??"";return `${get("year")}-${get("month")}-${get("day")}`}
function parisOffset(date:string,time:string){const probe=new Date(`${date}T${time}:00Z`);const name=new Intl.DateTimeFormat("en-US",{timeZone:"Europe/Paris",timeZoneName:"shortOffset",hour:"2-digit"}).formatToParts(probe).find(p=>p.type==="timeZoneName")?.value??"GMT+1";const m=name.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/);if(!m)return 60;const minutes=Number(m[2])*60+Number(m[3]??0);return m[1]==="-"?-minutes:minutes}
function parisDateTimeMs(date:string,time:string){return Date.parse(`${date}T${time}:00Z`)-parisOffset(date,time)*60_000}
function incidentLabel(type:IncidentType){return type==="DAMAGE"?"Dommage":type==="ACCESS"?"Accès / clés":type==="CLEANLINESS"?"Propreté":type==="SAFETY"?"Sécurité":type==="BEHAVIOR"?"Comportement":type==="NO_SHOW"?"Voyageur absent":"Autre incident"}
function supportPriority(type:IncidentType){return type==="SAFETY"?"URGENT":"HIGH"}
function supportCategory(type:IncidentType){return type==="SAFETY"?"SAFETY":"DISPUTE"}
function evidenceExtension(mimeType:string){return mimeType==="application/pdf"?"pdf":mimeType==="image/jpeg"?"jpg":mimeType==="image/png"?"png":mimeType==="image/avif"?"avif":"webp"}
function evidenceShape(row:EvidenceRow,admin=false){return{id:row.id,incidentId:row.incidentId,uploadedById:row.uploadedById,fileName:row.fileName,mimeType:row.mimeType,sizeBytes:row.sizeBytes,createdAt:row.createdAt.toISOString(),downloadUrl:admin?`/api/admin/vacation-incidents/${row.incidentId}/evidence/${row.id}/download`:`/api/vacances/incidents/${row.incidentId}/evidence/${row.id}/download`}}
async function incidentParticipant(userId:string,incidentId:string){const rows=await prisma.$queryRawUnsafe<Array<IncidentRow&{guestId:string;hostId:string;listingId:string;title:string|null}>>(`SELECT i.*,r."guestId",r."hostId",r."listingId",l."title",t."reference" AS "supportReference" FROM "VacationIncident" i JOIN "VacationReservationRequest" r ON r."id"=i."reservationId" JOIN "Listing" l ON l."id"=r."listingId" LEFT JOIN "SupportTicket" t ON t."id"=i."supportTicketId" WHERE i."id"=$1 LIMIT 1`,incidentId);const row=rows[0];if(!row||(row.guestId!==userId&&row.hostId!==userId))return null;return row}
async function evidenceForIncident(incidentId:string){return prisma.$queryRawUnsafe<EvidenceRow[]>(`SELECT * FROM "VacationIncidentEvidence" WHERE "incidentId"=$1 ORDER BY "createdAt" ASC`,incidentId)}

async function reservationForUser(userId:string,reservationId:string){
 const rows=await prisma.$queryRawUnsafe<ReservationRow[]>(`SELECT r."id",r."listingId",r."guestId",r."hostId",r."status",r."checkIn",r."checkOut",l."title",o."checkInFrom",o."checkOutUntil" FROM "VacationReservationRequest" r JOIN "Listing" l ON l."id"=r."listingId" LEFT JOIN "VacationStayOperations" o ON o."listingId"=r."listingId" WHERE r."id"=$1 LIMIT 1`,reservationId);const row=rows[0];if(!row||(row.guestId!==userId&&row.hostId!==userId))return null;return row;
}
function roleFor(userId:string,r:ReservationRow):ParticipantRole{return r.hostId===userId?"HOST":"GUEST"}
async function lifecycle(reservationId:string){const rows=await prisma.$queryRawUnsafe<LifecycleRow[]>(`SELECT * FROM "VacationStayLifecycle" WHERE "reservationId"=$1 LIMIT 1`,reservationId);return rows[0]??null}
async function incidents(reservationId:string){return prisma.$queryRawUnsafe<IncidentRow[]>(`SELECT i.*,t."reference" AS "supportReference" FROM "VacationIncident" i LEFT JOIN "SupportTicket" t ON t."id"=i."supportTicketId" WHERE i."reservationId"=$1 ORDER BY i."createdAt" DESC`,reservationId)}
async function holdPayout(reservationId:string,reason:string){await prisma.$executeRawUnsafe(`UPDATE "VacationDepositPayout" SET "status"='HOLD',"failureReason"=$2,"updatedAt"=NOW() WHERE "reservationId"=$1 AND "status" IN ('PENDING','HOLD','FAILED')`,reservationId,reason).catch(()=>undefined)}
async function releasePayoutIfClear(reservationId:string){const active=await prisma.$queryRawUnsafe<Array<{count:bigint}>>(`SELECT COUNT(*)::bigint AS count FROM "VacationIncident" WHERE "reservationId"=$1 AND "status" IN ('OPEN','UNDER_REVIEW')`,reservationId);if(Number(active[0]?.count??0)>0)return false;const changed=await prisma.$executeRawUnsafe(`UPDATE "VacationDepositPayout" SET "status"='PENDING',"failureReason"=NULL,"updatedAt"=NOW() WHERE "reservationId"=$1 AND "status"='HOLD' AND "failureReason" IN ('vacation_incident_open','vacation_no_show_review')`,reservationId);return Number(changed)>0}

async function openIncident(input:{reservation:ReservationRow;openedById:string;type:IncidentType;summary:string;role:ParticipantRole}){
 const count=await prisma.$queryRawUnsafe<Array<{count:bigint}>>(`SELECT COUNT(*)::bigint AS count FROM "VacationIncident" WHERE "reservationId"=$1 AND "status" IN ('OPEN','UNDER_REVIEW')`,input.reservation.id);if(Number(count[0]?.count??0)>=3)throw new Error("incident_limit_reached");
 if(input.type==="NO_SHOW"){const existing=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "VacationIncident" WHERE "reservationId"=$1 AND "type"='NO_SHOW' AND "status" IN ('OPEN','UNDER_REVIEW') LIMIT 1`,input.reservation.id);if(existing.length)throw new Error("no_show_already_reported")}
 const id=randomUUID(),ticketId=randomUUID(),reference=`VAC-${Date.now().toString(36).toUpperCase()}-${id.slice(0,6).toUpperCase()}`;const subject=`Vacances · ${incidentLabel(input.type)} · ${input.reservation.title??"Hébergement"}`.slice(0,180);const body=`Incident Vacances ${id}
Réservation : ${input.reservation.id}
Déclaré par : ${input.role==="HOST"?"Hôte":"Voyageur"}
Type : ${incidentLabel(input.type)}

${input.summary}`;
 await prisma.$transaction(async tx=>{await tx.$executeRawUnsafe(`INSERT INTO "SupportTicket" ("id","reference","userId","category","subject","status","priority","listingId","lastMessageAt","createdAt","updatedAt") VALUES ($1,$2,$3,$4::"SupportTicketCategory",$5,'PENDING_INTERNAL',$6::"SupportTicketPriority",$7,NOW(),NOW(),NOW())`,ticketId,reference,input.openedById,supportCategory(input.type),subject,supportPriority(input.type),input.reservation.listingId);await tx.$executeRawUnsafe(`INSERT INTO "VacationIncident" ("id","reservationId","openedById","type","summary","status","supportTicketId","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,'OPEN',$6,NOW(),NOW())`,id,input.reservation.id,input.openedById,input.type,input.summary,ticketId);if(input.type==="NO_SHOW"){const changed=await tx.$queryRawUnsafe<Array<{reservationId:string}>>(`INSERT INTO "VacationStayLifecycle" ("reservationId","state","noShowAt","noShowById","createdAt","updatedAt") VALUES ($1,'NO_SHOW',NOW(),$2,NOW(),NOW()) ON CONFLICT ("reservationId") DO UPDATE SET "state"='NO_SHOW',"noShowAt"=NOW(),"noShowById"=$2,"updatedAt"=NOW() WHERE "VacationStayLifecycle"."state"='UPCOMING' RETURNING "reservationId"`,input.reservation.id,input.openedById);if(!changed.length)throw new Error("invalid_stay_state")}await tx.$executeRawUnsafe(`INSERT INTO "SupportTicketMessage" ("id","ticketId","authorUserId","authorType","body") VALUES ($1,$2,$3,'CUSTOMER',$4)`,randomUUID(),ticketId,input.openedById,body)});
 await holdPayout(input.reservation.id,input.type==="NO_SHOW"?"vacation_no_show_review":"vacation_incident_open");const other=input.role==="HOST"?input.reservation.guestId:input.reservation.hostId;await Promise.all([deliverUserEvent({userId:other,eventKind:"LISTING",notificationKind:"SYSTEM",title:"Incident signalé sur un séjour Vacances",body:`Un incident « ${incidentLabel(input.type)} » a été déclaré pour ${input.reservation.title??"votre réservation"}. Le service client peut examiner le dossier ${reference}.`,actionUrl:"/mon-compte/reservations",transactional:true,dedupeKey:`vacation-incident:${id}:other`,metadata:{reservationId:input.reservation.id,incidentId:id,supportTicketId:ticketId}}),deliverUserEvent({userId:input.openedById,eventKind:"LISTING",notificationKind:"SYSTEM",title:"Signalement Vacances enregistré",body:`Votre dossier ${reference} a été transmis au service client.`,actionUrl:`/assistance?ticket=${encodeURIComponent(ticketId)}`,transactional:true,dedupeKey:`vacation-incident:${id}:opener`,metadata:{reservationId:input.reservation.id,incidentId:id,supportTicketId:ticketId}})]).catch(()=>undefined);return{id,support:{ticketId,reference}};
}

export async function ensureVacationStayLifecycleSchema(){
 await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "VacationStayLifecycle" ("reservationId" TEXT PRIMARY KEY REFERENCES "VacationReservationRequest"("id") ON DELETE CASCADE,"state" TEXT NOT NULL DEFAULT 'UPCOMING',"checkedInAt" TIMESTAMPTZ NULL,"checkedInById" TEXT NULL REFERENCES "User"("id") ON DELETE SET NULL,"noShowAt" TIMESTAMPTZ NULL,"noShowById" TEXT NULL REFERENCES "User"("id") ON DELETE SET NULL,"checkedOutAt" TIMESTAMPTZ NULL,"checkedOutById" TEXT NULL REFERENCES "User"("id") ON DELETE SET NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "VacationStayLifecycle_state" CHECK ("state" IN ('UPCOMING','CHECKED_IN','NO_SHOW','CHECKED_OUT')))`);
 await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "VacationIncident" ("id" TEXT PRIMARY KEY,"reservationId" TEXT NOT NULL REFERENCES "VacationReservationRequest"("id") ON DELETE CASCADE,"openedById" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,"type" TEXT NOT NULL,"summary" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'OPEN',"supportTicketId" TEXT NULL REFERENCES "SupportTicket"("id") ON DELETE SET NULL,"resolution" TEXT NULL,"resolvedById" TEXT NULL REFERENCES "User"("id") ON DELETE SET NULL,"resolvedAt" TIMESTAMPTZ NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "VacationIncident_type" CHECK ("type" IN ('DAMAGE','ACCESS','CLEANLINESS','SAFETY','BEHAVIOR','NO_SHOW','OTHER')),CONSTRAINT "VacationIncident_status" CHECK ("status" IN ('OPEN','UNDER_REVIEW','RESOLVED','CLOSED')))`);
 await prisma.$executeRawUnsafe(`ALTER TABLE "VacationIncident" ADD COLUMN IF NOT EXISTS "claimStatus" TEXT NOT NULL DEFAULT 'NONE'`);
 await prisma.$executeRawUnsafe(`ALTER TABLE "VacationIncident" ADD COLUMN IF NOT EXISTS "claimedAmountMinor" INTEGER NULL`);
 await prisma.$executeRawUnsafe(`ALTER TABLE "VacationIncident" ADD COLUMN IF NOT EXISTS "approvedAmountMinor" INTEGER NULL`);
 await prisma.$executeRawUnsafe(`ALTER TABLE "VacationIncident" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'EUR'`);
 await prisma.$executeRawUnsafe(`ALTER TABLE "VacationIncident" ADD COLUMN IF NOT EXISTS "claimDecisionNote" TEXT NULL`);
 await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "VacationIncidentEvidence" ("id" TEXT PRIMARY KEY,"incidentId" TEXT NOT NULL REFERENCES "VacationIncident"("id") ON DELETE CASCADE,"uploadedById" TEXT NULL REFERENCES "User"("id") ON DELETE SET NULL,"objectKey" TEXT NOT NULL,"fileName" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"sizeBytes" INTEGER NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`);
 await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "VacationIncidentEvidence_incident_created_idx" ON "VacationIncidentEvidence" ("incidentId","createdAt")`);
 await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "VacationIncident_reservation_status_idx" ON "VacationIncident" ("reservationId","status","createdAt" DESC)`);
 await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "VacationIncident_support_ticket_idx" ON "VacationIncident" ("supportTicketId") WHERE "supportTicketId" IS NOT NULL`);
 await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "VacationIncident_active_noshow_idx" ON "VacationIncident" ("reservationId") WHERE "type"='NO_SHOW' AND "status" IN ('OPEN','UNDER_REVIEW')`);
}

export function registerVacationStayLifecycleRoutes(app:FastifyInstance){
 app.addContentTypeParser("application/vnd.petitannonces.vacation-evidence",{parseAs:"buffer",bodyLimit:MAX_EVIDENCE_BYTES},(_request,body,done)=>done(null,body));
 app.get("/vacances/reservations/:id/stay-lifecycle",async(request,reply)=>{
  const user=await requireListingUser(request,reply);if(!user)return;
  const params=z.object({id:z.string().min(1)}).safeParse(request.params);if(!params.success)return reply.code(400).send({error:"invalid_request"});
  const r=await reservationForUser(user.id,params.data.id);if(!r)return reply.code(404).send({error:"reservation_not_found"});if(r.status!=="ACCEPTED")return reply.code(409).send({error:"reservation_not_accepted"});
  const role=roleFor(user.id,r),state=await lifecycle(r.id),allIncidents=await incidents(r.id);const checkIn=dateOnly(r.checkIn),checkOut=dateOnly(r.checkOut),currentState=state?.state??"UPCOMING",checkInStart=parisDateTimeMs(checkIn,r.checkInFrom??"15:00");
  const incidentPayload=await Promise.all(allIncidents.map(async i=>({...i,isReporter:i.openedById===user.id,evidence:(await evidenceForIncident(i.id)).map(row=>evidenceShape(row)),createdAt:i.createdAt.toISOString(),updatedAt:i.updatedAt.toISOString(),resolvedAt:i.resolvedAt?.toISOString()??null})));
  return reply.send({role,state:currentState,checkedInAt:state?.checkedInAt?.toISOString()??null,noShowAt:state?.noShowAt?.toISOString()??null,checkedOutAt:state?.checkedOutAt?.toISOString()??null,checkIn,checkOut,canCheckIn:currentState==="UPCOMING"&&parisToday()>=checkIn,canNoShow:role==="HOST"&&currentState==="UPCOMING"&&Date.now()>=checkInStart+2*3600_000,canCheckOut:currentState==="CHECKED_IN",incidents:incidentPayload});
 });
 app.post("/vacances/reservations/:id/stay-lifecycle",async(request,reply)=>{const user=await requireListingUser(request,reply);if(!user)return;const params=z.object({id:z.string().min(1)}).safeParse(request.params);const body=z.object({action:z.enum(["CHECK_IN","NO_SHOW","CHECK_OUT"])}).safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({error:"invalid_request"});const r=await reservationForUser(user.id,params.data.id);if(!r)return reply.code(404).send({error:"reservation_not_found"});if(r.status!=="ACCEPTED")return reply.code(409).send({error:"reservation_not_accepted"});const role=roleFor(user.id,r),current=(await lifecycle(r.id))?.state??"UPCOMING",other=role==="HOST"?r.guestId:r.hostId;
  if(body.data.action==="CHECK_IN"){if(current!=="UPCOMING")return reply.code(409).send({error:"invalid_stay_state"});if(parisToday()<dateOnly(r.checkIn))return reply.code(409).send({error:"checkin_not_started"});await prisma.$executeRawUnsafe(`INSERT INTO "VacationStayLifecycle" ("reservationId","state","checkedInAt","checkedInById","createdAt","updatedAt") VALUES ($1,'CHECKED_IN',NOW(),$2,NOW(),NOW()) ON CONFLICT ("reservationId") DO UPDATE SET "state"='CHECKED_IN',"checkedInAt"=COALESCE("VacationStayLifecycle"."checkedInAt",NOW()),"checkedInById"=COALESCE("VacationStayLifecycle"."checkedInById",$2),"updatedAt"=NOW() WHERE "VacationStayLifecycle"."state"='UPCOMING'`,r.id,user.id);await deliverUserEvent({userId:other,eventKind:"LISTING",notificationKind:"SYSTEM",title:"Arrivée confirmée",body:`L’arrivée pour ${r.title??"le séjour Vacances"} a été confirmée.`,actionUrl:"/mon-compte/reservations",transactional:true,dedupeKey:`vacation-stay:${r.id}:checked-in`,metadata:{reservationId:r.id,state:"CHECKED_IN"}}).catch(()=>undefined);return reply.send({saved:true,state:"CHECKED_IN"});}
  if(body.data.action==="NO_SHOW"){if(role!=="HOST")return reply.code(403).send({error:"host_required"});if(current!=="UPCOMING")return reply.code(409).send({error:"invalid_stay_state"});const start=parisDateTimeMs(dateOnly(r.checkIn),r.checkInFrom??"15:00");if(Date.now()<start+2*3600_000)return reply.code(409).send({error:"no_show_too_early"});let opened;try{opened=await openIncident({reservation:r,openedById:user.id,type:"NO_SHOW",summary:"Le voyageur ne s’est pas présenté après l’heure d’arrivée prévue. Vérification demandée avant tout versement d’acompte.",role})}catch(error){const code=error instanceof Error?error.message:"";if(code==="incident_limit_reached"||code==="no_show_already_reported"||code==="invalid_stay_state")return reply.code(409).send({error:code});if(String(error).includes("VacationIncident_active_noshow_idx"))return reply.code(409).send({error:"no_show_already_reported"});throw error}return reply.send({saved:true,state:"NO_SHOW",incidentId:opened.id,supportTicketId:opened.support.ticketId});}
  if(current!=="CHECKED_IN")return reply.code(409).send({error:"stay_not_checked_in"});await prisma.$executeRawUnsafe(`UPDATE "VacationStayLifecycle" SET "state"='CHECKED_OUT',"checkedOutAt"=NOW(),"checkedOutById"=$2,"updatedAt"=NOW() WHERE "reservationId"=$1 AND "state"='CHECKED_IN'`,r.id,user.id);await deliverUserEvent({userId:other,eventKind:"LISTING",notificationKind:"SYSTEM",title:"Départ confirmé",body:`Le départ pour ${r.title??"le séjour Vacances"} a été confirmé.`,actionUrl:"/mon-compte/reservations",transactional:true,dedupeKey:`vacation-stay:${r.id}:checked-out`,metadata:{reservationId:r.id,state:"CHECKED_OUT"}}).catch(()=>undefined);return reply.send({saved:true,state:"CHECKED_OUT"});
 });
 app.post("/vacances/reservations/:id/incidents",async(request,reply)=>{const user=await requireListingUser(request,reply);if(!user)return;const params=z.object({id:z.string().min(1)}).safeParse(request.params);const body=z.object({type:z.enum(incidentTypes),summary:z.string().trim().min(20).max(3000)}).safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({error:"invalid_request"});const r=await reservationForUser(user.id,params.data.id);if(!r)return reply.code(404).send({error:"reservation_not_found"});if(r.status!=="ACCEPTED")return reply.code(409).send({error:"reservation_not_accepted"});const role=roleFor(user.id,r);if(body.data.type==="NO_SHOW")return reply.code(409).send({error:"use_stay_lifecycle_no_show"});try{const opened=await openIncident({reservation:r,openedById:user.id,type:body.data.type,summary:body.data.summary,role});return reply.code(201).send({incidentId:opened.id,supportTicketId:opened.support.ticketId,supportReference:opened.support.reference,status:"OPEN"})}catch(error){if(error instanceof Error&&error.message==="incident_limit_reached")return reply.code(409).send({error:"incident_limit_reached"});throw error}
 });
 app.patch("/vacances/incidents/:id/claim",async(request,reply)=>{
  const user=await requireListingUser(request,reply);if(!user)return;
  const params=z.object({id:z.string().min(1)}).safeParse(request.params);const body=z.object({amountMinor:z.number().int().min(100).max(5_000_000)}).safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({error:"invalid_request"});
  const incident=await incidentParticipant(user.id,params.data.id);if(!incident)return reply.code(404).send({error:"incident_not_found"});if(incident.hostId!==user.id||incident.type!=="DAMAGE")return reply.code(403).send({error:"damage_claim_host_only"});if(!["OPEN","UNDER_REVIEW"].includes(incident.status))return reply.code(409).send({error:"incident_closed"});
  await prisma.$executeRawUnsafe(`UPDATE "VacationIncident" SET "claimedAmountMinor"=$2,"currency"='EUR',"claimStatus"='REQUESTED',"approvedAmountMinor"=NULL,"claimDecisionNote"=NULL,"status"='UNDER_REVIEW',"updatedAt"=NOW() WHERE "id"=$1`,incident.id,body.data.amountMinor);
  if(incident.supportTicketId){const authorType=incident.openedById===user.id?"CUSTOMER":"SYSTEM";await prisma.$executeRawUnsafe(`INSERT INTO "SupportTicketMessage" ("id","ticketId","authorUserId","authorType","body") VALUES ($1,$2,$3,$4::"SupportMessageAuthorType",$5)`,randomUUID(),incident.supportTicketId,user.id,authorType,`Montant du préjudice déclaré par l’hôte : ${(body.data.amountMinor/100).toFixed(2)} €.`).catch(()=>undefined);}
  await deliverUserEvent({userId:incident.guestId,eventKind:"LISTING",notificationKind:"SYSTEM",title:"Demande d’indemnisation Vacances",body:`L’hôte a déclaré un préjudice estimé à ${(body.data.amountMinor/100).toFixed(2)} € pour ${incident.title??"votre séjour"}. Aucun montant supplémentaire n’est débité automatiquement ; le dossier doit être examiné.`,actionUrl:"/mon-compte/reservations",transactional:true,dedupeKey:`vacation-claim:${incident.id}:${body.data.amountMinor}`,metadata:{reservationId:incident.reservationId,incidentId:incident.id,claimedAmountMinor:body.data.amountMinor}}).catch(()=>undefined);
  return reply.send({saved:true,claimStatus:"REQUESTED",claimedAmountMinor:body.data.amountMinor,currency:"EUR"});
 });
 app.post("/vacances/incidents/:id/evidence/upload-direct",{bodyLimit:MAX_EVIDENCE_BYTES},async(request,reply)=>{
  const user=await requireListingUser(request,reply);if(!user)return;if(!storageConfigured())return reply.code(503).send({error:"object_storage_not_configured"});
  const params=z.object({id:z.string().min(1)}).safeParse(request.params);if(!params.success)return reply.code(400).send({error:"invalid_request"});const incident=await incidentParticipant(user.id,params.data.id);if(!incident)return reply.code(404).send({error:"incident_not_found"});if(!["OPEN","UNDER_REVIEW"].includes(incident.status))return reply.code(409).send({error:"incident_closed"});
  const mimeType=String(request.headers["x-file-mime"]??"").toLowerCase();if(!EVIDENCE_MIME_TYPES.has(mimeType))return reply.code(415).send({error:"unsupported_evidence_type"});const data=request.body;if(!Buffer.isBuffer(data)||data.length<1)return reply.code(400).send({error:"empty_evidence"});if(data.length>MAX_EVIDENCE_BYTES)return reply.code(413).send({error:"evidence_too_large",maxBytes:MAX_EVIDENCE_BYTES});
  const count=await prisma.$queryRawUnsafe<Array<{count:bigint}>>(`SELECT COUNT(*)::bigint AS count FROM "VacationIncidentEvidence" WHERE "incidentId"=$1`,incident.id);if(Number(count[0]?.count??0n)>=12)return reply.code(409).send({error:"evidence_limit_reached",limit:12});
  const rawName=String(request.headers["x-file-name"]??"justificatif");let fileName=rawName.slice(0,180);try{fileName=decodeURIComponent(rawName).slice(0,180)}catch{}const evidenceId=randomUUID(),objectKey=`private/vacation-incidents/${incident.id}/${evidenceId}.${evidenceExtension(mimeType)}`;await uploadPrivateStoredObject(objectKey,mimeType,data);
  try{await prisma.$executeRawUnsafe(`INSERT INTO "VacationIncidentEvidence" ("id","incidentId","uploadedById","objectKey","fileName","mimeType","sizeBytes") VALUES ($1,$2,$3,$4,$5,$6,$7)`,evidenceId,incident.id,user.id,objectKey,fileName,mimeType,data.length)}catch(error){await deleteStoredObject(objectKey).catch(()=>undefined);throw error}
  if(incident.supportTicketId){const authorType=incident.openedById===user.id?"CUSTOMER":"SYSTEM";await prisma.$executeRawUnsafe(`INSERT INTO "SupportTicketMessage" ("id","ticketId","authorUserId","authorType","body") VALUES ($1,$2,$3,$4::"SupportMessageAuthorType",$5)`,randomUUID(),incident.supportTicketId,user.id,authorType,`Justificatif ajouté${authorType==="SYSTEM"?" par l’autre partie":""} : ${fileName}`).catch(()=>undefined);}
  const other=incident.hostId===user.id?incident.guestId:incident.hostId;await deliverUserEvent({userId:other,eventKind:"LISTING",notificationKind:"SYSTEM",title:"Nouveau justificatif Vacances",body:`Un justificatif a été ajouté au dossier ${incident.supportReference??incident.id.slice(0,8)}.`,actionUrl:"/mon-compte/reservations",transactional:true,dedupeKey:`vacation-evidence:${evidenceId}:${other}`,metadata:{reservationId:incident.reservationId,incidentId:incident.id,evidenceId}}).catch(()=>undefined);
  const rows=await evidenceForIncident(incident.id);const row=rows.find(x=>x.id===evidenceId)!;return reply.code(201).send({evidence:evidenceShape(row)});
 });
 app.get("/vacances/incidents/:id/evidence/:evidenceId/download",async(request,reply)=>{
  const user=await requireListingUser(request,reply);if(!user)return;const params=z.object({id:z.string().min(1),evidenceId:z.string().min(1)}).safeParse(request.params);if(!params.success)return reply.code(400).send({error:"invalid_request"});const incident=await incidentParticipant(user.id,params.data.id);if(!incident)return reply.code(404).send({error:"incident_not_found"});const rows=await prisma.$queryRawUnsafe<EvidenceRow[]>(`SELECT * FROM "VacationIncidentEvidence" WHERE "id"=$1 AND "incidentId"=$2 LIMIT 1`,params.data.evidenceId,incident.id);const evidence=rows[0];if(!evidence)return reply.code(404).send({error:"evidence_not_found"});return reply.redirect(await createPresignedDownload(evidence.objectKey,evidence.fileName,90));
 });
 app.post("/admin/vacation-incidents/:id/assessment",{preHandler:requireAdminRoles(["SUPER_ADMIN","ADMIN","SUPPORT","FINANCE"])},async(request,reply)=>{
  const params=z.object({id:z.string().min(1)}).safeParse(request.params);const body=z.object({decision:z.enum(["APPROVED","REJECTED","NEEDS_MORE_INFO"]),approvedAmountMinor:z.number().int().min(0).max(5_000_000).optional(),note:z.string().trim().max(2000).optional()}).safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({error:"invalid_request"});const adminId=await adminUserId(request);
  const rows=await prisma.$queryRawUnsafe<Array<IncidentRow&{guestId:string;hostId:string;title:string|null}>>(`SELECT i.*,r."guestId",r."hostId",l."title",t."reference" AS "supportReference" FROM "VacationIncident" i JOIN "VacationReservationRequest" r ON r."id"=i."reservationId" JOIN "Listing" l ON l."id"=r."listingId" LEFT JOIN "SupportTicket" t ON t."id"=i."supportTicketId" WHERE i."id"=$1 LIMIT 1`,params.data.id);const incident=rows[0];if(!incident)return reply.code(404).send({error:"incident_not_found"});if(!["OPEN","UNDER_REVIEW"].includes(incident.status))return reply.code(409).send({error:"incident_closed"});if(!incident.claimedAmountMinor||incident.claimStatus==="NONE")return reply.code(409).send({error:"no_compensation_claim"});
  const approved=body.data.decision==="APPROVED"?(body.data.approvedAmountMinor??incident.claimedAmountMinor):null;if(approved!==null&&(approved<100||approved>incident.claimedAmountMinor))return reply.code(400).send({error:"invalid_approved_amount"});const claimStatus:ClaimStatus=body.data.decision==="APPROVED"?"APPROVED":body.data.decision==="REJECTED"?"REJECTED":"UNDER_REVIEW";
  await prisma.$executeRawUnsafe(`UPDATE "VacationIncident" SET "claimStatus"=$2,"approvedAmountMinor"=$3,"claimDecisionNote"=$4,"status"='UNDER_REVIEW',"updatedAt"=NOW() WHERE "id"=$1`,incident.id,claimStatus,approved,body.data.note?.trim()||null);
  const decisionText=claimStatus==="APPROVED"?`Montant retenu après examen : ${(approved!/100).toFixed(2)} €.`:claimStatus==="REJECTED"?"La demande d’indemnisation a été rejetée après examen.":"Des éléments complémentaires sont nécessaires avant décision.";if(incident.supportTicketId)await prisma.$executeRawUnsafe(`INSERT INTO "SupportTicketMessage" ("id","ticketId","authorUserId","authorType","body") VALUES ($1,$2,$3,'AGENT',$4)`,randomUUID(),incident.supportTicketId,adminId,`${decisionText}${body.data.note?.trim()?`\n${body.data.note.trim()}`:""}`).catch(()=>undefined);
  await Promise.all([incident.guestId,incident.hostId].map(userId=>deliverUserEvent({userId,eventKind:"LISTING",notificationKind:"SYSTEM",title:"Évaluation du dossier Vacances",body:`${decisionText} Aucun débit supplémentaire n’est effectué automatiquement.`,actionUrl:"/mon-compte/reservations",transactional:true,dedupeKey:`vacation-assessment:${incident.id}:${claimStatus}:${approved??0}:${userId}`,metadata:{reservationId:incident.reservationId,incidentId:incident.id,claimStatus,approvedAmountMinor:approved}}))).catch(()=>undefined);
  return reply.send({assessed:true,claimStatus,approvedAmountMinor:approved,currency:incident.currency??"EUR"});
 });
 app.get("/admin/vacation-incidents/:id/evidence/:evidenceId/download",{preHandler:requireAdminRoles(["SUPER_ADMIN","ADMIN","SUPPORT","FINANCE"])},async(request,reply)=>{const params=z.object({id:z.string().min(1),evidenceId:z.string().min(1)}).safeParse(request.params);if(!params.success)return reply.code(400).send({error:"invalid_request"});const rows=await prisma.$queryRawUnsafe<EvidenceRow[]>(`SELECT * FROM "VacationIncidentEvidence" WHERE "id"=$1 AND "incidentId"=$2 LIMIT 1`,params.data.evidenceId,params.data.id);const evidence=rows[0];if(!evidence)return reply.code(404).send({error:"evidence_not_found"});return reply.redirect(await createPresignedDownload(evidence.objectKey,evidence.fileName,90));});
 app.post("/admin/vacation-incidents/:id/resolve",{preHandler:requireAdminRoles(["SUPER_ADMIN","ADMIN","SUPPORT","FINANCE"])},async(request,reply)=>{const params=z.object({id:z.string().min(1)}).safeParse(request.params);const body=z.object({decision:z.enum(["RELEASE_HOST","KEEP_HOLD","REFUND_REVIEW"]),note:z.string().trim().max(2000).optional()}).safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({error:"invalid_request"});const adminId=await adminUserId(request);const rows=await prisma.$queryRawUnsafe<Array<IncidentRow&{guestId:string;hostId:string;title:string|null}>>(`SELECT i.*,r."guestId",r."hostId",l."title",t."reference" AS "supportReference" FROM "VacationIncident" i JOIN "VacationReservationRequest" r ON r."id"=i."reservationId" JOIN "Listing" l ON l."id"=r."listingId" LEFT JOIN "SupportTicket" t ON t."id"=i."supportTicketId" WHERE i."id"=$1 LIMIT 1`,params.data.id);const incident=rows[0];if(!incident)return reply.code(404).send({error:"incident_not_found"});if(!["OPEN","UNDER_REVIEW"].includes(incident.status))return reply.code(409).send({error:"incident_already_resolved"});if(incident.claimedAmountMinor&&["REQUESTED","UNDER_REVIEW"].includes(incident.claimStatus))return reply.code(409).send({error:"claim_assessment_required"});const resolution=body.data.decision;await prisma.$transaction(async tx=>{await tx.$executeRawUnsafe(`UPDATE "VacationIncident" SET "status"='RESOLVED',"resolution"=$2,"resolvedById"=$3,"resolvedAt"=NOW(),"updatedAt"=NOW() WHERE "id"=$1`,incident.id,resolution,adminId);if(incident.supportTicketId){await tx.$executeRawUnsafe(`UPDATE "SupportTicket" SET "status"='RESOLVED',"resolvedAt"=NOW(),"lastMessageAt"=NOW(),"updatedAt"=NOW() WHERE "id"=$1`,incident.supportTicketId);await tx.$executeRawUnsafe(`INSERT INTO "SupportTicketMessage" ("id","ticketId","authorUserId","authorType","body") VALUES ($1,$2,$3,'AGENT',$4)`,randomUUID(),incident.supportTicketId,adminId,body.data.note?.trim()||`Dossier Vacances résolu · décision paiement : ${resolution}`)}});let payoutReleased=false;if(resolution==="RELEASE_HOST")payoutReleased=await releasePayoutIfClear(incident.reservationId);else await holdPayout(incident.reservationId,resolution==="REFUND_REVIEW"?"vacation_refund_review":"vacation_incident_manual_hold");await Promise.all([incident.guestId,incident.hostId].map(userId=>deliverUserEvent({userId,eventKind:"LISTING",notificationKind:"SYSTEM",title:"Dossier Vacances mis à jour",body:`Le dossier ${incident.supportReference??incident.id.slice(0,8)} concernant ${incident.title??"un séjour Vacances"} a été traité par le service client.`,actionUrl:"/mon-compte/reservations",transactional:true,dedupeKey:`vacation-incident:${incident.id}:resolved:${resolution}:${userId}`,metadata:{reservationId:incident.reservationId,incidentId:incident.id,resolution}}))).catch(()=>undefined);return reply.send({resolved:true,resolution,payoutReleased});
 });
}

export async function vacationPayoutBlockedByIncident(reservationId:string){const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "VacationIncident" WHERE "reservationId"=$1 AND "status" IN ('OPEN','UNDER_REVIEW') LIMIT 1`,reservationId).catch(()=>[]);return rows.length>0}