"use client";
import {useEffect,useMemo,useState} from "react";
import {AppIcon} from "../../components/app-icon";
import styles from "./page.module.css";

type Cat={id:string;name:string;slug:string;children?:Cat[]};
type Preview={sourceUrl:string|null;title:string|null;description:string|null;priceMinor:number|null;imageUrl:string|null;imageUrls?:string[];city:string|null;postalCode:string|null;histovecUrl?:string|null;suggestedCategorySlug?:string|null;suggestionReason?:string|null;detectedFields?:Record<string,string|number|boolean>;manualRequired?:boolean};
type ImportSource="vinted"|"leboncoin"|"other";
const api=()=> (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"");
function previewImageSrc(imageUrl:string,sourceUrl:string){const qs=new URLSearchParams({imageUrl,sourceUrl});return `${api()}/listing-import/image-preview?${qs.toString()}`}
function categoryOptions(items:Cat[],prefix=""):Array<{id:string;label:string;slug:string}>{return items.flatMap(c=>[{id:c.id,label:`${prefix}${c.name}`,slug:c.slug},...(c.children?.length?categoryOptions(c.children,`${prefix}${c.name} › `):[])])}
function categoryPath(items:Cat[],targetId:string):{root:Cat;branch:Cat|null;item:Cat}|null{for(const root of items){if(root.id===targetId)return{root,branch:null,item:root};for(const child of root.children??[]){if(child.id===targetId)return{root,branch:child,item:child};for(const leaf of child.children??[])if(leaf.id===targetId)return{root,branch:child,item:leaf}}}return null}
function quality(preview:Preview|null,categoryId:string,imageCount:number){if(!preview)return{score:0,checks:[] as string[]};let score=0;const checks:string[]=[];if((preview.title??"").trim().length>=10)score+=20;else checks.push("Titre trop court");if((preview.description??"").trim().length>=80)score+=25;else checks.push("Description à compléter");if(preview.priceMinor!=null)score+=15;else checks.push("Prix à renseigner");if(categoryId)score+=15;else checks.push("Catégorie à choisir");const hasCity=Boolean((preview.city??"").trim()),hasPostal=Boolean((preview.postalCode??"").trim());if(hasCity&&hasPostal)score+=10;else if(hasCity||hasPostal){score+=5;checks.push("Ville ou code postal à compléter")}else checks.push("Localisation à compléter");if(imageCount>=3)score+=15;else if(imageCount>=1){score+=8;checks.push("Ajoutez idéalement 3 photos ou plus")}else checks.push("Aucune photo importée");return{score,checks}}
const detectedLabels:Record<string,string>={brand:"Marque",model:"Modèle",version:"Version / finition",modelYear:"Année modèle",firstRegistration:"1re mise en circulation",mileage:"Kilométrage",fuel:"Énergie",gearbox:"Boîte de vitesse",doors:"Portes",seats:"Places",color:"Couleur",critAir:"Crit’Air",fiscalPower:"Puissance fiscale",powerDinHp:"Puissance DIN",powerKw:"Puissance",bodyStyle:"Type de véhicule",warranty:"Garantie",propertyType:"Type de bien",surface:"Surface habitable",rooms:"Pièces",bedrooms:"Chambres",floor:"Étage",totalFloors:"Nombre d’étages",landM2:"Surface du terrain",furnished:"Meublé",elevator:"Ascenseur",parking:"Parking / garage",outdoor:"Extérieurs",heating:"Chauffage",charges:"Charges",deposit:"Dépôt de garantie",dpe:"Classe énergie",ges:"Classe climat",condition:"État",storage:"Stockage",ram:"Mémoire RAM",screenSize:"Taille écran",resolution:"Résolution",shoeSize:"Pointure",size:"Taille"};
function detectedLabel(key:string){return detectedLabels[key]??key.replace(/([a-z])([A-Z])/g,"$1 $2").replace(/^./,x=>x.toUpperCase())}
function sharedUrlFrom(...values:Array<string|null>){for(const value of values){const match=(value??"").match(/https?:\/\/[^\s<>"']+/i);if(match?.[0])return match[0].replace(/[\]),.;]+$/g,"")}return""}
function sourceFromUrl(value:string):ImportSource{try{const host=new URL(value).hostname.toLowerCase();if(host==="vinted.fr"||host.endsWith(".vinted.fr"))return"vinted";if(host==="leboncoin.fr"||host.endsWith(".leboncoin.fr"))return"leboncoin";return"other"}catch{return"other"}}
function validPublicUrl(value:string){try{const u=new URL(value.trim());return (u.protocol==="https:"||u.protocol==="http:")&&Boolean(u.hostname)}catch{return false}}

export default function ImportPage(){
 const[cats,setCats]=useState<Cat[]>([]),[rootCategoryId,setRootCategoryId]=useState(""),[branchCategoryId,setBranchCategoryId]=useState(""),[categoryId,setCategoryId]=useState("");const[url,setUrl]=useState("");const[preview,setPreview]=useState<Preview|null>(null);const[busy,setBusy]=useState(false),[msg,setMsg]=useState("");const[rights,setRights]=useState(false);const[duplicateUrl,setDuplicateUrl]=useState("");const[duplicateKind,setDuplicateKind]=useState<""|"exact"|"similar">("");const[selectedImages,setSelectedImages]=useState<string[]>([]);const[sourceHint,setSourceHint]=useState<ImportSource|"">("");const[sharedIncoming,setSharedIncoming]=useState(false);const[autoShared,setAutoShared]=useState(false);
 useEffect(()=>{const qs=new URLSearchParams(location.search);const hinted=qs.get("source"),hintedUrl=qs.get("url");if(hinted==="pwa-share"){const shareUrl=sharedUrlFrom(qs.get("share_url"),qs.get("share_text"),qs.get("share_title"));setSharedIncoming(true);if(shareUrl){setUrl(shareUrl);setSourceHint(sourceFromUrl(shareUrl));setAutoShared(true)}else setMsg("Le contenu partagé ne contient pas de lien d’annonce. Ouvrez l’annonce source puis partagez son URL vers Petit Annonces.")}else if(hintedUrl){setUrl(hintedUrl);setSourceHint(sourceFromUrl(hintedUrl));setAutoShared(true)}fetch(`${api()}/categories/tree`,{credentials:"include"}).then(r=>r.json()).then(p=>setCats(p.categories??[])).catch(()=>setMsg("Impossible de charger les catégories."))},[]);
 const options=useMemo(()=>categoryOptions(cats),[cats]);
 const rootCategory=useMemo(()=>cats.find(c=>c.id===rootCategoryId),[cats,rootCategoryId]);
 const branchCategory=useMemo(()=>rootCategory?.children?.find(c=>c.id===branchCategoryId),[rootCategory,branchCategoryId]);
 useEffect(()=>{if(!preview?.suggestedCategorySlug)return;const suggested=options.find(o=>o.slug===preview.suggestedCategorySlug);if(!suggested)return;const path=categoryPath(cats,suggested.id);if(!path)return;setRootCategoryId(path.root.id);setBranchCategoryId(path.branch?.id??"");setCategoryId(path.item.id)},[preview?.suggestedCategorySlug,options,cats]);
 const q=useMemo(()=>quality(preview,categoryId,selectedImages.length),[preview,categoryId,selectedImages.length]);
 const suggestedOption=preview?.suggestedCategorySlug?options.find(o=>o.slug===preview.suggestedCategorySlug):undefined;
 const selectedOption=categoryId?options.find(o=>o.id===categoryId):undefined;
 const categoryMismatch=Boolean(suggestedOption&&selectedOption&&suggestedOption.id!==selectedOption.id);
 const primaryPreviewImage=preview?.imageUrl??preview?.imageUrls?.[0]??null;
 function patch<K extends keyof Preview>(key:K,value:Preview[K]){setPreview(p=>p?{...p,[key]:value}:p)}
 async function analyze(){const raw=url.trim();setMsg("");setPreview(null);setDuplicateUrl("");setDuplicateKind("");setSelectedImages([]);setRootCategoryId("");setBranchCategoryId("");setCategoryId("");if(!validPublicUrl(raw)){setMsg("Collez l’URL complète de l’annonce source, par exemple https://www.leboncoin.fr/ad/...");return}setSourceHint(sourceFromUrl(raw));setBusy(true);try{const r=await fetch(`${api()}/listing-import/preview`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({url:raw})});const p=await r.json().catch(()=>({}));if(r.status===401){location.href=`/connexion?next=${encodeURIComponent(location.pathname+location.search)}`;return}if(!r.ok)throw new Error(p.error??"import_failed");setPreview(p.preview);if(p.preview?.sourceUrl)setSourceHint(sourceFromUrl(p.preview.sourceUrl));setSelectedImages((p.preview?.imageUrls??(p.preview?.imageUrl?[p.preview.imageUrl]:[])).slice(0,20))}catch(e){const c=e instanceof Error?e.message:"import_failed";setMsg(c==="invalid_request"||c==="unsupported_url"?"Le lien saisi n’est pas valide. Copiez l’URL complète de la page de l’annonce.":c==="source_listing_unavailable"?"Cette annonce semble supprimée, expirée ou non accessible publiquement.":c==="source_anti_bot_challenge"||c==="reader_unavailable"||c.startsWith("reader_http_")?"Le site source bloque temporairement la lecture automatique. Réessayez avec l’URL publique complète de l’annonce.":c.startsWith("source_http_")||c==="source_network_error"?"Le site source ne répond pas correctement pour ce lien. Vérifiez l’URL puis réessayez.":"Impossible d’analyser cette annonce publique. Vérifiez qu’elle est encore en ligne et accessible sans connexion.")}finally{setBusy(false)}}
 useEffect(()=>{if(!autoShared)return;setAutoShared(false);void analyze()},[autoShared]);
 async function create(forceSimilar=false){if(!preview||!preview.sourceUrl||!categoryId||!rights)return;setBusy(true);setMsg("");setDuplicateUrl("");setDuplicateKind("");try{const r=await fetch(`${api()}/listing-import/create-draft`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({categoryId,sourceUrl:preview.sourceUrl,title:preview.title,description:preview.description,priceMinor:preview.priceMinor,city:preview.city,postalCode:preview.postalCode,histovecUrl:preview.histovecUrl??null,imageUrls:selectedImages,detectedFields:preview.detectedFields??{},rightsConfirmed:true,allowSimilarDuplicate:forceSimilar})});const p=await r.json().catch(()=>({}));if(r.status===401){location.href=`/connexion?next=${encodeURIComponent(location.pathname+location.search)}`;return}if(!r.ok){const code=String(p.error??"");setMsg(code==="category_not_found"?"La catégorie choisie n’est plus disponible. Sélectionnez une autre catégorie.":code==="invalid_source_url"?"Le lien source n’est plus valide. Relancez l’analyse de l’annonce.":code==="import_conflict"?"Cet import est déjà en cours ou existe déjà. Rechargez la page puis ouvrez le brouillon existant.":"Le brouillon n’a pas pu être créé. Les données saisies restent affichées : vérifiez-les puis réessayez.");return}if(p.duplicate){setDuplicateUrl(p.editUrl??"");setDuplicateKind(p.duplicateKind??"exact");setMsg(p.duplicateKind==="similar"?"Une annonce très similaire existe déjà sur votre compte.":"Cette annonce a déjà été importée.");return}if(selectedImages.length>0&&Number(p.media?.imported??0)===0){setMsg("Le brouillon est créé, mais le site source n’a pas autorisé le transfert direct des photos. Vous allez arriver à l’étape Photos pour les ajouter ou réessayer.");window.setTimeout(()=>{location.href=p.editUrl},900);return}const failedPhotos=Number(p.media?.failed??0),importedPhotos=Number(p.media?.imported??0);const missing=Array.isArray(p.preflight?.missing)?p.preflight.missing.filter((x:unknown)=>typeof x==="string"):[];if(failedPhotos>0||missing.length>0){const parts:string[]=[];if(failedPhotos>0)parts.push(`${importedPhotos} photo(s) importée(s), ${failedPhotos} non récupérée(s)`);if(missing.length>0)parts.push(`À compléter : ${missing.slice(0,3).join(" · ")}`);setMsg(parts.join(". ")+" — ouverture automatique de la bonne étape.");window.setTimeout(()=>{location.href=p.editUrl},700);return}location.href=p.editUrl}catch{setMsg("Connexion interrompue pendant la création du brouillon. Réessayez.")}finally{setBusy(false)}}
 const activeSource=sourceHint||"other";
 return <div className={styles.page}><main className={styles.shell}>
  <div className={styles.topbar}><a className={styles.back} href="/deposer-une-annonce"><AppIcon name="arrow-left"/>Retour au dépôt</a><span className={styles.safeBadge}><AppIcon name="shield"/>Import sécurisé en brouillon</span></div>
  <header className={styles.hero}><div className={styles.heroCopy}><span>Importer une annonce</span><h1>Importez depuis<br/>le lien de l’annonce.</h1><p>Copiez l’URL publique de votre annonce déjà publiée. Petit Annonces détecte automatiquement Leboncoin, Vinted et les autres sites compatibles.</p></div><div className={styles.heroSteps}><div><b>1</b><span><strong>Collez le lien</strong><small>URL de l’annonce source</small></span></div><div><b>2</b><span><strong>Vérification</strong><small>Relisez les informations</small></span></div><div><b>3</b><span><strong>Brouillon</strong><small>Terminez dans le wizard</small></span></div></div></header>
  <section className={styles.importCard}>{sharedIncoming&&<div className={styles.shareReceived}><AppIcon name="share"/><div><strong>Lien reçu depuis le menu Partager</strong><span>Petit Annonces utilise uniquement l’URL publique partagée pour analyser l’annonce.</span></div></div>}<div className={styles.sectionHead}><div><span>Étape 1</span><h2>Collez le lien de l’annonce</h2><p>L’import fonctionne uniquement à partir de l’URL publique de la page source. Aucun code, référence ou texte copié n’est nécessaire.</p></div><span className={styles.sectionIcon}><AppIcon name="share"/></span></div>
   <div className={styles.smartImport}><div className={styles.smartSources}><span className={`${styles.smartSource} ${styles.smartLeboncoin} ${activeSource==="leboncoin"?styles.smartSourceActive:""}`}><b>L</b><em><strong>Leboncoin</strong><small>Annonce publique</small></em>{activeSource==="leboncoin"&&<AppIcon name="circle-check"/>}</span><span className={`${styles.smartSource} ${styles.smartVinted} ${activeSource==="vinted"?styles.smartSourceActive:""}`}><b>V</b><em><strong>Vinted</strong><small>Annonce publique</small></em>{activeSource==="vinted"&&<AppIcon name="circle-check"/>}</span><span className={`${styles.smartSource} ${styles.smartOther} ${activeSource==="other"&&validPublicUrl(url)?styles.smartSourceActive:""}`}><b><AppIcon name="share"/></b><em><strong>Autre site</strong><small>Lien public</small></em>{activeSource==="other"&&validPublicUrl(url)&&<AppIcon name="circle-check"/>}</span></div><label><span>Lien de l’annonce *</span><input type="url" inputMode="url" autoCapitalize="none" autoCorrect="off" spellCheck={false} value={url} onChange={e=>{const next=e.target.value;setUrl(next);setPreview(null);setMsg("");setSourceHint(validPublicUrl(next)?sourceFromUrl(next):"")}} placeholder="https://www.vinted.fr/items/... ou https://www.leboncoin.fr/ad/..."/><small>Copiez l’adresse complète visible dans votre navigateur ou utilisez Partager → Petit Annonces depuis la page de l’annonce.</small></label><button className={styles.primary} disabled={busy||!validPublicUrl(url)} onClick={()=>void analyze()}>{busy?<><span className={styles.spinner}/>Analyse en cours…</>:<><AppIcon name="search"/>Importer depuis ce lien</>}</button></div>
   {msg&&<div className={styles.notice}><AppIcon name="info"/><div><span>{msg}</span>{duplicateUrl&&<div className={styles.noticeActions}><a href={duplicateUrl}>{duplicateKind?"Ouvrir l’annonce existante":"Ouvrir le brouillon"}</a>{duplicateKind==="similar"&&<button type="button" onClick={()=>void create(true)} disabled={busy}>Créer quand même</button>}</div>}</div></div>}
  </section>
  {preview&&<section className={styles.reviewSection}><div className={styles.reviewAside}><div className={styles.image}>{primaryPreviewImage&&preview.sourceUrl?<img src={previewImageSrc(primaryPreviewImage,preview.sourceUrl)} alt="Aperçu de l’annonce importée"/>:<span>PA</span>}</div><div className={styles.qualityCard}><div className={styles.qualityHead}><span>Qualité de l’import</span><strong>{q.score}<small>/100</small></strong></div><div className={styles.qualityBar}><i style={{width:`${q.score}%`}}/></div>{q.checks.length?<ul>{q.checks.map(item=><li key={item}><AppIcon name="info"/>{item}</li>)}</ul>:<div className={styles.ready}><AppIcon name="circle-check"/>Import prêt à être transformé en brouillon.</div>}</div><div className={styles.sourceInfo}><span className={`${styles.brandMark} ${activeSource==="vinted"?styles.vintedMark:activeSource==="leboncoin"?styles.leboncoinMark:""}`}>{activeSource==="vinted"?"V":activeSource==="leboncoin"?"L":"+"}</span><div><strong>{activeSource==="vinted"?"Vinted":activeSource==="leboncoin"?"Leboncoin":"Site source"}</strong><small>Les données importées restent modifiables.</small></div></div></div>
   <div className={styles.reviewCard}><div className={styles.sectionHead}><div><span>Étape 2</span><h2>Vérifiez les informations importées</h2><p>Corrigez les champs si nécessaire. Rien n’est publié automatiquement.</p></div><span className={styles.sectionIcon}><AppIcon name="list"/></span></div>
    {preview.manualRequired&&<div className={styles.guided}><AppIcon name="info"/><div><strong>Lecture automatique limitée</strong><span>Le site source n’a pas fourni toutes les données publiques. Vous pouvez compléter les champs disponibles ci-dessous ou essayer une autre URL publique de cette même annonce.</span></div></div>}
    <div className={styles.formGrid}><label className={styles.full}><span>Titre *</span><input value={preview.title??""} maxLength={120} onChange={e=>patch("title",e.target.value)}/></label><label><span>Prix (€)</span><input inputMode="decimal" value={preview.priceMinor==null?"":String(preview.priceMinor/100).replace(".",",")} onChange={e=>{const raw=e.target.value.replace(",",".");patch("priceMinor",raw===""?null:Math.round(Number(raw)*100)||0)}}/></label><label><span>Catégorie principale *</span><select value={rootCategoryId} onChange={e=>{const next=e.target.value;const root=cats.find(c=>c.id===next);setRootCategoryId(next);setBranchCategoryId("");setCategoryId(root?.children?.length?"":next)}}><option value="">Choisir une catégorie</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{rootCategory?.children?.length?<label><span>Sous-catégorie *</span><select value={branchCategoryId} onChange={e=>{const next=e.target.value;const child=rootCategory.children?.find(c=>c.id===next);setBranchCategoryId(next);setCategoryId(child?.children?.length?"":next)}}><option value="">Choisir une sous-catégorie</option>{(rootCategory.children??[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>:null}{branchCategory?.children?.length?<label><span>Type précis *</span><select value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Choisir le type précis</option><option value={branchCategory.id}>Autre / {branchCategory.name}</option>{(branchCategory.children??[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>:null}<label><span>Ville</span><input value={preview.city??""} onChange={e=>patch("city",e.target.value)}/></label><label><span>Code postal</span><input inputMode="numeric" value={preview.postalCode??""} onChange={e=>patch("postalCode",e.target.value)}/></label><label className={styles.full}><span>Description *</span><textarea rows={8} value={preview.description??""} maxLength={12000} onChange={e=>patch("description",e.target.value)}/></label></div>
    {categoryMismatch&&<div className={styles.guided}><AppIcon name="info"/><div><strong>Catégorie différente de celle détectée</strong><span>Petit Annonces recommande « {suggestedOption?.label} », mais vous avez choisi « {selectedOption?.label} ». Vérifiez ce choix avant de continuer afin d’éviter une annonce mal classée.</span></div></div>}
    {preview.suggestionReason&&<div className={styles.suggestion}><AppIcon name="sparkles"/><span>{preview.suggestionReason}</span></div>}
    {preview.histovecUrl&&<div className={styles.suggestion}><AppIcon name="shield"/><span>Rapport HistoVec officiel détecté : le lien sera ajouté automatiquement à la fiche véhicule.</span></div>}
    {preview.detectedFields&&Object.keys(preview.detectedFields).length>0&&<div className={styles.detected}><strong>Champs détectés automatiquement</strong><div>{Object.entries(preview.detectedFields).map(([k,v])=><span key={k}><b>{detectedLabel(k)}</b>{String(v)}</span>)}</div></div>}
    {(preview.imageUrls?.length??0)>0&&preview.sourceUrl&&<div className={styles.photoReview}><div className={styles.photoReviewHead}><div><strong>Photos à importer</strong><small>Sélectionnez uniquement les photos utiles.</small></div><span>{selectedImages.length}/{preview.imageUrls!.length}</span></div><div className={styles.photoGrid}>{preview.imageUrls!.map((img,i)=>{const selected=selectedImages.includes(img);return <button type="button" key={img} className={selected?styles.photoSelected:""} onClick={()=>setSelectedImages(prev=>selected?prev.filter(x=>x!==img):[...prev,img])}><img src={previewImageSrc(img,preview.sourceUrl!)} alt={`Photo source ${i+1}`}/><span>{selected?"✓":"+"}</span></button>})}</div></div>}
    <label className={styles.check}><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/><span><strong>Je confirme disposer des droits nécessaires et être responsable du contenu importé.</strong><small>Je suis l’auteur, le propriétaire ou je suis autorisé à republier cette annonce, ses textes et ses photos. Je vérifie également l’exactitude des informations avant publication.</small></span></label>
    <div className={styles.reviewFooter}><div><AppIcon name="shield"/><span><strong>Étape suivante : wizard Petit Annonces</strong><small>Vous pourrez encore modifier photos, détails, prix et livraison.</small></span></div><button className={styles.primary} disabled={busy||!rights||!preview.sourceUrl||!categoryId||(preview.title??"").trim().length<5} onClick={()=>void create(false)}>{busy?"Création…":"Créer le brouillon et continuer"}<AppIcon name="arrow-right"/></button></div>
   </div></section>}
  <section className={styles.info}><AppIcon name="shield"/><div><strong>Responsabilité du contenu importé</strong><p>L’utilisateur est responsable de l’annonce qu’il importe, de l’exactitude des informations ainsi que de son droit à republier les textes et les photos provenant du site source. Petit Annonces fournit uniquement l’outil technique d’importation. Aucun import n’est publié automatiquement : le brouillon doit être vérifié par l’utilisateur puis reste soumis aux règles et à la modération de Petit Annonces.</p></div></section>
 </main></div>
}
