module.exports = {
  apps: [
    {
      name: "petitannonces-web",
      cwd: "/var/www/petitannonces/current",
      script: "pnpm",
      args: "--filter @pa/web start",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_memory_restart: "1200M",
      kill_timeout: 10000,
      env: { NODE_ENV: "production", PORT: "3000" },
    },
    {
      name: "petitannonces-admin",
      cwd: "/var/www/petitannonces/current",
      script: "pnpm",
      args: "--filter @pa/admin start",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_memory_restart: "900M",
      kill_timeout: 10000,
      env: { NODE_ENV: "production", PORT: "3001" },
    },
    {
      name: "petitannonces-api",
      cwd: "/var/www/petitannonces/current",
      script: "pnpm",
      args: "--filter @pa/api start",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_memory_restart: "1200M",
      kill_timeout: 10000,
      env: {
        NODE_ENV: "production",
        API_PORT: "4000",
        REQUIRE_REDIS_READY: "true",
        APP_VERSION: process.env.APP_VERSION || "unknown",
      },
    },
  ],
};
