import type { Metadata } from "next";
import { notFound, permanentRedirect } from "next/navigation";
import { LongtailListingPage, moneyRange, seoApi, type LongtailData } from "../../../../lib/seo-longtail";

export const revalidate=120;
type Props={params:Promise<{transaction:string;city:string}>};type Meta={transactionType:"SALE"|"RENTAL";transactionLabel:string;city:string;total:number;minPrice:number|null;maxPrice:number|null};
function redirectLegacyProperty(transaction:string,city:string){if(transaction==="locations"&&city==="appartement")permanentRedirect("/categorie/location-immobilier")}
async function meta(transaction:string,city:string):Promise<Meta|null>{if(!["vente","location"].includes(transaction))return null;const r=await fetch(`${seoApi()}/seo/property/${transaction}/${encodeURIComponent(city)}`,{next:{revalidate:300}});if(!r.ok)return null;return r.json()}
async function data(m:Meta):Promise<LongtailData>{const q=new URLSearchParams({category:"immobilier",city:m.city,transactionType:m.transactionType,limit:"24",sort:"recent"});const r=await fetch(`${seoApi()}/search?${q}`,{next:{revalidate:120}});return r.ok?r.json():{total:0,items:[]}}
export async function generateMetadata({params}:Props):Promise<Metadata>{const{transaction,city}=await params;redirectLegacyProperty(transaction,city);const m=await meta(transaction,city);if(!m)return{title:"Immobilier | Petit Annonces",robots:{index:false,follow:true}};const noun=m.transactionType==="SALE"?"Immobilier à vendre":"Location immobilière";const description=`${m.total} annonce${m.total>1?"s":""} ${m.transactionType==="SALE"?"immobilière en vente":"de location"} à ${m.city}${moneyRange(m.minPrice,m.maxPrice)?`. Prix observés : ${moneyRange(m.minPrice,m.maxPrice)}`:""}.`;return{title:`${noun} à ${m.city} - Annonces | Petit Annonces`,description,alternates:{canonical:`/immobilier/${transaction}/${city}`},robots:{index:m.total>=3,follow:true}}}
export default async function Page({params}:Props){const{transaction,city}=await params;redirectLegacyProperty(transaction,city);const m=await meta(transaction,city);if(!m)notFound();const d=await data(m);const title=m.transactionType==="SALE"?`Immobilier à vendre à ${m.city}`:`Location immobilière à ${m.city}`;return <LongtailListingPage eyebrow={m.transactionLabel} title={title} description={`Consultez les biens actuellement disponibles à ${m.city}. ${m.total} annonce${m.total>1?"s":""}${moneyRange(m.minPrice,m.maxPrice)?`, avec des prix affichés de ${moneyRange(m.minPrice,m.maxPrice)}`:""}. Les résultats sont issus des annonces réellement publiées sur Petit Annonces.`} data={d} backHref="/categorie/immobilier" backLabel="Immobilier" canonicalPath={`/immobilier/${transaction}/${city}`}/>}