"use client";

import { useEffect, useState } from "react";
import { AppIcon } from "./app-icon";
import styles from "./listing-real-estate-form.module.css";

type DraftResponse={listing:{property?:Record<string,unknown>|null;energy?:Record<string,unknown>|null}};
type FormState={
 transactionType:"SALE"|"RENTAL";propertyType:string;surfaceM2:string;rooms:string;bedrooms:string;furnished:boolean;floor:string;totalFloors:string;landM2:string;postalCode:string;city:string;
 isExempt:boolean;exemptionReason:string;dpeNumber:string;dpeDate:string;energyClass:string;climateClass:string;energyConsumption:string;ghg:string;annualCostMin:string;annualCostMax:string;referenceYears:string;
};
const initial:FormState={transactionType:"SALE",propertyType:"Appartement",surfaceM2:"",rooms:"",bedrooms:"",furnished:false,floor:"",totalFloors:"",landM2:"",postalCode:"",city:"",isExempt:false,exemptionReason:"",dpeNumber:"",dpeDate:"",energyClass:"",climateClass:"",energyConsumption:"",ghg:"",annualCostMin:"",annualCostMax:"",referenceYears:""};
const api=()=> (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"");
const decimal=(v:string)=>{const normalized=v.replace(/[\s\u00a0\u202f]/g,"").replace(",",".").trim();if(!normalized)return null;const n=Number(normalized);return Number.isFinite(n)?n:null};
const num=(v:string)=>decimal(v);
const int=(v:string)=>{const n=num(v);return n==null?null:Math.trunc(n)};
const dateOnly=(v:unknown)=>typeof v==="string"?v.slice(0,10):"";

export function ListingRealEstateForm({listingId,onSaved,onDirty}:{listingId:string;onSaved?:()=>void;onDirty?:()=>void}){
 const[form,setForm]=useState<FormState>(initial),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[cityOptions,setCityOptions]=useState<string[]>([]),[postalLookup,setPostalLookup]=useState<"idle"|"loading"|"found"|"multiple"|"missing">("idle"),[attempted,setAttempted]=useState(false);
 const scrollError=()=>window.setTimeout(()=>document.querySelector<HTMLElement>("[data-realestate-error='true']")?.scrollIntoView({behavior:"smooth",block:"center"}),40);
 useEffect(()=>{let cancelled=false;fetch(`${api()}/listings/${encodeURIComponent(listingId)}/draft`,{credentials:"include"}).then(async r=>{if(!r.ok)throw 0;return r.json() as Promise<DraftResponse>}).then(payload=>{if(cancelled)return;const p=payload.listing.property??null,e=payload.listing.energy??null;if(p||e){setForm(current=>({...current,transactionType:(p?.transactionType as "SALE"|"RENTAL")??current.transactionType,propertyType:String(p?.propertyType??current.propertyType),surfaceM2:p?.surfaceM2==null?"":String(p.surfaceM2),rooms:p?.rooms==null?"":String(p.rooms),bedrooms:p?.bedrooms==null?"":String(p.bedrooms),furnished:Boolean(p?.furnished),floor:p?.floor==null?"":String(p.floor),totalFloors:p?.totalFloors==null?"":String(p.totalFloors),landM2:p?.landM2==null?"":String(p.landM2),postalCode:String(p?.postalCode??""),city:String(p?.city??""),isExempt:Boolean(e?.isExempt),exemptionReason:String(e?.exemptionReason??""),dpeNumber:String(e?.dpeNumber??""),dpeDate:dateOnly(e?.dpeDate),energyClass:String(e?.energyClass??""),climateClass:String(e?.climateClass??""),energyConsumption:e?.energyConsumptionKwhM2Year==null?"":String(e.energyConsumptionKwhM2Year),ghg:e?.ghgKgCo2M2Year==null?"":String(e.ghgKgCo2M2Year),annualCostMin:e?.annualCostMinMinor==null?"":String(Number(e.annualCostMinMinor)/100),annualCostMax:e?.annualCostMaxMinor==null?"":String(Number(e.annualCostMaxMinor)/100),referenceYears:String(e?.energyPriceReferenceYears??"")}));if(p&&e)onSaved?.()}}).catch(()=>setMessage("Impossible de charger les informations immobilières.")).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[listingId]);
 useEffect(()=>{const clean=form.postalCode.replace(/\D/g,"").slice(0,5);if(form.postalCode!==clean){setForm(v=>({...v,postalCode:clean}));return}if(clean.length!==5){setCityOptions([]);setPostalLookup("idle");return}let cancelled=false;const timer=window.setTimeout(async()=>{setPostalLookup("loading");try{const r=await fetch(`${api()}/locations/postal-code/${encodeURIComponent(clean)}`);const p=await r.json().catch(()=>({cities:[]}));if(cancelled)return;const names=Array.isArray(p.cities)?p.cities.map((x:{name?:string})=>String(x.name??"").trim()).filter(Boolean):[];setCityOptions(names);if(names.length===1){setForm(v=>({...v,city:names[0]!}));setPostalLookup("found")}else if(names.length>1){setForm(v=>({...v,city:names.includes(v.city)?v.city:names[0]!}));setPostalLookup("multiple")}else setPostalLookup("missing")}catch{if(!cancelled){setCityOptions([]);setPostalLookup("missing")}}},280);return()=>{cancelled=true;window.clearTimeout(timer)}},[form.postalCode]);
 function update<K extends keyof FormState>(key:K,value:FormState[K]){onDirty?.();setForm(v=>({...v,[key]:value}))}
 async function save(){setMessage("");setAttempted(true);const surface=num(form.surfaceM2);if(surface==null||surface<=0){setMessage("Indiquez une surface valide.");scrollError();return}if(!form.propertyType.trim()){setMessage("Indiquez le type de bien.");scrollError();return}if(!/^\d{5}$/.test(form.postalCode)||postalLookup==="missing"||!form.city.trim()){setMessage("Indiquez une ville et un code postal valides.");scrollError();return}if(form.isExempt&&!form.exemptionReason.trim()){setMessage("Précisez le motif d’exemption DPE.");scrollError();return}if(!form.isExempt){if(form.dpeNumber.trim().length<8){setMessage("Le numéro DPE doit contenir au moins 8 caractères.");scrollError();return}if(!form.dpeDate||!form.energyClass||!form.climateClass){setMessage("Complétez la date du DPE, la classe énergie et la classe GES.");scrollError();return}if(num(form.energyConsumption)==null||num(form.ghg)==null||num(form.annualCostMin)==null||num(form.annualCostMax)==null||!form.referenceYears.trim()){setMessage("Complétez les consommations et l’estimation annuelle des coûts énergétiques.");scrollError();return}}
 setSaving(true);try{const property={transactionType:form.transactionType,propertyType:form.propertyType.trim(),surfaceM2:surface,rooms:int(form.rooms),bedrooms:int(form.bedrooms),furnished:form.furnished,floor:int(form.floor),totalFloors:int(form.totalFloors),landM2:num(form.landM2),postalCode:form.postalCode.trim(),city:form.city.trim(),countryCode:"FR"};const energy=form.isExempt?{isExempt:true,exemptionReason:form.exemptionReason.trim()}:{isExempt:false,dpeNumber:form.dpeNumber.trim(),dpeDate:form.dpeDate,energyClass:form.energyClass,climateClass:form.climateClass,energyConsumptionKwhM2Year:num(form.energyConsumption),ghgKgCo2M2Year:num(form.ghg),annualCostMinMinor:Math.round((decimal(form.annualCostMin)??0)*100),annualCostMaxMinor:Math.round((decimal(form.annualCostMax)??0)*100),energyPriceReferenceYears:form.referenceYears.trim()};const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/property-energy`,{method:"PUT",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({property,energy})});const payload=await r.json().catch(()=>({}));if(!r.ok){if(payload.error==="invalid_energy_cost_range")throw new Error("cost_range");if(payload?.details?.fieldErrors){const first=Object.entries(payload.details.fieldErrors as Record<string,string[]>).find(([,v])=>Array.isArray(v)&&v.length);if(first)throw new Error(`field:${first[0]}:${first[1][0]}`)}throw new Error("save_failed")}setAttempted(false);setMessage("Informations immobilières et DPE enregistrés.");onSaved?.()}catch(e){if(e instanceof Error&&e.message==="cost_range")setMessage("Le coût annuel maximum doit être supérieur au minimum.");else if(e instanceof Error&&e.message.startsWith("field:"))setMessage(`Vérifiez les informations DPE / immobilier : ${e.message.split(":").slice(2).join(":")}`);else setMessage("Impossible d’enregistrer les informations immobilières. Vérifiez les champs indiqués.")}finally{setSaving(false)}}
 if(loading)return <div className={styles.loading}>Chargement des informations immobilières…</div>;
 const classes=["A","B","C","D","E","F","G"];
 return <section className={styles.wrapper}>
  <div className={styles.heading}><div><span>Informations du bien</span><h3>Caractéristiques immobilières</h3></div><AppIcon name="home"/></div>
  <div className={styles.grid}>
   <label><span>Transaction *</span><select value={form.transactionType} onChange={e=>update("transactionType",e.target.value as "SALE"|"RENTAL")}><option value="SALE">Vente</option><option value="RENTAL">Location</option></select></label>
   <label><span>Type de bien *</span><select value={form.propertyType} onChange={e=>update("propertyType",e.target.value)}><option>Appartement</option><option>Maison</option><option>Terrain</option><option>Local commercial</option><option>Parking</option><option>Autre</option></select></label>
   <label className={attempted&&(num(form.surfaceM2)==null||Number(num(form.surfaceM2))<=0)?styles.validationError:undefined} data-realestate-error={attempted&&(num(form.surfaceM2)==null||Number(num(form.surfaceM2))<=0)?"true":undefined}><span>Surface *</span><div className={styles.unit}><input type="number" min="1" value={form.surfaceM2} onChange={e=>update("surfaceM2",e.target.value)}/><i>m²</i></div></label>
   <label><span>Pièces</span><input type="number" min="1" value={form.rooms} onChange={e=>update("rooms",e.target.value)}/></label>
   <label><span>Chambres</span><input type="number" min="0" value={form.bedrooms} onChange={e=>update("bedrooms",e.target.value)}/></label>
   <label><span>Étage</span><input type="number" value={form.floor} onChange={e=>update("floor",e.target.value)}/></label>
   <label><span>Nombre d’étages</span><input type="number" min="1" value={form.totalFloors} onChange={e=>update("totalFloors",e.target.value)}/></label>
   <label><span>Terrain</span><div className={styles.unit}><input type="number" min="0" value={form.landM2} onChange={e=>update("landM2",e.target.value)}/><i>m²</i></div></label>
   <label className={`${styles.locationField} ${attempted&&(!/^\d{5}$/.test(form.postalCode)||postalLookup==="missing")?styles.validationError:""}`} data-realestate-error={attempted&&(!/^\d{5}$/.test(form.postalCode)||postalLookup==="missing")?"true":undefined}><span>Code postal *</span><input inputMode="numeric" pattern="[0-9]*" value={form.postalCode} maxLength={5} onChange={e=>update("postalCode",e.target.value.replace(/\D/g,"").slice(0,5))}/>{postalLookup==="loading"&&<small className={styles.lookupHint}>Recherche de la ville…</small>}{postalLookup==="found"&&<small className={styles.lookupSuccess}><AppIcon name="circle-check"/>Ville détectée automatiquement</small>}{postalLookup==="missing"&&form.postalCode.length===5&&<small className={styles.lookupError}>Code postal introuvable.</small>}</label>
   <label className={`${styles.locationField} ${attempted&&!form.city.trim()?styles.validationError:""}`} data-realestate-error={attempted&&!form.city.trim()?"true":undefined}><span>Ville *</span>{cityOptions.length>1?<select value={form.city} onChange={e=>update("city",e.target.value)}>{cityOptions.map(name=><option key={name} value={name}>{name}</option>)}</select>:<input value={form.city} placeholder="La ville apparaît automatiquement" onChange={e=>update("city",e.target.value)}/>} {postalLookup==="multiple"&&<small className={styles.lookupHint}>Plusieurs communes utilisent ce code postal.</small>}</label>
   <label className={styles.check}><input type="checkbox" checked={form.furnished} onChange={e=>update("furnished",e.target.checked)}/><span>Bien meublé</span></label>
  </div>
  <div className={styles.energyHead}><div><span>Diagnostic énergétique</span><h3>DPE & GES</h3></div><label className={styles.exempt}><input type="checkbox" checked={form.isExempt} onChange={e=>update("isExempt",e.target.checked)}/><span>Bien exempté de DPE</span></label></div>
  {form.isExempt?<label className={`${styles.full} ${attempted&&!form.exemptionReason.trim()?styles.validationError:""}`} data-realestate-error={attempted&&!form.exemptionReason.trim()?"true":undefined}><span>Motif d’exemption *</span><textarea rows={3} value={form.exemptionReason} onChange={e=>update("exemptionReason",e.target.value)} placeholder="Précisez le motif légal ou technique de l’exemption."/></label>:<div className={styles.energyGrid}>
   <label className={attempted&&form.dpeNumber.trim().length<8?styles.validationError:undefined} data-realestate-error={attempted&&form.dpeNumber.trim().length<8?"true":undefined}><span>N° DPE *</span><input minLength={8} maxLength={40} value={form.dpeNumber} onChange={e=>update("dpeNumber",e.target.value)} placeholder="Numéro du diagnostic"/><small>8 caractères minimum</small></label>
   <label className={attempted&&!form.dpeDate?styles.validationError:undefined} data-realestate-error={attempted&&!form.dpeDate?"true":undefined}><span>Date du DPE *</span><input type="date" min="2021-07-01" max={new Date().toISOString().slice(0,10)} value={form.dpeDate} onChange={e=>update("dpeDate",e.target.value)}/></label>
   <label className={attempted&&!form.energyClass?styles.validationError:undefined} data-realestate-error={attempted&&!form.energyClass?"true":undefined}><span>Classe énergie *</span><select value={form.energyClass} onChange={e=>update("energyClass",e.target.value)}><option value="">Choisir</option>{classes.map(c=><option key={c}>{c}</option>)}</select></label>
   <label className={attempted&&!form.climateClass?styles.validationError:undefined} data-realestate-error={attempted&&!form.climateClass?"true":undefined}><span>Classe GES *</span><select value={form.climateClass} onChange={e=>update("climateClass",e.target.value)}><option value="">Choisir</option>{classes.map(c=><option key={c}>{c}</option>)}</select></label>
   <label className={attempted&&num(form.energyConsumption)==null?styles.validationError:undefined} data-realestate-error={attempted&&num(form.energyConsumption)==null?"true":undefined}><span>Consommation *</span><div className={styles.unit}><input type="number" min="0" value={form.energyConsumption} onChange={e=>update("energyConsumption",e.target.value)}/><i>kWh/m²/an</i></div></label>
   <label className={attempted&&num(form.ghg)==null?styles.validationError:undefined} data-realestate-error={attempted&&num(form.ghg)==null?"true":undefined}><span>Émissions GES *</span><div className={styles.unit}><input type="number" min="0" value={form.ghg} onChange={e=>update("ghg",e.target.value)}/><i>kg CO₂/m²/an</i></div></label>
   <label className={attempted&&num(form.annualCostMin)==null?styles.validationError:undefined} data-realestate-error={attempted&&num(form.annualCostMin)==null?"true":undefined}><span>Coût annuel min. *</span><div className={styles.unit}><input inputMode="decimal" value={form.annualCostMin} onChange={e=>update("annualCostMin",e.target.value)}/><i>€</i></div></label>
   <label className={attempted&&num(form.annualCostMax)==null?styles.validationError:undefined} data-realestate-error={attempted&&num(form.annualCostMax)==null?"true":undefined}><span>Coût annuel max. *</span><div className={styles.unit}><input inputMode="decimal" value={form.annualCostMax} onChange={e=>update("annualCostMax",e.target.value)}/><i>€</i></div></label>
   <label className={`${styles.full} ${attempted&&!form.referenceYears.trim()?styles.validationError:""}`} data-realestate-error={attempted&&!form.referenceYears.trim()?"true":undefined}><span>Années de référence des prix de l’énergie *</span><input value={form.referenceYears} onChange={e=>update("referenceYears",e.target.value)} placeholder="Ex. 2021, 2022, 2023"/></label>
  </div>}
  {message&&<div className={styles.message}><AppIcon name="info"/>{message}</div>}
  <button type="button" className={styles.save} onClick={save} disabled={saving}><AppIcon name="check"/>{saving?"Enregistrement…":"Enregistrer les informations du bien"}</button>
 </section>;
}
