"use client";

import { useState } from "react";

function apiBase(){return (process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000").replace(/\/$/,"");}
function loginNext(){const path=`${window.location.pathname}${window.location.search}`;window.location.href=`/connexion?next=${encodeURIComponent(path)}`;}

export function ListingContactActions({listingId,acceptsOffers,classNameMessage,classNameOffer}:{listingId:string;acceptsOffers:boolean;classNameMessage?:string;classNameOffer?:string}){
  const [busy,setBusy]=useState(false);const [showOffer,setShowOffer]=useState(false);const [amount,setAmount]=useState("");const [error,setError]=useState("");
  async function conversation(){const r=await fetch(`${apiBase()}/conversations`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({listingId})});if(r.status===401){loginNext();throw new Error("redirecting");}const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error??"conversation_failed");return p.conversation as {id:string};}
  async function message(){setBusy(true);setError("");try{const c=await conversation();window.location.href=`/messages?conversation=${encodeURIComponent(c.id)}`;}catch(e){if(e instanceof Error&&e.message!=="redirecting")setError(e.message==="cannot_message_own_listing"?"Vous ne pouvez pas contacter votre propre annonce.":"Impossible d’ouvrir la conversation.");}finally{setBusy(false)}}
  async function offer(){const value=Number(amount.replace(",","."));if(!Number.isFinite(value)||value<=0){setError("Montant de l’offre invalide.");return;}setBusy(true);setError("");try{const c=await conversation();const r=await fetch(`${apiBase()}/conversations/${c.id}/offers`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({amount:value})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error??"offer_failed");window.location.href=`/messages?conversation=${encodeURIComponent(c.id)}`;}catch(e){if(e instanceof Error&&e.message!=="redirecting")setError(e.message==="offers_disabled"?"Le vendeur n’accepte pas les offres sur cette annonce.":e.message==="cannot_message_own_listing"?"Vous ne pouvez pas faire une offre sur votre propre annonce.":"Impossible d’envoyer cette offre.");}finally{setBusy(false)}}
  return <div style={{display:"grid",gap:10}}><button className={classNameMessage} onClick={message} disabled={busy}>{busy?"Ouverture…":"Envoyer un message"}</button>{acceptsOffers&&<>{!showOffer?<button className={classNameOffer} onClick={()=>setShowOffer(true)} disabled={busy}>Faire une offre</button>:<div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><input aria-label="Montant de l’offre" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Montant €" style={{minWidth:0,height:44,border:"1px solid #d1d5db",borderRadius:12,padding:"0 12px",font:"inherit"}}/><button className={classNameOffer} onClick={offer} disabled={busy||!amount} style={{marginTop:0,width:"auto",padding:"0 16px"}}>{busy?"Envoi…":"Envoyer"}</button></div>}</>}{error&&<div style={{fontSize:13,color:"#b91c1c"}}>{error}</div>}</div>;
}
