"use client";
import {useEffect,useMemo,useState} from "react";
import {AppIcon} from "./app-icon";
type Perf={metrics:{views:number;views7:number;views30:number;favorites:number;conversations:number;messages:number;offers:number};insight:string;performance:{score:number;level:string};actions:Array<{code:string;label:string;href:string}>;series:Array<{day:string;views:number}>};
export function ListingOwnerPerformance({listingId}:{listingId:string}){
 const[data,setData]=useState<Perf|null>(null);
 useEffect(()=>{let stop=false;fetch(`/api/account/listings/${encodeURIComponent(listingId)}/performance`,{credentials:"include",cache:"no-store"}).then(async r=>r.ok?r.json():null).then(p=>{if(!stop&&p)setData(p)}).catch(()=>{});return()=>{stop=true}},[listingId]);
 const bars=useMemo(()=>{if(!data)return[];const max=Math.max(1,...data.series.map(x=>x.views));return data.series.slice(-14).map(x=>({...x,h:Math.max(8,Math.round(x.views/max*100))}))},[data]);
 if(!data)return null;const m=data.metrics;const level=data.performance.level==="FORTE"?"Forte":data.performance.level==="CORRECTE"?"Correcte":"Faible";return <section style={{marginTop:14,padding:14,border:"1px solid #e3defc",borderRadius:16,background:"linear-gradient(135deg,#f8f7ff,#fff)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginBottom:10}}><div style={{display:"flex",alignItems:"center",gap:8}}><AppIcon name="sparkles"/><strong style={{fontSize:13}}>Performance de votre annonce</strong></div><span style={{padding:"5px 8px",borderRadius:999,background:"#eeeaff",color:"#5145d6",fontSize:10,fontWeight:900}}>{data.performance.score}/100 · {level}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:7}}><Metric v={m.views} l="Vues"/><Metric v={m.favorites} l="Favoris"/><Metric v={m.messages} l="Messages"/><Metric v={m.offers} l="Offres"/></div><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:9,fontSize:11,color:"#716d80"}}><span>7 j : <b>{m.views7} vues</b></span><span>30 j : <b>{m.views30} vues</b></span></div>{bars.length>0&&<div style={{height:70,display:"flex",alignItems:"end",gap:4,marginTop:12,padding:"8px 6px",borderRadius:12,background:"#fff",border:"1px solid #ece9f8"}}>{bars.map(x=><i key={x.day} title={`${x.day} · ${x.views} vues`} style={{display:"block",flex:1,height:`${x.h}%`,minWidth:3,borderRadius:999,background:"#6759e8"}}/>)}</div>}<p style={{margin:"10px 0 0",fontSize:11.5,lineHeight:1.5,color:"#565266"}}>{data.insight}</p><div style={{display:"flex",flexWrap:"wrap",gap:7,marginTop:10}}>{data.actions.map(a=><a key={a.code} href={a.href} style={{padding:"8px 10px",borderRadius:10,border:"1px solid #dcd6fb",background:a.code==="VISIBILITY"?"#5b4cf0":"#fff",color:a.code==="VISIBILITY"?"#fff":"#5145d6",fontSize:10.5,fontWeight:850}}>{a.label}</a>)}</div></section>}
function Metric({v,l}:{v:number;l:string}){return <div style={{padding:"9px 7px",borderRadius:12,background:"#fff",border:"1px solid #ece9f8",textAlign:"center"}}><b style={{display:"block",fontSize:15,color:"#5145d6"}}>{v}</b><small style={{fontSize:9.5,color:"#777287"}}>{l}</small></div>}
