"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { AppIcon } from "./app-icon";
import { navigateApp } from "../lib/app-navigation";

function apiBase(){return (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"");}

export function ListingContactActions({listingId,acceptsOffers,classNameMessage,classNameOffer,wrapperClassName,messageLabel="Envoyer un message",messageOnly=false,messageIconOnly=false}:{listingId:string;acceptsOffers:boolean;classNameMessage?:string;classNameOffer?:string;wrapperClassName?:string;messageLabel?:string;messageOnly?:boolean;messageIconOnly?:boolean}){
  const router=useRouter();
  const [busy,setBusy]=useState(false);const [showOffer,setShowOffer]=useState(false);const [amount,setAmount]=useState("");const [error,setError]=useState("");
  async function conversation(){const r=await fetch(`${apiBase()}/conversations`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({listingId})});if(r.status===401){const path=`${window.location.pathname}${window.location.search}`;navigateApp(router,`/connexion?next=${encodeURIComponent(path)}`);throw new Error("redirecting");}const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error??"conversation_failed");return p.conversation as {id:string};}
  async function message(){setBusy(true);setError("");try{const c=await conversation();navigateApp(router,`/messages?conversation=${encodeURIComponent(c.id)}`);}catch(e){if(e instanceof Error&&e.message!=="redirecting")setError(e.message==="cannot_message_own_listing"?"Vous ne pouvez pas contacter votre propre annonce.":"Impossible d’ouvrir la conversation.");}finally{setBusy(false)}}
  async function offer(){const value=Number(amount.replace(",","."));if(!Number.isFinite(value)||value<=0){setError("Montant de l’offre invalide.");return;}setBusy(true);setError("");try{const c=await conversation();const r=await fetch(`${apiBase()}/conversations/${c.id}/offers`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({amount:value})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error??"offer_failed");navigateApp(router,`/messages?conversation=${encodeURIComponent(c.id)}`);}catch(e){if(e instanceof Error&&e.message!=="redirecting")setError(e.message==="offers_disabled"?"Le vendeur n’accepte pas les offres sur cette annonce.":e.message==="cannot_message_own_listing"?"Vous ne pouvez pas faire une offre sur votre propre annonce.":"Impossible d’envoyer cette offre.");}finally{setBusy(false)}}
  return <div className={wrapperClassName} style={wrapperClassName?undefined:{display:"grid",gap:10}}><button type="button" className={classNameMessage} onClick={message} disabled={busy} aria-label={busy?"Ouverture de la messagerie":messageLabel} title={messageLabel}>{messageIconOnly?<AppIcon name="comments"/>:(busy?"Ouverture…":messageLabel)}</button>{!messageOnly&&acceptsOffers&&<>{!showOffer?<button type="button" className={classNameOffer} onClick={()=>setShowOffer(true)} disabled={busy}>Faire une offre</button>:<div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><input aria-label="Montant de l’offre" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Montant €" style={{minWidth:0,height:44,border:"1px solid #d1d5db",borderRadius:12,padding:"0 12px",font:"inherit"}}/><button type="button" className={classNameOffer} onClick={offer} disabled={busy||!amount} style={{marginTop:0,width:"auto",padding:"0 16px"}}>{busy?"Envoi…":"Envoyer"}</button></div>}</>}{error&&<div style={{fontSize:13,color:"#b91c1c"}}>{error}</div>}</div>;
}
