"use client";

import { FormEvent, useEffect, useState } from "react";
import { AppIcon } from "./app-icon";
import { VacationCalendarSync } from "./vacation-calendar-sync";
import styles from "./listing-vacation-availability.module.css";

type Block={id:string;startDate:string;endDate:string;note:string|null};
type Booking={instantBooking:boolean;depositEnabled:boolean;depositMode:"PERCENT"|"FIXED";depositPercent:number|null;depositFixedMinor:number|null;cancellationPolicy:"FLEXIBLE"|"MODERATE"|"STRICT";cleaningFeeMinor:number;extraGuestFeeMinor:number;baseGuestsIncluded:number;weekendNightlyPriceMinor:number|null;weeklyDiscountPercent:number;monthlyDiscountPercent:number;checkInTime:string;checkOutTime:string;minAdvanceDays:number;maxStayNights:number;sameDayBooking:boolean;checkInWeekdays:number[];checkOutWeekdays:number[]};
type SeasonalRate={id:string;listingId:string;label:string;startDate:string;endDate:string;nightlyPriceMinor:number;minimumNights:number|null};
type TouristTaxState={classification:string;classificationLabel:string;municipality:string|null;inseeCode:string|null;officialRate:{baseRate:number;totalRate:number;unit:"EUR"|"PERCENT";effectiveYear:number;source:string}|null;classifications:Array<{value:string;label:string}>};
const api=()=> (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"");
const weekdayOptions=[{value:1,label:"Lun"},{value:2,label:"Mar"},{value:3,label:"Mer"},{value:4,label:"Jeu"},{value:5,label:"Ven"},{value:6,label:"Sam"},{value:0,label:"Dim"}];
const euros=(minor:number|null|undefined)=>minor==null?"":String(minor/100);
function minor(value:string){const n=Number(value.replace(",","."));return Number.isFinite(n)?Math.round(n*100):NaN}
function date(value:string){return new Date(`${value}T12:00:00`).toLocaleDateString("fr-FR")}
function money(value:number){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:value%100===0?0:2}).format(value/100)}

export function ListingVacationAvailability({listingId}:{listingId:string}){
 const[blocks,setBlocks]=useState<Block[]>([]),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState(""),[note,setNote]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const[booking,setBooking]=useState<Booking>({instantBooking:false,depositEnabled:false,depositMode:"PERCENT",depositPercent:30,depositFixedMinor:null,cancellationPolicy:"FLEXIBLE",cleaningFeeMinor:0,extraGuestFeeMinor:0,baseGuestsIncluded:1,weekendNightlyPriceMinor:null,weeklyDiscountPercent:0,monthlyDiscountPercent:0,checkInTime:"15:00",checkOutTime:"11:00",minAdvanceDays:0,maxStayNights:365,sameDayBooking:true,checkInWeekdays:[0,1,2,3,4,5,6],checkOutWeekdays:[0,1,2,3,4,5,6]});
 const[depositEuros,setDepositEuros]=useState(""),[cleaningEuros,setCleaningEuros]=useState(""),[extraGuestEuros,setExtraGuestEuros]=useState(""),[weekendEuros,setWeekendEuros]=useState("");
 const[rates,setRates]=useState<SeasonalRate[]>([]),[seasonLabel,setSeasonLabel]=useState(""),[seasonStart,setSeasonStart]=useState(""),[seasonEnd,setSeasonEnd]=useState(""),[seasonPrice,setSeasonPrice]=useState(""),[seasonMinimum,setSeasonMinimum]=useState("");
 const[tax,setTax]=useState<TouristTaxState|null>(null),[taxClassification,setTaxClassification]=useState("UNCLASSIFIED");
 async function load(){setLoading(true);try{const[a,b,c,d]=await Promise.all([fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-availability`,{credentials:"include",cache:"no-store"}),fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-booking-settings`,{credentials:"include",cache:"no-store"}),fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-seasonal-rates`,{credentials:"include",cache:"no-store"}),fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-tourist-tax-settings`,{credentials:"include",cache:"no-store"})]);if(a.ok){const p=await a.json();setBlocks(p.blocks??[])}if(b.ok){const p=await b.json();const s=p.settings as Booking;setBooking(s);setDepositEuros(euros(s.depositFixedMinor));setCleaningEuros(euros(s.cleaningFeeMinor));setExtraGuestEuros(euros(s.extraGuestFeeMinor));setWeekendEuros(euros(s.weekendNightlyPriceMinor))}if(c.ok){const p=await c.json();setRates(p.rates??[])}if(d.ok){const p=await d.json();const t:TouristTaxState={classification:p.settings?.classification??"UNCLASSIFIED",classificationLabel:p.settings?.classificationLabel??"Non classé",municipality:p.location?.municipalityName??p.settings?.municipalityName??null,inseeCode:p.location?.inseeCode??p.settings?.inseeCode??null,officialRate:p.officialRate??null,classifications:p.classifications??[]};setTax(t);setTaxClassification(t.classification)}}finally{setLoading(false)}}
 useEffect(()=>{void load()},[listingId]);
 async function add(e:FormEvent){e.preventDefault();setMessage("");if(!startDate||!endDate||endDate<=startDate){setMessage("La date de fin doit être après la date de début.");return}setBusy(true);try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-availability`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({startDate,endDate,note:note.trim()||undefined})});if(!r.ok){setMessage("Impossible d’ajouter cette période pour le moment.");return}setStartDate("");setEndDate("");setNote("");setMessage("Période indisponible ajoutée.");await load()}catch{setMessage("Connexion interrompue pendant l’enregistrement.")}finally{setBusy(false)}}
 async function remove(id:string){setBusy(true);setMessage("");try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-availability/${encodeURIComponent(id)}`,{method:"DELETE",credentials:"include"});if(!r.ok){setMessage("Impossible de supprimer cette période.");return}setBlocks(current=>current.filter(block=>block.id!==id));setMessage("Période supprimée.")}finally{setBusy(false)}}
 async function saveBooking(){setMessage("");const fixedMinor=booking.depositMode==="FIXED"?minor(depositEuros):null,cleaning=cleaningEuros.trim()?minor(cleaningEuros):0,extra=extraGuestEuros.trim()?minor(extraGuestEuros):0,weekend=weekendEuros.trim()?minor(weekendEuros):null;if([cleaning,extra].some(v=>!Number.isFinite(v)||Number(v)<0)||weekend!==null&&(!Number.isFinite(weekend)||weekend<100)){setMessage("Vérifiez les montants de tarification saisis.");return}if(booking.depositEnabled&&booking.depositMode==="FIXED"&&(!fixedMinor||!Number.isFinite(fixedMinor)||fixedMinor<100)){setMessage("Indiquez un acompte fixe d’au moins 1 €.");return}setBusy(true);try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-booking-settings`,{method:"PUT",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({instantBooking:booking.instantBooking,depositEnabled:booking.depositEnabled,depositMode:booking.depositMode,depositPercent:booking.depositMode==="PERCENT"?(booking.depositPercent??30):null,depositFixedMinor:fixedMinor,cancellationPolicy:booking.cancellationPolicy,cleaningFeeMinor:cleaning,extraGuestFeeMinor:extra,baseGuestsIncluded:booking.baseGuestsIncluded,weekendNightlyPriceMinor:weekend,weeklyDiscountPercent:booking.weeklyDiscountPercent,monthlyDiscountPercent:booking.monthlyDiscountPercent,checkInTime:booking.checkInTime,checkOutTime:booking.checkOutTime,minAdvanceDays:booking.minAdvanceDays,maxStayNights:booking.maxStayNights,sameDayBooking:booking.sameDayBooking,checkInWeekdays:booking.checkInWeekdays,checkOutWeekdays:booking.checkOutWeekdays})});if(!r.ok){setMessage("Impossible d’enregistrer les conditions de réservation.");return}const p=await r.json();const s=p.settings as Booking;setBooking(s);setCleaningEuros(euros(s.cleaningFeeMinor));setExtraGuestEuros(euros(s.extraGuestFeeMinor));setWeekendEuros(euros(s.weekendNightlyPriceMinor));setMessage("Tarification et conditions enregistrées.")}catch{setMessage("Connexion interrompue pendant l’enregistrement.")}finally{setBusy(false)}}
 async function saveTouristTax(){setBusy(true);setMessage("");try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-tourist-tax-settings`,{method:"PUT",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({classification:taxClassification})});if(!r.ok){setMessage("Impossible d’enregistrer le classement pour la taxe de séjour.");return}setMessage("Classement fiscal Vacances enregistré. Les prochains devis utiliseront le tarif officiel de la commune.");await load()}catch{setMessage("Connexion interrompue pendant l’enregistrement de la taxe de séjour.")}finally{setBusy(false)}}
 async function addSeason(e:FormEvent){e.preventDefault();setMessage("");const price=minor(seasonPrice),minimum=seasonMinimum.trim()?Number(seasonMinimum):null;if(seasonLabel.trim().length<2||!seasonStart||!seasonEnd||seasonEnd<=seasonStart||!Number.isFinite(price)||price<100||minimum!==null&&(!Number.isInteger(minimum)||minimum<1)){setMessage("Vérifiez les dates, le prix et le minimum de nuits du tarif saisonnier.");return}setBusy(true);try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-seasonal-rates`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({label:seasonLabel.trim(),startDate:seasonStart,endDate:seasonEnd,nightlyPriceMinor:price,minimumNights:minimum})});const p=await r.json().catch(()=>null) as {error?:string}|null;if(!r.ok){setMessage(p?.error==="seasonal_rate_overlap"?"Cette période chevauche déjà un autre tarif saisonnier.":"Impossible d’ajouter ce tarif saisonnier.");return}setSeasonLabel("");setSeasonStart("");setSeasonEnd("");setSeasonPrice("");setSeasonMinimum("");setMessage("Tarif saisonnier ajouté.");await load()}finally{setBusy(false)}}
 async function removeSeason(id:string){setBusy(true);setMessage("");try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-seasonal-rates/${encodeURIComponent(id)}`,{method:"DELETE",credentials:"include"});if(!r.ok){setMessage("Impossible de supprimer ce tarif saisonnier.");return}setRates(current=>current.filter(rate=>rate.id!==id));setMessage("Tarif saisonnier supprimé.")}finally{setBusy(false)}}
 function toggleBookingDay(field:"checkInWeekdays"|"checkOutWeekdays",day:number){setBooking(current=>{const active=current[field].includes(day),next=active?current[field].filter(value=>value!==day):[...current[field],day];return next.length?{...current,[field]:next}:{...current}})}
 return <section className={styles.panel}>
  <div className={styles.head}><span><AppIcon name="calendar"/></span><div><small>Calendrier de disponibilité</small><h3>Périodes indisponibles</h3><p>Les dates comprises entre « Disponible du » et « Disponible jusqu’au » restent réservables, sauf les périodes que vous bloquez ici.</p></div></div>
  <form className={styles.form} onSubmit={add}><label><span>Indisponible du</span><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} required/></label><label><span>Jusqu’au</span><input type="date" value={endDate} min={startDate||undefined} onChange={e=>setEndDate(e.target.value)} required/></label><label className={styles.note}><span>Note privée (facultatif)</span><input value={note} maxLength={180} onChange={e=>setNote(e.target.value)} placeholder="Ex. réservation externe, fermeture…"/></label><button disabled={busy}>{busy?"Enregistrement…":"Bloquer ces dates"}</button></form>
  <div className={styles.blocks}>{loading?<span className={styles.empty}>Chargement du calendrier…</span>:blocks.length?blocks.map(block=><article key={block.id}><div><b>{date(block.startDate)} → {date(block.endDate)}</b><span>{block.note||"Indisponible"}</span></div><button type="button" disabled={busy} onClick={()=>void remove(block.id)}>Supprimer</button></article>):<span className={styles.empty}>Aucune période bloquée. Votre plage de disponibilité principale reste ouverte.</span>}</div>

  <VacationCalendarSync listingId={listingId}/>

  <div className={styles.pricingBox}><div className={styles.depositHead}><span><AppIcon name="credit-card"/></span><div><small>Tarification du séjour</small><h3>Prix et frais</h3><p>Le prix principal de l’annonce reste votre tarif normal par nuit. Ajoutez ici uniquement vos règles complémentaires.</p></div></div><div className={styles.pricingGrid}><label><span>Frais de ménage</span><div className={styles.withSuffix}><input inputMode="decimal" value={cleaningEuros} onChange={e=>setCleaningEuros(e.target.value)} placeholder="0"/><b>€ / séjour</b></div></label><label><span>Prix week-end</span><div className={styles.withSuffix}><input inputMode="decimal" value={weekendEuros} onChange={e=>setWeekendEuros(e.target.value)} placeholder="Optionnel"/><b>€ / nuit</b></div></label><label><span>Remise 7+ nuits</span><div className={styles.withSuffix}><input type="number" min="0" max="80" value={booking.weeklyDiscountPercent} onChange={e=>setBooking(v=>({...v,weeklyDiscountPercent:Math.max(0,Math.min(80,Number(e.target.value)||0))}))}/><b>%</b></div></label><label><span>Remise 28+ nuits</span><div className={styles.withSuffix}><input type="number" min="0" max="80" value={booking.monthlyDiscountPercent} onChange={e=>setBooking(v=>({...v,monthlyDiscountPercent:Math.max(0,Math.min(80,Number(e.target.value)||0))}))}/><b>%</b></div></label><label><span>Voyageurs inclus dans le prix</span><input type="number" min="1" max="50" value={booking.baseGuestsIncluded} onChange={e=>setBooking(v=>({...v,baseGuestsIncluded:Math.max(1,Number(e.target.value)||1)}))}/></label><label><span>Supplément par voyageur</span><div className={styles.withSuffix}><input inputMode="decimal" value={extraGuestEuros} onChange={e=>setExtraGuestEuros(e.target.value)} placeholder="0"/><b>€ / nuit</b></div></label></div><p className={styles.ruleHint}><AppIcon name="info"/>Vendredi et samedi utilisent le prix week-end, sauf si un tarif saisonnier couvre la date. Dès 7 nuits, la remise hebdomadaire s’applique aux nuits ; dès 28 nuits, la remise mensuelle la remplace. Les frais et la taxe de séjour ne sont pas remisés.</p></div>

  <div className={styles.pricingBox}><div className={styles.depositHead}><span><AppIcon name="home"/></span><div><small>TAXE DE SÉJOUR</small><h3>Classement officiel de l’hébergement</h3><p>Petit Annonces utilise la commune et les tarifs officiels DGFiP/DELTA pour calculer la taxe dans le devis du voyageur.</p></div></div><div className={styles.pricingGrid}><label><span>Classement tourisme</span><select value={taxClassification} onChange={e=>setTaxClassification(e.target.value)}>{(tax?.classifications??[]).map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label><span>Commune détectée</span><input readOnly value={tax?.municipality?`${tax.municipality}${tax.inseeCode?` · INSEE ${tax.inseeCode}`:""}`:"À confirmer depuis le code postal"}/></label><label><span>Tarif officiel actuel</span><input readOnly value={tax?.officialRate?`${tax.officialRate.totalRate}${tax.officialRate.unit==="PERCENT"?" %":" € / adulte / nuit"} · ${tax.officialRate.effectiveYear}`:"Tarif à confirmer"}/></label></div><p className={styles.ruleHint}><AppIcon name="info"/>Le « classement » correspond au classement touristique officiel, pas aux avis clients. Les mineurs sont exonérés. Le calcul est figé avec la réservation ; les autres exonérations légales restent à vérifier par l’hébergeur.</p><div className={styles.depositFoot}><p><AppIcon name="shield"/>Source : DGFiP / DELTA. La collecte et le reversement à la collectivité restent sous la responsabilité de l’hébergeur tant qu’un service de reversement Petit Annonces n’est pas activé.</p><button type="button" disabled={busy||!tax} onClick={()=>void saveTouristTax()}>{busy?"Enregistrement…":"Enregistrer le classement"}</button></div></div>

  <div className={styles.seasonBox}><div className={styles.seasonHead}><div><small>Tarifs saisonniers</small><h3>Haute saison, vacances scolaires, événements…</h3><p>Un tarif saisonnier remplace le prix normal et le prix week-end pour les nuits couvertes.</p></div></div><form className={styles.seasonForm} onSubmit={addSeason}><label><span>Nom</span><input value={seasonLabel} maxLength={80} onChange={e=>setSeasonLabel(e.target.value)} placeholder="Ex. Été 2027"/></label><label><span>Du</span><input type="date" value={seasonStart} onChange={e=>setSeasonStart(e.target.value)}/></label><label><span>Au</span><input type="date" min={seasonStart||undefined} value={seasonEnd} onChange={e=>setSeasonEnd(e.target.value)}/></label><label><span>Prix / nuit</span><div className={styles.withSuffix}><input inputMode="decimal" value={seasonPrice} onChange={e=>setSeasonPrice(e.target.value)} placeholder="120"/><b>€</b></div></label><label><span>Minimum de nuits</span><input type="number" min="1" max="90" value={seasonMinimum} onChange={e=>setSeasonMinimum(e.target.value)} placeholder="Optionnel"/></label><button disabled={busy}>{busy?"Enregistrement…":"Ajouter"}</button></form><div className={styles.seasonList}>{rates.length?rates.map(rate=><article key={rate.id}><div><strong>{rate.label}</strong><span>{date(rate.startDate)} → {date(rate.endDate)} · {money(rate.nightlyPriceMinor)} / nuit{rate.minimumNights?` · min. ${rate.minimumNights} nuit${rate.minimumNights>1?"s":""}`:""}</span></div><button type="button" disabled={busy} onClick={()=>void removeSeason(rate.id)}>Supprimer</button></article>):<span className={styles.empty}>Aucun tarif saisonnier. Le tarif normal ou week-end s’applique.</span>}</div></div>

  <div className={styles.pricingBox}><div className={styles.depositHead}><span><AppIcon name="clock"/></span><div><small>RÈGLES DE RÉSERVATION</small><h3>Arrivée, départ et durée du séjour</h3><p>Définissez quand un voyageur peut arriver, partir et combien de temps à l’avance il doit réserver.</p></div><label className={styles.depositSwitch}><input type="checkbox" checked={booking.sameDayBooking} onChange={e=>setBooking(v=>({...v,sameDayBooking:e.target.checked}))}/><span>{booking.sameDayBooking?"Même jour autorisé":"Même jour refusé"}</span></label></div><div className={styles.pricingGrid}><label><span>Heure d’arrivée</span><input type="time" value={booking.checkInTime} onChange={e=>setBooking(v=>({...v,checkInTime:e.target.value}))}/></label><label><span>Heure de départ</span><input type="time" value={booking.checkOutTime} onChange={e=>setBooking(v=>({...v,checkOutTime:e.target.value}))}/></label><label><span>Délai minimum avant arrivée</span><div className={styles.withSuffix}><input type="number" min="0" max="365" value={booking.minAdvanceDays} onChange={e=>setBooking(v=>({...v,minAdvanceDays:Math.max(0,Math.min(365,Number(e.target.value)||0))}))}/><b>jour(s)</b></div></label><label><span>Durée maximale</span><div className={styles.withSuffix}><input type="number" min="1" max="365" value={booking.maxStayNights} onChange={e=>setBooking(v=>({...v,maxStayNights:Math.max(1,Math.min(365,Number(e.target.value)||1))}))}/><b>nuit(s)</b></div></label></div><div className={styles.dayRules}><div><strong>Jours d’arrivée autorisés</strong><div className={styles.dayGrid}>{weekdayOptions.map(day=><label key={`in-${day.value}`} className={booking.checkInWeekdays.includes(day.value)?styles.dayActive:undefined}><input type="checkbox" checked={booking.checkInWeekdays.includes(day.value)} onChange={()=>toggleBookingDay("checkInWeekdays",day.value)}/><span>{day.label}</span></label>)}</div></div><div><strong>Jours de départ autorisés</strong><div className={styles.dayGrid}>{weekdayOptions.map(day=><label key={`out-${day.value}`} className={booking.checkOutWeekdays.includes(day.value)?styles.dayActive:undefined}><input type="checkbox" checked={booking.checkOutWeekdays.includes(day.value)} onChange={()=>toggleBookingDay("checkOutWeekdays",day.value)}/><span>{day.label}</span></label>)}</div></div></div><div className={styles.depositFoot}><p><AppIcon name="shield"/>Ces règles sont contrôlées côté serveur lors de chaque vérification et avant toute demande ou réservation instantanée.</p><button type="button" disabled={busy} onClick={()=>void saveBooking()}>{busy?"Enregistrement…":"Enregistrer les règles"}</button></div></div>

  <div className={styles.instantBox}><div className={styles.depositHead}><span><AppIcon name="bolt"/></span><div><small>MODE DE RÉSERVATION</small><h3>Réservation instantanée</h3><p>Autorisez les voyageurs à confirmer immédiatement les dates disponibles, sans attendre votre validation manuelle.</p></div><label className={styles.depositSwitch}><input type="checkbox" checked={booking.instantBooking} onChange={e=>setBooking(v=>({...v,instantBooking:e.target.checked}))}/><span>{booking.instantBooking?"Activée":"Désactivée"}</span></label></div><p className={styles.ruleHint}><AppIcon name="shield"/>{booking.instantBooking?"Les dates sont vérifiées une dernière fois et bloquées automatiquement dès la réservation. L’acompte, s’il est demandé, reste à régler depuis l’espace du voyageur.":"Les voyageurs envoient une demande et vous conservez l’étape Accepter / Refuser."}</p></div>

  <div className={styles.depositBox}><div className={styles.depositHead}><span><AppIcon name="credit-card"/></span><div><small>Conditions de réservation</small><h3>Demander un acompte</h3><p>Vous pouvez indiquer qu’un acompte sera demandé après acceptation de la réservation.</p></div><label className={styles.depositSwitch}><input type="checkbox" checked={booking.depositEnabled} onChange={e=>setBooking(v=>({...v,depositEnabled:e.target.checked}))}/><span>{booking.depositEnabled?"Activé":"Désactivé"}</span></label></div>{booking.depositEnabled&&<div className={styles.depositFields}><label><span>Mode de calcul</span><select value={booking.depositMode} onChange={e=>setBooking(v=>({...v,depositMode:e.target.value as Booking["depositMode"]}))}><option value="PERCENT">Pourcentage du séjour</option><option value="FIXED">Montant fixe</option></select></label>{booking.depositMode==="PERCENT"?<label><span>Pourcentage</span><div className={styles.withSuffix}><input type="number" min="1" max="100" value={booking.depositPercent??30} onChange={e=>setBooking(v=>({...v,depositPercent:Number(e.target.value)}))}/><b>%</b></div></label>:<label><span>Montant de l’acompte</span><div className={styles.withSuffix}><input inputMode="decimal" value={depositEuros} onChange={e=>setDepositEuros(e.target.value)} placeholder="Ex. 100"/><b>€</b></div></label>}</div>}<div className={styles.policyBox}><div><span>Politique d’annulation</span><select value={booking.cancellationPolicy} onChange={e=>setBooking(v=>({...v,cancellationPolicy:e.target.value as Booking["cancellationPolicy"]}))}><option value="FLEXIBLE">Flexible</option><option value="MODERATE">Modérée</option><option value="STRICT">Stricte</option></select></div><p>{booking.cancellationPolicy==="FLEXIBLE"?"Remboursement de l’acompte : 100 % au moins 1 jour avant l’arrivée, 50 % le jour de l’arrivée.":booking.cancellationPolicy==="MODERATE"?"Remboursement : 100 % au moins 7 jours avant, 50 % entre 2 et 6 jours, puis 0 %.":"Remboursement : 100 % au moins 14 jours avant, 50 % entre 7 et 13 jours, puis 0 %."} Si l’hôte annule avant versement, l’acompte est remboursé à 100 %.</p></div><div className={styles.depositFoot}><p><AppIcon name="info"/>Le prix détaillé, l’acompte et les conditions sont figés au moment de la demande du voyageur.</p><button type="button" disabled={busy} onClick={()=>void saveBooking()}>{busy?"Enregistrement…":"Enregistrer les prix et conditions"}</button></div></div>
  {message&&<p className={styles.message}>{message}</p>}
 </section>
}
