"use client";

import {FormEvent,useEffect,useState} from "react";
import {AppIcon} from "./app-icon";
import styles from "./vacation-stay-lifecycle.module.css";

const api=()=> (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"");
type State="UPCOMING"|"CHECKED_IN"|"NO_SHOW"|"CHECKED_OUT";
type Role="HOST"|"GUEST";
type IncidentType="DAMAGE"|"ACCESS"|"CLEANLINESS"|"SAFETY"|"BEHAVIOR"|"OTHER";
type Evidence={id:string;fileName:string;mimeType:string;sizeBytes:number;downloadUrl:string;createdAt:string};
type Incident={id:string;type:string;summary:string;status:"OPEN"|"UNDER_REVIEW"|"RESOLVED"|"CLOSED";supportTicketId:string|null;supportReference:string|null;resolution:string|null;isReporter:boolean;claimStatus:"NONE"|"REQUESTED"|"UNDER_REVIEW"|"APPROVED"|"REJECTED";claimedAmountMinor:number|null;approvedAmountMinor:number|null;currency:string;claimDecisionNote:string|null;evidence:Evidence[];createdAt:string;resolvedAt:string|null};
type Payload={role:Role;state:State;checkedInAt:string|null;noShowAt:string|null;checkedOutAt:string|null;checkIn:string;checkOut:string;canCheckIn:boolean;canNoShow:boolean;canCheckOut:boolean;incidents:Incident[]};
const stateLabel:Record<State,string>={UPCOMING:"À venir",CHECKED_IN:"Séjour en cours",NO_SHOW:"Absence signalée",CHECKED_OUT:"Séjour terminé"};
const incidentLabel:Record<string,string>={DAMAGE:"Dommage",ACCESS:"Accès / clés",CLEANLINESS:"Propreté",SAFETY:"Sécurité",BEHAVIOR:"Comportement",NO_SHOW:"Voyageur absent",OTHER:"Autre incident"};
const claimLabel:Record<string,string>={NONE:"Aucune demande",REQUESTED:"Montant déclaré",UNDER_REVIEW:"En cours d’examen",APPROVED:"Montant retenu",REJECTED:"Demande rejetée"};
const allowedEvidence=new Set(["image/jpeg","image/png","image/webp","image/avif","application/pdf"]);
function when(value:string|null){return value?new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):""}
function money(minor:number|null){return minor==null?"—":new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(minor/100)}
function fileSize(bytes:number){return bytes>=1024*1024?`${(bytes/(1024*1024)).toFixed(1)} Mo`:`${Math.max(1,Math.round(bytes/1024))} Ko`}

export function VacationStayLifecycle({reservationId}:{reservationId:string}){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[showIncident,setShowIncident]=useState(false),[type,setType]=useState<IncidentType>("DAMAGE"),[summary,setSummary]=useState(""),[claimDrafts,setClaimDrafts]=useState<Record<string,string>>({});
 async function load(){setLoading(true);try{const r=await fetch(`${api()}/vacances/reservations/${encodeURIComponent(reservationId)}/stay-lifecycle`,{credentials:"include",cache:"no-store"});if(r.ok){const p=await r.json() as Payload;setData(p);setClaimDrafts(current=>{const next={...current};for(const i of p.incidents)if(next[i.id]===undefined&&i.claimedAmountMinor)next[i.id]=(i.claimedAmountMinor/100).toFixed(2);return next})}}finally{setLoading(false)}}
 useEffect(()=>{void load()},[reservationId]);
 async function action(next:"CHECK_IN"|"NO_SHOW"|"CHECK_OUT"){if(next==="NO_SHOW"&&!window.confirm("Signaler que le voyageur ne s’est pas présenté ? Un dossier support sera ouvert et l’acompte sera bloqué jusqu’à vérification."))return;if(next==="CHECK_OUT"&&!window.confirm("Confirmer que le séjour est terminé ?"))return;setBusy(next);setMessage("");try{const r=await fetch(`${api()}/vacances/reservations/${encodeURIComponent(reservationId)}/stay-lifecycle`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({action:next})});const p=await r.json().catch(()=>null) as {error?:string}|null;if(!r.ok){setMessage(p?.error==="no_show_too_early"?"Le no-show ne peut être déclaré qu’au moins 2 heures après l’heure d’arrivée.":p?.error==="checkin_not_started"?"L’arrivée ne peut pas être confirmée avant la date de début du séjour.":"Cette action n’est pas disponible dans l’état actuel du séjour.");return}setMessage(next==="CHECK_IN"?"Arrivée confirmée.":next==="NO_SHOW"?"Absence signalée. Un dossier support a été ouvert et le versement est bloqué.":"Départ confirmé.");await load()}finally{setBusy("")}}
 async function report(e:FormEvent){e.preventDefault();if(summary.trim().length<20){setMessage("Décrivez l’incident avec au moins 20 caractères.");return}setBusy("INCIDENT");setMessage("");try{const r=await fetch(`${api()}/vacances/reservations/${encodeURIComponent(reservationId)}/incidents`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({type,summary:summary.trim()})});const p=await r.json().catch(()=>null) as {error?:string;supportReference?:string}|null;if(!r.ok){setMessage(p?.error==="incident_limit_reached"?"Plusieurs dossiers sont déjà ouverts pour ce séjour. Utilisez l’espace Assistance pour compléter le dossier existant.":"Impossible d’enregistrer le signalement.");return}setSummary("");setShowIncident(false);setMessage(`Signalement transmis au service client${p?.supportReference?` · ${p.supportReference}`:""}. Tout versement encore en attente est automatiquement protégé pendant l’examen.`);await load()}finally{setBusy("")}}
 async function saveClaim(incident:Incident){const raw=(claimDrafts[incident.id]??"").trim().replace(",",".");const amount=Number(raw);if(!Number.isFinite(amount)||amount<1||amount>50000){setMessage("Indiquez un montant de dommage compris entre 1 € et 50 000 €.");return}setBusy(`CLAIM:${incident.id}`);setMessage("");try{const r=await fetch(`${api()}/vacances/incidents/${encodeURIComponent(incident.id)}/claim`,{method:"PATCH",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({amountMinor:Math.round(amount*100)})});const p=await r.json().catch(()=>null) as {error?:string}|null;if(!r.ok){setMessage(p?.error==="damage_claim_host_only"?"Seul l’hôte peut déclarer un montant de dommage sur ce dossier.":"Le montant n’a pas pu être enregistré.");return}setMessage("Montant du préjudice enregistré. Aucun débit supplémentaire n’est effectué automatiquement.");await load()}finally{setBusy("")}}
 async function uploadEvidence(incident:Incident,files:FileList|null){if(!files?.length)return;const chosen=Array.from(files);setBusy(`EVIDENCE:${incident.id}`);setMessage("");try{for(const file of chosen){if(!allowedEvidence.has(file.type)){setMessage("Format non accepté. Utilisez JPG, PNG, WebP, AVIF ou PDF.");continue}if(file.size>10*1024*1024){setMessage(`${file.name} dépasse la limite de 10 Mo.`);continue}const r=await fetch(`${api()}/vacances/incidents/${encodeURIComponent(incident.id)}/evidence/upload-direct`,{method:"POST",credentials:"include",headers:{"content-type":"application/vnd.petitannonces.vacation-evidence","x-file-mime":file.type,"x-file-name":encodeURIComponent(file.name)},body:file});const p=await r.json().catch(()=>null) as {error?:string}|null;if(!r.ok){setMessage(p?.error==="evidence_limit_reached"?"Ce dossier contient déjà le nombre maximal de justificatifs.":"Un justificatif n’a pas pu être envoyé.");break}}await load();setMessage("Justificatif(s) ajouté(s) au dossier privé.")}finally{setBusy("")}}
 if(loading&&!data)return null;if(!data)return null;const active=data.incidents.filter(i=>["OPEN","UNDER_REVIEW"].includes(i.status));
 return <section className={styles.box}>
  <div className={styles.head}><div><span><AppIcon name="circle-check"/></span><div><small>SUIVI DU SÉJOUR</small><h3>{stateLabel[data.state]}</h3><p>Confirmez les étapes réelles du séjour et signalez rapidement tout problème.</p></div></div><b className={`${styles.state} ${styles[data.state.toLowerCase()]}`}>{stateLabel[data.state]}</b></div>
  <div className={styles.timeline}><div className={data.state!=="UPCOMING"?styles.done:""}><i/><span>Réservation</span></div><div className={["CHECKED_IN","CHECKED_OUT"].includes(data.state)?styles.done:""}><i/><span>Arrivée</span></div><div className={data.state==="CHECKED_OUT"?styles.done:""}><i/><span>Départ</span></div></div>
  <div className={styles.actions}>{data.canCheckIn&&<button disabled={Boolean(busy)} onClick={()=>void action("CHECK_IN")}><AppIcon name="door"/>Confirmer l’arrivée</button>}{data.canCheckOut&&<button disabled={Boolean(busy)} onClick={()=>void action("CHECK_OUT")}><AppIcon name="circle-check"/>Confirmer le départ</button>}{data.canNoShow&&<button className={styles.warning} disabled={Boolean(busy)} onClick={()=>void action("NO_SHOW")}>Signaler un no-show</button>}<button className={styles.report} disabled={Boolean(busy)} onClick={()=>setShowIncident(v=>!v)}><AppIcon name="shield"/>Signaler un incident</button></div>
  {showIncident&&<form className={styles.incidentForm} onSubmit={report}><div><strong>Ouvrir un dossier Vacances</strong><span>En cas de problème réel pendant ou après le séjour. L’acompte non versé sera mis en attente le temps de la vérification.</span></div><select value={type} onChange={e=>setType(e.target.value as IncidentType)}><option value="DAMAGE">Dommage dans le logement</option><option value="ACCESS">Problème d’accès / clés</option><option value="CLEANLINESS">Propreté</option><option value="SAFETY">Sécurité</option><option value="BEHAVIOR">Comportement</option><option value="OTHER">Autre incident</option></select><textarea rows={4} maxLength={3000} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Décrivez précisément ce qui s’est passé, avec les faits et les heures si possible…"/><div><button type="button" onClick={()=>setShowIncident(false)}>Annuler</button><button className={styles.submit} disabled={busy==="INCIDENT"}>{busy==="INCIDENT"?"Envoi…":"Transmettre au support"}</button></div></form>}
  {active.length>0&&<div className={styles.incidents}><strong>Dossier{active.length>1?"s":""} en cours</strong>{active.map(i=><article className={styles.incidentCard} key={i.id}><div className={styles.incidentTop}><div><b>{incidentLabel[i.type]??i.type}</b><span>{i.supportReference??"Dossier support"} · {i.status==="UNDER_REVIEW"?"En cours d’examen":"Ouvert"}</span><small>{i.summary}</small></div><a href={i.isReporter&&i.supportTicketId?`/assistance?ticket=${encodeURIComponent(i.supportTicketId)}`:"/assistance?category=DISPUTE"}>{i.isReporter?"Voir le dossier":"Contacter le support"}</a></div>
   {i.type==="DAMAGE"&&<div className={styles.claimBox}><div><strong>Demande d’indemnisation</strong><span>{claimLabel[i.claimStatus]??i.claimStatus}{i.claimedAmountMinor?` · ${money(i.claimedAmountMinor)}`:""}{i.claimStatus==="APPROVED"&&i.approvedAmountMinor!=null?` · retenu ${money(i.approvedAmountMinor)}`:""}</span>{i.claimDecisionNote&&<small>{i.claimDecisionNote}</small>}</div>{data.role==="HOST"&&<div className={styles.claimInput}><label>Préjudice estimé (€)<input inputMode="decimal" type="number" min="1" max="50000" step="0.01" value={claimDrafts[i.id]??""} onChange={e=>setClaimDrafts(v=>({...v,[i.id]:e.target.value}))}/></label><button type="button" disabled={Boolean(busy)} onClick={()=>void saveClaim(i)}>{busy===`CLAIM:${i.id}`?"Enregistrement…":"Enregistrer le montant"}</button></div>}<p>Aucun montant supplémentaire n’est prélevé automatiquement sur le voyageur. Le service client examine les justificatifs et le montant déclaré.</p></div>}
   <div className={styles.evidenceBox}><div className={styles.evidenceHead}><div><strong>Justificatifs privés</strong><span>{i.evidence?.length??0}/12 · photos ou PDF · 10 Mo maximum par fichier</span></div><label className={styles.uploadButton}><input type="file" multiple accept="image/jpeg,image/png,image/webp,image/avif,application/pdf" disabled={Boolean(busy)} onChange={e=>{void uploadEvidence(i,e.target.files);e.currentTarget.value=""}}/>{busy===`EVIDENCE:${i.id}`?"Envoi…":"Ajouter des fichiers"}</label></div>{i.evidence?.length>0&&<div className={styles.evidenceList}>{i.evidence.map(e=><a key={e.id} href={e.downloadUrl} target="_blank" rel="noreferrer"><AppIcon name={e.mimeType==="application/pdf"?"list":"image"}/><span><b>{e.fileName}</b><small>{fileSize(e.sizeBytes)}</small></span></a>)}</div>}<p><AppIcon name="shield"/>Les fichiers ne sont pas publics. Ils sont accessibles uniquement aux parties de la réservation et au service client.</p></div>
  </article>)}</div>}
  {data.state==="CHECKED_IN"&&data.checkedInAt&&<p className={styles.meta}>Arrivée confirmée le {when(data.checkedInAt)}.</p>}{data.state==="CHECKED_OUT"&&data.checkedOutAt&&<p className={styles.meta}>Départ confirmé le {when(data.checkedOutAt)}.</p>}{data.state==="NO_SHOW"&&<p className={styles.alert}><AppIcon name="info"/>Un contrôle support est requis avant toute décision sur l’acompte.</p>}
  {message&&<p className={styles.message}><AppIcon name="info"/>{message}</p>}
 </section>
}
