"use client";

import {FormEvent,useEffect,useState} from "react";
import {AppIcon} from "./app-icon";
import styles from "./vacation-stay-operations.module.css";

const api=()=> (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"");
type KeyMode="IN_PERSON"|"LOCKBOX"|"SMART_LOCK"|"RECEPTION"|"OTHER";
type Settings={listingId:string;checkInFrom:string;checkInUntil:string|null;checkOutUntil:string;keyHandoverMode:KeyMode;arrivalInstructions:string|null;accessInstructions:string|null;houseRules:string|null;autoGuestMessage:boolean;guestMessageHoursBefore:number;accessRevealHoursBefore:number;updatedAt:string|null};
const keyLabels:Record<KeyMode,string>={IN_PERSON:"Remise en main propre",LOCKBOX:"Boîte à clés",SMART_LOCK:"Serrure connectée",RECEPTION:"Réception",OTHER:"Autre"};

export function VacationStayOperations({listingId}:{listingId:string}){
 const[data,setData]=useState<Settings|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 async function load(){setLoading(true);setMessage("");try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-stay-operations`,{credentials:"include",cache:"no-store"});if(r.ok){const p=await r.json() as {settings:Settings};setData(p.settings)}}catch{setMessage("Impossible de charger les informations d’arrivée.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[listingId]);
 function patch<K extends keyof Settings>(key:K,value:Settings[K]){setData(v=>v?{...v,[key]:value}:v)}
 async function save(e:FormEvent){e.preventDefault();if(!data)return;setSaving(true);setMessage("");try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-stay-operations`,{method:"PUT",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({checkInFrom:data.checkInFrom,checkInUntil:data.checkInUntil||null,checkOutUntil:data.checkOutUntil,keyHandoverMode:data.keyHandoverMode,arrivalInstructions:data.arrivalInstructions,accessInstructions:data.accessInstructions,houseRules:data.houseRules,autoGuestMessage:data.autoGuestMessage,guestMessageHoursBefore:Number(data.guestMessageHoursBefore),accessRevealHoursBefore:Number(data.accessRevealHoursBefore)})});const p=await r.json().catch(()=>null) as {settings?:Settings}|null;if(!r.ok||!p?.settings){setMessage("Impossible d’enregistrer ces informations.");return}setData(p.settings);setMessage("Informations d’arrivée enregistrées.")}catch{setMessage("Connexion interrompue pendant l’enregistrement.")}finally{setSaving(false)}}
 if(loading&&!data)return <section className={styles.card}><span>Chargement des informations d’arrivée…</span></section>;
 if(!data)return <section className={styles.card}><span>{message||"Informations indisponibles."}</span></section>;
 return <form className={styles.card} onSubmit={save}>
  <div className={styles.head}><span><AppIcon name="door"/></span><div><small>ACCUEIL DES VOYAGEURS</small><h3>Arrivée, départ et remise des clés</h3><p>Préparez les informations utiles avant le séjour. Les instructions d’accès sensibles ne sont révélées au voyageur qu’à l’approche de l’arrivée.</p></div></div>
  <div className={styles.times}><label><span>Arrivée à partir de</span><input type="time" value={data.checkInFrom} onChange={e=>patch("checkInFrom",e.target.value)}/></label><label><span>Arrivée jusqu’à</span><input type="time" value={data.checkInUntil??""} onChange={e=>patch("checkInUntil",e.target.value||null)}/></label><label><span>Départ avant</span><input type="time" value={data.checkOutUntil} onChange={e=>patch("checkOutUntil",e.target.value)}/></label><label><span>Remise des clés</span><select value={data.keyHandoverMode} onChange={e=>patch("keyHandoverMode",e.target.value as KeyMode)}>{Object.entries(keyLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>
  <div className={styles.textGrid}><label><span>Instructions d’arrivée</span><textarea maxLength={2500} value={data.arrivalInstructions??""} onChange={e=>patch("arrivalInstructions",e.target.value)} placeholder="Ex. accès depuis la rue, étage, point de rendez-vous, parking…"/></label><label><span>Accès / remise des clés <em>information sensible</em></span><textarea maxLength={2500} value={data.accessInstructions??""} onChange={e=>patch("accessInstructions",e.target.value)} placeholder="Ex. emplacement de la boîte à clés, code ou procédure de remise…"/></label><label className={styles.full}><span>Règles du logement</span><textarea maxLength={3500} value={data.houseRules??""} onChange={e=>patch("houseRules",e.target.value)} placeholder="Ex. non-fumeur, pas de fête, respect du voisinage, animaux…"/></label></div>
  <div className={styles.automation}><label className={styles.switch}><input type="checkbox" checked={data.autoGuestMessage} onChange={e=>patch("autoGuestMessage",e.target.checked)}/><span><b>Rappel automatique avant l’arrivée</b><small>Petit Annonces envoie au voyageur un rappel sans inclure de code d’accès sensible.</small></span></label><label><span>Envoyer le rappel</span><select value={data.guestMessageHoursBefore} onChange={e=>patch("guestMessageHoursBefore",Number(e.target.value))}>{[24,48,72,120,168].map(v=><option key={v} value={v}>{v===24?"24 h":v===48?"48 h":v===72?"3 jours":v===120?"5 jours":"7 jours"} avant</option>)}</select></label><label><span>Révéler les instructions d’accès</span><select value={data.accessRevealHoursBefore} onChange={e=>patch("accessRevealHoursBefore",Number(e.target.value))}>{[24,48,72].map(v=><option key={v} value={v}>{v===24?"24 h":v===48?"48 h":"72 h"} avant</option>)}</select></label></div>
  <div className={styles.footer}><p><AppIcon name="shield"/>Les codes et consignes d’accès restent réservés à l’hôte et au voyageur d’une réservation acceptée.</p><button disabled={saving}>{saving?"Enregistrement…":"Enregistrer"}</button></div>
  {message&&<p className={styles.message}><AppIcon name="info"/>{message}</p>}
 </form>
}
