"use client";

import {FormEvent,useEffect,useState} from "react";
import {AppIcon} from "./app-icon";
import styles from "./vacation-calendar-sync.module.css";

const api=()=> (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"");
type Source={id:string;label:string;url:string;enabled:boolean;lastSyncAt:string|null;lastSuccessAt:string|null;lastError:string|null;eventCount:number;conflictCount:number;createdAt:string;updatedAt:string};
type Payload={sources:Source[];exportPath:string;syncIntervalMinutes:number;maxSources:number};
function dateTime(value:string|null){return value?new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"Jamais"}
function sourceError(code:string|null){if(!code)return"";if(code.includes("calendar_https_required"))return"L’adresse du calendrier doit utiliser HTTPS.";if(code.includes("unsafe_calendar_url"))return"Cette adresse de calendrier n’est pas autorisée.";if(code.includes("invalid_calendar_format"))return"Le fichier reçu n’est pas un calendrier iCal valide.";if(code.includes("calendar_http_"))return"Le calendrier externe ne répond pas correctement.";if(code.includes("calendar_too_large"))return"Le calendrier externe est trop volumineux.";return"La synchronisation a échoué. Vérifiez l’URL iCal et réessayez."}

export function VacationCalendarSync({listingId}:{listingId:string}){
 const[data,setData]=useState<Payload|null>(null),[url,setUrl]=useState(""),[label,setLabel]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[origin,setOrigin]=useState("");
 async function load(){setLoading(true);try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-calendar-sync`,{credentials:"include",cache:"no-store"});if(r.ok)setData(await r.json())}finally{setLoading(false)}}
 useEffect(()=>{setOrigin(window.location.origin);void load()},[listingId]);
 async function addSource(e:FormEvent){e.preventDefault();setMessage("");if(!url.trim()){setMessage("Collez l’URL iCal fournie par la plateforme externe.");return}setBusy("add");try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-calendar-sync/sources`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({url:url.trim(),label:label.trim()||undefined})});const p=await r.json().catch(()=>null) as {error?:string;sync?:{ok:boolean;eventCount:number;conflictCount?:number;error:string|null}}|null;if(!r.ok){setMessage(p?.error==="calendar_source_limit"?"Vous avez atteint la limite de calendriers externes.":sourceError(p?.error??null)||"Impossible d’ajouter ce calendrier.");return}setUrl("");setLabel("");setMessage(p?.sync?.ok?`Calendrier ajouté · ${p.sync.eventCount} période${p.sync.eventCount>1?"s":""} importée${p.sync.eventCount>1?"s":""}.${(p.sync.conflictCount??0)>0?` ${p.sync.conflictCount} conflit${(p.sync.conflictCount??0)>1?"s":""} à vérifier.`:""}`:`Calendrier enregistré, mais la première synchronisation a échoué. ${sourceError(p?.sync?.error??null)}`);await load()}finally{setBusy("")}}
 async function syncSource(source:Source){setBusy(source.id);setMessage("");try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-calendar-sync/sources/${encodeURIComponent(source.id)}/sync`,{method:"POST",credentials:"include"});const p=await r.json().catch(()=>null) as {ok?:boolean;eventCount?:number;conflictCount?:number;error?:string}|null;if(!r.ok||!p?.ok){setMessage(sourceError(p?.error??null));await load();return}setMessage(`Synchronisation terminée · ${p.eventCount??0} période${(p.eventCount??0)>1?"s":""} externe${(p.eventCount??0)>1?"s":""}.${(p.conflictCount??0)>0?` ${p.conflictCount} conflit${(p.conflictCount??0)>1?"s":""} à vérifier.`:""}`);await load()}finally{setBusy("")}}
 async function removeSource(source:Source){if(!window.confirm(`Supprimer le calendrier « ${source.label} » ? Les dates importées depuis cette source seront libérées.`))return;setBusy(source.id);setMessage("");try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-calendar-sync/sources/${encodeURIComponent(source.id)}`,{method:"DELETE",credentials:"include"});if(!r.ok){setMessage("Impossible de supprimer ce calendrier.");return}setMessage("Calendrier externe supprimé. Ses dates ont été libérées.");await load()}finally{setBusy("")}}
 function exportUrl(path=data?.exportPath??""){return `${origin}${path}`}
 async function copyExport(){if(!data?.exportPath)return;try{await navigator.clipboard.writeText(exportUrl());setMessage("Lien iCal Petit Annonces copié.")}catch{setMessage("Copiez le lien iCal affiché ci-dessous.")}}
 async function rotateExport(){if(!window.confirm("Générer un nouveau lien iCal ? L’ancien lien cessera immédiatement de fonctionner sur les plateformes externes."))return;setBusy("rotate");try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-calendar-sync/export/rotate`,{method:"POST",credentials:"include"});const p=await r.json().catch(()=>null) as {exportPath?:string}|null;if(!r.ok||!p?.exportPath){setMessage("Impossible de renouveler le lien iCal.");return}setData(v=>v?{...v,exportPath:p.exportPath!}:v);setMessage("Nouveau lien iCal généré. Pensez à le remplacer sur vos plateformes externes.")}finally{setBusy("")}}
 return <section className={styles.box}>
  <div className={styles.head}><span><AppIcon name="calendar"/></span><div><small>SYNCHRONISATION iCAL</small><h3>Airbnb, Booking.com et calendriers externes</h3><p>Importez les réservations externes pour fermer automatiquement les dates sur Petit Annonces. Synchronisation automatique toutes les {data?.syncIntervalMinutes??30} minutes.</p></div></div>
  <form className={styles.form} onSubmit={addSource}><label><span>Nom du calendrier</span><input value={label} maxLength={80} onChange={e=>setLabel(e.target.value)} placeholder="Ex. Airbnb, Booking.com"/></label><label className={styles.url}><span>URL iCal (.ics)</span><input type="url" inputMode="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…/calendar.ics" required/></label><button disabled={busy==="add"||Boolean(data&&data.sources.length>=data.maxSources)}>{busy==="add"?"Synchronisation…":"Ajouter et synchroniser"}</button></form>
  <div className={styles.sources}>{loading&&!data?<span className={styles.empty}>Chargement des calendriers…</span>:data?.sources.length?data.sources.map(source=><article key={source.id}><div className={styles.sourceInfo}><div><strong>{source.label}</strong><em>{source.lastError?"Erreur de synchronisation":"Synchronisé"}</em>{source.conflictCount>0&&<em className={styles.conflict}>{source.conflictCount} conflit{source.conflictCount>1?"s":""}</em>}</div><span title={source.url}>{source.url}</span><small>{source.eventCount} période{source.eventCount>1?"s":""} importée{source.eventCount>1?"s":""} · Dernier succès : {dateTime(source.lastSuccessAt)}</small>{source.lastError&&<p>{sourceError(source.lastError)}</p>}{source.conflictCount>0&&<p className={styles.conflictText}>Des dates externes chevauchent une réservation Petit Annonces acceptée. Vérifiez ce calendrier avant d’accueillir le voyageur.</p>}</div><div className={styles.sourceActions}><button type="button" disabled={busy===source.id} onClick={()=>void syncSource(source)}>{busy===source.id?"Synchronisation…":"Synchroniser"}</button><button type="button" className={styles.delete} disabled={busy===source.id} onClick={()=>void removeSource(source)}>Supprimer</button></div></article>):<span className={styles.empty}>Aucun calendrier externe connecté. Vous pouvez en ajouter jusqu’à {data?.maxSources??5}.</span>}</div>
  <div className={styles.exportBox}><div><small>EXPORTER PETIT ANNONCES</small><strong>Calendrier iCal de cet hébergement</strong><p>Ajoutez ce lien dans Airbnb, Booking.com ou une autre plateforme pour y bloquer les dates indisponibles de Petit Annonces. Le flux n’expose aucun nom de voyageur.</p></div><div className={styles.exportField}><input readOnly value={exportUrl()} aria-label="Lien iCal Petit Annonces"/><button type="button" onClick={()=>void copyExport()}>Copier</button></div><button type="button" className={styles.rotate} disabled={busy==="rotate"} onClick={()=>void rotateExport()}>Renouveler le lien</button></div>
  <p className={styles.hint}><AppIcon name="shield"/>Seules les URLs HTTPS publiques sont acceptées. Les adresses locales/privées, les redirections dangereuses et les fichiers excessifs sont refusés.</p>
  {message&&<p className={styles.message}><AppIcon name="info"/>{message}</p>}
 </section>
}
