"use client";

import { useEffect, useMemo, useState } from "react";
import { AppIcon } from "./app-icon";
import { VacationCalendarSync } from "./vacation-calendar-sync";
import { VacationStayOperations } from "./vacation-stay-operations";
import styles from "./vacation-calendar-manager.module.css";

const api=()=> (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"");
type Listing={id:string;title:string|null;slug:string|null;status:string;city:string|null;priceMinor:number|null;currency:string;category:{name:string;slug:string}};
type ManualBlock={id:string;startDate:string;endDate:string;note:string|null};
type ExternalBlock={id:string;startDate:string;endDate:string;note:string|null;sourceId:string|null};
type Reservation={id:string;checkIn:string;checkOut:string;guests:number;nights:number;status:"PENDING"|"ACCEPTED";availabilityBlockId:string|null;depositEnabled:boolean;depositAmountMinor:number;currency:string;message:string|null;guestName:string|null;createdAt:string;depositPayment:{status:string;amountMinor:number;currency:string}|null};
type Payload={month:string;monthStart:string;nextMonth:string;listings:Listing[];selectedListingId:string|null;manualBlocks:ManualBlock[];externalBlocks:ExternalBlock[];reservations:Reservation[];summary:{manualBlocks:number;externalBlocks:number;pendingRequests:number;acceptedReservations:number}};

function iso(d:Date){return d.toISOString().slice(0,10)}
function addDays(value:string,days:number){const d=new Date(`${value}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return iso(d)}
function monthShift(month:string,delta:number){const d=new Date(`${month}-01T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+delta);return iso(d).slice(0,7)}
function inRange(day:string,start:string,end:string){return day>=start&&day<end}
function money(minor:number,currency:string){return new Intl.NumberFormat("fr-FR",{style:"currency",currency,maximumFractionDigits:minor%100===0?0:2}).format(minor/100)}
function pretty(value:string){return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T12:00:00`))}
function monthLabel(month:string){return new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(`${month}-01T12:00:00`))}
function daysForMonth(month:string){const first=new Date(`${month}-01T00:00:00Z`);const next=new Date(first);next.setUTCMonth(next.getUTCMonth()+1);const mondayOffset=(first.getUTCDay()+6)%7;const cells:(string|null)[]=Array.from({length:mondayOffset},()=>null);for(let d=new Date(first);d<next;d.setUTCDate(d.getUTCDate()+1))cells.push(iso(d));while(cells.length%7)cells.push(null);return cells}

export function VacationCalendarManager(){
 const [payload,setPayload]=useState<Payload|null>(null),[month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)),[listingId,setListingId]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[selectionStart,setSelectionStart]=useState<string|null>(null),[selectionEnd,setSelectionEnd]=useState<string|null>(null),[dragging,setDragging]=useState(false),[note,setNote]=useState(""),[activeReservation,setActiveReservation]=useState<Reservation|null>(null),[activeBlock,setActiveBlock]=useState<ManualBlock|null>(null),[activeExternal,setActiveExternal]=useState<ExternalBlock|null>(null);
 const cells=useMemo(()=>daysForMonth(month),[month]);const today=new Date().toISOString().slice(0,10);
 async function load(nextListingId=listingId,nextMonth=month){setLoading(true);setMessage("");try{const q=new URLSearchParams({month:nextMonth});if(nextListingId)q.set("listingId",nextListingId);const r=await fetch(`${api()}/vacances/calendar?${q.toString()}`,{credentials:"include",cache:"no-store"});if(r.status===401){location.href="/connexion";return}const p=await r.json().catch(()=>null) as Payload|null;if(!r.ok||!p){setMessage("Impossible de charger le calendrier Vacances.");return}setPayload(p);if(p.selectedListingId&&!nextListingId)setListingId(p.selectedListingId)}catch{setMessage("Connexion interrompue pendant le chargement du calendrier.")}finally{setLoading(false)}}
 useEffect(()=>{void load("",month)},[]);
 async function changeListing(id:string){setListingId(id);setSelectionStart(null);setSelectionEnd(null);setActiveReservation(null);setActiveBlock(null);setActiveExternal(null);await load(id,month)}
 async function changeMonth(next:string){setMonth(next);setSelectionStart(null);setSelectionEnd(null);setActiveReservation(null);setActiveBlock(null);setActiveExternal(null);await load(listingId,next)}
 function statusFor(day:string){if(!payload)return{kind:"AVAILABLE" as const,reservation:null,block:null,external:null};const accepted=payload.reservations.find(r=>r.status==="ACCEPTED"&&inRange(day,r.checkIn,r.checkOut));if(accepted)return{kind:"ACCEPTED" as const,reservation:accepted,block:null,external:null};const external=payload.externalBlocks?.find(b=>inRange(day,b.startDate,b.endDate));if(external)return{kind:"EXTERNAL" as const,reservation:null,block:null,external};const block=payload.manualBlocks.find(b=>inRange(day,b.startDate,b.endDate));if(block)return{kind:"BLOCKED" as const,reservation:null,block,external:null};const pending=payload.reservations.find(r=>r.status==="PENDING"&&inRange(day,r.checkIn,r.checkOut));if(pending)return{kind:"PENDING" as const,reservation:pending,block:null,external:null};return{kind:"AVAILABLE" as const,reservation:null,block:null,external:null}}
 function selected(day:string){if(!selectionStart)return false;const end=selectionEnd??selectionStart;const a=selectionStart<end?selectionStart:end,b=selectionStart<end?end:selectionStart;return day>=a&&day<=b}
 function beginDesktop(day:string){if(day<today)return;const state=statusFor(day);if(state.kind==="ACCEPTED"){setActiveReservation(state.reservation);setActiveBlock(null);setActiveExternal(null);return}if(state.kind==="EXTERNAL"){setActiveExternal(state.external);setActiveBlock(null);setActiveReservation(null);return}if(state.kind==="BLOCKED"){setActiveBlock(state.block);setActiveReservation(null);setActiveExternal(null);return}setActiveReservation(null);setActiveBlock(null);setActiveExternal(null);setSelectionStart(day);setSelectionEnd(day);setDragging(true)}
 function enterDesktop(day:string){if(dragging&&selectionStart&&day>=today){const state=statusFor(day);if(state.kind!=="ACCEPTED"&&state.kind!=="BLOCKED"&&state.kind!=="EXTERNAL")setSelectionEnd(day)}}
 function finishDesktop(){if(dragging)setDragging(false)}
 function tapMobile(day:string){if(day<today)return;const state=statusFor(day);if(state.kind==="ACCEPTED"){setActiveReservation(state.reservation);setActiveBlock(null);setActiveExternal(null);return}if(state.kind==="EXTERNAL"){setActiveExternal(state.external);setActiveBlock(null);setActiveReservation(null);return}if(state.kind==="BLOCKED"){setActiveBlock(state.block);setActiveReservation(null);setActiveExternal(null);return}setActiveExternal(null);if(!selectionStart||selectionEnd){setSelectionStart(day);setSelectionEnd(null)}else setSelectionEnd(day)}
 function selectionRange(){if(!selectionStart)return null;const end=selectionEnd??selectionStart;const start=selectionStart<end?selectionStart:end,finish=selectionStart<end?end:selectionStart;return{start,endExclusive:addDays(finish,1),finish}}
 async function blockSelection(){const range=selectionRange();if(!range||!listingId)return;setBusy(true);setMessage("");try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-availability`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({startDate:range.start,endDate:range.endExclusive,note:note.trim()||"Blocage calendrier"})});const p=await r.json().catch(()=>null) as {error?:string}|null;if(!r.ok){setMessage(p?.error==="dates_already_blocked"?"Une partie de cette période est déjà bloquée ou réservée.":"Impossible de bloquer cette période.");return}setMessage(`Période bloquée du ${pretty(range.start)} au ${pretty(range.finish)}.`);setSelectionStart(null);setSelectionEnd(null);setNote("");await load(listingId,month)}finally{setBusy(false)}}
 async function removeBlock(block:ManualBlock){if(!listingId||!window.confirm("Rendre cette période de nouveau disponible ?"))return;setBusy(true);setMessage("");try{const r=await fetch(`${api()}/listings/${encodeURIComponent(listingId)}/vacation-availability/${encodeURIComponent(block.id)}`,{method:"DELETE",credentials:"include"});const p=await r.json().catch(()=>null) as {error?:string}|null;if(!r.ok){setMessage(p?.error==="reservation_block_protected"?"Cette période appartient à une réservation acceptée et ne peut pas être libérée manuellement.":"Impossible de rouvrir cette période.");return}setActiveBlock(null);setMessage("Période de nouveau disponible.");await load(listingId,month)}finally{setBusy(false)}}
 const current=payload?.listings.find(x=>x.id===listingId)??null;const range=selectionRange();
 return <section className={styles.manager}>
  <div className={styles.head}><div><span>PETIT ANNONCES VACANCES</span><h2>Calendrier des disponibilités</h2><p>Gérez les réservations et bloquez vos dates depuis un seul calendrier.</p></div>{payload&&payload.listings.length>0&&<select value={listingId} onChange={e=>void changeListing(e.target.value)}>{payload.listings.map(item=><option key={item.id} value={item.id}>{item.title||item.category.name}{item.city?` · ${item.city}`:""}</option>)}</select>}</div>
  {message&&<div className={styles.message}><AppIcon name="info"/><span>{message}</span></div>}
  {loading&&!payload?<div className={styles.empty}>Chargement du calendrier…</div>:payload&&payload.listings.length===0?<div className={styles.empty}><span>☀️</span><h3>Aucun hébergement Vacances</h3><p>Publiez un hôtel, appartement, gîte ou autre hébergement pour activer le calendrier.</p></div>:payload&&current&&<>
   <div className={styles.toolbar}><button type="button" onClick={()=>void changeMonth(monthShift(month,-1))} aria-label="Mois précédent"><AppIcon name="chevron-left"/></button><div><strong>{monthLabel(month)}</strong><small>{current.category.name} · {current.status}</small></div><button type="button" onClick={()=>void changeMonth(monthShift(month,1))} aria-label="Mois suivant"><AppIcon name="chevron-right"/></button></div>
   <div className={styles.stats}><div><i className={styles.availableDot}/><span>Disponible</span></div><div><i className={styles.pendingDot}/><span>Demande en attente · {payload.summary.pendingRequests}</span></div><div><i className={styles.acceptedDot}/><span>Réservé · {payload.summary.acceptedReservations}</span></div><div><i className={styles.externalDot}/><span>Externe · {payload.summary.externalBlocks??0}</span></div><div><i className={styles.blockedDot}/><span>Bloqué · {payload.summary.manualBlocks}</span></div></div>
   <VacationCalendarSync listingId={current.id}/>
   <VacationStayOperations listingId={current.id}/>
   <div className={styles.calendarWrap}><div className={styles.weekdays}>{["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"].map(d=><span key={d}>{d}</span>)}</div><div className={styles.grid} onMouseLeave={()=>setDragging(false)}>{cells.map((day,index)=>{if(!day)return <div className={styles.blank} key={`blank-${index}`}/>;const state=statusFor(day),past=day<today;const cls=state.kind==="ACCEPTED"?styles.accepted:state.kind==="EXTERNAL"?styles.external:state.kind==="BLOCKED"?styles.blocked:state.kind==="PENDING"?styles.pending:styles.available;return <button key={day} type="button" className={`${styles.day} ${cls} ${past?styles.past:""} ${selected(day)?styles.selected:""}`} onMouseDown={()=>beginDesktop(day)} onMouseEnter={()=>enterDesktop(day)} onMouseUp={finishDesktop} onClick={()=>{if(window.matchMedia("(pointer: coarse)").matches)tapMobile(day)}}><b>{Number(day.slice(-2))}</b><small>{state.kind==="ACCEPTED"?"Réservé":state.kind==="EXTERNAL"?"Externe":state.kind==="BLOCKED"?"Bloqué":state.kind==="PENDING"?"En attente":past?"Passé":"Libre"}</small>{state.reservation&&<span>{state.reservation.guestName||"Voyageur"}</span>}{state.external&&<span>iCal</span>}</button>})}</div></div>
   {range&&<div className={styles.selection}><div><strong>Bloquer du {pretty(range.start)} au {pretty(range.finish)}</strong><span>Sur ordinateur, faites glisser sur les jours. Sur mobile, touchez le premier puis le dernier jour.</span></div><input value={note} maxLength={180} onChange={e=>setNote(e.target.value)} placeholder="Note privée (facultatif)"/><button type="button" disabled={busy} onClick={()=>void blockSelection()}>{busy?"Enregistrement…":"Bloquer les dates"}</button><button type="button" className={styles.clear} onClick={()=>{setSelectionStart(null);setSelectionEnd(null)}}>Annuler</button></div>}
   {activeBlock&&<div className={styles.detail}><div><small>PÉRIODE BLOQUÉE</small><h3>{pretty(activeBlock.startDate)} → {pretty(addDays(activeBlock.endDate,-1))}</h3><p>{activeBlock.note||"Blocage manuel"}</p></div><button type="button" disabled={busy} onClick={()=>void removeBlock(activeBlock)}>Rendre disponible</button></div>}
   {activeExternal&&<div className={`${styles.detail} ${styles.externalDetail}`}><div><small>RÉSERVATION EXTERNE · iCAL</small><h3>{pretty(activeExternal.startDate)} → {pretty(addDays(activeExternal.endDate,-1))}</h3><p>{activeExternal.note||"Période importée depuis un calendrier externe"}. Modifiez ou supprimez cette période depuis la source Airbnb/Booking correspondante, puis synchronisez le calendrier.</p></div></div>}
   {activeReservation&&<div className={`${styles.detail} ${styles.reservationDetail}`}><div><small>{activeReservation.status==="ACCEPTED"?"RÉSERVATION CONFIRMÉE":"DEMANDE EN ATTENTE"}</small><h3>{activeReservation.guestName||"Voyageur Petit Annonces"}</h3><p>{pretty(activeReservation.checkIn)} → {pretty(activeReservation.checkOut)} · {activeReservation.nights} nuit{activeReservation.nights>1?"s":""} · {activeReservation.guests} voyageur{activeReservation.guests>1?"s":""}</p>{activeReservation.depositEnabled&&<span>Acompte : {money(activeReservation.depositAmountMinor,activeReservation.currency)} · {activeReservation.depositPayment?.status??"non payé"}</span>}{activeReservation.message&&<blockquote>“{activeReservation.message}”</blockquote>}</div><a href="#vacation-reservations">Gérer la réservation</a></div>}
  </>}
 </section>
}
