"use client";

import { useEffect, useState } from "react";
import { AppIcon } from "./app-icon";
import { VacationCalendarManager } from "./vacation-calendar-manager";
import { VacationStayReviewForm } from "./vacation-stay-review-form";
import { VacationStayGuide } from "./vacation-stay-guide";
import { VacationStayLifecycle } from "./vacation-stay-lifecycle";
import styles from "./vacation-reservations.module.css";
import { fetchWithRetry } from "../lib/fetch-resilient";

const api=()=> (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"");
type DepositPayment={id:string;status:"PENDING"|"PAID"|"PARTIALLY_REFUNDED"|"REFUND_PENDING"|"REFUNDED"|"FAILED"|"CANCELED";amountMinor:number;currency:string;paidAt:string|null;refundedAt:string|null};
type DepositPayout={id:string;status:"PENDING"|"HOLD"|"PROCESSING"|"PAID"|"FAILED"|"CANCELED";amountMinor:number;currency:string;eligibleAt:string;failureReason:string|null;paidAt:string|null};
type PriceBreakdown={nights:number;baseNightlyPriceMinor:number;nightSubtotalMinor:number;cleaningFeeMinor:number;extraGuestFeeMinor:number;extraGuests:number;totalMinor:number;minimumNights:number;nightRates:Array<{date:string;rateMinor:number;source:"BASE"|"WEEKEND"|"SEASON";label:string|null}>};
type ChangeRequest={id:string;reservationId:string;checkIn:string;checkOut:string;adults:number;children:number;guests:number;nights:number;estimatedStayMinor:number;touristTaxMinor:number;grandTotalMinor:number;priceBreakdown:PriceBreakdown;depositAmountMinor:number;message:string|null;status:"PENDING";createdAt:string};
type Reservation={id:string;listingId:string;checkIn:string;checkOut:string;guests:number;adults:number;children:number;nights:number;nightlyPriceMinor:number;estimatedStayMinor:number;touristTaxMinor:number;touristTaxBreakdown:{status?:string;municipality?:string|null;classificationLabel?:string;source?:string|null;message?:string|null}|null;grandTotalMinor:number|null;priceBreakdown:PriceBreakdown|null;currency:string;depositEnabled:boolean;depositMode:"PERCENT"|"FIXED"|null;depositAmountMinor:number;cancellationPolicy:"FLEXIBLE"|"MODERATE"|"STRICT";cancelledBy:"GUEST"|"HOST"|null;refundPercent:number|null;refundAmountMinor:number;cancellation:{policy:"FLEXIBLE"|"MODERATE"|"STRICT";guestRefundPercentNow:number|null};depositPayment:DepositPayment|null;depositPayout:DepositPayout|null;changeRequest:ChangeRequest|null;message:string|null;status:"PENDING"|"ACCEPTED"|"REJECTED"|"CANCELLED";createdAt:string;title:string|null;slug:string|null;city:string|null;guestName:string|null;hostName:string|null};
type HbxBooking={id:string;providerReference:string|null;clientReference:string;hotelCode:number;hotelName:string|null;city:string|null;imageUrl:string|null;checkIn:string;checkOut:string;guests:number;status:string;environment:string;currency:string|null;total:number|null;createdAt:string;updatedAt:string};
type HbxPayload={bookings:HbxBooking[]};
type Payload={asGuest:Reservation[];asHost:Reservation[]};
function money(minor:number,currency:string){return new Intl.NumberFormat("fr-FR",{style:"currency",currency,maximumFractionDigits:minor%100===0?0:2}).format(minor/100)}
function date(value:string){return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value.length===10?`${value}T12:00:00`:value))}
const statusLabel:Record<Reservation["status"],string>={PENDING:"En attente",ACCEPTED:"Acceptée",REJECTED:"Refusée",CANCELLED:"Annulée"};
const paymentLabel:Record<DepositPayment["status"],string>={PENDING:"En attente",PAID:"Payé",PARTIALLY_REFUNDED:"Partiellement remboursé",REFUND_PENDING:"Remboursement en cours",REFUNDED:"Remboursé",FAILED:"Paiement interrompu",CANCELED:"Annulé"};
const payoutLabel:Record<DepositPayout["status"],string>={PENDING:"Versement programmé",HOLD:"Compte de versement requis",PROCESSING:"Versement en cours",PAID:"Versé",FAILED:"Versement à vérifier",CANCELED:"Versement annulé"};
function policyLabel(policy:Reservation["cancellationPolicy"]){return policy==="FLEXIBLE"?"Flexible":policy==="MODERATE"?"Modérée":"Stricte"}
function policyCopy(policy:Reservation["cancellationPolicy"]){return policy==="FLEXIBLE"?"100 % ≥ 1 jour avant · 50 % le jour d’arrivée":policy==="MODERATE"?"100 % ≥ 7 jours · 50 % entre 2 et 6 jours · 0 % ensuite":"100 % ≥ 14 jours · 50 % entre 7 et 13 jours · 0 % ensuite"}

export function VacationReservations(){
 const[data,setData]=useState<Payload>({asGuest:[],asHost:[]}),[hbxBookings,setHbxBookings]=useState<HbxBooking[]>([]),[tab,setTab]=useState<"HOST"|"GUEST"|"HBX">("HOST"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const[editing,setEditing]=useState(""),[editCheckIn,setEditCheckIn]=useState(""),[editCheckOut,setEditCheckOut]=useState(""),[editAdults,setEditAdults]=useState("1"),[editChildren,setEditChildren]=useState("0"),[editMessage,setEditMessage]=useState("");
 async function load(){setLoading(true);try{const [nativeRes,hbxRes]=await Promise.all([fetchWithRetry(`${api()}/vacances/reservations/mine`,{credentials:"include",cache:"no-store"},{timeoutMs:7000,retries:1}),fetchWithRetry(`${api()}/vacances/hbx/bookings/mine`,{credentials:"include",cache:"no-store"},{timeoutMs:7000,retries:1})]);if(nativeRes.status===401||hbxRes.status===401){location.href="/connexion";return}if(!nativeRes.ok)throw new Error();setData(await nativeRes.json());if(hbxRes.ok){const hp=await hbxRes.json() as HbxPayload;setHbxBookings(hp.bookings??[])}else setHbxBookings([])}catch{setMessage("Impossible de charger les réservations.")}finally{setLoading(false)}}
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const paymentReturn=params.get("acompte");if(paymentReturn==="success"){setTab("GUEST");setMessage("Paiement transmis. La confirmation de l’acompte peut prendre quelques instants.")}else if(paymentReturn==="annule"){setTab("GUEST");setMessage("Paiement de l’acompte annulé. Vous pouvez reprendre le paiement depuis cette page.")}if(paymentReturn)window.history.replaceState({},"",window.location.pathname);void load()},[]);
 async function decision(id:string,decision:"ACCEPT"|"REJECT"){setBusy(id);setMessage("");try{const r=await fetch(`${api()}/vacances/reservations/${encodeURIComponent(id)}/decision`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({decision})});const p=await r.json().catch(()=>null) as {error?:string}|null;if(!r.ok){setMessage(p?.error==="dates_unavailable"?"Ces dates ne sont plus disponibles. La demande ne peut pas être acceptée.":"Impossible de traiter cette demande.");return}setMessage(decision==="ACCEPT"?"Réservation acceptée : les dates ont été bloquées automatiquement.":"Demande refusée.");await load()}finally{setBusy("")}}
 function startEdit(item:Reservation){setEditing(item.id);setEditCheckIn(item.checkIn);setEditCheckOut(item.checkOut);setEditAdults(String(item.adults??item.guests));setEditChildren(String(item.children??0));setEditMessage("");setMessage("")}
 async function submitChange(item:Reservation){if(!editCheckIn||!editCheckOut||editCheckOut<=editCheckIn){setMessage("La date de départ doit être après la date d’arrivée.");return}const adults=Math.max(1,Number(editAdults)||1),children=Math.max(0,Number(editChildren)||0);setBusy(item.id);setMessage("");try{const r=await fetch(`${api()}/vacances/reservations/${encodeURIComponent(item.id)}/change-requests`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({checkIn:editCheckIn,checkOut:editCheckOut,adults,children,message:editMessage.trim()||undefined})});const p=await r.json().catch(()=>null) as {error?:string;availability?:{reason?:string}}|null;if(!r.ok){setMessage(p?.error==="reservation_change_pending"?"Une demande de modification est déjà en attente.":p?.error==="reservation_change_noop"?"Aucune modification n’a été détectée.":p?.error==="dates_unavailable"?"Les nouvelles dates ne respectent pas les disponibilités ou les règles de réservation.":"Impossible d’envoyer la demande de modification.");return}setEditing("");setMessage("Demande de modification envoyée à l’hôte. Le nouveau prix a été recalculé.");await load()}finally{setBusy("")}}
 async function cancelChange(change:ChangeRequest){if(!window.confirm("Annuler cette demande de modification ? La réservation actuelle restera inchangée."))return;setBusy(change.id);setMessage("");try{const r=await fetch(`${api()}/vacances/reservation-change-requests/${encodeURIComponent(change.id)}/cancel`,{method:"POST",credentials:"include"});if(!r.ok){setMessage("Impossible d’annuler cette demande de modification.");return}setMessage("Demande de modification annulée. La réservation actuelle reste inchangée.");await load()}finally{setBusy("")}}
 async function changeDecision(change:ChangeRequest,decision:"APPROVE"|"REJECT"){setBusy(change.id);setMessage("");try{const r=await fetch(`${api()}/vacances/reservation-change-requests/${encodeURIComponent(change.id)}/decision`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({decision})});const p=await r.json().catch(()=>null) as {error?:string}|null;if(!r.ok){setMessage(p?.error==="dates_unavailable"?"Les nouvelles dates ne sont plus disponibles.":p?.error==="deposit_payment_in_progress"?"Un paiement d’acompte est actuellement en cours. Attendez sa confirmation ou son expiration avant d’accepter la modification.":p?.error==="paid_deposit_amount_change_requires_support"?"L’acompte a déjà été payé et le nouveau montant d’acompte est différent. Cette modification doit passer par l’assistance pour éviter un écart de paiement.":p?.error==="deposit_already_released_support_required"?"L’acompte est déjà en cours de versement ou versé. La modification nécessite l’assistance Petit Annonces.":"Impossible de traiter cette modification.");return}setMessage(decision==="APPROVE"?"Modification acceptée : réservation, prix, taxe de séjour et calendrier mis à jour.":"Modification refusée. La réservation actuelle reste inchangée.");await load()}finally{setBusy("")}}
 async function cancel(item:Reservation){const refund=tab==="HOST"?100:(item.cancellation.guestRefundPercentNow??100);const copy=item.status==="PENDING"?"Annuler cette demande de réservation ?":tab==="HOST"?"Annuler cette réservation ? L’acompte payé sera remboursé à 100 % tant qu’il n’a pas déjà été versé.":`Annuler cette réservation ? Selon la politique ${policyLabel(item.cancellationPolicy)}, le remboursement actuel de l’acompte est de ${refund} %. `;if(!window.confirm(copy))return;setBusy(item.id);setMessage("");try{const r=await fetch(`${api()}/vacances/reservations/${encodeURIComponent(item.id)}/cancel`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({reason:"Annulation depuis l’espace réservations"})});const p=await r.json().catch(()=>null) as {error?:string;refundPercent?:number;refundAmountMinor?:number;refundStatus?:string;actionUrl?:string}|null;if(!r.ok){setMessage(p?.error==="deposit_already_released_support_required"?"L’acompte a déjà été versé à l’hôte. L’annulation nécessite maintenant l’assistance Petit Annonces.":p?.error==="deposit_payment_state_requires_sync"?"Un paiement est en cours de confirmation. Réessayez après la mise à jour du statut.":p?.error==="deposit_refund_already_pending"?"Un remboursement est déjà en cours. Attendez sa confirmation avant une nouvelle action.":"Cette réservation ne peut pas être annulée automatiquement pour le moment.");return}const amount=p?.refundAmountMinor??0;setMessage(amount>0?`Réservation annulée. Remboursement ${p?.refundPercent??0} % : ${money(amount,item.currency)} ${p?.refundStatus==="PENDING"?"en cours":"confirmé"}.`:"Réservation annulée. Les dates sont de nouveau disponibles.");await load()}finally{setBusy("")}}
 async function payDeposit(id:string){setBusy(id);setMessage("");try{const r=await fetch(`${api()}/vacances/reservations/${encodeURIComponent(id)}/deposit-checkout`,{method:"POST",credentials:"include"});const p=await r.json().catch(()=>null) as {checkoutUrl?:string;error?:string}|null;if(!r.ok||!p?.checkoutUrl){setMessage(p?.error==="deposit_already_settled"?"Cet acompte est déjà traité.":"Impossible d’ouvrir le paiement de l’acompte pour le moment.");return}window.location.href=p.checkoutUrl}catch{setMessage("Connexion interrompue pendant l’ouverture du paiement.")}finally{setBusy("")}}
 async function refundDeposit(id:string){if(!window.confirm("Rembourser intégralement cet acompte ? Cette action déclenchera le remboursement via le prestataire de paiement."))return;setBusy(id);setMessage("");try{const r=await fetch(`${api()}/vacances/reservations/${encodeURIComponent(id)}/deposit-refund`,{method:"POST",credentials:"include"});const p=await r.json().catch(()=>null) as {error?:string;status?:string}|null;if(!r.ok){setMessage(p?.error==="deposit_already_released"?"L’acompte a déjà été envoyé vers le compte de versement et ne peut plus être remboursé automatiquement depuis cette action.":p?.error==="deposit_not_refundable"?"Cet acompte n’est pas remboursable dans son état actuel.":"Impossible de lancer le remboursement pour le moment.");return}setMessage(p?.status==="REFUNDED"?"Acompte remboursé.":"Remboursement de l’acompte demandé.");await load()}finally{setBusy("")}}
 const items=tab==="HOST"?data.asHost:tab==="GUEST"?data.asGuest:[];const pendingHost=data.asHost.filter(x=>x.status==="PENDING").length;
 return <div className={styles.wrap} id="vacation-reservations">
  <div className={styles.head}><div><span>PETIT ANNONCES VACANCES</span><h1>Mes réservations</h1><p>Suivez vos séjours, acomptes et versements.</p></div><a href="/vacances"><AppIcon name="search"/>Explorer Vacances</a></div>
  <VacationCalendarManager/>
  <div className={styles.tabs}><button className={tab==="HOST"?styles.active:""} onClick={()=>setTab("HOST")}><AppIcon name="home"/>Demandes reçues{pendingHost>0&&<b>{pendingHost}</b>}</button><button className={tab==="GUEST"?styles.active:""} onClick={()=>setTab("GUEST")}><AppIcon name="calendar"/>Mes séjours</button><button className={tab==="HBX"?styles.active:""} onClick={()=>setTab("HBX")}><AppIcon name="calendar"/>Hôtels HBX{hbxBookings.length>0&&<b>{hbxBookings.length}</b>}</button></div>
  {message&&<div className={styles.message}><AppIcon name="info"/>{message}</div>}
  {loading?<div className={styles.empty}>Chargement des réservations…</div>:tab==="HBX"?(hbxBookings.length===0?<div className={styles.empty}><span>🏨</span><h2>Aucune réservation d’hôtel HBX</h2><p>Vos réservations d’hôtels partenaires apparaîtront ici après confirmation.</p><a className={styles.hbxExplore} href="/vacances">Rechercher un hôtel</a></div>:<div className={styles.hbxList}>{hbxBookings.map(item=><article key={item.id} className={styles.hbxBookingCard}><div className={styles.hbxBookingPhoto}>{item.imageUrl?<img src={item.imageUrl} alt={item.hotelName??"Hôtel HBX"} loading="lazy"/>:<span>🏨</span>}<em>HBX · {item.environment.toUpperCase()}</em></div><div className={styles.hbxBookingBody}><div className={styles.hbxBookingTop}><div><span className={`${styles.hbxStatus} ${styles[`hbxStatus${item.status.toUpperCase()}`]??""}`}>{item.status}</span><h2>{item.hotelName??`Hôtel HBX #${item.hotelCode}`}</h2><p><AppIcon name="location"/>{item.city??"France"}</p></div>{item.total!=null&&<div className={styles.hbxBookingTotal}><span>Total</span><strong>{new Intl.NumberFormat("fr-FR",{style:"currency",currency:item.currency??"EUR"}).format(Number(item.total))}</strong></div>}</div><div className={styles.hbxBookingFacts}><div><span>Arrivée</span><b>{date(item.checkIn)}</b></div><div><span>Départ</span><b>{date(item.checkOut)}</b></div><div><span>Voyageurs</span><b>{item.guests}</b></div><div><span>Référence HBX</span><b>{item.providerReference??"En attente"}</b></div></div><div className={styles.hbxRefs}><span>Référence Petit Annonces</span><code>{item.clientReference}</code></div>{item.providerReference&&<a className={styles.hbxBookingLink} href={`/mon-compte/reservations/hbx/${encodeURIComponent(item.providerReference)}`}><AppIcon name="list"/>Voir le détail</a>}</div></article>)}</div>):items.length===0?<div className={styles.empty}><span>☀️</span><h2>{tab==="HOST"?"Aucune demande reçue":"Aucune demande de séjour"}</h2><p>{tab==="HOST"?"Les demandes envoyées depuis vos annonces Vacances apparaîtront ici.":"Vérifiez les disponibilités d’un hébergement puis envoyez votre demande."}</p></div>:<div className={styles.list}>{items.map(item=>{
   const payment=item.depositPayment,payout=item.depositPayout;
   const canPay=tab==="GUEST"&&item.status==="ACCEPTED"&&item.depositEnabled&&(!payment||["FAILED","CANCELED","PENDING"].includes(payment.status));
   const canRefund=tab==="HOST"&&item.status==="ACCEPTED"&&item.depositEnabled&&payment?.status==="PAID"&&!payout?.status.match(/PROCESSING|PAID/);const payoutReleased=Boolean(payout&&["PROCESSING","PAID"].includes(payout.status));
   return <article key={item.id} className={styles.card}>
    <div className={styles.top}><div><span className={`${styles.status} ${styles[item.status.toLowerCase()]}`}>{statusLabel[item.status]}</span><a href={item.slug?`/annonce/${item.slug}`:"/vacances"}><h2>{item.title||"Hébergement de vacances"}</h2></a><p><AppIcon name="location"/>{item.city||"France"}</p></div><div className={styles.total}><span>Total estimé</span><strong>{money(item.grandTotalMinor??item.estimatedStayMinor,item.currency)}</strong></div></div>
    <div className={styles.facts}><div><span>Arrivée</span><b>{date(item.checkIn)}</b></div><div><span>Départ</span><b>{date(item.checkOut)}</b></div><div><span>Durée</span><b>{item.nights} nuit{item.nights>1?"s":""}</b></div><div><span>Voyageurs</span><b>{item.adults??item.guests} adulte{(item.adults??item.guests)>1?"s":""}{item.children?` + ${item.children} enfant${item.children>1?"s":""}`:""}</b></div></div>
    {item.changeRequest&&<div className={styles.changeRequest}><div className={styles.changeHead}><div><span>MODIFICATION EN ATTENTE</span><strong>{date(item.changeRequest.checkIn)} → {date(item.changeRequest.checkOut)}</strong><small>{item.changeRequest.nights} nuit{item.changeRequest.nights>1?"s":""} · {item.changeRequest.adults} adulte{item.changeRequest.adults>1?"s":""}{item.changeRequest.children?` + ${item.changeRequest.children} enfant${item.changeRequest.children>1?"s":""}`:""}</small></div><div><span>Nouveau total</span><b>{money(item.changeRequest.grandTotalMinor,item.currency)}</b>{item.depositEnabled&&<small>Acompte recalculé : {money(item.changeRequest.depositAmountMinor,item.currency)}</small>}</div></div>{item.changeRequest.message&&<p>“{item.changeRequest.message}”</p>}{tab==="HOST"?<div className={styles.changeActions}><button disabled={busy===item.changeRequest.id} onClick={()=>void changeDecision(item.changeRequest!,"REJECT")}>Refuser</button><button className={styles.accept} disabled={busy===item.changeRequest.id} onClick={()=>void changeDecision(item.changeRequest!,"APPROVE")}><AppIcon name="circle-check"/>Accepter la modification</button></div>:<div className={styles.changeActions}><span>La réservation actuelle reste valable jusqu’à la décision de l’hôte.</span><button disabled={busy===item.changeRequest.id} onClick={()=>void cancelChange(item.changeRequest!)}>Annuler la demande</button></div>}</div>}
    {tab==="GUEST"&&item.status==="ACCEPTED"&&!item.changeRequest&&!payoutReleased&&editing!==item.id&&<div className={styles.modifyBar}><div><strong>Modifier mon séjour</strong><span>Changez les dates ou le nombre de voyageurs. Le tarif et la taxe seront recalculés avant validation par l’hôte.</span></div><button onClick={()=>startEdit(item)}><AppIcon name="calendar"/>Demander une modification</button></div>}
    {tab==="GUEST"&&item.status==="ACCEPTED"&&!item.changeRequest&&editing===item.id&&<div className={styles.changeForm}><div className={styles.changeFormGrid}><label><span>Nouvelle arrivée</span><input type="date" value={editCheckIn} onChange={e=>setEditCheckIn(e.target.value)}/></label><label><span>Nouveau départ</span><input type="date" min={editCheckIn||undefined} value={editCheckOut} onChange={e=>setEditCheckOut(e.target.value)}/></label><label><span>Adultes</span><input type="number" min="1" max="50" value={editAdults} onChange={e=>setEditAdults(e.target.value)}/></label><label><span>Enfants</span><input type="number" min="0" max="49" value={editChildren} onChange={e=>setEditChildren(e.target.value)}/></label></div><label className={styles.changeMessage}><span>Message à l’hôte (facultatif)</span><textarea rows={2} maxLength={500} value={editMessage} onChange={e=>setEditMessage(e.target.value)} placeholder="Ex. Nous souhaitons arriver un jour plus tôt…"/></label><div className={styles.changeActions}><button onClick={()=>setEditing("")}>Fermer</button><button className={styles.accept} disabled={busy===item.id} onClick={()=>void submitChange(item)}><AppIcon name="circle-check"/>Calculer et envoyer</button></div></div>}
    {item.priceBreakdown&&<div className={styles.priceBreakdown}><div><span>{item.nights} nuit{item.nights>1?"s":""}</span><b>{money(item.priceBreakdown.nightSubtotalMinor,item.currency)}</b></div>{item.priceBreakdown.cleaningFeeMinor>0&&<div><span>Frais de ménage</span><b>{money(item.priceBreakdown.cleaningFeeMinor,item.currency)}</b></div>}{item.priceBreakdown.extraGuestFeeMinor>0&&<div><span>Supplément voyageurs</span><b>{money(item.priceBreakdown.extraGuestFeeMinor,item.currency)}</b></div>}<div><span>Taxe de séjour{item.touristTaxBreakdown?.municipality?` · ${item.touristTaxBreakdown.municipality}`:""}</span><b>{item.touristTaxBreakdown?.status==="UNAVAILABLE"?"À confirmer":money(item.touristTaxMinor??0,item.currency)}</b></div><div className={styles.priceBreakdownTotal}><span>Total du séjour</span><strong>{money(item.grandTotalMinor??item.priceBreakdown.totalMinor,item.currency)}</strong></div>{item.touristTaxBreakdown?.source&&<small>Taxe calculée à la réservation à partir du tarif officiel DGFiP/DELTA.</small>}</div>}
    <div className={styles.people}><span>{tab==="HOST"?"Voyageur":"Hôte"}</span><b>{tab==="HOST"?(item.guestName||"Voyageur Petit Annonces"):(item.hostName||"Hôte Petit Annonces")}</b>{item.message&&<p>“{item.message}”</p>}</div>
    {item.depositEnabled&&<div className={styles.deposit}><AppIcon name="credit-card"/><div><span>Acompte</span><strong>{money(item.depositAmountMinor,item.currency)}</strong><small>{payment?paymentLabel[payment.status]:item.status==="ACCEPTED"?"À payer":"Prévu après acceptation"}</small></div>{payment&&<em className={`${styles.paymentStatus} ${styles[`payment${payment.status}`]??""}`}>{paymentLabel[payment.status]}</em>}</div>}
    <div className={styles.cancellationPolicy}><AppIcon name="info"/><div><span>Politique d’annulation · <b>{policyLabel(item.cancellationPolicy)}</b></span><small>{policyCopy(item.cancellationPolicy)}. {item.status==="ACCEPTED"&&tab==="GUEST"?`Remboursement actuel : ${item.cancellation.guestRefundPercentNow??0} % de l’acompte.`:"Si l’hôte annule avant le versement : 100 %."}</small></div></div>
    {["PAID","PARTIALLY_REFUNDED"].includes(payment?.status??"")&&payout&&<div className={`${styles.payoutBox} ${styles[`payout${payout.status}`]??""}`}><AppIcon name="credit-card"/><div><span>{tab==="HOST"?"Versement de l’acompte":"Protection de l’acompte"}</span><strong>{payoutLabel[payout.status]}</strong><small>{payout.status==="PENDING"?`Prévu à partir du ${date(payout.eligibleAt)} — 2 jours après l’arrivée.`:payout.status==="HOLD"?"La date de versement est atteinte mais le compte de versement de l’hôte doit être finalisé.":payout.status==="PROCESSING"?"Petit Annonces a lancé le transfert vers le compte de versement de l’hôte.":payout.status==="PAID"?`Acompte envoyé au compte de versement${payout.paidAt?` le ${date(payout.paidAt)}`:""}.`:payout.status==="FAILED"?"Le transfert sera retenté automatiquement. Aucun second acompte n’est demandé au voyageur.":"Aucun versement ne sera effectué."}</small></div></div>}
    {["PAID","PARTIALLY_REFUNDED"].includes(payment?.status??"")&&!payout&&<div className={styles.payoutBox}><AppIcon name="credit-card"/><div><span>Protection de l’acompte</span><strong>Conservé par Petit Annonces</strong><small>Le versement à l’hôte sera programmé 2 jours après la date d’arrivée.</small></div></div>}
    {tab==="HOST"&&item.status==="PENDING"&&<div className={styles.actions}><button disabled={busy===item.id} onClick={()=>void decision(item.id,"REJECT")}>Refuser</button><button className={styles.accept} disabled={busy===item.id} onClick={()=>void decision(item.id,"ACCEPT")}><AppIcon name="circle-check"/>Accepter et bloquer les dates</button></div>}
    {tab==="GUEST"&&item.status==="PENDING"&&<div className={styles.actions}><button disabled={busy===item.id} onClick={()=>void cancel(item)}>Annuler ma demande</button></div>}
    {item.status==="ACCEPTED"&&<div className={styles.cancelReservation}>{payoutReleased?<><div><strong>Annulation avec assistance</strong><span>L’acompte a déjà été envoyé ou le versement est en cours. Une vérification Petit Annonces est nécessaire.</span></div><a href="/assistance">Contacter l’assistance</a></>:<><div><strong>Annuler la réservation</strong><span>{tab==="HOST"?"Une annulation par l’hôte rembourse 100 % de l’acompte avant son versement.":`Remboursement actuel selon la politique ${policyLabel(item.cancellationPolicy)} : ${item.cancellation.guestRefundPercentNow??0} % de l’acompte.`}</span></div><button disabled={busy===item.id} onClick={()=>void cancel(item)}>Annuler la réservation</button></>}</div>}
    {canPay&&<div className={styles.paymentActions}><div><strong>{payment?.status==="PENDING"?"Paiement commencé":"Acompte à régler"}</strong><span>{payment?.status==="PENDING"?"Vous pouvez reprendre la session de paiement en cours.":"La réservation est acceptée. Réglez maintenant l’acompte demandé par l’hôte."}</span></div><button disabled={busy===item.id} onClick={()=>void payDeposit(item.id)}><AppIcon name="credit-card"/>{payment?.status==="PENDING"?"Reprendre le paiement":"Payer l’acompte"}</button></div>}
    {canRefund&&<div className={styles.refundActions}><div><strong>Acompte payé</strong><span>Avant le versement à l’hôte, vous pouvez encore lancer un remboursement intégral.</span></div><button disabled={busy===item.id} onClick={()=>void refundDeposit(item.id)}>Rembourser l’acompte</button></div>}
    {item.status==="ACCEPTED"&&<div className={styles.acceptedInfo}><AppIcon name="circle-check"/><span>{item.depositEnabled&&payment?.status!=="PAID"&&payment?.status!=="PARTIALLY_REFUNDED"&&payment?.status!=="REFUNDED"?"Réservation acceptée. Les dates sont bloquées et l’acompte reste à régler.":"Réservation acceptée. Les dates sont indisponibles pour les autres voyageurs."}</span></div>}
    {["ACCEPTED","CANCELLED"].includes(item.status)&&<a className={styles.receiptLink} href={`/mon-compte/reservations/${encodeURIComponent(item.id)}/recu`}><AppIcon name="list"/>Voir le reçu / récapitulatif</a>}
    {item.status==="ACCEPTED"&&<VacationStayLifecycle reservationId={item.id}/>} 
    {tab==="GUEST"&&item.status==="ACCEPTED"&&<VacationStayGuide reservationId={item.id}/>} 
    {item.status==="ACCEPTED"&&<VacationStayReviewForm reservationId={item.id} role={tab}/>} 
    {item.status==="CANCELLED"&&<div className={styles.cancelledInfo}><AppIcon name="info"/><div><strong>Réservation annulée {item.cancelledBy==="HOST"?"par l’hôte":item.cancelledBy==="GUEST"?"par le voyageur":""}</strong><span>Les dates ont été remises à disposition.{item.refundAmountMinor>0?` Remboursement prévu : ${item.refundPercent??0} % · ${money(item.refundAmountMinor,item.currency)}.`:item.refundPercent===0&&item.depositAmountMinor>0?" Aucun remboursement automatique de l’acompte selon la politique applicable.":""}</span></div></div>}
   </article>})}</div>}
 </div>
}
