"use client";

import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {AppIcon} from "../../../../../components/app-icon";
import styles from "./page.module.css";

const api=()=> (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"");
type Receipt={id:string;number:string;issuedAt:string;reservationId:string;status:string;checkIn:string;checkOut:string;nights:number;adults:number;children:number;guests:number;currency:string;title:string|null;city:string|null;postalCode:string|null;priceBreakdown:{nightSubtotalMinor?:number;cleaningFeeMinor?:number;extraGuestFeeMinor?:number;totalMinor?:number}|null;accommodationTotalMinor:number;touristTaxMinor:number;touristTaxBreakdown:{status?:string;municipality?:string|null;classificationLabel?:string;source?:string|null;message?:string|null}|null;grandTotalMinor:number;depositAmountMinor:number;depositEnabled:boolean;payment:{status:string;amountMinor:number;paidAt:string|null;refundedAmountMinor:number}|null;host:{kind:string;name:string;email:string;business:{legalName:string|null;tradeName:string|null;siren:string|null;siret:string|null;vatNumber:string|null;legalForm:string|null;address:string|null;postalCode:string|null;city:string|null}|null};guest:{name:string;email:string;address:{recipient:string|null;line1:string;line2:string|null;postalCode:string;city:string;countryCode:string}|null};documentNotice:string};
function money(value:number|undefined,currency="EUR"){return new Intl.NumberFormat("fr-FR",{style:"currency",currency}).format((value??0)/100)}
function date(value:string){return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(value.length===10?`${value}T12:00:00`:value))}

export default function Page(){
 const{id}=useParams<{id:string}>();const[receipt,setReceipt]=useState<Receipt|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;(async()=>{try{const r=await fetch(`${api()}/vacances/reservations/${encodeURIComponent(id)}/receipt`,{credentials:"include",cache:"no-store"});if(r.status===401){location.href=`/connexion?next=${encodeURIComponent(location.pathname)}`;return}const p=await r.json().catch(()=>null) as {receipt?:Receipt}|null;if(!r.ok||!p?.receipt){if(active)setError("Ce reçu n’est pas disponible pour cette réservation.");return}if(active)setReceipt(p.receipt)}catch{if(active)setError("Impossible de charger le récapitulatif de réservation.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[id]);
 return <div className={styles.page}><div className={styles.noPrint}></div><main className={styles.shell}>{loading?<div className={styles.state}>Chargement du reçu…</div>:error||!receipt?<div className={styles.state}><AppIcon name="info"/><h1>Reçu indisponible</h1><p>{error}</p><a href="/mon-compte/reservations">Retour aux réservations</a></div>:<>
  <div className={`${styles.actions} ${styles.noPrint}`}><a href="/mon-compte/reservations">← Mes réservations</a><button type="button" onClick={()=>window.print()}><AppIcon name="list"/>Imprimer / enregistrer en PDF</button></div>
  <article className={styles.receipt}>
   <header><div><strong>PETIT ANNONCES</strong><span>VACANCES</span><p>Reçu / récapitulatif de réservation</p></div><div className={styles.reference}><small>N° DU REÇU</small><b>{receipt.number}</b><span>Émis le {date(receipt.issuedAt)}</span></div></header>
   <section className={styles.hero}><div><small>HÉBERGEMENT</small><h1>{receipt.title||"Hébergement de vacances"}</h1><p>{[receipt.postalCode,receipt.city].filter(Boolean).join(" ")}</p></div><span className={styles.status}>{receipt.status==="CANCELLED"?"Réservation annulée":"Réservation confirmée"}</span></section>
   <section className={styles.parties}><div><small>HÔTE</small><strong>{receipt.host.name}</strong>{receipt.host.business?<><span>{receipt.host.business.legalName}</span>{receipt.host.business.siret&&<span>SIRET : {receipt.host.business.siret}</span>}{receipt.host.business.vatNumber&&<span>TVA : {receipt.host.business.vatNumber}</span>}<span>{[receipt.host.business.address,receipt.host.business.postalCode,receipt.host.business.city].filter(Boolean).join(" · ")}</span></>:<span>Particulier</span>}</div><div><small>VOYAGEUR</small><strong>{receipt.guest.name}</strong><span>{receipt.guest.email}</span>{receipt.guest.address&&<span>{[receipt.guest.address.line1,receipt.guest.address.line2,receipt.guest.address.postalCode,receipt.guest.address.city].filter(Boolean).join(" · ")}</span>}</div></section>
   <section className={styles.stay}><div><small>ARRIVÉE</small><b>{date(receipt.checkIn)}</b></div><div><small>DÉPART</small><b>{date(receipt.checkOut)}</b></div><div><small>DURÉE</small><b>{receipt.nights} nuit{receipt.nights>1?"s":""}</b></div><div><small>VOYAGEURS</small><b>{receipt.adults} adulte{receipt.adults>1?"s":""}{receipt.children?` · ${receipt.children} enfant${receipt.children>1?"s":""}`:""}</b></div></section>
   <section className={styles.amounts}><h2>Détail du séjour</h2><div><span>Hébergement · {receipt.nights} nuit{receipt.nights>1?"s":""}</span><b>{money(receipt.priceBreakdown?.nightSubtotalMinor??receipt.accommodationTotalMinor,receipt.currency)}</b></div>{Boolean(receipt.priceBreakdown?.cleaningFeeMinor)&&<div><span>Frais de ménage</span><b>{money(receipt.priceBreakdown?.cleaningFeeMinor,receipt.currency)}</b></div>}{Boolean(receipt.priceBreakdown?.extraGuestFeeMinor)&&<div><span>Supplément voyageurs</span><b>{money(receipt.priceBreakdown?.extraGuestFeeMinor,receipt.currency)}</b></div>}<div className={styles.subtotal}><span>Sous-total hébergement</span><b>{money(receipt.accommodationTotalMinor,receipt.currency)}</b></div><div><span>Taxe de séjour{receipt.touristTaxBreakdown?.municipality?` · ${receipt.touristTaxBreakdown.municipality}`:""}</span><b>{receipt.touristTaxBreakdown?.status==="UNAVAILABLE"?"À confirmer":money(receipt.touristTaxMinor,receipt.currency)}</b></div><div className={styles.grand}><span>Total du séjour</span><strong>{money(receipt.grandTotalMinor,receipt.currency)}</strong></div></section>
   {receipt.touristTaxBreakdown&&<section className={styles.tax}><AppIcon name="info"/><div><strong>Taxe de séjour</strong><p>{receipt.touristTaxBreakdown.classificationLabel??"Classement enregistré"}. {receipt.touristTaxBreakdown.source?"Calcul fondé sur les données officielles DGFiP/DELTA. ":""}{receipt.children>0?`${receipt.children} mineur${receipt.children>1?"s":""} déclaré${receipt.children>1?"s":""}, exonéré${receipt.children>1?"s":""} de taxe de séjour. `:""}{receipt.touristTaxBreakdown.message??""}</p></div></section>}
   {receipt.depositEnabled&&<section className={styles.deposit}><div><small>ACOMPTE DE RÉSERVATION</small><strong>{money(receipt.depositAmountMinor,receipt.currency)}</strong></div><div><span>Statut</span><b>{receipt.payment?.status??"Non payé"}</b>{receipt.payment?.paidAt&&<small>Payé le {date(receipt.payment.paidAt)}</small>}{Boolean(receipt.payment?.refundedAmountMinor)&&<small>Remboursé : {money(receipt.payment?.refundedAmountMinor,receipt.currency)}</small>}</div></section>}
   <footer><p>{receipt.documentNotice}</p><p>Référence réservation : {receipt.reservationId}</p><small>Petit Annonces · petitannonces.fr</small></footer>
  </article>
 </>}</main></div>
}
