"use client";

import { useEffect, useState } from "react";
import { AppIcon } from "../../components/app-icon";
import styles from "../auth.module.css";

function apiBase(){return (process.env.NEXT_PUBLIC_API_URL??"/api").replace(/\/$/,"")}

export default function VerifyEmailPage(){
  const [state,setState]=useState<"loading"|"success"|"error">("loading");
  const [nextTarget,setNextTarget]=useState("/bienvenue");
  useEffect(()=>{const q=new URLSearchParams(window.location.search);const token=q.get("token")??"";const next=q.get("next");if(next&&next.startsWith("/")&&!next.startsWith("//"))setNextTarget(next);if(!token){setState("error");return}fetch(`${apiBase()}/auth/verify-email`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({token})}).then(r=>{if(!r.ok)throw new Error();setState("success")}).catch(()=>setState("error"))},[]);
  return <div className={styles.page}><main className={styles.main}><div className={styles.authGrid}><section className={styles.formCard}><span className={styles.eyebrow}>Vérification e-mail</span><h1 className={styles.title}>{state==="loading"?"Vérification en cours…":state==="success"?"Votre e-mail est vérifié":"Lien de vérification invalide"}</h1><p className={styles.lead}>{state==="loading"?"Nous validons votre lien sécurisé.":state==="success"?"Votre compte Petit Annonces est maintenant activé et vous êtes connecté. Un crédit de bienvenue de 5,00 € a été ajouté à votre compte.":"Le lien a expiré, a déjà été utilisé ou n’est pas valide."}</p>{state==="success"&&<a className={styles.primary} href={nextTarget}>{nextTarget.startsWith("/espace-pro/abonnement")?"Continuer vers mon abonnement Pro":nextTarget.startsWith("/espace-pro")?"Accéder à mon Espace Pro":"Continuer"}</a>}{state==="error"&&<div className={styles.error}>Demandez un nouveau lien de vérification depuis votre compte ou recommencez l’inscription si nécessaire.</div>}<p className={styles.footText}><a href="/connexion">Aller à la connexion</a></p></section><aside className={styles.benefitCard}><span className={styles.eyebrow}>Compte activé</span><h2 className={styles.title}>La vérification renforce la confiance.</h2><p className={styles.lead}>Une adresse e-mail confirmée facilite la récupération du compte, les notifications et les échanges avec les autres membres.</p><div className={styles.benefits}><div className={styles.benefit}><div className={styles.benefitIcon}><AppIcon name="circle-check"/></div><div><strong>Compte activé</strong><p>Accédez aux annonces, favoris, messages et transactions.</p></div></div><div className={styles.benefit}><div className={styles.benefitIcon}><AppIcon name="envelope"/></div><div><strong>Notifications fiables</strong><p>Recevez les messages importants liés à votre activité.</p></div></div><div className={styles.benefit}><div className={styles.benefitIcon}><AppIcon name="lock"/></div><div><strong>Récupération simplifiée</strong><p>Retrouvez plus facilement votre compte en cas d’oubli du mot de passe.</p></div></div></div></aside></div></main></div>
}
