import { useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { router, useFocusEffect } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PA } from '../constants/theme';
import { useAuth } from '../lib/auth';
import { apiRequest } from '../lib/api';
import { money } from '../lib/format';
import { AppIcon } from '../components/app-icon';

type Favorite={id:string;listingId:string;title:string|null;slug:string|null;priceMinor:number|null;currency:string;city:string|null;categoryName:string;categoryDomain:string;propertyTransactionType?:string|null;imageUrl:string|null;createdAt:string};

export default function FavoritesScreen(){
  const {user,token,loading:authLoading}=useAuth();
  const [items,setItems]=useState<Favorite[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
  const load=useCallback(async(soft=false)=>{if(!token){setLoading(false);return}if(soft)setRefreshing(true);else setLoading(true);setError('');try{const p=await apiRequest<{favorites:Favorite[]}>('/account/favorites',{token});setItems(p.favorites??[])}catch{setError('Impossible de charger vos favoris.')}finally{setLoading(false);setRefreshing(false)}},[token]);
  useFocusEffect(useCallback(()=>{void load();return()=>{}},[load]));
  async function remove(listingId:string){if(!token)return;const before=items;setItems(v=>v.filter(x=>x.listingId!==listingId));try{await apiRequest(`/account/favorites/${encodeURIComponent(listingId)}`,{method:'DELETE',token})}catch{setItems(before)}}
  if(authLoading)return <SafeAreaView style={s.center}><ActivityIndicator color={PA.primary}/></SafeAreaView>;
  if(!user||!token)return <SafeAreaView style={s.safe}><View style={s.top}><Pressable onPress={()=>router.back()} style={s.back}><AppIcon name="chevron-left" size={15} color={PA.ink}/></Pressable><Text style={s.topTitle}>Mes favoris</Text><View style={{width:40}}/></View><View style={s.guest}><AppIcon name="heart" size={18} color={PA.primary} solid={false}/><Text style={s.guestTitle}>Retrouvez vos annonces préférées</Text><Text style={s.guestText}>Connectez-vous pour synchroniser vos favoris sur tous vos appareils.</Text><Pressable style={s.primary} onPress={()=>router.push('/auth/login')}><Text style={s.primaryText}>Se connecter</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={s.safe}><View style={s.top}><Pressable onPress={()=>router.back()} style={s.back}><AppIcon name="chevron-left" size={15} color={PA.ink}/></Pressable><View><Text style={s.eyebrow}>MON COMPTE</Text><Text style={s.topTitle}>Mes favoris</Text></View><Text style={s.count}>{items.length}</Text></View>{loading?<View style={s.center}><ActivityIndicator color={PA.primary}/></View>:<FlatList data={items} keyExtractor={x=>x.id} contentContainerStyle={items.length?s.list:s.emptyList} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={PA.primary}/>} ListHeaderComponent={error?<Text style={s.error}>{error}</Text>:null} ListEmptyComponent={<View style={s.empty}><AppIcon name="heart" size={18} color={PA.primary} solid={false}/><Text style={s.emptyTitle}>Aucun favori pour le moment</Text><Text style={s.emptyText}>Ajoutez des annonces à vos favoris pour les retrouver rapidement ici.</Text><Pressable style={s.outline} onPress={()=>router.push('/(tabs)/search')}><Text style={s.outlineText}>Découvrir les annonces</Text></Pressable></View>} renderItem={({item})=><Pressable style={s.card} onPress={()=>item.slug&&router.push(`/annonce/${item.slug}` as never)}><View style={s.imageWrap}>{item.imageUrl?<Image source={{uri:item.imageUrl}} style={s.image} contentFit="cover" transition={100}/>:<View style={s.noImage}><Text style={s.noImageText}>PA</Text></View>}</View><View style={s.body}><Text style={s.category} numberOfLines={1}>{item.categoryName}</Text><Text style={s.title} numberOfLines={2}>{item.title||'Annonce Petit Annonces'}</Text><Text style={s.price}>{money(item.priceMinor,item.currency)}</Text><View style={{flexDirection:'row',alignItems:'center',gap:4}}><AppIcon name="location" size={9} color={PA.muted}/><Text style={s.meta} numberOfLines={1}>{item.city||'France'}</Text></View></View><Pressable hitSlop={10} onPress={()=>void remove(item.listingId)} style={s.heart}><AppIcon name="heart" size={18} color={PA.accent} solid={true}/></Pressable></Pressable>}/>}</SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:PA.bg},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:PA.bg},top:{minHeight:60,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:PA.bg},back:{width:40,height:40,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center'},backText:{fontSize:30,lineHeight:31,color:PA.ink},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1,color:PA.primary},topTitle:{fontSize:18,fontWeight:'900',color:PA.ink},count:{minWidth:36,height:30,paddingHorizontal:8,borderRadius:15,textAlign:'center',textAlignVertical:'center',backgroundColor:'#ece9ff',color:PA.primary,fontWeight:'900'},list:{padding:14,paddingBottom:28},emptyList:{flexGrow:1,padding:18},error:{padding:11,borderRadius:12,backgroundColor:'#fff1f1',color:PA.danger,marginBottom:10},card:{minHeight:128,flexDirection:'row',gap:12,padding:10,marginBottom:11,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line},imageWrap:{width:118,height:108,borderRadius:15,overflow:'hidden',backgroundColor:'#f0f1f5'},image:{width:'100%',height:'100%'},noImage:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#efedff'},noImageText:{fontSize:22,fontWeight:'900',color:PA.primary},body:{flex:1,minWidth:0,paddingVertical:2,paddingRight:28},category:{fontSize:9,fontWeight:'900',textTransform:'uppercase',color:PA.primary},title:{fontSize:14,fontWeight:'900',lineHeight:18,color:PA.ink,marginTop:4},price:{fontSize:17,fontWeight:'900',color:PA.ink,marginTop:7},meta:{fontSize:10.5,color:PA.muted,marginTop:5},heart:{position:'absolute',right:10,top:10,width:32,height:32,borderRadius:16,backgroundColor:'#fff0f3',alignItems:'center',justifyContent:'center'},heartText:{fontSize:16,color:'#e54865'},empty:{flex:1,alignItems:'center',justifyContent:'center',paddingHorizontal:24},emptyIcon:{fontSize:48,color:PA.primary},emptyTitle:{fontSize:19,fontWeight:'900',color:PA.ink,marginTop:12},emptyText:{fontSize:13,lineHeight:19,color:PA.muted,textAlign:'center',marginTop:6},outline:{marginTop:18,minHeight:48,paddingHorizontal:18,borderRadius:14,borderWidth:1,borderColor:PA.primary,alignItems:'center',justifyContent:'center'},outlineText:{fontWeight:'900',color:PA.primary},guest:{margin:18,padding:28,borderRadius:24,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,alignItems:'center'},guestIcon:{fontSize:46,color:PA.primary},guestTitle:{fontSize:18,fontWeight:'900',color:PA.ink,marginTop:12,textAlign:'center'},guestText:{fontSize:13,lineHeight:19,color:PA.muted,marginTop:6,textAlign:'center'},primary:{marginTop:18,minHeight:49,paddingHorizontal:24,borderRadius:14,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontWeight:'900'}});