import {useCallback,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as WebBrowser from 'expo-web-browser';
import {router,useFocusEffect,useLocalSearchParams} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {PA} from '../constants/theme';
import {ApiError,apiRequest} from '../lib/api';
import {useAuth} from '../lib/auth';
import {nativeScheme} from '../lib/app-variant';
import {money} from '../lib/format';
import { AppIcon } from '../components/app-icon';
type Product={id:string;code:string;type:string;name:string;description?:string|null;priceMinor:number;currency:string;durationHours?:number|null};type BillingPolicy={externalDigitalBillingEnabled:boolean;externalProBillingEnabled:boolean};type L={id:string;title:string|null;status:string;priceMinor:number|null;currency:string;promotions?:{name:string;type:string}[]};type Wallet={balanceMinor?:number;currency?:string};
export default function ProPromotions(){const params=useLocalSearchParams<{ids?:string;listingId?:string;promotion?:string}>();const{user,token,loading:authLoading}=useAuth();const[products,setProducts]=useState<Product[]>([]),[listings,setListings]=useState<L[]>([]),[wallet,setWallet]=useState<Wallet>({}),[selectedProduct,setSelectedProduct]=useState(''),[coupon,setCoupon]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[message,setMessage]=useState(''),[billingEnabled,setBillingEnabled]=useState(false);
 const ids=useMemo(()=>String(params.ids||params.listingId||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,100),[params.ids,params.listingId]);
 const load=useCallback(async(soft=false)=>{if(!token){setLoading(false);return}if(soft)setRefreshing(true);else setLoading(true);try{const[p,l,w,policy]=await Promise.all([apiRequest<{products:Product[]}>('/promotions/products'),apiRequest<{listings:L[]}>('/account/listings',{token}),apiRequest<Wallet>('/promotions/wallet',{token}),apiRequest<BillingPolicy>('/billing/native-policy',{token})]);setProducts(p.products??[]);setListings((l.listings??[]).filter(x=>ids.includes(x.id)&&x.status==='PUBLISHED'));setWallet(w);setBillingEnabled(Boolean(policy.externalDigitalBillingEnabled));setSelectedProduct(v=>v||(p.products?.[0]?.code??''));if(params.promotion==='success')setMessage('Paiement traité. L’activation du boost sera visible dès confirmation Stripe.');if(params.promotion==='cancel')setMessage('Paiement interrompu. Aucun nouveau boost n’a été activé.')}catch(e){if(e instanceof ApiError&&e.status===401)router.replace('/auth/login');else setMessage('Impossible de charger les promotions.')}finally{setLoading(false);setRefreshing(false)}},[token,ids,params.promotion]);useFocusEffect(useCallback(()=>{void load();return()=>{}},[load]));
 async function promote(listingId:string){if(!token||busy||!selectedProduct||!billingEnabled)return;setBusy(listingId);setMessage('');try{const r=await apiRequest<{activated?:boolean;url?:string;paidWith?:string;amountMinor?:number}>(`/listings/${encodeURIComponent(listingId)}/promotions`,{method:'POST',token,body:{productCode:selectedProduct,couponCode:coupon.trim()||undefined,returnMode:'NATIVE',appScheme:nativeScheme()}});if(r.activated){setMessage(r.paidWith==='SITE_CREDIT'?'Boost activé avec votre crédit Petit Annonces.':'Boost activé.');await load(true)}else if(r.url){await WebBrowser.openBrowserAsync(r.url);await load(true)}}catch(e){const c=e instanceof ApiError?e.code:'';setMessage(c==='invalid_coupon'?'Code promo invalide.':c==='coupon_already_used'?'Ce code promo a déjà été utilisé.':c==='native_external_digital_billing_disabled'?'L’achat de boost est désactivé dans cette version Store.':c==='promotion_checkout_unavailable'?'Le paiement du boost est momentanément indisponible.':'Impossible d’activer cette promotion.')}finally{setBusy('')}}
 if(authLoading||loading)return <SafeAreaView style={s.center}><ActivityIndicator color={PA.primary}/></SafeAreaView>;if(!user||!token)return <SafeAreaView style={s.center}><Text style={s.title}>Promotions</Text></SafeAreaView>;
 return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled" keyboardDismissMode="interactive" automaticallyAdjustKeyboardInsets refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={PA.primary}/>}><View style={s.head}><Pressable accessibilityRole="button" accessibilityLabel="Retour" style={s.back} onPress={()=>router.back()}><AppIcon name="chevron-left" size={15} color={PA.ink}/></Pressable><View><Text style={s.eyebrow}>VISIBILITÉ PRO</Text><Text style={s.title}>Booster les annonces</Text></View></View>{message?<Text style={s.message}>{message}</Text>:null}<View style={s.wallet}><Text style={s.walletLabel}>CRÉDIT PETIT ANNONCES</Text><Text style={s.walletValue}>{money(Number(wallet.balanceMinor??0),String(wallet.currency??'EUR'))}</Text></View>{!billingEnabled?<View style={s.policy}><Text style={s.policyTitle}>Boost depuis l’application indisponible</Text><Text style={s.policyText}>Les achats de visibilité numérique sont désactivés dans cette version Store jusqu’à l’activation du mode de facturation autorisé.</Text></View>:null}<Text style={s.sectionTitle}>Choisir une promotion</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.products} keyboardShouldPersistTaps="handled" keyboardDismissMode="interactive" automaticallyAdjustKeyboardInsets>{products.map(p=><Pressable key={p.id} style={[s.product,selectedProduct===p.code&&s.productOn]} onPress={()=>setSelectedProduct(p.code)}><Text style={[s.productName,selectedProduct===p.code&&s.productNameOn]}>{p.name}</Text><Text style={s.productPrice}>{money(p.priceMinor,p.currency)}</Text><Text style={s.productMeta}>{p.durationHours?`${Math.round(p.durationHours/24)} j`:'Durée selon offre'}</Text></Pressable>)}</ScrollView><TextInput value={coupon} onChangeText={setCoupon} placeholder="Code promo (facultatif)" autoCapitalize="characters" style={s.input}/><Text style={s.note}>Pour éviter un paiement partiel involontaire, chaque annonce est confirmée séparément. Le crédit PA est utilisé automatiquement s’il couvre le boost, sinon Stripe s’ouvre.</Text><Text style={s.sectionTitle}>Annonces sélectionnées</Text>{listings.length?listings.map(l=><View key={l.id} style={s.card}><View style={{flex:1}}><Text style={s.cardTitle}>{l.title||'Annonce'}</Text><Text style={s.cardMeta}>{l.promotions?.length?`Actif : ${l.promotions.map(x=>x.name).join(' · ')}`:'Aucune promotion active'}</Text></View><Pressable style={s.primary} disabled={busy===l.id||!selectedProduct||!billingEnabled} onPress={()=>void promote(l.id)}><Text style={s.primaryText}>{busy===l.id?'…':'Activer'}</Text></Pressable></View>):<View style={s.empty}><Text style={s.emptyTitle}>Aucune annonce publiée sélectionnée</Text><Pressable onPress={()=>router.replace('/pro-listings')}><Text style={s.link}>Retour à la gestion des annonces</Text></Pressable></View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:PA.bg},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:PA.bg},page:{padding:16,paddingBottom:42},head:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:14},back:{width:40,height:40,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center'},backText:{fontSize:29,lineHeight:30,color:PA.ink},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1,color:PA.primary},title:{fontSize:24,fontWeight:'900',color:PA.ink},message:{padding:11,borderRadius:12,backgroundColor:'#fff8dd',color:'#735b13',fontSize:10.5,marginBottom:10},wallet:{padding:15,borderRadius:18,backgroundColor:PA.primary,marginBottom:14},walletLabel:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#ddd9ff'},walletValue:{fontSize:22,fontWeight:'900',color:'#fff',marginTop:3},sectionTitle:{fontSize:14,fontWeight:'900',color:PA.ink,marginBottom:8,marginTop:4},products:{gap:8,paddingBottom:10},product:{minWidth:130,padding:12,borderRadius:15,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line},productOn:{borderColor:PA.primary,backgroundColor:'#f4f2ff'},productName:{fontSize:11,fontWeight:'900',color:PA.ink},productNameOn:{color:PA.primary},productPrice:{fontSize:15,fontWeight:'900',color:PA.ink,marginTop:5},productMeta:{fontSize:9.5,color:PA.muted,marginTop:3},input:{minHeight:44,borderRadius:13,borderWidth:1,borderColor:PA.line,backgroundColor:'#fff',paddingHorizontal:12,fontSize:12,color:PA.ink,marginBottom:8},note:{fontSize:9.5,lineHeight:14,color:PA.muted,marginBottom:14},card:{flexDirection:'row',alignItems:'center',gap:10,padding:13,borderRadius:16,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,marginBottom:8},cardTitle:{fontSize:12.5,fontWeight:'900',color:PA.ink},cardMeta:{fontSize:9.5,color:PA.muted,marginTop:3},primary:{minHeight:38,paddingHorizontal:13,borderRadius:11,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center'},primaryText:{fontSize:9.5,fontWeight:'900',color:'#fff'},policy:{padding:13,borderRadius:15,backgroundColor:'#fff8dd',borderWidth:1,borderColor:'#f2df91',marginBottom:12},policyTitle:{fontSize:11,fontWeight:'900',color:'#624d0b'},policyText:{fontSize:9.5,lineHeight:14,color:'#735b13',marginTop:4},empty:{padding:30,alignItems:'center'},emptyTitle:{fontSize:15,fontWeight:'900',color:PA.ink},link:{fontSize:10.5,fontWeight:'900',color:PA.primary,marginTop:8}});
