import {useCallback,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {router,useFocusEffect} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {PA} from '../constants/theme';
import {ApiError,apiRequest} from '../lib/api';
import {useAuth} from '../lib/auth';
import {AppIcon} from '../components/app-icon';

type Stage='NEW'|'CONTACTED'|'APPOINTMENT'|'NEGOTIATION'|'WON'|'LOST';
type Lead={id:string;name:string|null;email:string|null;phone:string|null;stage:Stage;source:string;conversationId:string|null;listingTitle:string|null;listingSlug:string|null;assignedMemberId:string|null;assignedName:string|null;lastActivityAt:string};
type Payload={leads:Lead[];counts:Record<string,number>};
const stages:Stage[]=['NEW','CONTACTED','APPOINTMENT','NEGOTIATION','WON','LOST'];
const labels:Record<Stage,string>={NEW:'Nouveaux',CONTACTED:'Contactés',APPOINTMENT:'Rendez-vous',NEGOTIATION:'Négociation',WON:'Gagnés',LOST:'Perdus'};

export default function ProCrm(){
 const{token,loading:authLoading}=useAuth();const[leads,setLeads]=useState<Lead[]>([]);const[counts,setCounts]=useState<Record<string,number>>({});const[filter,setFilter]=useState<Stage|'ALL'>('ALL');const[q,setQ]=useState('');const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[msg,setMsg]=useState('');
 const load=useCallback(async(soft=false)=>{if(!token){setLoading(false);return}if(soft)setRefreshing(true);else setLoading(true);setMsg('');try{const sp=new URLSearchParams();if(filter!=='ALL')sp.set('stage',filter);if(q.trim())sp.set('q',q.trim());const p=await apiRequest<Payload>('/pro/crm/leads?'+sp.toString(),{token});setLeads(p.leads??[]);setCounts(p.counts??{})}catch(e){if(e instanceof ApiError&&e.status===401)router.replace('/auth/login');else setMsg(e instanceof ApiError&&e.status===403?'Votre rôle ne permet pas d’accéder au CRM.':'Impossible de charger les prospects.')}finally{setLoading(false);setRefreshing(false)}},[token,filter,q]);
 useFocusEffect(useCallback(()=>{void load();return()=>{}},[load]));
 async function patch(id:string,stage:Stage){if(!token)return;try{await apiRequest('/pro/crm/leads/'+encodeURIComponent(id),{method:'PATCH',token,body:{stage}});await load(true)}catch{setMsg('Modification impossible.')}}
 const total=useMemo(()=>Object.values(counts).reduce((a,b)=>a+Number(b||0),0),[counts]);
 if(authLoading||loading)return <SafeAreaView style={s.center}><ActivityIndicator color={PA.primary}/></SafeAreaView>;
 return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={PA.primary}/>}>
  <View style={s.head}><Pressable style={s.back} onPress={()=>router.back()}><AppIcon name="chevron-left" size={14}/></Pressable><View style={{flex:1}}><Text style={s.kicker}>PIPELINE COMMERCIAL</Text><Text style={s.title}>CRM & prospects</Text><Text style={s.lead}>Suivez chaque contact jusqu’au rendez-vous et à la vente.</Text></View><Pressable style={s.calendar} onPress={()=>router.push('/pro-appointments')}><AppIcon name="calendar-days" size={15} color={PA.primary}/></Pressable></View>
  {msg?<Text style={s.notice}>{msg}</Text>:null}
  <View style={s.kpis}>{[['Prospects',total],['Nouveaux',counts.NEW??0],['RDV',counts.APPOINTMENT??0],['Gagnés',counts.WON??0]].map(([l,v])=><View style={s.kpi} key={String(l)}><Text style={s.kpiLabel}>{l}</Text><Text style={s.kpiValue}>{v}</Text></View>)}</View>
  <View style={s.search}><AppIcon name="magnifying-glass" size={13} color={PA.muted}/><TextInput value={q} onChangeText={setQ} onSubmitEditing={()=>void load()} placeholder="Nom, e-mail ou annonce…" placeholderTextColor="#9999a7" style={s.searchInput}/><Pressable onPress={()=>void load()}><Text style={s.searchAction}>Rechercher</Text></Pressable></View>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}><Filter label="Tous" count={total} active={filter==='ALL'} press={()=>setFilter('ALL')}/>{stages.map(st=><Filter key={st} label={labels[st]} count={counts[st]??0} active={filter===st} press={()=>setFilter(st)}/>)}</ScrollView>
  {!leads.length?<View style={s.empty}><AppIcon name="users" size={25} color={PA.primary}/><Text style={s.emptyTitle}>Aucun prospect</Text><Text style={s.emptyText}>Les nouvelles conversations apparaîtront automatiquement ici.</Text></View>:leads.map(l=><View key={l.id} style={s.card}><View style={s.cardTop}><View style={{flex:1}}><Text style={s.name}>{l.name||l.email||'Prospect'}</Text><Text style={s.listing}>{l.listingTitle||'Contact direct'}</Text></View><Text style={s.date}>{new Date(l.lastActivityAt).toLocaleDateString('fr-FR')}</Text></View><View style={s.meta}>{l.email?<Text style={s.metaText}>{l.email}</Text>:null}{l.phone?<Text style={s.metaText}>{l.phone}</Text>:null}{l.assignedName?<Text style={s.metaText}>Assigné : {l.assignedName}</Text>:null}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.stageRow}>{stages.map(st=><Pressable key={st} onPress={()=>void patch(l.id,st)} style={[s.stage,l.stage===st&&s.stageOn]}><Text style={[s.stageText,l.stage===st&&s.stageTextOn]}>{labels[st]}</Text></Pressable>)}</ScrollView><View style={s.actions}>{l.conversationId?<Pressable style={s.action} onPress={()=>router.push(('/messages/'+l.conversationId) as never)}><Text style={s.actionText}>Message</Text></Pressable>:null}<Pressable style={s.action} onPress={()=>router.push(('/pro-appointments?leadId='+encodeURIComponent(l.id)+'&name='+encodeURIComponent(l.name??'')) as never)}><Text style={s.actionText}>Planifier</Text></Pressable>{l.listingSlug?<Pressable style={s.action} onPress={()=>router.push(('/annonce/'+l.listingSlug) as never)}><Text style={s.actionText}>Annonce</Text></Pressable>:null}</View></View>)}
 </ScrollView></SafeAreaView>
}
function Filter({label,count,active,press}:{label:string;count:number;active:boolean;press:()=>void}){return <Pressable onPress={press} style={[s.filter,active&&s.filterOn]}><Text style={[s.filterText,active&&s.filterTextOn]}>{label} · {count}</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f7f7fb'},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#f7f7fb'},page:{padding:16,paddingBottom:48},head:{flexDirection:'row',alignItems:'flex-start',gap:10},back:{width:40,height:40,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center'},calendar:{width:40,height:40,borderRadius:13,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center'},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1,color:PA.primary},title:{fontSize:25,fontWeight:'900',color:PA.ink,marginTop:2},lead:{fontSize:11,color:PA.muted,marginTop:3},notice:{padding:11,borderRadius:12,backgroundColor:'#fff8dd',color:'#735b13',fontSize:11,marginTop:12},kpis:{flexDirection:'row',gap:7,marginTop:14},kpi:{flex:1,padding:10,borderRadius:16,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line},kpiLabel:{fontSize:8.5,color:PA.muted,fontWeight:'800'},kpiValue:{fontSize:20,fontWeight:'900',color:PA.ink,marginTop:3},search:{marginTop:12,minHeight:47,borderRadius:14,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:12},searchInput:{flex:1,fontSize:12.5,color:PA.ink},searchAction:{fontSize:10,fontWeight:'900',color:PA.primary},filters:{gap:7,paddingVertical:10},filter:{paddingHorizontal:12,minHeight:34,borderRadius:17,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,justifyContent:'center'},filterOn:{backgroundColor:PA.ink,borderColor:PA.ink},filterText:{fontSize:9.5,fontWeight:'900',color:PA.muted},filterTextOn:{color:'#fff'},empty:{padding:36,alignItems:'center'},emptyTitle:{fontSize:17,fontWeight:'900',color:PA.ink,marginTop:9},emptyText:{fontSize:11,color:PA.muted,textAlign:'center',marginTop:4},card:{padding:14,borderRadius:18,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,marginBottom:9},cardTop:{flexDirection:'row',gap:8},name:{fontSize:14,fontWeight:'900',color:PA.ink},listing:{fontSize:10.5,color:PA.muted,marginTop:3},date:{fontSize:9.5,color:PA.muted},meta:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:9},metaText:{fontSize:9.5,color:PA.muted},stageRow:{gap:6,paddingVertical:10},stage:{paddingHorizontal:9,minHeight:30,borderRadius:10,backgroundColor:'#f4f4f8',justifyContent:'center'},stageOn:{backgroundColor:'#efedff'},stageText:{fontSize:8.5,fontWeight:'800',color:PA.muted},stageTextOn:{color:PA.primary},actions:{flexDirection:'row',gap:7},action:{flex:1,minHeight:36,borderRadius:11,borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center'},actionText:{fontSize:9.5,fontWeight:'900',color:PA.ink}});