import {useCallback,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {router,useFocusEffect,useLocalSearchParams} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {PA} from '../constants/theme';
import {ApiError,apiRequest} from '../lib/api';
import {useAuth} from '../lib/auth';
import {AppIcon} from '../components/app-icon';

type Appointment={id:string;customerName:string|null;customerEmail:string|null;customerPhone:string|null;type:string;startAt:string;endAt:string;status:string;notes:string|null;listingTitle:string|null;listingSlug:string|null;assignedName:string|null};
type Payload={appointments:Appointment[]};
const statusLabels:Record<string,string>={REQUESTED:'À confirmer',CONFIRMED:'Confirmé',COMPLETED:'Terminé',CANCELED:'Annulé',NO_SHOW:'Absent'};
const typeLabels:Record<string,string>={VISIT:'Visite',TEST_DRIVE:'Essai véhicule',CALL:'Appel',VIDEO:'Visio',OTHER:'Rendez-vous'};
function localValue(d:Date){const z=(n:number)=>String(n).padStart(2,'0');return d.getFullYear()+'-'+z(d.getMonth()+1)+'-'+z(d.getDate())+' '+z(d.getHours())+':'+z(d.getMinutes())}
function parseLocal(v:string){const m=v.trim().match(/^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2})$/);if(!m)return null;const d=new Date(Number(m[1]),Number(m[2])-1,Number(m[3]),Number(m[4]),Number(m[5]));return Number.isNaN(d.getTime())?null:d}
const initialAppointmentStart=new Date(Date.now()+86400000);
const initialAppointmentEnd=new Date(initialAppointmentStart.getTime()+3600000);
const INITIAL_START=localValue(initialAppointmentStart);
const INITIAL_END=localValue(initialAppointmentEnd);

export default function ProAppointments(){
 const params=useLocalSearchParams<{leadId?:string;name?:string}>();const{token,loading:authLoading}=useAuth();const[list,setList]=useState<Appointment[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[msg,setMsg]=useState('');const[name,setName]=useState(String(params.name??''));const[leadId,setLeadId]=useState(String(params.leadId??''));const[email,setEmail]=useState('');const[phone,setPhone]=useState('');const[type,setType]=useState('OTHER');const[start,setStart]=useState(INITIAL_START);const[end,setEnd]=useState(INITIAL_END);const[busy,setBusy]=useState(false);
 const load=useCallback(async(soft=false)=>{if(!token){setLoading(false);return}if(soft)setRefreshing(true);else setLoading(true);try{const p=await apiRequest<Payload>('/pro/appointments',{token});setList(p.appointments??[])}catch(e){if(e instanceof ApiError&&e.status===401)router.replace('/auth/login');else setMsg('Impossible de charger les rendez-vous.')}finally{setLoading(false);setRefreshing(false)}},[token]);
 useFocusEffect(useCallback(()=>{void load();return()=>{}},[load]));
 async function create(){if(!token||busy)return;const a=parseLocal(start),b=parseLocal(end);if(!a||!b||b<=a){setMsg('Vérifiez la date et l’heure. Format : AAAA-MM-JJ HH:mm.');return}setBusy(true);setMsg('');try{await apiRequest('/pro/appointments',{method:'POST',token,body:{leadId:leadId||undefined,customerName:name.trim()||undefined,customerEmail:email.trim()||undefined,customerPhone:phone.trim()||undefined,type,startAt:a.toISOString(),endAt:b.toISOString()}});setMsg('Rendez-vous ajouté.');setName('');setEmail('');setPhone('');setLeadId('');await load(true)}catch(e){setMsg(e instanceof ApiError&&e.code==='invalid_time_range'?'La plage horaire est invalide.':'Le rendez-vous n’a pas pu être créé.')}finally{setBusy(false)}}
 async function patch(id:string,status:string){if(!token)return;try{await apiRequest('/pro/appointments/'+encodeURIComponent(id),{method:'PATCH',token,body:{status}});await load(true)}catch{setMsg('Mise à jour impossible.')}}
 const upcoming=useMemo(()=>list.filter(x=>['REQUESTED','CONFIRMED'].includes(x.status)&&new Date(x.startAt)>new Date()).length,[list]);const requested=useMemo(()=>list.filter(x=>x.status==='REQUESTED').length,[list]);
 if(authLoading||loading)return <SafeAreaView style={s.center}><ActivityIndicator color={PA.primary}/></SafeAreaView>;
 return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={PA.primary}/>}>
  <View style={s.head}><Pressable style={s.back} onPress={()=>router.back()}><AppIcon name="chevron-left" size={14}/></Pressable><View style={{flex:1}}><Text style={s.kicker}>AGENDA COMMERCIAL</Text><Text style={s.title}>Rendez-vous</Text><Text style={s.lead}>Visites, essais véhicules, appels et rendez-vous clients.</Text></View><Pressable style={s.crm} onPress={()=>router.push('/pro-crm')}><AppIcon name="users" size={15} color={PA.primary}/></Pressable></View>
  {msg?<Text style={s.notice}>{msg}</Text>:null}
  <View style={s.kpis}>{[['À venir',upcoming],['À confirmer',requested],['Total',list.length],['Terminés',list.filter(x=>x.status==='COMPLETED').length]].map(([l,v])=><View style={s.kpi} key={String(l)}><Text style={s.kpiLabel}>{l}</Text><Text style={s.kpiValue}>{v}</Text></View>)}</View>
  <View style={s.form}><Text style={s.sectionTitle}>Ajouter au calendrier</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="Nom du client" placeholderTextColor="#9999a7"/><View style={s.two}><TextInput style={[s.input,s.half]} value={email} onChangeText={setEmail} placeholder="E-mail" keyboardType="email-address" autoCapitalize="none" placeholderTextColor="#9999a7"/><TextInput style={[s.input,s.half]} value={phone} onChangeText={setPhone} placeholder="Téléphone" keyboardType="phone-pad" placeholderTextColor="#9999a7"/></View><Text style={s.label}>Type</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.types}>{Object.entries(typeLabels).map(([k,l])=><Pressable key={k} onPress={()=>setType(k)} style={[s.type,type===k&&s.typeOn]}><Text style={[s.typeText,type===k&&s.typeTextOn]}>{l}</Text></Pressable>)}</ScrollView><Text style={s.label}>Début · AAAA-MM-JJ HH:mm</Text><TextInput style={s.input} value={start} onChangeText={setStart} placeholder="2026-09-20 14:00" autoCapitalize="none"/><Text style={s.label}>Fin · AAAA-MM-JJ HH:mm</Text><TextInput style={s.input} value={end} onChangeText={setEnd} placeholder="2026-09-20 15:00" autoCapitalize="none"/><Pressable disabled={busy} onPress={()=>void create()} style={[s.primary,busy&&s.disabled]}><Text style={s.primaryText}>{busy?'Ajout…':'Ajouter au calendrier'}</Text></Pressable></View>
  <Text style={s.sectionTitle}>Agenda</Text>
  {!list.length?<View style={s.empty}><AppIcon name="calendar-days" size={24} color={PA.primary}/><Text style={s.emptyTitle}>Aucun rendez-vous</Text></View>:list.map(a=><View key={a.id} style={s.card}><View style={s.timeBox}><Text style={s.day}>{new Date(a.startAt).toLocaleDateString('fr-FR',{day:'2-digit',month:'short'})}</Text><Text style={s.time}>{new Date(a.startAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</Text></View><View style={{flex:1}}><View style={s.cardTop}><Text style={s.customer}>{a.customerName||a.customerEmail||'Client'}</Text><Text style={s.status}>{statusLabels[a.status]??a.status}</Text></View><Text style={s.meta}>{typeLabels[a.type]??a.type}{a.listingTitle?' · '+a.listingTitle:''}</Text>{a.customerPhone?<Text style={s.meta}>{a.customerPhone}</Text>:null}<View style={s.actions}>{a.status==='REQUESTED'?<Pressable style={s.action} onPress={()=>void patch(a.id,'CONFIRMED')}><Text style={s.actionText}>Confirmer</Text></Pressable>:null}{a.status==='CONFIRMED'?<Pressable style={s.action} onPress={()=>void patch(a.id,'COMPLETED')}><Text style={s.actionText}>Terminé</Text></Pressable>:null}{['REQUESTED','CONFIRMED'].includes(a.status)?<Pressable style={[s.action,s.cancel]} onPress={()=>void patch(a.id,'CANCELED')}><Text style={[s.actionText,{color:PA.danger}]}>Annuler</Text></Pressable>:null}{a.listingSlug?<Pressable style={s.action} onPress={()=>router.push(('/annonce/'+a.listingSlug) as never)}><Text style={s.actionText}>Annonce</Text></Pressable>:null}</View></View></View>)}
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f7f7fb'},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#f7f7fb'},page:{padding:16,paddingBottom:48},head:{flexDirection:'row',alignItems:'flex-start',gap:10},back:{width:40,height:40,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center'},crm:{width:40,height:40,borderRadius:13,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center'},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1,color:PA.primary},title:{fontSize:25,fontWeight:'900',color:PA.ink,marginTop:2},lead:{fontSize:11,color:PA.muted,marginTop:3},notice:{padding:11,borderRadius:12,backgroundColor:'#fff8dd',color:'#735b13',fontSize:11,marginTop:12},kpis:{flexDirection:'row',gap:7,marginTop:14},kpi:{flex:1,padding:10,borderRadius:16,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line},kpiLabel:{fontSize:8.5,color:PA.muted,fontWeight:'800'},kpiValue:{fontSize:20,fontWeight:'900',color:PA.ink,marginTop:3},form:{padding:14,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,marginTop:12},sectionTitle:{fontSize:15,fontWeight:'900',color:PA.ink,marginTop:14,marginBottom:8},input:{minHeight:44,borderRadius:12,borderWidth:1,borderColor:PA.line,backgroundColor:'#fafafd',paddingHorizontal:12,fontSize:12.5,color:PA.ink,marginBottom:8},two:{flexDirection:'row',gap:8},half:{flex:1},label:{fontSize:9.5,fontWeight:'800',color:PA.muted,marginBottom:6},types:{gap:6,paddingBottom:9},type:{minHeight:34,paddingHorizontal:10,borderRadius:10,backgroundColor:'#f4f4f8',justifyContent:'center'},typeOn:{backgroundColor:'#efedff'},typeText:{fontSize:8.5,fontWeight:'800',color:PA.muted},typeTextOn:{color:PA.primary},primary:{minHeight:44,borderRadius:13,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center'},primaryText:{fontSize:11,fontWeight:'900',color:'#fff'},disabled:{opacity:.45},empty:{padding:32,alignItems:'center'},emptyTitle:{fontSize:16,fontWeight:'900',color:PA.ink,marginTop:8},card:{padding:13,borderRadius:18,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,marginBottom:9,flexDirection:'row',gap:11},timeBox:{width:54,alignItems:'center',padding:7,borderRadius:12,backgroundColor:'#efedff'},day:{fontSize:9,fontWeight:'900',color:PA.primary,textTransform:'uppercase'},time:{fontSize:13,fontWeight:'900',color:PA.ink,marginTop:3},cardTop:{flexDirection:'row',alignItems:'flex-start',gap:6},customer:{flex:1,fontSize:13,fontWeight:'900',color:PA.ink},status:{fontSize:8.5,fontWeight:'900',color:PA.primary},meta:{fontSize:9.5,color:PA.muted,marginTop:3},actions:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:9},action:{minHeight:32,paddingHorizontal:9,borderRadius:9,borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center'},cancel:{borderColor:'#ffdada'},actionText:{fontSize:8.5,fontWeight:'900',color:PA.ink}});
