import {useCallback,useState} from 'react';
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {router,useFocusEffect} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {PA} from '../constants/theme';
import {ApiError,apiRequest} from '../lib/api';
import {useAuth} from '../lib/auth';
import {AppIcon} from '../components/app-icon';

type Role='MANAGER'|'SALES'|'CATALOG';
type Member={id:string;email:string;displayName:string|null;role:Role;status:string;invitedAt:string;acceptedAt:string|null;lastActiveAt:string|null};
type Payload={members:Member[];isOwner:boolean;role:string};
const roleLabels:Record<Role,string>={MANAGER:'Responsable',SALES:'Commercial',CATALOG:'Catalogue'};

export default function ProTeam(){
 const{token,loading:authLoading}=useAuth();const[members,setMembers]=useState<Member[]>([]);const[isOwner,setIsOwner]=useState(false);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[email,setEmail]=useState('');const[name,setName]=useState('');const[role,setRole]=useState<Role>('SALES');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 const load=useCallback(async(soft=false)=>{if(!token){setLoading(false);return}if(soft)setRefreshing(true);else setLoading(true);try{const p=await apiRequest<Payload>('/pro/team',{token});setMembers(p.members??[]);setIsOwner(Boolean(p.isOwner))}catch(e){if(e instanceof ApiError&&e.status===401)router.replace('/auth/login');else setMsg('Impossible de charger l’équipe.')}finally{setLoading(false);setRefreshing(false)}},[token]);
 useFocusEffect(useCallback(()=>{void load();return()=>{}},[load]));
 async function invite(){if(!token||!email.trim()||busy)return;setBusy(true);setMsg('');try{const p=await apiRequest<{delivery?:{sent?:boolean}}>('/pro/team/invite',{method:'POST',token,body:{email:email.trim().toLowerCase(),displayName:name.trim()||undefined,role}});setEmail('');setName('');setMsg(p.delivery?.sent?'Invitation envoyée par e-mail.':'Invitation créée. L’e-mail n’a pas pu être envoyé automatiquement.');await load(true)}catch(e){setMsg(e instanceof ApiError&&e.code==='professional_permission_required'?'Seul le propriétaire peut gérer les invitations.':'Invitation impossible.')}finally{setBusy(false)}}
 async function patch(id:string,data:{role?:Role;status?:'ACTIVE'|'REVOKED'}){if(!token)return;try{await apiRequest('/pro/team/'+encodeURIComponent(id),{method:'PATCH',token,body:data});await load(true)}catch{setMsg('Modification impossible.')}}
 if(authLoading||loading)return <SafeAreaView style={s.center}><ActivityIndicator color={PA.primary}/></SafeAreaView>;
 return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={PA.primary}/>}>
  <View style={s.head}><Pressable style={s.back} onPress={()=>router.back()}><AppIcon name="chevron-left" size={14}/></Pressable><View style={{flex:1}}><Text style={s.kicker}>ORGANISATION</Text><Text style={s.title}>Équipe & rôles</Text><Text style={s.lead}>Ajoutez vos collaborateurs sans partager le mot de passe principal.</Text></View></View>
  {msg?<Text style={s.notice}>{msg}</Text>:null}
  <View style={s.roleGrid}>{(['MANAGER','SALES','CATALOG'] as Role[]).map(r=><View style={s.roleCard} key={r}><Text style={s.roleTitle}>{roleLabels[r]}</Text><Text style={s.roleText}>{r==='MANAGER'?'CRM, rendez-vous, statistiques et catalogue.':r==='SALES'?'CRM, prospects, rendez-vous et ventes.':'Annonces, imports et gestion du catalogue.'}</Text></View>)}</View>
  {isOwner?<View style={s.invite}><Text style={s.sectionTitle}>Inviter un collaborateur</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="Nom" placeholderTextColor="#9999a7"/><TextInput style={s.input} value={email} onChangeText={setEmail} placeholder="E-mail" autoCapitalize="none" keyboardType="email-address" placeholderTextColor="#9999a7"/><Text style={s.label}>Rôle</Text><View style={s.rolePicker}>{(['MANAGER','SALES','CATALOG'] as Role[]).map(r=><Pressable key={r} onPress={()=>setRole(r)} style={[s.roleChip,role===r&&s.roleChipOn]}><Text style={[s.roleChipText,role===r&&s.roleChipTextOn]}>{roleLabels[r]}</Text></Pressable>)}</View><Pressable disabled={busy||!email.trim()} onPress={()=>void invite()} style={[s.primary,(busy||!email.trim())&&s.disabled]}><Text style={s.primaryText}>{busy?'Envoi…':'Inviter'}</Text></Pressable></View>:null}
  <Text style={s.sectionTitle}>Collaborateurs · {members.length}</Text>
  {!members.length?<View style={s.empty}><Text style={s.emptyTitle}>Aucun collaborateur</Text><Text style={s.emptyText}>Les invitations et membres actifs apparaîtront ici.</Text></View>:members.map(m=><View style={s.member} key={m.id}><View style={s.memberTop}><View style={s.avatar}><Text style={s.avatarText}>{(m.displayName||m.email).slice(0,1).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.memberName}>{m.displayName||m.email}</Text><Text style={s.memberMail}>{m.email}</Text></View><Text style={[s.status,m.status==='ACTIVE'&&s.statusActive]}>{m.status==='ACTIVE'?'Actif':m.status==='PENDING'?'En attente':'Retiré'}</Text></View><Text style={s.last}>Dernière activité : {m.lastActiveAt?new Date(m.lastActiveAt).toLocaleString('fr-FR'):'—'}</Text>{isOwner&&m.status!=='REVOKED'?<><View style={s.rolePicker}>{(['MANAGER','SALES','CATALOG'] as Role[]).map(r=><Pressable key={r} onPress={()=>void patch(m.id,{role:r})} style={[s.roleChip,m.role===r&&s.roleChipOn]}><Text style={[s.roleChipText,m.role===r&&s.roleChipTextOn]}>{roleLabels[r]}</Text></Pressable>)}</View><Pressable style={s.revoke} onPress={()=>void patch(m.id,{status:'REVOKED'})}><Text style={s.revokeText}>Retirer l’accès</Text></Pressable></>:<Text style={s.memberRole}>{roleLabels[m.role]}</Text>}</View>)}
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f7f7fb'},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#f7f7fb'},page:{padding:16,paddingBottom:48},head:{flexDirection:'row',alignItems:'flex-start',gap:10},back:{width:40,height:40,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center'},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1,color:PA.primary},title:{fontSize:25,fontWeight:'900',color:PA.ink,marginTop:2},lead:{fontSize:11,color:PA.muted,marginTop:3},notice:{padding:11,borderRadius:12,backgroundColor:'#fff8dd',color:'#735b13',fontSize:11,marginTop:12},roleGrid:{flexDirection:'row',gap:7,marginTop:14},roleCard:{flex:1,padding:11,borderRadius:16,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line},roleTitle:{fontSize:10.5,fontWeight:'900',color:PA.ink},roleText:{fontSize:8.5,lineHeight:12,color:PA.muted,marginTop:4},invite:{padding:14,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,marginTop:12},sectionTitle:{fontSize:15,fontWeight:'900',color:PA.ink,marginTop:14,marginBottom:8},input:{minHeight:44,borderRadius:12,borderWidth:1,borderColor:PA.line,backgroundColor:'#fafafd',paddingHorizontal:12,fontSize:12.5,color:PA.ink,marginBottom:8},label:{fontSize:9.5,fontWeight:'800',color:PA.muted,marginBottom:6},rolePicker:{flexDirection:'row',gap:6,marginBottom:9},roleChip:{flex:1,minHeight:34,borderRadius:10,backgroundColor:'#f4f4f8',alignItems:'center',justifyContent:'center'},roleChipOn:{backgroundColor:'#efedff'},roleChipText:{fontSize:8.5,fontWeight:'800',color:PA.muted},roleChipTextOn:{color:PA.primary},primary:{minHeight:44,borderRadius:13,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center'},primaryText:{fontSize:11,fontWeight:'900',color:'#fff'},disabled:{opacity:.45},empty:{padding:30,alignItems:'center'},emptyTitle:{fontSize:16,fontWeight:'900',color:PA.ink},emptyText:{fontSize:10.5,color:PA.muted,marginTop:4,textAlign:'center'},member:{padding:14,borderRadius:18,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,marginBottom:9},memberTop:{flexDirection:'row',alignItems:'center',gap:9},avatar:{width:40,height:40,borderRadius:13,backgroundColor:'#efedff',alignItems:'center',justifyContent:'center'},avatarText:{fontSize:15,fontWeight:'900',color:PA.primary},memberName:{fontSize:12.5,fontWeight:'900',color:PA.ink},memberMail:{fontSize:9.5,color:PA.muted,marginTop:2},status:{fontSize:8.5,fontWeight:'900',paddingHorizontal:8,paddingVertical:5,borderRadius:9,backgroundColor:'#f2f2f5',color:PA.muted},statusActive:{backgroundColor:'#e8f8f0',color:PA.success},last:{fontSize:9.5,color:PA.muted,marginVertical:9},revoke:{minHeight:34,borderRadius:10,backgroundColor:'#fff0f0',alignItems:'center',justifyContent:'center'},revokeText:{fontSize:9.5,fontWeight:'900',color:PA.danger},memberRole:{fontSize:10,fontWeight:'800',color:PA.primary}});