import {router} from 'expo-router';
import {useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Share,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {AppIcon} from '../components/app-icon';
import {PA} from '../constants/theme';
import {apiRequest} from '../lib/api';
import {useAuth} from '../lib/auth';

type Referral={id:string;status:string;createdAt:string;rewardedAt:string|null;displayName:string;maskedEmail:string;emailVerifiedAt:string|null;rewardMinor:number};
type Payload={referralCode:{code:string;rewardCredits:number};referrals:Referral[];stats:{total:number;verified:number;rewarded:number;pending:number;awaitingFirstListing?:number;earnedMinor:number;currency:string}};

function euro(minor:number){return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format((Number(minor)||0)/100)}
function statusLabel(v:string){return v==='REWARDED'?'5 € gagnés':v==='QUALIFIED'?'E-mail vérifié · 1re annonce à valider':v==='PENDING'?'En attente de vérification':v==='CANCELED'?'Annulée':v}

export default function ReferralsScreen(){
 const{token}=useAuth();const[data,setData]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{if(!token){router.replace('/auth/login');return}apiRequest<Payload>('/referrals/me',{token}).then(setData).catch(()=>setError('Impossible de charger votre parrainage.')).finally(()=>setLoading(false))},[token]);
 const link=useMemo(()=>data?`https://petitannonces.fr/inscription?ref=${encodeURIComponent(data.referralCode.code)}&utm_source=referral&utm_medium=share&utm_campaign=parrainage_5eur`:'',[data]);
 async function share(){if(!link)return;await Share.share({title:'Petit Annonces · Parrainage 5 €',message:`Rejoignez Petit Annonces avec mon lien. Après vérification de votre e-mail et validation de votre première annonce, je gagne 5 € de crédit Petit Annonces. ${link}`})}
 return <SafeAreaView style={s.safe} edges={['top']}><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><AppIcon name="chevron-left" size={14} color={PA.ink}/></Pressable><View><Text style={s.eyebrow}>PARRAINAGE</Text><Text style={s.headerTitle}>Invitez et gagnez 5 €</Text></View></View><ScrollView contentContainerStyle={s.page}>
  {loading?<ActivityIndicator color={PA.primary}/>:null}{error?<Text style={s.error}>{error}</Text>:null}
  {data?<><View style={s.hero}><Text style={s.heroKicker}>VOTRE CODE</Text><Text style={s.code}>{data.referralCode.code}</Text><Text style={s.heroText}>Dès qu’un membre invité vérifie son e-mail puis publie une première annonce approuvée, 5 € de crédit Petit Annonces sont ajoutés à votre compte.</Text><Pressable style={s.share} onPress={()=>void share()}><AppIcon name="share" size={14} color="#fff"/><Text style={s.shareText}>Partager mon lien</Text></Pressable></View>
  <View style={s.stats}><Stat label="Gains" value={euro(data.stats.earnedMinor)}/><Stat label="Invités" value={String(data.stats.total)}/><Stat label="À publier" value={String(data.stats.awaitingFirstListing??0)}/><Stat label="E-mail à vérifier" value={String(data.stats.pending)}/></View>
  <Text style={s.section}>Mes membres parrainés</Text><View style={s.list}>{data.referrals.length?data.referrals.map(r=><View key={r.id} style={s.row}><View style={{flex:1,minWidth:0}}><Text style={s.name} numberOfLines={1}>{r.displayName||'Membre invité'}</Text><Text style={s.meta}>{r.maskedEmail} · {new Date(r.createdAt).toLocaleDateString('fr-FR')}</Text><Text style={[s.status,r.status==='REWARDED'&&s.statusOk]}>{statusLabel(r.status)}</Text></View><Text style={[s.reward,r.rewardMinor>0&&s.rewardOk]}>{r.rewardMinor>0?`+${euro(r.rewardMinor)}`:'—'}</Text></View>):<Text style={s.empty}>Aucun membre parrainé pour le moment.</Text>}</View>
  <Text style={s.foot}>Le crédit de parrainage n’est pas retirable en espèces et s’utilise uniquement pour les services Petit Annonces éligibles.</Text></>:null}
 </ScrollView></SafeAreaView>
}
function Stat({label,value}:{label:string;value:string}){return <View style={s.stat}><Text style={s.statLabel}>{label}</Text><Text style={s.statValue}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:PA.bg},header:{height:66,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:PA.line,backgroundColor:'#fff'},back:{width:38,height:38,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:'#f4f3f8'},eyebrow:{fontSize:9.5,fontWeight:'900',letterSpacing:1.1,color:PA.primary},headerTitle:{fontSize:16,fontWeight:'900',color:PA.ink,marginTop:2},page:{padding:16,paddingBottom:40},error:{padding:12,borderRadius:12,backgroundColor:'#fff0f0',color:'#a52a2a',marginBottom:12},hero:{padding:20,borderRadius:22,backgroundColor:PA.primary},heroKicker:{fontSize:10,fontWeight:'900',letterSpacing:1.1,color:'#ddd8ff'},code:{fontSize:28,fontWeight:'900',color:'#fff',letterSpacing:1.2,marginTop:5},heroText:{fontSize:12,lineHeight:18,color:'#ebe9ff',marginTop:9},share:{marginTop:15,height:46,borderRadius:13,backgroundColor:'#fff2',borderWidth:1,borderColor:'#ffffff4d',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},shareText:{fontWeight:'900',color:'#fff'},stats:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',rowGap:8,marginTop:12},stat:{width:'48.8%',padding:14,borderRadius:17,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line},statLabel:{fontSize:10,fontWeight:'800',color:PA.muted},statValue:{fontSize:21,fontWeight:'900',color:PA.ink,marginTop:3},section:{fontSize:16,fontWeight:'900',color:PA.ink,marginTop:20,marginBottom:8},list:{borderWidth:1,borderColor:PA.line,borderRadius:20,backgroundColor:'#fff',overflow:'hidden'},row:{minHeight:74,padding:14,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#f0f0f4'},name:{fontSize:13.5,fontWeight:'900',color:PA.ink},meta:{fontSize:10.5,color:PA.muted,marginTop:3},status:{fontSize:10.5,fontWeight:'800',color:PA.primary,marginTop:5},statusOk:{color:PA.success},reward:{fontSize:15,fontWeight:'900',color:PA.muted},rewardOk:{color:PA.success},empty:{padding:18,color:PA.muted,fontSize:12},foot:{fontSize:10.5,lineHeight:16,color:PA.muted,marginTop:14}});