import { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Pressable, RefreshControl, StyleSheet, Switch, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PA } from '../constants/theme';
import { ApiError, apiRequest } from '../lib/api';
import { useAuth } from '../lib/auth';
import { AppIcon } from '../components/app-icon';

type Frequency='INSTANT'|'DAILY'|'WEEKLY';
type SavedSearch={id:string;name:string;query?:string|null;categorySlug?:string|null;city?:string|null;postalCode?:string|null;minPriceMinor?:number|null;maxPriceMinor?:number|null;filters?:Record<string,unknown>|null;alertEnabled:boolean;frequency:Frequency;createdAt?:string;updatedAt?:string};
const freqLabel:Record<Frequency,string>={INSTANT:'Dès que possible',DAILY:'Chaque jour',WEEKLY:'Chaque semaine'};
function moneyFilter(v?:number|null){return v==null?null:`${(v/100).toLocaleString('fr-FR',{maximumFractionDigits:2})} €`}
function bodyOf(x:SavedSearch,patch:Partial<SavedSearch>={}){const v={...x,...patch};return{name:v.name,query:v.query??null,categorySlug:v.categorySlug??null,city:v.city??null,postalCode:v.postalCode??null,minPriceMinor:v.minPriceMinor??null,maxPriceMinor:v.maxPriceMinor??null,filters:v.filters??{},alertEnabled:Boolean(v.alertEnabled),frequency:v.frequency}}
function searchHref(x:SavedSearch){const p=new URLSearchParams();if(x.query)p.set('q',x.query);if(x.categorySlug)p.set('category',x.categorySlug);if(x.city)p.set('city',x.city);if(x.minPriceMinor!=null)p.set('minPrice',String(x.minPriceMinor/100));if(x.maxPriceMinor!=null)p.set('maxPrice',String(x.maxPriceMinor/100));p.set('savedSearchId',x.id);return `/search?${p.toString()}`}
export default function SavedSearchesScreen(){const{user,token,loading:authLoading}=useAuth();const[items,setItems]=useState<SavedSearch[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState('');
 const load=useCallback(async(soft=false)=>{if(!token){setLoading(false);return}if(soft)setRefreshing(true);else setLoading(true);setError('');try{const p=await apiRequest<{searches:SavedSearch[]}>('/account/saved-searches',{token});setItems(p.searches??[])}catch(e){if(e instanceof ApiError&&e.status===401){router.replace('/auth/login');return}setError('Impossible de charger vos recherches enregistrées.')}finally{setLoading(false);setRefreshing(false)}},[token]);
 useFocusEffect(useCallback(()=>{void load();return()=>{}},[load]));
 async function update(item:SavedSearch,patch:Partial<SavedSearch>){if(!token)return;setBusy(item.id);setError('');try{await apiRequest(`/account/saved-searches/${encodeURIComponent(item.id)}`,{method:'PUT',token,body:bodyOf(item,patch)});setItems(v=>v.map(x=>x.id===item.id?{...x,...patch}:x))}catch{setError('La recherche n’a pas pu être mise à jour.')}finally{setBusy(null)}}
 function remove(item:SavedSearch){Alert.alert('Supprimer la recherche ?',`« ${item.name} » ne déclenchera plus d’alerte.`,[{text:'Annuler',style:'cancel'},{text:'Supprimer',style:'destructive',onPress:()=>void (async()=>{if(!token)return;setBusy(item.id);try{await apiRequest(`/account/saved-searches/${encodeURIComponent(item.id)}`,{method:'DELETE',token});setItems(v=>v.filter(x=>x.id!==item.id))}catch{setError('Impossible de supprimer cette recherche.')}finally{setBusy(null)}})()}])}
 if(authLoading||loading)return <SafeAreaView style={s.center}><ActivityIndicator color={PA.primary}/></SafeAreaView>;if(!user||!token)return <SafeAreaView style={s.center}><Text style={s.title}>Mes recherches</Text><Pressable style={s.primary} onPress={()=>router.replace('/auth/login')}><Text style={s.primaryText}>Se connecter</Text></Pressable></SafeAreaView>;
 return <SafeAreaView style={s.safe} edges={['top']}><View style={s.header}><Pressable accessibilityRole="button" accessibilityLabel="Retour" style={s.back} onPress={()=>router.back()}><AppIcon name="chevron-left" size={15} color={PA.ink}/></Pressable><View style={{flex:1}}><Text style={s.eyebrow}>ALERTES</Text><Text style={s.title}>Mes recherches enregistrées</Text><Text style={s.sub}>Soyez prévenu lorsque de nouvelles annonces correspondent à vos critères.</Text></View></View>{error?<Text style={s.error}>{error}</Text>:null}<FlatList data={items} keyExtractor={x=>x.id} contentContainerStyle={items.length?s.list:s.emptyList} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={PA.primary}/>} ListEmptyComponent={<View style={s.empty}><AppIcon name="search" size={24} color={PA.primary}/><Text style={s.emptyTitle}>Aucune recherche enregistrée</Text><Text style={s.muted}>Faites une recherche puis touchez « Enregistrer » pour recevoir des alertes.</Text><Pressable style={s.primary} onPress={()=>router.push('/search')}><Text style={s.primaryText}>Faire une recherche</Text></Pressable></View>} renderItem={({item})=><View style={s.card}><View style={s.top}><View style={{flex:1}}><Text style={s.name}>{item.name}</Text><Text style={s.criteria}>{[item.query,item.categorySlug?.replaceAll('-',' '),item.city,item.minPriceMinor!=null?`min ${moneyFilter(item.minPriceMinor)}`:null,item.maxPriceMinor!=null?`max ${moneyFilter(item.maxPriceMinor)}`:null].filter(Boolean).join(' · ')||'Tous les critères'}</Text></View><Switch value={item.alertEnabled} disabled={busy===item.id} onValueChange={v=>void update(item,{alertEnabled:v})} trackColor={{false:'#d7d7df',true:'#bdb6ff'}} thumbColor={item.alertEnabled?PA.primary:'#fff'}/></View><Text style={s.freqTitle}>Fréquence</Text><View style={s.freqRow}>{(['INSTANT','DAILY','WEEKLY'] as Frequency[]).map(f=><Pressable key={f} disabled={busy===item.id} style={[s.freq,item.frequency===f&&s.freqOn]} onPress={()=>void update(item,{frequency:f})}><Text style={[s.freqText,item.frequency===f&&s.freqTextOn]}>{freqLabel[f]}</Text></Pressable>)}</View>{item.frequency==='INSTANT'?<Text style={s.hint}>Vérification périodique, généralement dans l’heure.</Text>:null}<View style={s.actions}><Pressable style={s.open} onPress={()=>router.push(searchHref(item) as never)}><Text style={s.openText}>Voir les résultats</Text></Pressable><Pressable style={s.delete} disabled={busy===item.id} onPress={()=>remove(item)}><Text style={s.deleteText}>{busy===item.id?'…':'Supprimer'}</Text></Pressable></View></View>} /></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:PA.bg},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12,padding:28,backgroundColor:PA.bg},header:{padding:15,flexDirection:'row',alignItems:'flex-start',gap:10},back:{width:40,height:40,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center'},backText:{fontSize:29,lineHeight:30,color:PA.ink},eyebrow:{fontSize:9.5,fontWeight:'900',letterSpacing:1.1,color:PA.primary},title:{fontSize:22,fontWeight:'900',letterSpacing:-.5,color:PA.ink,marginTop:2},sub:{fontSize:10.5,lineHeight:15,color:PA.muted,marginTop:3},error:{marginHorizontal:14,marginBottom:8,padding:10,borderRadius:12,backgroundColor:'#fff0f0',color:PA.danger,fontSize:11},list:{padding:14,paddingTop:4,paddingBottom:36},emptyList:{flexGrow:1,padding:18},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:30},emptyIcon:{width:54,height:54,borderRadius:27,textAlign:'center',textAlignVertical:'center',backgroundColor:'#efedff',fontSize:26,color:PA.primary},emptyTitle:{fontSize:18,fontWeight:'900',color:PA.ink,marginTop:12},muted:{fontSize:11.5,lineHeight:17,color:PA.muted,textAlign:'center',marginTop:5,marginBottom:14},card:{padding:14,borderRadius:18,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,marginBottom:10},top:{flexDirection:'row',alignItems:'flex-start',gap:10},name:{fontSize:15,fontWeight:'900',color:PA.ink},criteria:{fontSize:10.5,lineHeight:15,color:PA.muted,marginTop:4,textTransform:'capitalize'},freqTitle:{fontSize:9,fontWeight:'900',letterSpacing:.7,color:PA.muted,marginTop:13,marginBottom:6,textTransform:'uppercase'},freqRow:{flexDirection:'row',gap:6},freq:{flex:1,minHeight:36,borderRadius:10,borderWidth:1,borderColor:PA.line,alignItems:'center',justifyContent:'center',paddingHorizontal:4},freqOn:{backgroundColor:'#efedff',borderColor:'#cfcafc'},freqText:{fontSize:9.2,fontWeight:'800',color:PA.muted,textAlign:'center'},freqTextOn:{color:PA.primary},hint:{fontSize:9.2,lineHeight:13,color:PA.muted,marginTop:5},actions:{flexDirection:'row',gap:8,marginTop:13},open:{flex:1,minHeight:41,borderRadius:11,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center'},openText:{fontSize:10.5,fontWeight:'900',color:'#fff'},delete:{minWidth:86,minHeight:41,paddingHorizontal:10,borderRadius:11,backgroundColor:'#fff',borderWidth:1,borderColor:'#f2cece',alignItems:'center',justifyContent:'center'},deleteText:{fontSize:10.5,fontWeight:'900',color:PA.danger},primary:{minHeight:45,paddingHorizontal:20,borderRadius:13,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center'},primaryText:{fontSize:11,fontWeight:'900',color:'#fff'}});