import {useCallback,useEffect,useState} from 'react';
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {router} from 'expo-router';
import * as WebBrowser from 'expo-web-browser';
import {PA} from '../constants/theme';
import {apiRequest} from '../lib/api';
import {useAuth} from '../lib/auth';
import {nativeScheme} from '../lib/app-variant';
import { AppIcon } from '../components/app-icon';

type Pack={id:string;name:string;description:string|null;badge:string|null;creditMinor:number;priceMinor:number;currency:string};
type Tx={id:string;type:string;amountMinor:number;referenceType:string;createdAt:string};
type Wallet={wallet:{balanceMinor:number;currency:string};transactions:Tx[];packages:Pack[]};
type BillingPolicy={externalDigitalBillingEnabled:boolean;externalProBillingEnabled:boolean};
const money=(n:number,c='EUR')=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:c}).format(n/100);
const txLabel:Record<string,string>={WELCOME:'Crédit de bienvenue',CREDIT_PURCHASE:'Recharge',LISTING_PROMOTION:'Mise en avant',LISTING_RENEWAL:'Prolongation',ADMIN_ADJUSTMENT:'Ajustement'};
export default function WalletScreen(){const{token}=useAuth();const[data,setData]=useState<Wallet|null>(null),[billingEnabled,setBillingEnabled]=useState(false),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const load=useCallback(async(refresh=false)=>{if(!token){router.replace('/auth/login');return}if(refresh)setRefreshing(true);else setLoading(true);setError('');try{const[w,p]=await Promise.all([apiRequest<Wallet>('/promotions/wallet',{token}),apiRequest<BillingPolicy>('/billing/native-policy',{token})]);setData(w);setBillingEnabled(Boolean(p.externalDigitalBillingEnabled))}catch{setError('Impossible de charger votre crédit.')}finally{setLoading(false);setRefreshing(false)}},[token]);useEffect(()=>{void load()},[load]);
 async function buy(pack:Pack){if(!token||busy||!billingEnabled)return;setBusy(pack.id);setError('');try{const r=await apiRequest<{url:string}>('/billing/stripe/credits/checkout',{method:'POST',token,body:{packageId:pack.id,returnMode:'NATIVE',appScheme:nativeScheme()}});await WebBrowser.openBrowserAsync(r.url,{presentationStyle:WebBrowser.WebBrowserPresentationStyle.PAGE_SHEET});await load(true)}catch{setError('Le paiement ne peut pas être ouvert pour le moment.')}finally{setBusy('')}}
 return <SafeAreaView style={s.safe}><View style={s.head}><Pressable onPress={()=>router.back()}><AppIcon name="chevron-left" size={15} color={PA.ink}/></Pressable><View><Text style={s.eyebrow}>MON COMPTE</Text><Text style={s.title}>Crédit Petit Annonces</Text></View></View>{loading?<View style={s.center}><ActivityIndicator color={PA.primary}/></View>:<ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={PA.primary}/>} contentContainerStyle={s.page}>{error?<Text style={s.error}>{error}</Text>:null}<View style={s.balance}><Text style={s.balanceLabel}>Solde disponible</Text><Text style={s.balanceValue}>{money(data?.wallet.balanceMinor??0,data?.wallet.currency)}</Text><Text style={s.balanceNote}>Utilisable uniquement pour les services Petit Annonces. Non retirable en espèces.</Text></View><Text style={s.section}>Recharger mon crédit</Text>{!billingEnabled?<View style={s.policy}><Text style={s.policyTitle}>Achat dans l’application indisponible</Text><Text style={s.policyText}>La recharge de crédit est désactivée dans cette version Store tant que le mode de paiement numérique autorisé par App Store / Google Play n’est pas configuré.</Text></View>:<View style={s.grid}>{(data?.packages??[]).map(p=><Pressable key={p.id} disabled={Boolean(busy)} onPress={()=>void buy(p)} style={s.pack}><Text style={s.packName}>{p.name}</Text><Text style={s.packCredit}>{money(p.creditMinor,p.currency)}</Text><Text style={s.packPrice}>Paiement {money(p.priceMinor,p.currency)}</Text><Text style={s.packDesc}>{p.description??'Crédit valable sur Petit Annonces.'}</Text><View style={s.buy}><Text style={s.buyText}>{busy===p.id?'Ouverture…':'Choisir'}</Text></View></Pressable>)}</View>}<Text style={s.section}>Mouvements récents</Text><View style={s.list}>{(data?.transactions??[]).slice(0,30).map(t=><View key={t.id} style={s.tx}><View style={{flex:1}}><Text style={s.txTitle}>{txLabel[t.referenceType]??t.referenceType.replaceAll('_',' ')}</Text><Text style={s.txDate}>{new Date(t.createdAt).toLocaleDateString('fr-FR')}</Text></View><Text style={[s.txAmount,t.amountMinor>0?s.plus:s.minus]}>{t.amountMinor>0?'+':''}{money(t.amountMinor,data?.wallet.currency)}</Text></View>)}{!data?.transactions?.length?<Text style={s.empty}>Aucun mouvement pour le moment.</Text>:null}</View></ScrollView>}</SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:PA.bg},head:{height:76,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:PA.line,backgroundColor:'#fff'},back:{fontSize:36,color:PA.ink},eyebrow:{fontSize:10,fontWeight:'900',color:PA.primary,letterSpacing:1},title:{fontSize:20,fontWeight:'900',color:PA.ink},center:{flex:1,alignItems:'center',justifyContent:'center'},page:{padding:18,paddingBottom:42},error:{backgroundColor:'#fff0f0',color:PA.danger,padding:12,borderRadius:12,marginBottom:12},balance:{backgroundColor:PA.primary,borderRadius:24,padding:22},balanceLabel:{color:'#ddd8ff',fontWeight:'700'},balanceValue:{color:'#fff',fontSize:34,fontWeight:'900',marginTop:6},balanceNote:{color:'#e8e5ff',fontSize:11,lineHeight:16,marginTop:8},section:{fontSize:17,fontWeight:'900',color:PA.ink,marginTop:22,marginBottom:10},grid:{gap:10},pack:{backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,borderRadius:18,padding:16},packName:{fontSize:13,fontWeight:'900',color:PA.primary},packCredit:{fontSize:25,fontWeight:'900',color:PA.ink,marginTop:3},packPrice:{fontSize:11,fontWeight:'800',color:PA.muted,marginTop:2},packDesc:{fontSize:11,lineHeight:16,color:PA.muted,marginTop:6},buy:{alignSelf:'flex-start',backgroundColor:'#efedff',paddingHorizontal:13,paddingVertical:8,borderRadius:11,marginTop:11},buyText:{fontSize:11,fontWeight:'900',color:PA.primary},list:{backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,borderRadius:18,overflow:'hidden'},tx:{padding:14,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#f0f0f4'},txTitle:{fontSize:12,fontWeight:'800',color:PA.ink},txDate:{fontSize:10,color:PA.muted,marginTop:3},txAmount:{fontSize:13,fontWeight:'900'},plus:{color:PA.success},minus:{color:PA.ink},empty:{padding:18,textAlign:'center',color:PA.muted},policy:{padding:14,borderRadius:16,backgroundColor:'#fff8dd',borderWidth:1,borderColor:'#f2df91'},policyTitle:{fontSize:11,fontWeight:'900',color:'#624d0b'},policyText:{fontSize:10,lineHeight:15,color:'#735b13',marginTop:4}})