CREATE TABLE IF NOT EXISTS "UserNotificationPreference" (
  "userId" TEXT PRIMARY KEY,
  "emailMessages" BOOLEAN NOT NULL DEFAULT TRUE,
  "emailOffers" BOOLEAN NOT NULL DEFAULT TRUE,
  "emailListingUpdates" BOOLEAN NOT NULL DEFAULT TRUE,
  "emailMarketing" BOOLEAN NOT NULL DEFAULT FALSE,
  "pushMessages" BOOLEAN NOT NULL DEFAULT TRUE,
  "pushOffers" BOOLEAN NOT NULL DEFAULT TRUE,
  "pushListingUpdates" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "UserNotificationPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
