import { createReadStream, existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import { basename, extname, join, resolve } from "node:path";
import { hash } from "@node-rs/argon2";
import { prisma } from "@pa/database";
import { PutObjectCommand, PutObjectAclCommand, S3Client } from "@aws-sdk/client-s3";

type UserRow={legacyId:string;email:string;displayName?:string;firstName?:string;lastName?:string;phone?:string;createdAt?:string;kind?:"PARTICULIER"|"PROFESSIONNEL"};
type ListingRow={legacyId:string;sellerLegacyId:string;categoryLegacyId:string;title?:string;description?:string;priceMinor?:number;city?:string;postalCode?:string;region?:string;createdAt?:string;publishedAt?:string;status?:string};
type MediaRow={legacyId:string;listingLegacyId:string;source:string;mimeType?:string;sortOrder?:number;isCover?:boolean;altText?:string};

const args=process.argv.slice(2);const val=(k:string)=>{const i=args.indexOf(k);return i>=0?args[i+1]:undefined};
const input=val("--input");const mapFile=val("--category-map");const apply=args.includes("--apply");const preservePublished=args.includes("--preserve-published");
if(args.includes("--help")||!input||!mapFile){console.log("Usage: pnpm exec tsx scripts/flynax-migrate.ts --input DIR --category-map FILE [--apply] [--preserve-published]");process.exit(args.includes("--help")?0:2)}
const root=resolve(input);const categoryMap=JSON.parse(await readFile(resolve(mapFile),"utf8")) as Record<string,string>;
async function ndjson<T>(name:string):Promise<T[]>{const file=join(root,name);if(!existsSync(file))return[];return (await readFile(file,"utf8")).split(/\r?\n/).filter(Boolean).map((x,i)=>{try{return JSON.parse(x) as T}catch{throw new Error(`${name}:${i+1}:invalid_json`)}})}
const users=await ndjson<UserRow>("users.ndjson"), listings=await ndjson<ListingRow>("listings.ndjson"), media=await ndjson<MediaRow>("media.ndjson");
const targetSlugs=[...new Set(Object.values(categoryMap))];const cats=await prisma.category.findMany({where:{slug:{in:targetSlugs}},select:{id:true,slug:true}});const catBySlug=new Map(cats.map(c=>[c.slug,c.id]));
const report={mode:apply?"APPLY":"DRY_RUN",users:{total:users.length,new:0,existing:0,invalid:0,emailConflicts:0},listings:{total:listings.length,new:0,existing:0,blocked:0},media:{total:media.length,ready:0,blocked:0},categories:{mapped:Object.keys(categoryMap).length,invalidTargets:[] as string[]},unmappedCategories:new Set<string>(),warnings:[] as string[]};
async function ledgerTableExists(){const r=await prisma.$queryRawUnsafe<Array<{exists:boolean}>>(`SELECT to_regclass('public."LegacyMigrationLedger"') IS NOT NULL AS exists`);return Boolean(r[0]?.exists)}
for(const slug of targetSlugs)if(!catBySlug.has(slug))report.categories.invalidTargets.push(slug);
let hasLedger=await ledgerTableExists();
if(apply&&!hasLedger){await prisma.$executeRawUnsafe(`CREATE TABLE "LegacyMigrationLedger" ("id" text PRIMARY KEY,"source" text NOT NULL,"entityType" text NOT NULL,"legacyId" text NOT NULL,"newId" text NOT NULL,"createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("source","entityType","legacyId"))`);hasLedger=true}
const ledger=async(type:string,id:string)=> hasLedger?(await prisma.$queryRawUnsafe<Array<{newId:string}>>(`SELECT "newId" FROM "LegacyMigrationLedger" WHERE "source"='flynax' AND "entityType"=$1 AND "legacyId"=$2 LIMIT 1`,type,id))[0]?.newId:undefined;
const mapUser=new Map<string,string>(), mapListing=new Map<string,string>();
for(const u of users){if(!u.legacyId||!u.email?.includes("@")){report.users.invalid++;continue}const prior=await ledger("user",u.legacyId);if(prior){mapUser.set(u.legacyId,prior);report.users.existing++;continue}const existing=await prisma.user.findUnique({where:{email:u.email.trim().toLowerCase()},select:{id:true}});if(existing){mapUser.set(u.legacyId,existing.id);report.users.existing++;report.users.emailConflicts++;if(apply)await prisma.$executeRawUnsafe(`INSERT INTO "LegacyMigrationLedger" ("id","source","entityType","legacyId","newId") VALUES ($1,'flynax','user',$2,$3) ON CONFLICT DO NOTHING`,randomUUID(),u.legacyId,existing.id);continue}report.users.new++;if(!apply){mapUser.set(u.legacyId,`dry-user:${u.legacyId}`);continue}const passwordHash=await hash(randomBytes(48).toString("base64url"),{algorithm:2,memoryCost:19456,timeCost:2,parallelism:1});const created=await prisma.user.create({data:{email:u.email.trim().toLowerCase(),passwordHash,kind:u.kind??"PARTICULIER",status:"ACTIVE",emailVerifiedAt:new Date(),createdAt:u.createdAt?new Date(u.createdAt):undefined,profile:{create:{displayName:u.displayName,firstName:u.firstName,lastName:u.lastName,phone:u.phone,locale:"fr-FR",countryCode:"FR"}}},select:{id:true}});mapUser.set(u.legacyId,created.id);await prisma.$executeRawUnsafe(`INSERT INTO "LegacyMigrationLedger" ("id","source","entityType","legacyId","newId") VALUES ($1,'flynax','user',$2,$3)`,randomUUID(),u.legacyId,created.id)}
for(const l of listings){const prior=await ledger("listing",l.legacyId);if(prior){mapListing.set(l.legacyId,prior);report.listings.existing++;continue}const sellerId=mapUser.get(l.sellerLegacyId)??await ledger("user",l.sellerLegacyId);const slug=categoryMap[l.categoryLegacyId],categoryId=slug?catBySlug.get(slug):undefined;if(!categoryId){report.unmappedCategories.add(l.categoryLegacyId);report.listings.blocked++;if(slug)report.warnings.push(`listing ${l.legacyId}: category target ${slug} does not exist`);continue}if(!sellerId){report.listings.blocked++;report.warnings.push(`listing ${l.legacyId}: missing seller ${l.sellerLegacyId}`);continue}report.listings.new++;if(!apply){mapListing.set(l.legacyId,`dry-listing:${l.legacyId}`);continue}const wantedPublished=preservePublished&&l.status==="PUBLISHED";const created=await prisma.listing.create({data:{sellerId,categoryId,title:l.title?.slice(0,120),description:l.description?.slice(0,12000),priceMinor:Number.isInteger(l.priceMinor)?l.priceMinor:undefined,city:l.city,postalCode:l.postalCode,region:l.region,status:wantedPublished?"PUBLISHED":"DRAFT",publishedAt:wantedPublished?(l.publishedAt?new Date(l.publishedAt):new Date()):null,createdAt:l.createdAt?new Date(l.createdAt):undefined},select:{id:true}});mapListing.set(l.legacyId,created.id);await prisma.$executeRawUnsafe(`INSERT INTO "LegacyMigrationLedger" ("id","source","entityType","legacyId","newId") VALUES ($1,'flynax','listing',$2,$3)`,randomUUID(),l.legacyId,created.id)}
function mime(row:MediaRow){if(row.mimeType)return row.mimeType;const e=extname(row.source).toLowerCase();return e===".png"?"image/png":e===".webp"?"image/webp":e===".avif"?"image/avif":e===".heic"?"image/heic":e===".heif"?"image/heif":"image/jpeg"}
function ext(m:string){return m==="image/png"?"png":m==="image/webp"?"webp":m==="image/avif"?"avif":m==="image/heic"?"heic":m==="image/heif"?"heif":"jpg"}
function storage(){const endpoint=process.env.OBJECT_STORAGE_ENDPOINT,bucket=process.env.OBJECT_STORAGE_BUCKET,accessKeyId=process.env.OBJECT_STORAGE_ACCESS_KEY_ID,secretAccessKey=process.env.OBJECT_STORAGE_SECRET_ACCESS_KEY,base=process.env.OBJECT_STORAGE_PUBLIC_BASE_URL;if(!endpoint||!bucket||!accessKeyId||!secretAccessKey||!base)throw new Error("object_storage_not_configured");return{bucket,base,client:new S3Client({region:process.env.OBJECT_STORAGE_REGION??"auto",endpoint,forcePathStyle:process.env.OBJECT_STORAGE_FORCE_PATH_STYLE==="true",credentials:{accessKeyId,secretAccessKey}})}}
async function bytes(source:string){if(/^https:\/\//i.test(source)){const u=new URL(source);const addresses=await import("node:dns/promises").then(m=>m.lookup(u.hostname,{all:true}));if(addresses.some(a=>/^(127\.|10\.|192\.168\.|169\.254\.)/.test(a.address)))throw new Error("private_source_blocked");const r=await fetch(u,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`media_http_${r.status}`);return Buffer.from(await r.arrayBuffer())}const f=resolve(root,source);if(f!==root&&!f.startsWith(root+"/"))throw new Error("unsafe_media_path");return readFile(f)}
let st:any=null;if(apply&&media.length)st=storage();
for(const m of media){const listingId=mapListing.get(m.listingLegacyId)??await ledger("listing",m.listingLegacyId);if(!listingId){report.media.blocked++;continue}const prior=await ledger("media",m.legacyId);if(prior){report.media.ready++;continue}if(!apply){report.media.ready++;continue}try{const data=await bytes(m.source);if(data.length===0||data.length>15*1024*1024)throw new Error("invalid_media_size");const mt=mime(m);if(!["image/jpeg","image/png","image/webp","image/avif","image/heic","image/heif"].includes(mt))throw new Error("unsupported_media_type");const id=randomUUID(),objectKey=`listings/${listingId}/${id}.${ext(mt)}`;await st.client.send(new PutObjectCommand({Bucket:st.bucket,Key:objectKey,Body:data,ContentType:mt,CacheControl:"public, max-age=31536000, immutable"}));await st.client.send(new PutObjectAclCommand({Bucket:st.bucket,Key:objectKey,ACL:"public-read"}));const url=`${st.base.replace(/\/$/,"")}/${objectKey.split("/").map(encodeURIComponent).join("/")}`;await prisma.$executeRawUnsafe(`INSERT INTO "ListingMedia" ("id","listingId","objectKey","publicUrl","mimeType","sizeBytes","status","sortOrder","isCover","altText","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,'READY',$7,$8,$9,NOW(),NOW())`,id,listingId,objectKey,url,mt,data.length,m.sortOrder??0,Boolean(m.isCover),m.altText??basename(m.source));await prisma.$executeRawUnsafe(`INSERT INTO "LegacyMigrationLedger" ("id","source","entityType","legacyId","newId") VALUES ($1,'flynax','media',$2,$3)`,randomUUID(),m.legacyId,id);report.media.ready++}catch(e){report.media.blocked++;report.warnings.push(`media ${m.legacyId}: ${e instanceof Error?e.message:"failed"}`)}}
console.log(JSON.stringify({...report,unmappedCategories:[...report.unmappedCategories]},null,2));await prisma.$disconnect();
