import { useEffect, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { PA } from '../../constants/theme';
import { apiRequest } from '../../lib/api';
import { AppIcon } from '../../components/app-icon';

export default function ForgotPasswordScreen(){const params=useLocalSearchParams<{email?:string}>();const[email,setEmail]=useState(typeof params.email==='string'?params.email:'');const[busy,setBusy]=useState(false);const[sent,setSent]=useState(false);const[error,setError]=useState('');useEffect(()=>{if(typeof params.email==='string'&&params.email)setEmail(params.email)},[params.email]);async function submit(){const value=email.trim().toLowerCase();if(!value||!value.includes('@')){setError('Saisissez une adresse e-mail valide.');return}setBusy(true);setError('');try{await apiRequest('/auth/forgot-password',{method:'POST',body:{email:value,client:'NATIVE'}});setSent(true)}catch{setError('Impossible d’envoyer la demande pour le moment. Réessayez plus tard.')}finally{setBusy(false)}}return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.page}><Pressable style={s.backButton} onPress={()=>router.back()}><AppIcon name="chevron-left" size={14} color={PA.ink}/><Text style={s.back}>Retour</Text></Pressable><Text style={s.kicker}>SÉCURITÉ DU COMPTE</Text><Text style={s.title}>Mot de passe oublié</Text><Text style={s.lead}>Nous vous enverrons un lien sécurisé valable 30 minutes.</Text><View style={s.card}>{sent?<><View style={s.icon}><AppIcon name="check" size={13} color={PA.success}/></View><Text style={s.cardTitle}>Vérifiez votre boîte e-mail</Text><Text style={s.copy}>Si un compte correspond à cette adresse, un e-mail vient d’être envoyé. Le lien vous proposera d’ouvrir Petit Annonces ou de continuer sur le site.</Text><Pressable style={s.button} onPress={()=>router.replace({pathname:'/auth/login',params:{email:email.trim().toLowerCase()}})}><Text style={s.buttonText}>Retour à la connexion</Text></Pressable></>:<><Text style={s.label}>Adresse e-mail</Text><TextInput autoCapitalize="none" autoComplete="email" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="vous@exemple.fr" style={s.input}/>{error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={busy} onPress={()=>void submit()} style={[s.button,busy&&s.disabled]}><Text style={s.buttonText}>{busy?'Envoi…':'Envoyer le lien sécurisé'}</Text></Pressable></>}</View></View></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:PA.bg},flex:{flex:1},page:{flex:1,padding:20},backButton:{alignSelf:'flex-start',minHeight:38,paddingHorizontal:12,borderRadius:12,borderWidth:1,borderColor:PA.line,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',gap:7,marginBottom:24},back:{fontSize:11,fontWeight:'800',color:PA.ink},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:PA.primary},title:{fontSize:31,fontWeight:'900',letterSpacing:-1,color:PA.ink,marginTop:6},lead:{fontSize:14,lineHeight:21,color:PA.muted,marginTop:8,marginBottom:20},card:{backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,borderRadius:22,padding:18,gap:10},label:{fontSize:12,fontWeight:'900',color:PA.ink},input:{height:52,borderWidth:1,borderColor:'#dcdde5',borderRadius:14,paddingHorizontal:14,fontSize:16,color:PA.ink},button:{height:52,borderRadius:14,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center',marginTop:5},buttonText:{color:'#fff',fontSize:14,fontWeight:'900'},disabled:{opacity:.55},error:{fontSize:12,lineHeight:18,color:PA.danger},icon:{width:48,height:48,borderRadius:24,backgroundColor:'#ecfdf3',alignItems:'center',justifyContent:'center'},iconText:{fontSize:22,fontWeight:'900',color:'#18794e'},cardTitle:{fontSize:18,fontWeight:'900',color:PA.ink},copy:{fontSize:13,lineHeight:20,color:PA.muted}});