import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Image } from 'expo-image';
import { router, useLocalSearchParams } from 'expo-router';
import { PA } from '../../constants/theme';
import { ApiError, apiRequest } from '../../lib/api';
import { useAuth } from '../../lib/auth';
import { AppIcon } from '../../components/app-icon';

type Kind='PARTICULIER'|'PROFESSIONNEL';
type Step='choice'|'particular'|'siret'|'pro-account'|'store'|'success';
type Company={legalName?:string;tradeName?:string|null;siren?:string;siret?:string;nafCode?:string|null;headquartersAddress?:string|null;headquartersCity?:string|null;headquartersPostalCode?:string|null;active?:boolean};
function errorText(code:string){const m:Record<string,string>={email_already_registered:'Un compte existe déjà avec cette adresse e-mail.',rate_limited:'Trop de tentatives. Réessayez un peu plus tard.',invalid_siret:'Le numéro SIRET n’est pas valide.',siret_required:'Un SIRET de 14 chiffres est nécessaire.',company_not_found:'Cette entreprise n’a pas été trouvée dans le registre public.',company_inactive:'Cette entreprise est indiquée comme inactive.',registry_unavailable:'Le registre des entreprises est momentanément indisponible.'};return m[code]??'Impossible de créer le compte. Vérifiez les informations saisies.'}

type FieldProps={label:string;value:string;onChange:(v:string)=>void;placeholder?:string;secure?:boolean;keyboard?:'default'|'email-address'|'number-pad'|'phone-pad'};
function AuthField({label,value,onChange,placeholder,secure=false,keyboard='default'}:FieldProps){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor="#9b97aa" secureTextEntry={secure} keyboardType={keyboard} autoCapitalize={keyboard==='email-address'?'none':'sentences'} style={s.input}/></View>}
function SignupProgress({kind,steps,current}:{kind:Kind|null;steps:string[];current:number}){if(!kind)return null;return <View style={s.progress}>{steps.map((label,i)=><View key={label} style={s.progressItem}><View style={[s.progressDot,i<=current&&s.progressDotActive]}>{i<current?<AppIcon name="check" size={10} color="#fff"/>:<Text style={[s.progressNo,i<=current&&s.progressNoActive]}>{i+1}</Text>}</View><Text style={[s.progressLabel,i<=current&&s.progressLabelActive]}>{label}</Text></View>)}</View>}

export default function RegisterScreen(){
  const params=useLocalSearchParams<{type?:string;plan?:string}>();
  const{register}=useAuth();
  const[step,setStep]=useState<Step>('choice');const[kind,setKind]=useState<Kind|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[terms,setTerms]=useState(false);const[verificationRequired,setVerificationRequired]=useState(false);
  const[personal,setPersonal]=useState({displayName:'',email:'',password:'',confirm:''});
  const[siret,setSiret]=useState('');const[company,setCompany]=useState<Company|null>(null);const[lookupBusy,setLookupBusy]=useState(false);
  const[pro,setPro]=useState({displayName:'',email:'',phone:'',password:'',confirm:''});
  const[store,setStore]=useState({name:'',city:'',postalCode:''});
  useEffect(()=>{if(params.type==='pro'){setKind('PROFESSIONNEL');setStep('siret')}},[params.type]);
  const steps=useMemo(()=>kind==='PROFESSIONNEL'?['Type','SIRET','Identifiants','Boutique','Terminé']:['Type','Informations','Terminé'],[kind]);
  const current=kind==='PROFESSIONNEL'?({choice:0,siret:1,'pro-account':2,store:3,success:4,particular:0} as Record<Step,number>)[step]:({choice:0,particular:1,success:2,siret:0,'pro-account':0,store:0} as Record<Step,number>)[step];
  function choose(v:Kind){setKind(v);setError('');setStep(v==='PARTICULIER'?'particular':'siret')}
  function reset(){setStep('choice');setKind(null);setCompany(null);setError('')}
  async function submitPersonal(){setError('');if(personal.displayName.trim().length<2||!personal.email.trim()||personal.password.length<10){setError('Complétez tous les champs. Le mot de passe doit contenir au moins 10 caractères.');return}if(personal.password!==personal.confirm){setError('Les mots de passe ne correspondent pas.');return}if(!terms){setError('Vous devez accepter les conditions générales et la politique de confidentialité.');return}setBusy(true);try{const r=await register({displayName:personal.displayName.trim(),email:personal.email.trim().toLowerCase(),password:personal.password,kind:'PARTICULIER'});if(r.verificationRequired){router.replace({pathname:'/auth/verify-pending',params:{email:personal.email.trim().toLowerCase()}});return}setVerificationRequired(false);setStep('success')}catch(e){setError(errorText(e instanceof ApiError?e.code:'signup_failed'))}finally{setBusy(false)}}
  async function verifySiret(){const id=siret.replace(/\D/g,'');setSiret(id);setError('');setCompany(null);if(id.length!==14){setError('Saisissez un numéro SIRET de 14 chiffres.');return}setLookupBusy(true);try{const p=await apiRequest<{company:Company}>(`/auth/register/pro/company-lookup?identifier=${encodeURIComponent(id)}`);if(p.company.active===false)throw new ApiError(409,'company_inactive',p);setCompany(p.company);setSiret(p.company.siret??id);setStore(v=>({name:v.name||p.company.tradeName||p.company.legalName||'',city:v.city||p.company.headquartersCity||'',postalCode:v.postalCode||p.company.headquartersPostalCode||''}))}catch(e){setError(errorText(e instanceof ApiError?e.code:'registry_unavailable'))}finally{setLookupBusy(false)}}
  function continuePro(){setError('');if(pro.displayName.trim().length<2||!pro.email.trim()||pro.password.length<10){setError('Complétez tous les champs obligatoires.');return}if(pro.password!==pro.confirm){setError('Les mots de passe ne correspondent pas.');return}setStep('store')}
  async function submitPro(){setError('');if(!company){setStep('siret');setError('Vérifiez d’abord votre SIRET.');return}if(store.name.trim().length<2){setError('Indiquez le nom de votre boutique.');return}if(!terms){setError('Vous devez accepter les conditions générales et la politique de confidentialité.');return}setBusy(true);try{const p=await apiRequest<{verificationRequired:boolean;authenticated:boolean}>('/auth/register/pro',{method:'POST',body:{email:pro.email.trim().toLowerCase(),password:pro.password,displayName:pro.displayName.trim(),phone:pro.phone.trim()||undefined,legalName:company.legalName||store.name,tradeName:company.tradeName||undefined,siren:company.siren,siret:company.siret||siret,city:company.headquartersCity||store.city,postalCode:company.headquartersPostalCode||store.postalCode,storeName:store.name.trim(),storeCity:store.city.trim(),storePostalCode:store.postalCode.trim(),planCode:typeof params.plan==='string'&&/^[A-Z0-9_-]{2,60}$/.test(params.plan)?params.plan:undefined,onboardingWizard:true}});setVerificationRequired(Boolean(p.verificationRequired));if(p.verificationRequired){router.replace({pathname:'/auth/verify-pending',params:{email:pro.email.trim().toLowerCase()}});return}setStep('success')}catch(e){setError(errorText(e instanceof ApiError?e.code:'signup_failed'))}finally{setBusy(false)}}
  return <SafeAreaView style={s.safe} edges={['top','bottom']}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.scroll} keyboardDismissMode="interactive" automaticallyAdjustKeyboardInsets>
    <View style={s.brandBar}><Pressable accessibilityRole="button" accessibilityLabel="Retour" onPress={()=>step==='choice'?router.back():reset()} style={s.backButton}><AppIcon name="chevron-left" size={14} color={PA.ink}/></Pressable><Image source={require('../../../assets/images/site-mobile-logo.png')} style={s.logo} contentFit="contain"/><View style={s.backSpacer}/></View>
    <View style={s.securityCard}><View style={s.securityGlow}/><View style={s.securityBadge}><AppIcon name="shield" size={11} color="#e6e1ff"/><Text style={s.securityBadgeText}>INSCRIPTION SÉCURISÉE</Text></View><Text style={s.securityTitle}>{kind==='PROFESSIONNEL'?'Construisez une présence professionnelle crédible dès le départ.':kind==='PARTICULIER'?'Tout votre espace personnel, prêt à acheter et vendre.':'Un compte adapté à votre façon d’utiliser Petit Annonces.'}</Text><Text style={s.securityLead}>{kind==='PROFESSIONNEL'?'SIRET vérifié, boutique publique, messagerie, ventes et outils Pro réunis dans un même espace.':'Publiez, échangez, enregistrez vos favoris et suivez vos transactions depuis un espace simple et sécurisé.'}</Text></View>
    <View style={s.shell}>
      <Text style={s.eyebrow}>CRÉER UN COMPTE</Text><View style={s.topRow}><Text style={s.title}>{kind==='PROFESSIONNEL'?'Votre activité, prête en quelques étapes.':kind==='PARTICULIER'?'Votre compte personnel, simplement.':'Comment souhaitez-vous utiliser Petit Annonces ?'}</Text>{step!=='choice'&&step!=='success'?<Pressable onPress={reset} style={s.reset}><Text style={s.resetText}>Changer de type</Text></Pressable>:null}</View><SignupProgress kind={kind} steps={steps} current={current}/>
      {error?<View style={s.errorBox}><AppIcon name="triangle-exclamation" size={14} color="#9f1239"/><Text style={s.errorText}>{error}</Text></View>:null}
      {step==='choice'?<View style={s.choices}><Pressable style={s.choice} onPress={()=>choose('PARTICULIER')}><View style={[s.choiceIcon,s.choiceIconBlue]}><AppIcon name="user" size={21} color="#3765c5"/></View><View style={{flex:1}}><Text style={s.choiceSmall}>COMPTE PERSONNEL</Text><Text style={s.choiceTitle}>Particulier</Text><Text style={s.choiceText}>Pour acheter, vendre ponctuellement, discuter et gérer vos favoris.</Text><Text style={s.choiceLink}>Continuer comme particulier</Text></View><AppIcon name="chevron-right" size={14} color={PA.muted}/></Pressable><Pressable style={s.choice} onPress={()=>choose('PROFESSIONNEL')}><View style={s.choiceIcon}><AppIcon name="briefcase" size={21} color={PA.primary}/></View><View style={{flex:1}}><Text style={s.choiceSmall}>COMPTE PROFESSIONNEL</Text><Text style={s.choiceTitle}>Professionnel</Text><Text style={s.choiceText}>Pour une entreprise avec SIRET, boutique publique et outils professionnels.</Text><Text style={s.choiceLink}>Créer mon espace Pro</Text></View><AppIcon name="chevron-right" size={14} color={PA.muted}/></Pressable></View>:null}
      {step==='particular'?<View style={s.card}><View style={s.cardHead}><View style={s.cardHeadIcon}><AppIcon name="user" size={17} color={PA.primary}/></View><View style={{flex:1}}><Text style={s.cardTitle}>Vos informations</Text><Text style={s.cardLead}>Ces informations servent à créer votre espace personnel.</Text></View></View><AuthField label="Nom affiché" value={personal.displayName} onChange={v=>setPersonal(x=>({...x,displayName:v}))} placeholder="Votre nom"/><AuthField label="Adresse e-mail" value={personal.email} onChange={v=>setPersonal(x=>({...x,email:v}))} placeholder="vous@exemple.fr" keyboard="email-address"/><AuthField label="Mot de passe" value={personal.password} onChange={v=>setPersonal(x=>({...x,password:v}))} placeholder="10 caractères minimum" secure/><AuthField label="Confirmer" value={personal.confirm} onChange={v=>setPersonal(x=>({...x,confirm:v}))} placeholder="Confirmez le mot de passe" secure/><Pressable style={s.termsRow} onPress={()=>setTerms(v=>!v)}><View style={[s.checkbox,terms&&s.checkboxOn]}>{terms?<AppIcon name="check" size={10} color="#fff"/>:null}</View><Text style={s.termsText}>J’accepte les conditions générales et la politique de confidentialité.</Text></Pressable><Pressable disabled={busy} style={[s.primary,busy&&s.disabled]} onPress={()=>void submitPersonal()}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Créer mon compte</Text>}</Pressable></View>:null}
      {step==='siret'?<View style={s.card}><View style={s.cardHead}><View style={s.cardHeadIcon}><AppIcon name="user-shield" size={17} color={PA.primary}/></View><View style={{flex:1}}><Text style={s.cardTitle}>Vérifiez votre entreprise</Text><Text style={s.cardLead}>Saisissez uniquement votre SIRET. Les données officielles seront récupérées automatiquement.</Text></View></View><AuthField label="Numéro SIRET" value={siret} onChange={v=>{setSiret(v.replace(/\D/g,'').slice(0,14));setCompany(null)}} placeholder="14 chiffres" keyboard="number-pad"/><Pressable disabled={lookupBusy||siret.length!==14} style={[s.primary,(lookupBusy||siret.length!==14)&&s.disabled]} onPress={()=>void verifySiret()}>{lookupBusy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Vérifier mon SIRET</Text>}</Pressable>{company?<><View style={s.companyVerified}><View style={s.companyIcon}><AppIcon name="circle-check" size={17} color="#17805a"/></View><View style={{flex:1}}><Text style={s.companySmall}>ENTREPRISE VÉRIFIÉE</Text><Text style={s.companyTitle}>{company.tradeName||company.legalName}</Text><Text style={s.companyText}>{[company.headquartersAddress,company.headquartersPostalCode,company.headquartersCity].filter(Boolean).join(' · ')}</Text><Text style={s.companyMeta}>SIRET {company.siret||siret}{company.nafCode?` · NAF ${company.nafCode}`:''}</Text></View></View><Pressable style={s.primary} onPress={()=>setStep('pro-account')}><Text style={s.primaryText}>Continuer avec cette entreprise</Text></Pressable></>:null}</View>:null}
      {step==='pro-account'?<View style={s.card}><View style={s.cardHead}><View style={s.cardHeadIcon}><AppIcon name="briefcase" size={17} color={PA.primary}/></View><View style={{flex:1}}><Text style={s.cardTitle}>Vos identifiants</Text><Text style={s.cardLead}>Les informations légales ont déjà été remplies grâce au SIRET.</Text></View></View><View style={s.companyMini}><Text style={s.companyMiniTitle}>{company?.tradeName||company?.legalName}</Text><Text style={s.companyMiniText}>SIRET {company?.siret||siret} · vérifié</Text></View><AuthField label="Nom du responsable" value={pro.displayName} onChange={v=>setPro(x=>({...x,displayName:v}))}/><AuthField label="E-mail professionnel" value={pro.email} onChange={v=>setPro(x=>({...x,email:v}))} placeholder="pro@entreprise.fr" keyboard="email-address"/><AuthField label="Téléphone (facultatif)" value={pro.phone} onChange={v=>setPro(x=>({...x,phone:v}))} keyboard="phone-pad"/><AuthField label="Mot de passe" value={pro.password} onChange={v=>setPro(x=>({...x,password:v}))} secure/><AuthField label="Confirmer" value={pro.confirm} onChange={v=>setPro(x=>({...x,confirm:v}))} secure/><View style={s.actions}><Pressable style={s.secondary} onPress={()=>setStep('siret')}><Text style={s.secondaryText}>Retour</Text></Pressable><Pressable style={s.primary} onPress={continuePro}><Text style={s.primaryText}>Continuer</Text></Pressable></View></View>:null}
      {step==='store'?<View style={s.card}><View style={s.cardHead}><View style={s.cardHeadIcon}><AppIcon name="store" size={17} color={PA.primary}/></View><View style={{flex:1}}><Text style={s.cardTitle}>Créez votre boutique</Text><Text style={s.cardLead}>Votre vitrine publique sera créée avec votre compte Pro.</Text></View></View><AuthField label="Nom de la boutique" value={store.name} onChange={v=>setStore(x=>({...x,name:v}))}/><AuthField label="Ville" value={store.city} onChange={v=>setStore(x=>({...x,city:v}))}/><AuthField label="Code postal" value={store.postalCode} onChange={v=>setStore(x=>({...x,postalCode:v.replace(/\D/g,'').slice(0,5)}))} keyboard="number-pad"/><View style={s.storePreview}><View style={s.storePreviewIcon}><AppIcon name="store" size={18} color="#fff"/></View><View style={{flex:1}}><Text style={s.storeSmall}>VOTRE VITRINE</Text><Text style={s.storeTitle}>{store.name||'Nom de votre boutique'}</Text><Text style={s.storeText}>{store.city||company?.headquartersCity||'France'} · Entreprise SIRET vérifiée</Text></View></View><Pressable style={s.termsRow} onPress={()=>setTerms(v=>!v)}><View style={[s.checkbox,terms&&s.checkboxOn]}>{terms?<AppIcon name="check" size={10} color="#fff"/>:null}</View><Text style={s.termsText}>J’accepte les conditions générales et la politique de confidentialité.</Text></Pressable><View style={s.actions}><Pressable style={s.secondary} onPress={()=>setStep('pro-account')}><Text style={s.secondaryText}>Retour</Text></Pressable><Pressable disabled={busy} style={[s.primary,busy&&s.disabled]} onPress={()=>void submitPro()}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Créer mon compte Pro</Text>}</Pressable></View></View>:null}
      {step==='success'?<View style={s.success}><View style={s.successIcon}><AppIcon name="circle-check" size={30} color="#17805a"/></View><Text style={s.successTitle}>{verificationRequired?'Votre compte est presque prêt !':'Félicitations, votre compte est créé !'}</Text><Text style={s.successLead}>{kind==='PROFESSIONNEL'?'Votre entreprise a été vérifiée et votre boutique professionnelle est prête.':'Votre espace personnel Petit Annonces est prêt.'}</Text><Pressable style={s.primary} onPress={()=>router.replace(kind==='PROFESSIONNEL'?'/auth/login':'/account')}><Text style={s.primaryText}>{kind==='PROFESSIONNEL'?'Se connecter':'Accéder à mon compte'}</Text></Pressable></View>:null}
      <Text style={s.footText}>Déjà membre ? <Text style={s.inlineLink} onPress={()=>router.replace('/auth/login')}>Se connecter</Text></Text>
    </View>
  </ScrollView></KeyboardAvoidingView></SafeAreaView>
}

const s=StyleSheet.create({
  safe:{flex:1,backgroundColor:'#f7f7fc'},flex:{flex:1},scroll:{padding:12,paddingBottom:34,gap:12},brandBar:{height:54,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},backButton:{width:38,height:38,borderRadius:13,backgroundColor:'#fff',borderWidth:1,borderColor:'#e6e3ee',alignItems:'center',justifyContent:'center'},backSpacer:{width:38},logo:{width:150,height:30},
  securityCard:{position:'relative',overflow:'hidden',borderRadius:22,padding:20,backgroundColor:'#211d48'},securityGlow:{position:'absolute',width:220,height:220,borderRadius:110,right:-85,top:-95,backgroundColor:'rgba(121,101,255,.20)'},securityBadge:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:10,paddingVertical:7,borderRadius:999,borderWidth:1,borderColor:'rgba(255,255,255,.14)',backgroundColor:'rgba(255,255,255,.07)'},securityBadgeText:{fontSize:9,fontWeight:'900',letterSpacing:.9,color:'#e6e1ff'},securityTitle:{fontSize:25,lineHeight:27,fontWeight:'900',letterSpacing:-.7,color:'#fff',marginTop:17},securityLead:{fontSize:12,lineHeight:18,color:'#cfcae9',marginTop:9},
  shell:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e3ef',borderRadius:24,padding:18,shadowColor:'#261f5c',shadowOpacity:.08,shadowRadius:23,shadowOffset:{width:0,height:10}},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.1,color:'#6253ea',marginBottom:8},topRow:{gap:9},title:{fontSize:27,lineHeight:30,fontWeight:'900',letterSpacing:-.8,color:'#17152b'},reset:{alignSelf:'flex-start',borderWidth:1,borderColor:'#dedbe9',borderRadius:10,paddingHorizontal:10,paddingVertical:8},resetText:{fontSize:10,fontWeight:'900',color:'#5c566c'},
  progress:{flexDirection:'row',alignItems:'flex-start',marginVertical:20,padding:10,borderWidth:1,borderColor:'#eceaf3',borderRadius:16,backgroundColor:'#faf9fd'},progressItem:{flex:1,alignItems:'center',gap:5},progressDot:{width:29,height:29,borderRadius:15,backgroundColor:'#f0f0f4',alignItems:'center',justifyContent:'center'},progressDotActive:{backgroundColor:PA.primary},progressNo:{fontSize:10,fontWeight:'900',color:'#9b99a6'},progressNoActive:{color:'#fff'},progressLabel:{fontSize:7.7,fontWeight:'800',color:'#a1a0aa',textAlign:'center'},progressLabelActive:{color:'#5143d7'},
  choices:{gap:12},choice:{borderWidth:1,borderColor:'#e3e1eb',borderRadius:21,padding:17,flexDirection:'row',gap:13,backgroundColor:'#fff'},choiceIcon:{width:48,height:48,borderRadius:15,backgroundColor:'#efedff',alignItems:'center',justifyContent:'center'},choiceIconBlue:{backgroundColor:'#edf3ff'},choiceSmall:{fontSize:9,fontWeight:'900',letterSpacing:.8,color:'#777887'},choiceTitle:{fontSize:23,fontWeight:'900',color:'#17152b',marginTop:3},choiceText:{fontSize:12,lineHeight:18,color:'#747482',marginTop:4},choiceLink:{alignSelf:'flex-start',marginTop:12,paddingHorizontal:10,paddingVertical:8,borderRadius:9,backgroundColor:'#f2efff',fontSize:11,fontWeight:'900',color:'#5143d7'},
  card:{gap:15,padding:17,borderWidth:1,borderColor:'#e7e5ef',borderRadius:21,backgroundColor:'#fcfcfe'},cardHead:{flexDirection:'row',gap:11,paddingBottom:14,borderBottomWidth:1,borderBottomColor:'#ecebf1'},cardHeadIcon:{width:43,height:43,borderRadius:13,backgroundColor:'#efedff',alignItems:'center',justifyContent:'center'},cardTitle:{fontSize:20,fontWeight:'900',color:'#17152b'},cardLead:{fontSize:11,lineHeight:16,color:'#797988',marginTop:4},field:{gap:7},label:{fontSize:12,fontWeight:'800',color:'#363249'},input:{height:51,borderWidth:1,borderColor:'#dcd9e8',borderRadius:13,paddingHorizontal:14,fontSize:16,color:'#1a1730',backgroundColor:'#fff'},primary:{minHeight:50,flex:1,borderRadius:13,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center',paddingHorizontal:13,shadowColor:PA.primary,shadowOpacity:.18,shadowRadius:12,shadowOffset:{width:0,height:6}},primaryText:{color:'#fff',fontSize:13,fontWeight:'900',textAlign:'center'},disabled:{opacity:.5},secondary:{minHeight:50,flex:1,borderRadius:13,borderWidth:1,borderColor:'#ddd9e8',backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},secondaryText:{fontSize:13,fontWeight:'900',color:'#5143d7'},actions:{flexDirection:'row',gap:9},
  termsRow:{flexDirection:'row',gap:9,alignItems:'flex-start'},checkbox:{width:20,height:20,borderRadius:6,borderWidth:1,borderColor:'#c9c4da',backgroundColor:'#fff',alignItems:'center',justifyContent:'center',marginTop:1},checkboxOn:{backgroundColor:PA.primary,borderColor:PA.primary},termsText:{flex:1,fontSize:11.5,lineHeight:17,color:'#686477'},errorBox:{borderRadius:12,padding:12,backgroundColor:'#fff1f2',borderWidth:1,borderColor:'#fecdd3',flexDirection:'row',gap:8,alignItems:'flex-start',marginBottom:14},errorText:{flex:1,color:'#9f1239',fontSize:12,lineHeight:18},
  companyVerified:{flexDirection:'row',gap:11,padding:14,borderRadius:16,backgroundColor:'#effaf5',borderWidth:1,borderColor:'#ccebdc'},companyIcon:{width:36,height:36,borderRadius:11,backgroundColor:'#dff5e9',alignItems:'center',justifyContent:'center'},companySmall:{fontSize:8.5,fontWeight:'900',letterSpacing:.7,color:'#205f49'},companyTitle:{fontSize:14,fontWeight:'900',color:'#205f49',marginTop:3},companyText:{fontSize:10.5,lineHeight:15,color:'#5c766b',marginTop:3},companyMeta:{fontSize:9.5,color:'#205f49',marginTop:4},companyMini:{padding:12,borderRadius:13,backgroundColor:'#f3f1ff'},companyMiniTitle:{fontSize:12.5,fontWeight:'900',color:'#5143d7'},companyMiniText:{fontSize:10,color:'#6d63b3',marginTop:3},
  storePreview:{flexDirection:'row',gap:11,alignItems:'center',padding:14,borderWidth:1,borderColor:'#e6e2fa',borderRadius:15,backgroundColor:'#f8f7ff'},storePreviewIcon:{width:44,height:44,borderRadius:13,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center'},storeSmall:{fontSize:8.5,fontWeight:'900',letterSpacing:.7,color:'#8173de'},storeTitle:{fontSize:13.5,fontWeight:'900',color:'#17152b',marginTop:2},storeText:{fontSize:10,color:'#81818d',marginTop:3},success:{alignItems:'center',gap:12,paddingVertical:22},successIcon:{width:70,height:70,borderRadius:35,backgroundColor:'#e8f8ef',alignItems:'center',justifyContent:'center'},successTitle:{fontSize:24,lineHeight:27,fontWeight:'900',textAlign:'center',color:'#17152b'},successLead:{fontSize:12.5,lineHeight:19,textAlign:'center',color:'#727381'},footText:{textAlign:'center',fontSize:12.5,color:'#6d687b',marginTop:18},inlineLink:{color:'#5848e8',fontWeight:'900'},
});