import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { PA } from '../../constants/theme';
import { ApiError, apiRequest } from '../../lib/api';
import { AppIcon } from '../../components/app-icon';

export default function ResetPasswordScreen(){const params=useLocalSearchParams<{token?:string}>();const token=typeof params.token==='string'?params.token:'';const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function submit(){if(!token){setError('Lien de réinitialisation invalide.');return}if(password.length<10){setError('Le mot de passe doit contenir au moins 10 caractères.');return}if(password!==confirm){setError('Les deux mots de passe ne correspondent pas.');return}setBusy(true);setError('');try{await apiRequest('/auth/reset-password',{method:'POST',body:{token,password}});router.replace({pathname:'/auth/login',params:{reset:'1'}})}catch(e){setError(e instanceof ApiError&&e.code==='invalid_or_expired_token'?'Ce lien a expiré ou a déjà été utilisé.':'Impossible de modifier le mot de passe pour le moment.')}finally{setBusy(false)}}return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.page}><View style={s.heroIcon}><AppIcon name="shield" size={24} color={PA.primary}/></View><Text style={s.kicker}>SÉCURITÉ DU COMPTE</Text><Text style={s.title}>Nouveau mot de passe</Text><Text style={s.lead}>Choisissez un mot de passe d’au moins 10 caractères. Toutes les anciennes sessions seront déconnectées.</Text><View style={s.card}><Text style={s.label}>Nouveau mot de passe</Text><TextInput secureTextEntry autoComplete="new-password" value={password} onChangeText={setPassword} placeholder="10 caractères minimum" style={s.input}/><Text style={s.label}>Confirmer</Text><TextInput secureTextEntry autoComplete="new-password" value={confirm} onChangeText={setConfirm} placeholder="Répétez le mot de passe" style={s.input}/>{error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={busy} onPress={()=>void submit()} style={[s.button,busy&&s.disabled]}><Text style={s.buttonText}>{busy?'Modification…':'Modifier mon mot de passe'}</Text></Pressable></View></View></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:PA.bg},flex:{flex:1},page:{flex:1,padding:20,paddingTop:50},heroIcon:{width:58,height:58,borderRadius:19,backgroundColor:PA.softPurple,alignItems:'center',justifyContent:'center',marginBottom:14},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:PA.primary},title:{fontSize:31,fontWeight:'900',letterSpacing:-1,color:PA.ink,marginTop:6},lead:{fontSize:14,lineHeight:21,color:PA.muted,marginTop:8,marginBottom:20},card:{backgroundColor:'#fff',borderWidth:1,borderColor:PA.line,borderRadius:22,padding:18,gap:9},label:{fontSize:12,fontWeight:'900',color:PA.ink},input:{height:52,borderWidth:1,borderColor:'#dcdde5',borderRadius:14,paddingHorizontal:14,fontSize:16,color:PA.ink},error:{fontSize:12,lineHeight:18,color:PA.danger},button:{height:52,borderRadius:14,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center',marginTop:7},buttonText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.55}});
