import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { PA } from '../../constants/theme';
import { AppIcon } from '../../components/app-icon';
import { apiRequest } from '../../lib/api';

export default function VerifyPendingScreen(){const params=useLocalSearchParams<{email?:string}>();const email=typeof params.email==='string'?params.email:'';const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[remaining,setRemaining]=useState(0);useEffect(()=>{if(remaining<=0)return;const id=setInterval(()=>setRemaining(v=>Math.max(0,v-1)),1000);return()=>clearInterval(id)},[remaining]);async function resend(){if(!email||remaining>0)return;setBusy(true);setMessage('');try{const r=await apiRequest<{cooldownSeconds?:number}>('/auth/resend-verification',{method:'POST',body:{email,client:'NATIVE'}});const seconds=Math.max(1,Number(r.cooldownSeconds??300));setRemaining(seconds);setMessage('Un nouveau lien de vérification a été envoyé si le compte est toujours en attente.')}catch{setMessage('Impossible de renvoyer l’e-mail pour le moment.')}finally{setBusy(false)}}return <SafeAreaView style={s.safe}><View style={s.page}><Pressable style={s.backButton} onPress={()=>router.replace('/auth/login')}><AppIcon name="chevron-left" size={14} color={PA.ink}/><Text style={s.back}>Connexion</Text></Pressable><View style={s.icon}><AppIcon name="envelope" size={24} color={PA.primary}/></View><Text style={s.kicker}>VÉRIFICATION E-MAIL</Text><Text style={s.title}>Confirmez votre adresse</Text><Text style={s.copy}>Nous avons envoyé un lien sécurisé à{email?` ${email}`:' votre adresse e-mail'}. Ouvrez-le pour activer votre compte.</Text><View style={s.note}><Text style={s.noteTitle}>Depuis votre téléphone</Text><Text style={s.noteText}>Le lien propose d’ouvrir directement l’application Petit Annonces. Si l’application n’est pas disponible, vous pouvez terminer la vérification sur le site.</Text></View>{message?<Text style={s.message}>{message}</Text>:null}<Pressable disabled={busy||remaining>0||!email} onPress={()=>void resend()} style={[s.primary,(busy||remaining>0||!email)&&s.disabled]}><Text style={s.primaryText}>{busy?'Envoi…':remaining>0?`Renvoyer dans ${remaining}s`:'Renvoyer l’e-mail'}</Text></Pressable><Pressable onPress={()=>router.replace({pathname:'/auth/login',params:{email}})} style={s.secondary}><Text style={s.secondaryText}>J’ai déjà vérifié mon e-mail</Text></Pressable></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:PA.bg},page:{flex:1,padding:20},backButton:{alignSelf:'flex-start',minHeight:38,paddingHorizontal:12,borderRadius:12,borderWidth:1,borderColor:PA.line,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',gap:7,marginBottom:24},back:{fontSize:11,fontWeight:'800',color:PA.ink},icon:{width:58,height:58,borderRadius:18,backgroundColor:'#efedff',alignItems:'center',justifyContent:'center',marginBottom:18},iconText:{fontSize:25},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:PA.primary},title:{fontSize:31,fontWeight:'900',letterSpacing:-1,color:PA.ink,marginTop:6},copy:{fontSize:14,lineHeight:22,color:PA.muted,marginTop:10},note:{marginTop:22,padding:16,borderRadius:18,backgroundColor:'#fff',borderWidth:1,borderColor:PA.line},noteTitle:{fontSize:13,fontWeight:'900',color:PA.ink},noteText:{fontSize:12,lineHeight:19,color:PA.muted,marginTop:5},message:{fontSize:12,lineHeight:18,color:PA.primary,marginTop:14},primary:{height:52,borderRadius:14,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center',marginTop:18},primaryText:{color:'#fff',fontWeight:'900'},secondary:{height:50,borderRadius:14,borderWidth:1,borderColor:'#d8d4f7',backgroundColor:'#fff',alignItems:'center',justifyContent:'center',marginTop:10},secondaryText:{color:PA.primary,fontWeight:'900'},disabled:{opacity:.5}});