import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { PA } from '../../constants/theme';
import { useAuth } from '../../lib/auth';
import { AppIcon } from '../../components/app-icon';

export default function VerifyEmailScreen(){const params=useLocalSearchParams<{token?:string}>();const token=typeof params.token==='string'?params.token:'';const{verifyEmail}=useAuth();const[state,setState]=useState<'loading'|'success'|'error'>(token?'loading':'error');useEffect(()=>{if(!token)return;let active=true;(async()=>{try{await verifyEmail(token);if(active)setState('success')}catch{if(active)setState('error')}})();return()=>{active=false}},[token,verifyEmail]);return <SafeAreaView style={s.safe}><View style={s.page}>{state==='loading'?<><ActivityIndicator color={PA.primary} size="large"/><Text style={s.title}>Vérification en cours…</Text><Text style={s.copy}>Nous activons votre compte de façon sécurisée.</Text></>:state==='success'?<><View style={s.successIcon}><AppIcon name="check" size={13} color={PA.success}/></View><Text style={s.title}>Adresse vérifiée</Text><Text style={s.copy}>Votre compte est actif et votre session a été ouverte dans l’application.</Text><Pressable style={s.primary} onPress={()=>router.replace('/account')}><Text style={s.primaryText}>Accéder à mon compte</Text></Pressable></>:<><View style={s.errorIcon}><Text style={s.errorText}>!</Text></View><Text style={s.title}>Lien non valide</Text><Text style={s.copy}>Le lien a expiré, a déjà été utilisé ou n’est pas valide. Vous pouvez demander un nouveau lien depuis l’écran de connexion.</Text><Pressable style={s.primary} onPress={()=>router.replace('/auth/login')}><Text style={s.primaryText}>Retour à la connexion</Text></Pressable></>}</View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:PA.bg},page:{flex:1,alignItems:'center',justifyContent:'center',padding:28},title:{fontSize:27,fontWeight:'900',letterSpacing:-.7,color:PA.ink,textAlign:'center',marginTop:20},copy:{fontSize:14,lineHeight:22,color:PA.muted,textAlign:'center',marginTop:9,maxWidth:330},successIcon:{width:66,height:66,borderRadius:22,backgroundColor:'#ecfdf3',alignItems:'center',justifyContent:'center'},successText:{fontSize:30,fontWeight:'900',color:'#18794e'},errorIcon:{width:66,height:66,borderRadius:22,backgroundColor:'#fff1f1',alignItems:'center',justifyContent:'center'},errorText:{fontSize:30,fontWeight:'900',color:PA.danger},primary:{height:52,minWidth:230,paddingHorizontal:20,borderRadius:14,backgroundColor:PA.primary,alignItems:'center',justifyContent:'center',marginTop:24},primaryText:{color:'#fff',fontWeight:'900'}});