import {LegalPage} from "../../components/legal-page";
export const metadata={title:"Politique de cookies | Petit Annonces",alternates:{canonical:"/cookies"}};
export default function Page(){const sections=[
{id:"definition",title:"Cookies, stockage local et traceurs",body:"Petit Annonces utilise des cookies, le stockage local du navigateur et des technologies comparables. Certains éléments sont strictement nécessaires au fonctionnement ou à la sécurité ; d’autres ne sont activés qu’après votre choix."},
{id:"necessaires",title:"Fonctionnement strictement nécessaire",body:"Les éléments nécessaires peuvent être utilisés sans consentement lorsqu’ils sont indispensables au service demandé, à l’authentification, à la sécurité ou à la mémorisation de votre choix de confidentialité.",bullets:["Session et authentification sécurisée.","Prévention des abus, protection du compte et continuité de navigation.","Mémorisation du choix de consentement et de certains réglages nécessaires à l’interface.","Stockage local strictement nécessaire à l’application/PWA lorsque la fonctionnalité le requiert."]},
{id:"analytics",title:"Mesure d’audience — Google Analytics",body:"Google Analytics n’est chargé par Petit Annonces qu’après acceptation de la finalité « Mesure d’audience ». Sans cet accord, le script Analytics n’est pas chargé par notre composant de mesure et aucun événement de navigation n’est envoyé par celui-ci.",bullets:["Finalité : comprendre l’usage du site, les pages consultées et les performances afin d’améliorer le service.","Base : consentement lorsqu’aucune exemption spécifique n’est appliquée.","Retrait : possible à tout moment via « Gérer les cookies » ; le stockage Analytics est alors refusé pour les événements suivants."]},
{id:"publicite",title:"Publicité et mesure de campagnes",body:"Les fonctions Google Ads, Meta ou partenaires comparables destinées à mesurer ou personnaliser une campagne ne sont activées que lorsque la finalité publicitaire a été acceptée, sauf transmission strictement nécessaire fondée sur une autre base juridique clairement identifiée.",bullets:["Le refus n’empêche pas d’utiliser les fonctionnalités essentielles de Petit Annonces.","Une publicité ou une mise en avant interne à Petit Annonces n’implique pas automatiquement le dépôt d’un traceur tiers.","Les paramètres publicitaires sont révoqués lorsque le choix correspondant est retiré."]},
{id:"choix",title:"Accepter, refuser ou personnaliser",body:"Le premier niveau du bandeau permet de refuser ou d’accepter les finalités non essentielles avec une simplicité comparable. Le bouton « Personnaliser » permet de choisir séparément mesure, personnalisation et publicité."},
{id:"modifier",title:"Modifier ou retirer votre choix",body:"Le bouton « Gérer les cookies » reste accessible sur ordinateur, mobile, PWA et application lorsque l’interface web est utilisée. Vous pouvez modifier ou retirer votre choix à tout moment. Le retrait est pris en compte pour les nouveaux événements.",bullets:["La préférence est mémorisée afin de ne pas vous solliciter à chaque visite.","Le mécanisme redemande un choix après environ 180 jours ou lors d’un changement substantiel de politique.","Le retrait n’affecte pas les traitements déjà réalisés légalement avant ce retrait."]},
{id:"preuve",title:"Preuve du consentement",body:"Petit Annonces conserve la version de la politique, la date du choix et les finalités acceptées ou refusées afin de respecter votre préférence et de démontrer sa prise en compte. Les données de preuve sont limitées à ce qui est nécessaire à cette finalité."},
{id:"tiers",title:"Services tiers et mise à jour",body:"Les services tiers effectivement utilisés peuvent évoluer. Les principaux services de mesure et de campagne actuellement intégrés sont Google Analytics et Google Ads ; des outils Meta peuvent être utilisés pour les campagnes lorsque la configuration et votre consentement l’autorisent. La présente page est mise à jour lorsque les finalités ou fournisseurs changent de manière significative."}
];return <LegalPage eyebrow="Préférences" title="Politique de cookies" intro="Quels traceurs sont nécessaires, lesquels nécessitent votre accord et comment modifier vos choix à tout moment." updated="26 septembre 2026" sections={sections}/>;}