import {LegalPage} from "../../components/legal-page";
export const metadata={title:"Politique de cookies | Petit Annonces",alternates:{canonical:"/cookies"}};
export default function Page(){const sections=[
{id:"definition",title:"Cookies et traceurs",body:"Un cookie ou traceur est une information déposée ou lue sur votre appareil lorsque vous utilisez un site ou une application. Certains sont indispensables au fonctionnement du service ; d'autres nécessitent votre consentement avant d'être utilisés."},
{id:"necessaires",title:"Traceurs strictement nécessaires",body:"Les traceurs indispensables peuvent être utilisés sans consentement lorsqu'ils sont nécessaires pour fournir un service demandé ou assurer son fonctionnement et sa sécurité.",bullets:["Maintien de session et authentification.","Protection contre les abus et la fraude.","Mémorisation d'un choix indispensable au fonctionnement de l'interface.","Équilibrage de charge ou sécurité technique lorsque nécessaire." ]},
{id:"consentement",title:"Traceurs soumis au consentement",body:"Les finalités non essentielles restent désactivées tant que vous ne les avez pas acceptées. Lorsque plusieurs finalités existent, vous devez pouvoir comprendre leur objet et choisir de manière suffisamment granulaire.",bullets:["Mesure d'audience lorsqu'elle ne bénéficie pas d'une exemption applicable.","Personnalisation non nécessaire au service.","Publicité ou mesure publicitaire.","Fonctionnalités tierces déposant des traceurs non essentiels." ]},
{id:"choix",title:"Accepter, refuser ou personnaliser",body:"Le choix doit être libre et compréhensible. Refuser les traceurs non essentiels doit être aussi simple que les accepter. Un bouton de refus doit être accessible au même niveau que l'acceptation ou via une solution offrant une simplicité équivalente.",note:"La CNIL rappelle en 2026 que les traceurs non strictement nécessaires doivent pouvoir être refusés et que le refus doit être aussi simple que l'acceptation."},
{id:"modifier",title:"Modifier votre consentement",body:"Vous pouvez modifier ou retirer votre choix à tout moment depuis le gestionnaire de cookies accessible sur le site. Le retrait doit être aussi simple que le consentement initial.",bullets:["Le refus n'empêche pas l'utilisation des fonctionnalités essentielles.","Les préférences sont enregistrées afin d'éviter de vous solliciter inutilement.","Une nouvelle demande peut être présentée en cas de changement significatif de finalités ou après une durée appropriée." ]},
{id:"audience",title:"Mesure d'audience",body:"Certains outils de mesure d'audience peuvent, sous conditions strictes, bénéficier d'une exemption de consentement lorsqu'ils sont limités à la mesure nécessaire au fonctionnement et à l'amélioration du service pour le seul compte de l'éditeur. Si ces conditions ne sont pas remplies, le consentement est requis."},
{id:"tiers",title:"Services tiers",body:"Lorsqu'un service tiers dépose des traceurs, l'information doit permettre d'identifier la finalité et, lorsque requis, les responsables concernés. La liste des fournisseurs effectivement utilisés doit être maintenue à jour dans le gestionnaire de consentement ou la documentation associée."},
{id:"preuve",title:"Traçabilité de vos choix",body:"Petit Annonces conserve une preuve technique du choix exprimé et de la version du mécanisme de consentement afin de respecter la préférence enregistrée et démontrer sa prise en compte."}
];return <LegalPage eyebrow="Préférences" title="Politique de cookies" intro="Comprendre quels traceurs peuvent être utilisés, lesquels nécessitent votre accord et comment modifier facilement vos choix." updated="7 septembre 2026" sections={sections}/>;}