import {LegalPage} from "../../components/legal-page";
export const metadata={title:{absolute:"Centre de conformité | Petit Annonces"},description:"DSA, sécurité produit GPSR, DAC7, vendeurs professionnels, vie privée et transparence de la marketplace Petit Annonces.",alternates:{canonical:"/conformite"}};
export default function Page(){const sections=[
{id:"contacts",title:"Points de contact conformité",body:"Les demandes de conformité adressées à Petit Annonces sont centralisées afin d’être tracées et orientées vers le bon traitement.",bullets:["Utilisateurs et consommateurs : Centre d’aide /assistance ou info@petitannonces.fr.","Données personnelles : info@getsy.fr.","Contenu potentiellement illicite : /signaler-contenu-illicite.","Sécurité produit / GPSR : Centre d’aide, en indiquant l’URL de l’annonce, le produit concerné et la nature du risque.","Autorités : les demandes officielles doivent identifier l’autorité, leur base juridique et les informations nécessaires au traitement."]},
{id:"dsa",title:"Digital Services Act — notification de contenu illicite",body:"Le formulaire DSA permet à toute personne de notifier un contenu qu’elle estime illicite et de recevoir une référence de suivi. Il est distinct du support classique.",bullets:["La notification demande les éléments permettant d’identifier précisément le contenu, une explication suffisamment motivée, l’identité et l’e-mail du notifiant lorsque le DSA les requiert, ainsi qu’une déclaration de bonne foi.","Les notifications sont examinées de manière diligente et non arbitraire ; une décision peut conduire au maintien, à la restriction ou au retrait du contenu.","Lorsqu’une décision de modération doit être motivée, la raison et les possibilités de contestation applicables sont communiquées.","Petit Annonces est une petite structure ; les obligations DSA réservées par l’article 19 aux plateformes qui ne sont ni micro ni petites entreprises sont appliquées lorsqu’elles deviennent juridiquement applicables."]},
{id:"moderation",title:"Modération et décisions automatisées",body:"Petit Annonces utilise des contrôles automatisés et humains pour identifier fraude, spam, doublons, coordonnées interdites, contenus à risque et non-conformités. Une détection automatisée peut conduire à une mise en attente ou à une demande de correction ; les décisions sensibles peuvent faire l’objet d’une revue humaine.",bullets:["Les motifs de modération sont enregistrés lorsque le parcours le prévoit.","Un mécanisme de recours interne existe pour les décisions de modération éligibles.","Le recours n’est pas facturé et n’empêche pas l’utilisateur d’exercer les autres voies de droit disponibles."]},
{id:"gpsr",title:"Sécurité des produits — GPSR",body:"Pour les offres de produits soumises au règlement européen sur la sécurité générale des produits, Petit Annonces met à disposition des champs permettant aux vendeurs de renseigner les informations de traçabilité et de sécurité nécessaires.",bullets:["Nom du fabricant et coordonnées postales et électroniques lorsque requis.","Lorsque le fabricant n’est pas établi dans l’Union européenne : personne responsable dans l’Union et ses coordonnées lorsque la réglementation l’exige.","Identifiant du produit, modèle, EAN ou autre référence permettant son identification.","Avertissements et informations de sécurité destinés au consommateur.","Les annonces de produits dangereux ou faisant l’objet d’une mesure de rappel peuvent être retirées, bloquées ou accompagnées d’un avertissement."]},
{id:"safetygate",title:"Safety Gate et rappels",body:"Petit Annonces prévoit un processus de traitement des alertes de sécurité produit, des ordres d’autorités et des rappels. Lorsqu’un produit vendu via la plateforme fait l’objet d’un rappel dont Petit Annonces a connaissance et que les acheteurs concernés peuvent être identifiés, ils peuvent être contactés avec les informations de sécurité pertinentes.",note:"L’enregistrement administratif de la marketplace sur le portail européen Safety Gate et la déclaration du point de contact doivent rester à jour auprès de la Commission européenne."},
{id:"pros",title:"Vendeurs professionnels",body:"Les comptes professionnels sont identifiés séparément. Le parcours Pro peut vérifier le SIRET à partir de sources officielles et présenter l’identité de l’entreprise afin d’aider le consommateur à distinguer un vendeur professionnel d’un particulier.",bullets:["Le professionnel reste responsable de ses informations précontractuelles, garanties, rétractation, facturation et service après-vente.","Le statut professionnel ne permet pas de contourner la modération ou les exigences de sécurité produit.","Les informations d’entreprise doivent être tenues à jour."]},
{id:"dac7",title:"DAC7 et obligations fiscales",body:"Lorsque Petit Annonces entre dans le champ de DAC7 pour une activité et qu’un vendeur dépasse les conditions d’exclusion prévues, la plateforme peut devoir collecter, vérifier puis déclarer certaines informations relatives au vendeur et aux montants concernés.",bullets:["Pour la vente de biens, l’exclusion de faible volume suppose en principe moins de 30 opérations ET un total n’excédant pas 2 000 € pendant la période de déclaration.","Le franchissement d’un seuil de déclaration ne signifie pas automatiquement que les sommes sont imposables.","Les utilisateurs concernés peuvent être invités à compléter des informations fiscales ou d’identification avant l’échéance réglementaire."]},
{id:"classement",title:"Transparence du classement",body:"Les règles de référencement, déréférencement, classement et l’influence des options payantes sont publiées dans /classement-referencement. Les annonces bénéficiant d’une mise en avant payante portent un badge de visibilité et peuvent apparaître dans des emplacements dédiés."},
{id:"rgpd",title:"Vie privée et RGPD",body:"Le responsable du traitement, les catégories de données, finalités, bases juridiques, destinataires, transferts, durées de conservation et droits sont décrits dans /confidentialite. Les demandes de droits peuvent être adressées à info@getsy.fr ou initiées via le support."},
{id:"cookies",title:"Cookies et consentement",body:"Les traceurs non essentiels sont bloqués avant consentement. Google Analytics n’est chargé par le composant de mesure qu’après acceptation de la finalité correspondante. Les choix peuvent être refusés aussi facilement qu’acceptés et modifiés depuis « Gérer les cookies » sur ordinateur, mobile, PWA et application."}
];return <LegalPage eyebrow="Confiance & conformité" title="Centre de conformité" intro="DSA, sécurité produit, transparence marketplace, fiscalité, données personnelles et mécanismes de protection appliqués à Petit Annonces." updated="26 septembre 2026" sections={sections}/>;}