import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { MarketplaceListingCard } from "../../../components/marketplace-listing-card";

export const revalidate=60;

type Props={params:Promise<{city:string}>};
type CityItem={id:string;slug:string|null;title:string|null;priceMinor:number|null;currency:string;city:string|null;imageUrl:string|null;category:{name:string;slug:string;domain:string};property?:{transactionType?:string|null}|null};
type Payload={city:string;slug:string;total:number;recent30?:number;priced?:number;medianPriceMinor?:number|null;updatedAt:string;indexable:boolean;categories:Array<{slug:string;name:string;count:number}>;primaryCategories?:Array<{slug:string;name:string;count:number}>;items:CityItem[]};
const api=()=> (process.env.API_INTERNAL_URL??process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:4000").replace(/\/$/,"");
const featuredCityNames:Record<string,string>={lille:"Lille",paris:"Paris",rennes:"Rennes",nantes:"Nantes",bordeaux:"Bordeaux",toulouse:"Toulouse",lyon:"Lyon",marseille:"Marseille",nice:"Nice",strasbourg:"Strasbourg"};
function emptyFeaturedCity(slug:string):Payload|null{const name=featuredCityNames[slug.toLowerCase()];return name?{city:name,slug:slug.toLowerCase(),total:0,updatedAt:new Date(0).toISOString(),indexable:false,categories:[],primaryCategories:[],items:[]}:null}
async function data(city:string){try{const r=await fetch(`${api()}/seo/city/${encodeURIComponent(city)}`,{next:{revalidate:60}});if(!r.ok)return null;return r.json() as Promise<Payload>}catch{return null}}
async function popularCities(){try{const r=await fetch(`${api()}/seo/cities/popular`,{next:{revalidate:900}});if(!r.ok)return[];const p=await r.json() as{cities?:Array<{city:string;slug:string;count:number}>};return p.cities??[]}catch{return[]}}
function safeJsonLd(value:unknown){return JSON.stringify(value).replace(/</g,"\\u003c")}
function cityFaq(city:string,total:number){return[
  {q:`Où trouver des petites annonces à ${city} ?`,a:`Cette page regroupe les annonces actuellement publiées à ${city}. Utilisez les catégories et les filtres pour cibler les offres qui vous intéressent.`},
  {q:`Puis-je publier gratuitement une annonce à ${city} ?`,a:"Oui. Les particuliers peuvent déposer gratuitement une annonce sur Petit Annonces, sous réserve des règles de publication et de modération de la plateforme."},
  {q:`Combien d’annonces sont disponibles à ${city} ?`,a:`Il y a actuellement ${total} annonce${total>1?"s":""} publiée${total>1?"s":""} à ${city} sur Petit Annonces.`}
]}
export async function generateMetadata({params}:Props):Promise<Metadata>{
  const{city}=await params;const d=(await data(city))??emptyFeaturedCity(city);if(!d)return{title:{absolute:"Petites annonces locales | Petit Annonces"},robots:{index:false,follow:true}};
  const title=`Petites annonces gratuites à ${d.city} | Petit Annonces`;
  const categoryNames=(d.primaryCategories?.length?d.primaryCategories:d.categories).slice(0,4).map(x=>x.name.toLowerCase());
  const categoryCopy=categoryNames.length?categoryNames.join(", "):"véhicules, maison, high-tech et services";
  const description=`Découvrez ${d.total} petite${d.total>1?"s":""} annonce${d.total>1?"s":""} à ${d.city} : ${categoryCopy}. Achetez et vendez entre particuliers ou professionnels, et publiez gratuitement près de chez vous.`;
  return{title:{absolute:title},description,alternates:{canonical:`/ville/${d.slug}`},robots:{index:d.indexable,follow:true},openGraph:{type:"website",url:`/ville/${d.slug}`,title,description}}
}
export default async function CityPage({params}:Props){
  const{city}=await params;const[apiCity,popular]=await Promise.all([data(city),popularCities()]);const d=apiCity??emptyFeaturedCity(city);if(!d)notFound();const otherCities=popular.filter(x=>x.slug!==d.slug).slice(0,8);
  const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Accueil",item:"https://petitannonces.fr/"},{"@type":"ListItem",position:2,name:`Annonces à ${d.city}`,item:`https://petitannonces.fr/ville/${d.slug}`}]};
  const itemList={"@context":"https://schema.org","@type":"ItemList",name:`Petites annonces à ${d.city}`,url:`https://petitannonces.fr/ville/${d.slug}`,numberOfItems:d.total,itemListElement:d.items.filter(item=>Boolean(item.slug)).map((item,index)=>({"@type":"ListItem",position:index+1,url:`https://petitannonces.fr/annonce/${item.slug}`,name:item.title??item.category.name}))};
  const faq=cityFaq(d.city,d.total);
  const faqJsonLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(item=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))};
  const collectionJsonLd={"@context":"https://schema.org","@type":"CollectionPage",name:`Petites annonces à ${d.city}`,url:`https://petitannonces.fr/ville/${d.slug}`,about:{"@type":"Place",name:d.city},mainEntity:itemList};
  return <div style={{minHeight:"100vh",background:"#f7f8fc"}}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(breadcrumb)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(itemList)}}/>{d.indexable&&<><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(faqJsonLd)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(collectionJsonLd)}}/></>}<main style={{width:"min(1180px,calc(100% - 24px))",margin:"0 auto",padding:"26px 0 72px"}}>
    <nav aria-label="Fil d’Ariane" style={{fontSize:13,color:"#777",marginBottom:15}}><a href="/" style={{color:"#5b4cf0"}}>Accueil</a> › {d.city}</nav>
    <header style={{padding:"28px",borderRadius:24,background:"linear-gradient(135deg,#171725,#312b67)",color:"white"}}><span style={{fontSize:12,fontWeight:900,letterSpacing:1,textTransform:"uppercase",opacity:.76}}>Petites annonces locales</span><h1 style={{fontSize:"clamp(30px,5vw,50px)",margin:"8px 0 10px"}}>Petites annonces gratuites à {d.city}</h1><p style={{maxWidth:820,margin:0,opacity:.88}}>Achetez et vendez près de chez vous entre particuliers ou professionnels. {d.total} annonce{d.total>1?"s":""} actuellement publiée{d.total>1?"s":""} à {d.city}, avec dépôt d’annonce gratuit.</p></header>
    {!d.indexable&&<section style={{marginTop:18,padding:18,borderRadius:16,background:"#fff8e7",border:"1px solid #f1d690"}}><strong>La page locale se développe</strong><p style={{margin:"6px 0 0"}}>Cette page reste accessible mais n’est pas proposée à l’indexation tant qu’elle ne contient pas assez d’annonces locales utiles.</p></section>}
    {(d.primaryCategories?.length??0)>0&&<section style={{marginTop:24,padding:18,borderRadius:18,background:"#f1efff",border:"1px solid #ded9ff"}}><small style={{color:"#6558d9",fontWeight:900}}>CATÉGORIES PRINCIPALES</small><h2 style={{margin:"5px 0 10px",fontSize:21}}>Petites annonces populaires à {d.city}</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:10}}>{d.primaryCategories!.map(c=><a key={c.slug} href={`/c/${c.slug}/${d.slug}`} style={{padding:"13px 14px",borderRadius:14,background:"white",textDecoration:"none",color:"#4338ca",fontWeight:850,fontSize:13,border:"1px solid #d9d4ff"}}><span style={{display:"block"}}>Petites annonces {c.name.toLowerCase()} à {d.city}</span><small style={{display:"block",marginTop:4,color:"#7772a5"}}>{c.count} annonce{c.count>1?"s":""}</small></a>)}</div></section>}
    {d.indexable&&<section style={{marginTop:18,padding:20,borderRadius:18,background:"#fff",border:"1px solid #e7e7ef"}}><small style={{color:"#5b4cf0",fontWeight:900}}>ACTIVITÉ LOCALE</small><h2 style={{margin:"5px 0 10px",fontSize:21}}>Le catalogue Petit Annonces à {d.city}</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:10}}><div style={{padding:14,borderRadius:14,background:"#fafafe"}}><small style={{color:"#7a7b88"}}>Annonces actives</small><strong style={{display:"block",marginTop:4,fontSize:23}}>{d.total}</strong></div><div style={{padding:14,borderRadius:14,background:"#fafafe"}}><small style={{color:"#7a7b88"}}>Ajouts sur 30 jours</small><strong style={{display:"block",marginTop:4,fontSize:23}}>{d.recent30??0}</strong></div>{(d.priced??0)>=3&&d.medianPriceMinor!=null&&<div style={{padding:14,borderRadius:14,background:"#fafafe"}}><small style={{color:"#7a7b88"}}>Prix médian affiché*</small><strong style={{display:"block",marginTop:4,fontSize:23}}>{new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(d.medianPriceMinor/100)}</strong></div>}</div><p style={{margin:"12px 0 0",color:"#737481",fontSize:12,lineHeight:1.55}}>* Indicateur calculé sur les annonces de {d.city} avec un prix renseigné. Les biens pouvant être très différents, ce chiffre n’est pas un indice de marché.</p><a href="/observatoire" style={{display:"inline-flex",marginTop:10,color:"#5143d7",fontWeight:850,textDecoration:"none",fontSize:13}}>Voir l’Observatoire Petit Annonces →</a></section>}
    <section style={{marginTop:24}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,flexWrap:"wrap"}}><div><small style={{color:"#777"}}>Explorer par catégorie</small><h2 style={{margin:"4px 0"}}>Que cherchez-vous à {d.city} ?</h2></div><a href={`/recherche?city=${encodeURIComponent(d.city)}`} style={{color:"#5b4cf0",fontWeight:850}}>Tous les filtres →</a></div><div style={{display:"flex",gap:9,flexWrap:"wrap",marginTop:12}}>{d.categories.map(c=><a key={c.slug} href={c.count>=3?`/c/${c.slug}/${d.slug}`:`/recherche?category=${encodeURIComponent(c.slug)}&city=${encodeURIComponent(d.city)}`} style={{padding:"10px 13px",border:"1px solid #e4e4ec",borderRadius:999,background:"white",textDecoration:"none",color:"#343542",fontWeight:800,fontSize:13}}>{c.name} <small style={{color:"#878895"}}>({c.count})</small></a>)}</div></section>
    <section style={{marginTop:28}}><h2>Annonces récentes à {d.city}</h2>{d.items.length?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(220px,1fr))",gap:12}}>{d.items.map(item=><MarketplaceListingCard key={item.id} item={item}/>)}</div>:<p>Aucune annonce récente pour le moment.</p>}</section>
    <section style={{marginTop:28,padding:22,borderRadius:20,background:"white",border:"1px solid #e7e7ef"}}><small style={{color:"#777887",fontWeight:850}}>ACHETER ET VENDRE LOCALEMENT</small><h2 style={{margin:"5px 0 8px"}}>Trouver une petite annonce à {d.city}</h2><p style={{margin:0,color:"#60616d",lineHeight:1.65}}>Parcourez les catégories qui comptent réellement des annonces à {d.city}, comparez les prix, l’état, les photos et les informations essentielles avant de contacter un membre. Les liens ci-dessus mènent directement vers les catégories locales disposant d’un stock suffisant, tandis que les autres recherches restent accessibles avec les filtres de Petit Annonces.</p></section>
    {d.indexable&&<section style={{marginTop:18,padding:22,borderRadius:20,background:"white",border:"1px solid #e7e7ef"}}><small style={{color:"#777887",fontWeight:850}}>QUESTIONS FRÉQUENTES</small><h2 style={{margin:"5px 0 12px"}}>Petites annonces à {d.city}</h2><div style={{display:"grid",gap:12}}>{faq.map(item=><details key={item.q} style={{padding:"13px 14px",border:"1px solid #ececf2",borderRadius:14,background:"#fbfbfe"}}><summary style={{cursor:"pointer",fontWeight:850,color:"#343542"}}>{item.q}</summary><p style={{margin:"9px 0 0",color:"#60616d",lineHeight:1.6}}>{item.a}</p></details>)}</div></section>}
    {otherCities.length>0&&<section style={{marginTop:18,padding:22,borderRadius:20,background:"white",border:"1px solid #e7e7ef"}}><small style={{color:"#777887",fontWeight:850}}>VILLES POPULAIRES</small><h2 style={{margin:"5px 0 12px"}}>Petites annonces dans d’autres villes</h2><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{otherCities.map(x=><a key={x.slug} href={`/ville/${x.slug}`} style={{padding:"9px 12px",border:"1px solid #e4e4ec",borderRadius:999,background:"#fafafe",textDecoration:"none",color:"#343542",fontWeight:800,fontSize:12}}>Petites annonces à {x.city} <small style={{color:"#878895"}}>({x.count})</small></a>)}</div></section>}
    <section style={{marginTop:30,padding:22,borderRadius:20,background:"white",border:"1px solid #e7e7ef"}}><h2>Publier gratuitement une annonce à {d.city}</h2><p>La publication est gratuite. Ajoutez des photos claires, un prix réaliste et une description précise pour aider les acheteurs locaux à trouver votre annonce.</p><a href="/deposer-annonce-gratuite" style={{display:"inline-flex",padding:"11px 15px",borderRadius:12,background:"#5b4cf0",color:"white",textDecoration:"none",fontWeight:900}}>Déposer une annonce gratuite</a></section>
  </main></div>
}

